### ISSUE TITLE
[Bug] Mermaid flow chart displays incorrectly

### ISSUE THREAD

**Issue by aykte** [vuepress-theme-hope/vuepress-theme-hope#1140]
## Describe the bug

Mermaid flow chart displays incorrectly

## Screenshots
![image](https://user-images.githubusercontent.com/74592537/139539894-6b41eb04-aba3-48ef-b6e2-a631843d4f65.png)

## Additional context

I just started using vuepress-theme-hope today. It's very cool! However, during use, I found that its Mermaid plugin could not be displayed normally. Whether I preview it locally or view docs, the error content is just like the image above, which is a screenshot of me in docs (I tried browsing on my mobile phone, but this problem still appears)

**Comment by Mister-Hope** [comment]
Issue comfirmed, may came from recent mermaid updates, I will check it when I have time.

**Comment by Mister-Hope** [comment]
Fixed, mermaid is starting to provide esm packages, and that should be a BR in mermaid.

**Comment by Mister-Hope** [comment]
Released in v1.20.5
