### ISSUE TITLE
[Bug]vue页面编译的中文依赖问题

### ISSUE THREAD

**Issue by senvon2** [vuepress-theme-hope/vuepress-theme-hope#1144]
## Describe the bug

我目前使用
"vuepress": "1.8.2",
"vuepress-theme-hope": "1.20.3"
在构建博客,本地(win10)+中文环境完美运行

当把dist包部署到远端服务器上后,发现页面不能访问,调试后发现如下问题

## Screenshots

![image](https://user-images.githubusercontent.com/93473524/139581057-fd06d8af-639d-4875-bbd2-e01a6d5e1e4c.png)

## Additional context

从请求地址可以看到页面中的请求了一个奇怪的js文件,随后我追查本地编译后的asset的js文件
![image](https://user-images.githubusercontent.com/93473524/139581130-028b9fc4-816a-4928-8553-e219676214c9.png)

这个编译出来的带中文的js,这个中文的来源是每个md页面的h1的标题

从程序角度出发,这个带中文的js文件,是程序编译的中间产物,压根可以不存在

目前存在的这个带中文的js文件,导致部署到nginx上,无法请求到.当然,如果要请求到,不但nginx要做设置,连linux的语言也要设置,会牵涉非常广泛

我对前端,vue不是很了解
这边请问,这个问题的根源是啥??有没有简单的解决方案???

**Comment by Mister-Hope** [comment]
我建议你加一下主题群我俩详细交流一下，我可以在QQ上给你指导一下。

我就两个主要观点：

1. 使用中文文件名没有任何问题。如果你不喜欢这个默认行为你可以改，主题文档有对应的选项。
2. 我很怀疑你的错误是你上传的时候没有上传全造成的，如果你访问一个encode过的链接得到了404，这说明你ngnix配置有问题。

总之这不是一个主题的bug。我不接这个锅。

**Comment by Mister-Hope** [comment]
Related options: https://vuepress-theme-hope.github.io/config/theme/plugin/#chunkrename
相关选项: https://vuepress-theme-hope.github.io/zh/config/theme/plugin/#chunkrename

**Comment by Mister-Hope** [comment]
> 一般来说,服务器OS,带不带中文环境,并不影响在服务器上运行服务的中文问题,因为有静态中文文件的存在,就和服务器的操作系统产生了联系

你听说过Unicode么？这是目前主流Linux系统的默认编码模式，也是你上传的所有数据的编码模式，压根就不涉及这是一个什么语言的问题。它跟中文环境这个东西没有一毛钱关系。你说的Linux的中文环境，可以指中文locale设置，也可以指对gbk编码等的支持，但这跟你这个问题同样没一毛钱关系。

另外正如我表达过的，默认的Nginx设置在一个正常的主流操作系统，是可以正常访问带有emoji，各国语言文字的文件的。应该是你自己配置或Nginx编译安装时没有带有必要flag，才会造成你无法访问文件名不是标准url规范的文件。

**Comment by Mister-Hope** [comment]
另外，url encode是基于字节码的，换言之，你的服务器不需要有中文或其他语言字库，或者需要能够渲染emoji之类的，他所处理的只是读取文件名的字节码，和urlencode后的参数对上，文件就匹配了。

建议自行提升服务器运维知识
