### ISSUE TITLE
[Bug] 使用Vssue作为评论插件时，评论组件宽度不当。

### ISSUE THREAD

**Issue by toddlerya** [vuepress-theme-hope/vuepress-theme-hope#1159]
## 缺陷描述

使用Vssue作为评论插件时，评论组件宽度不当。  
查看代码发现`@mr-hope/vuepress-plugin-comment`的 `index.js`中有对Valine和Waline的样式布局配置，但对Vssue没有进行样式配置。

### Vssue评论插件效果

> 宽度没有和正文对齐

![image](https://user-images.githubusercontent.com/5418150/140279962-57163863-d2b0-4f87-a45e-7ac7ccffe6fb.png)

### Waline评论插件效果
> 这是我期望的效果
![image](https://user-images.githubusercontent.com/5418150/140280696-406c59f9-f9a5-4b21-958a-85300f734b8f.png)

### OS

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

### Chrome

版本 92.0.4515.131（正式版本） （64 位）

### Nodejs

node: v16.13.0
npm: 8.1.0

### package.js
```json
{
  "name": "vuepress-theme-hope-project",
  "version": "1.0.0",
  "description": "A project of vuepress-theme-hope",
  "license": "MIT",
  "scripts": {
    "docs:build": "vuepress build vuepress-hope-blog",
    "docs:clean-dev": "vuepress dev vuepress-hope-blog --no-cache",
    "docs:dev": "vuepress dev vuepress-hope-blog",
    "docs:eject-theme": "vuepress eject-hope vuepress-hope-blog"
  },
  "devDependencies": {
    "vuepress": "^1.8.2",
    "vuepress-theme-hope": "^1.20.5"
  }
}
```

**Comment by Mister-Hope** [comment]
Will fix this soon, thx for reporting

**Comment by Mister-Hope** [comment]
This could be a solution.

```styl
@require '~@mr-hope/vuepress-shared/styles/wrapper'

.page
  .vssue
    @extend $wrapper
```

Besides, Vssus is still not ready for darkmode yet. Personally I recommand Waline.

PR is welcomed for darkmode styles for Vssue.

**Comment by Mister-Hope** [comment]
Closed, as vssue is not active, and it's still based on Vue2, V2 version can not support vssue.

Also, there is a workaround above.
