### ISSUE TITLE
[Bug] vuepress-plugin-copy-code2

### ISSUE THREAD

**Issue by dkrzyszczyk** [vuepress-theme-hope/vuepress-theme-hope#1197]
I'm using `vuepress/1.8.2` so the plugin should be supported as it's < v2.0. But when I did `yarn add global -D vuepress-plugin-copy-code2`and put the plugin under my `module.exports -> plugins` section and run `yarn run docs:build ` I received very nothing-telling err message: 

`warning An error was encountered in plugin "vuepress-plugin-copy-code2"`

Of course, it didn't work after running locally because of this error. Trying to use it with succinct theme which is almost the default vuepress theme. Do you have any idea why it's failing?

**Comment by Mister-Hope** [comment]
.......

The main branch is targeting v2.

The v1 branch and v1 version is something you should use. So you should use `@mr-hope/vuepress-plugin-cooy-code`
