### ISSUE TITLE
[Question] Unable to use pm2 with devServer

### ISSUE THREAD

**Issue by ajh99990** [vuepress-theme-hope/vuepress-theme-hope#1210]
当我使用pm2启动项目的时候，进程会停在如图所示的位置。
![This is an image](https://s6.bihukankan.com/img/16377202901637720201118_69E267A5-2790-42DF-80F8-E6DD708B9684.png)
上面这张截图中出现的日志是使用pm2 logs打印的。

vuepress版本：1.8.2
vuepress-theme-hope版本：1.21.0
pm2版本：5.1.2
我的启动指令是 **_pm2 start npm --name wiki -- run docs:dev_**
操作系统版本：macos 10.15.5 Beta 以及 Ubuntu 18.04.2 LTS

**Comment by Mister-Hope** [comment]
使用默认官方主题是否会出现类似问题问题么？

**Comment by Mister-Hope** [comment]
另外
![Screenshot_20211124-104600](https://user-images.githubusercontent.com/33315834/143162336-57c258e2-99c0-4b53-a157-2d30252ee4f3.jpg)
我不是很清楚你的图片是否上传全了

**Comment by ajh99990** [comment]
感谢您的回复。
官方主题是没有出现这个问题的，我敢保证，因为之前很长一段时间使用的就是官方主题。
我的图片确实上传全了，您截图中的灰色部分没有加载出来。 但我可以直接把日志的最后几行贴在这里供您参考。

```
0|wiki     | tip Apply plugin @mr-hope/feed (i.e. "@mr-hope/vuepress-plugin-feed") ...
0|wiki     | tip Apply plugin @mr-hope/pwa (i.e. "@mr-hope/vuepress-plugin-pwa") ...
0|wiki     | tip Apply plugin @mr-hope/seo (i.e. "@mr-hope/vuepress-plugin-seo") ...
0|wiki     | tip Apply plugin @mr-hope/sitemap (i.e. "@mr-hope/vuepress-plugin-sitemap") ...
0|wiki     | tip Apply plugin @mr-hope/git (i.e. "@mr-hope/vuepress-plugin-git") ...
0|wiki     | tip Apply plugin @mr-hope/smooth-scroll (i.e. "@mr-hope/vuepress-plugin-smooth-scroll") ...
0|wiki     | tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
0|wiki     | tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
0|wiki     | tip Apply plugin active-hash (i.e. "vuepress-plugin-active-hash") ...
0|wiki     | tip Apply plugin copyright (i.e. "vuepress-plugin-copyright") ...
0|wiki     | tip Apply plugin md-enhance (i.e. "vuepress-plugin-md-enhance") ...
0|wiki     | tip Apply plugin @mr-hope/copy-code (i.e. "@mr-hope/vuepress-plugin-copy-code") ...
0|wiki     | tip Apply plugin photo-swipe (i.e. "vuepress-plugin-photo-swipe") ...
0|wiki     | tip Apply plugin clean-url ...
0|wiki     | tip Apply plugin chunk-rename ...
```

重新补贴一张截图
![This is an image](https://s6.bihukankan.com/img/16377224561637722442663_660E664D-A6BC-46B0-BEB0-1B89CBA1225C.png)

**Comment by Mister-Hope** [comment]
好的，反我最近较忙，到周末我可能才有空排查这个问题。给你的建议是你可以先尝试禁用主题自带的插件，先试试全部禁用（git不行）能否正常工作，如果可以的话，你可以先用二分法试试禁用一些组件，看看问题发生在哪个或哪些组件或主题里，这样我回头更好排查问题。

**Comment by Mister-Hope** [comment]
我现在也很不确定这个问题的来源，因为我似乎没有用到一些可能会导致pm2挂起的node侧api

**Comment by ajh99990** [comment]
我尝试像下面这样关闭全部的语法增强插件，但仍然解决不了问题。
```
mdEnhance: {
      enableAll: false,
      presentation: false,
      lineNumbers:false,
      imageFix:false,
      align:false,
      sup:false,
      sub:false,
      footnote:false,
      mark:false,
      tasklist:false,
      jsfiddle:false,
      codepen:false,
    }
```
很抱歉没办法提供什么有价值的帮助。

**Comment by Mister-Hope** [comment]
不，你可以设置插件的camelCase名称加false禁用所有除git外的插件。
如：

```
themeConfig: {
  copyCode: false, 
  sitemap: false,
}
```

**Comment by Mister-Hope** [comment]
尽管此问题可能有效，更加推荐的解决方案是运行构建命令，并通过nginx apache或者nodejs 里的http-server来提供静态文件。

长时间保持webpack devServer可能会导致内存泄漏。

暂时没有时间详细定位问题，所以欢迎尝试上述替代方案。
