### ISSUE TITLE
[Bug] v1 版本 sidebarDepth 配置失效

### ISSUE THREAD

**Issue by Fuphoenixes** [vuepress-theme-hope/vuepress-theme-hope#1227]
## Additional context

Add any other context about the problem here. Especially the issue occurs in certain OS, browser or configuation.

**Comment by Mister-Hope** [comment]
Some screenshots or reproduction repo required plz.

**Comment by Fuphoenixes** [comment]
![image](https://user-images.githubusercontent.com/27912232/144383057-acc28b97-43d6-426a-9863-1da4e5a27103.png)
![image](https://user-images.githubusercontent.com/27912232/144382987-9cbc73b9-4960-4cf4-8912-f0e84a339a70.png)

**Comment by Fuphoenixes** [comment]
尝试使用字符串 ‘0’后可以生效

**Comment by Mister-Hope** [comment]
的确，有兴趣的话欢迎提个pr。

😂你这个就属于典型的没详细汇报bug，我回你之前我自己设了个数字是有效的。
