### ISSUE TITLE
[Bug] i don't kown this error

### ISSUE THREAD

**Issue by wo-ni** [vuepress-theme-hope/vuepress-theme-hope#1247]
![image](https://user-images.githubusercontent.com/26138771/145265995-0a553059-7b9e-48c1-aedf-a31e0f7a14a7.png)

**Comment by Mister-Hope** [comment]
This helps nothing locating issue.

Reproduction repo please.

**Comment by wo-ni** [comment]
![image](https://user-images.githubusercontent.com/26138771/145387723-55e53d5a-c915-4623-bf3c-d610b300e714.png)

**Comment by wo-ni** [comment]
老弟, 微信聊, 实在搞不来
