### ISSUE TITLE
[Bug] CodeGroup内插入table样式问题

### ISSUE THREAD

**Issue by ddmcc** [vuepress-theme-hope/vuepress-theme-hope#1252]
## 描述

在CodeGroup内插入table，背景超出了

## 截图
![image](https://user-images.githubusercontent.com/26783126/145671695-8d345e29-f0fc-4917-b3c6-30fe30520cb6.png)

## 运行环境
vuepress-theme-hope: 1.21.0
node: v12.20.0
npm: 6.14.8
Chrome: 92.0.4515.131
macOS: 12.0.1

**Comment by Mister-Hope** [comment]
从设计上它只能用于插入代码块。
