### ISSUE TITLE
[Bug] markdown enhance doesn't work with url in tasklist

### ISSUE THREAD

**Issue by remi-guan** [vuepress-theme-hope/vuepress-theme-hope#1270]
## Describe the bug

I'm using the commands from the docs to create my project:

```bash
yarn create vuepress-theme-hope [dir]
```

After everything was set up, I can only render this document with URL in tasklist with the `tasklist` feature of mdEnhance disabled. Otherwise, it prints errors on the console and doesn't render anything.

## Screenshots

After I have disabled the `tasklist` feature:

![image](https://user-images.githubusercontent.com/68253563/145984348-44bffe66-5bde-40d0-9cc9-781cdcff76d5.png)

![image](https://user-images.githubusercontent.com/68253563/145984184-8e2c2cbd-d730-429d-9750-dec8c0b9a359.png)

If I enable it (uncomment this setting): 

![image](https://user-images.githubusercontent.com/68253563/145984639-55c48f7e-a745-4619-a741-0bb7e9d8202d.png)

If I remove the URL in my document's tasklist, it's working without any error:

![image](https://user-images.githubusercontent.com/68253563/145984904-7573b577-ed49-4360-a631-ced243027bd7.png)

## Additional context

versions:

```json
"vuepress": "^1.8.2",
"vuepress-theme-hope": "^1.21.0"
```

**Comment by remi-crystal** [comment]
Another example to reproduce the problem:

1. `yarn create vuepress-theme-hope [dir]`
2.  Edit one of the `.md` files, add a tasklist with a linked item.
3. The page throws an error and doesn't show anything of this document.

![image](https://user-images.githubusercontent.com/68253563/145985956-900b186d-ac7d-4d04-aa5f-1bb05f7df5b0.png)

![image](https://user-images.githubusercontent.com/68253563/145986214-17e5a356-53e9-46fc-ba80-70e2b1d226eb.png)

**Comment by remi-crystal** [comment]
The excepted output of the above example:

![image](https://user-images.githubusercontent.com/68253563/145986840-3b50941f-d9db-4974-a23e-57b3436518a2.png)

Also, there's a workaround:

1. Have the `tasklist` option of mdEnhance disabled.
2. Install [markdown-it-task-lists](https://github.com/revin/markdown-it-task-lists)
3. Config it as [the example in the vuepress document](https://v1.vuepress.vuejs.org/guide/markdown.html#advanced-configuration).

```javascript
markdown: {
  extendMarkdown: md => {
    // use more markdown-it plugins!
    md.use(require('markdown-it-task-lists'))
  }
},
```

4. The result should be like the above image.

**Comment by Mister-Hope** [comment]
Thanks for the detailed infomation and sorry for the delay, I will investigate it in 2022 Jan(really busy in real life)

**Comment by Mister-Hope** [comment]
See https://github.com/revin/markdown-it-task-lists/issues/32

**Comment by Mister-Hope** [comment]
There is a workaround, since I am using `label: true, labelAfter: true` by default, you can trun off these options to avoid problems:

```js
themeConfig: {
  mdEnhance: {
    tasklist: {
      label: false,
      labelAfter: false
    }
  }
}
```

**Comment by Mister-Hope** [comment]
Glad to say that we fix this in https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/6d302d6fad1510ee28f0b446d9495cecdd5ba97a
