### ISSUE TITLE
[Bug]themeConfig.editLinkText 似乎失效了

### ISSUE THREAD

**Issue by VaguelyCloud** [vuepress-theme-hope/vuepress-theme-hope#1331]

**Comment by Mister-Hope** [comment]
Fist of all, I don't think I mention that this setting is supported

![image](https://user-images.githubusercontent.com/33315834/147902760-18393467-2440-4363-9bd3-ab6c0799b14c.png)

Second, the theme will inject built-in i18n config to your config according to your `lang` settings.

So if you really want to overide one, use the following settings:

```js
{
  themeConfig: {
    locales: {
      '/lang-path/': { // the path should be the one you want to set
        meta: {
          editLink: 'xxxxx',
        },
      },
    },
  },
}
```
