### ISSUE TITLE
[Bug] 启用tex报错

### ISSUE THREAD

**Issue by childrentime** [vuepress-theme-hope/vuepress-theme-hope#1339]
包版本： 1.22.0
os版本: centos8

## Describe the bug

yarn start报错

config.js中添加

```js
 [
            "md-enhance",
            {
                // 启用 TeX 支持
                tex: true,
            },
        ],
```

## Screenshots

![image](https://user-images.githubusercontent.com/58261676/147917870-5147d9fd-469a-4bac-ad88-a0404cfe39cf.png)

**Comment by childrentime** [comment]
vuepress和所有插件版本 2.0.0-beta.29

**Comment by Mister-Hope** [comment]
V1和V2不互相兼容，这在vuepress2文档里已经显著标出

**Comment by Mister-Hope** [comment]
另外鉴于最近v2仍然做了不少breaking changes，在v2进入rc（也就是不再做破坏性更改前），我不会再继续适配v2，大量的破坏性更改已经让我返工多次并浪费了很多额外时间，所以请暂时先使用v1或耐心等待。

**Comment by childrentime** [comment]
看到commit，我还以为直接适配2的，我错了😂
