### ISSUE TITLE
[Bug]引用element-ui后，在导入的主题内使用折叠面板报错

### ISSUE THREAD

**Issue by kk305cs** [vuepress-theme-hope/vuepress-theme-hope#1407]
1. 在enhance.js内引用了element-ui库
![image](https://user-images.githubusercontent.com/26682400/150302260-6d0b5ce8-760e-4eb1-948f-bf600fb01c32.png)

2.在自己写的组件内使用折叠面板 theme/components/
![image](https://user-images.githubusercontent.com/26682400/150302398-8c403c16-d917-4316-abfc-dc927d239891.png)

3. 在运行后，页面f12报错
![ASEY_GX6ZBY3DOKEXSY{9 X](https://user-images.githubusercontent.com/26682400/150302157-01eb5299-fa6c-445a-b59d-737767537f1d.png)

**Comment by Mister-Hope** [comment]
This error is thrown at element ui side, so I won't spend time investigating it.

You need to provide more infomation about how my theme is conflict with element ui, before I relook into this issue.

Only hiting the below situation, I will regard as my work:

- Errors are thrown at my code
- Related infomation about how errors are happening, and possiable solution avoiding it.

**Comment by Mister-Hope** [comment]
It seems that element ui are registing same directive as I did in my theme.

https://github.com/element-plus/element-plus/blob/dev/packages/directives/click-outside/index.ts

I will change the directive name in future versions.
