### ISSUE TITLE
图片懒加载导致报错 [Bug]

### ISSUE THREAD

**Issue by kings1990** [vuepress-theme-hope/vuepress-theme-hope#1421]
## Describe the bug

[使用了图片懒加载插件](https://tolking.github.io/vuepress-plugin-img-lazy) 导致页面不能渲染了

## Screenshots

![image](https://user-images.githubusercontent.com/8969637/150944684-1015e10a-ffff-44eb-9e2a-4c680a4555ba.png)

## Additional context

这一行角标[1]报错，可能是图片懒加载才会出这个问题，希望可以优化
```
token.attrs[token.attrIndex("src")][1], config)}" alt="${md.utils.escapeHtml(token.content)}" />`;
```

**Comment by Mister-Hope** [comment]
The plugin you are using is removing `src`  attribute in image element and set a new attr called `data-src`. This is obviously something unrelated to my code.
