### ISSUE TITLE
考虑加入友链布局

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress-theme-hope/vuepress-theme-hope#1426]
### Discussed in https://github.com/vuepress-theme-hope/vuepress-theme-hope/discussions/1425

<div type='discussions-op-text'>

<sup>Originally posted by **Sciroccogti** January 26, 2022</sup>
感觉类似 project 的卡片式的展示方式就很好！</div>

**Comment by Mister-Hope** [comment]
已添加于 V2

**Comment by Sciroccogti** [comment]
Well, I do noticed that `friend` is now an available type for projects in blog. But is there anyway to set a avatar for each friend?

**Comment by Mister-Hope** [comment]
You can use cover to provide a background image. And I do have plans improving the icon feature. Just like the way which SocialMediaLinks are rebuilt.

**Comment by lixiang810** [comment]
> Well, I do noticed that `friend` is now an available type for projects in blog. But is there anyway to set a avatar for each friend?

How to use it? I can't find the document of it. I have to write a component myself.

**Comment by Mister-Hope** [comment]
Do have plans, wait please. I majored in theoretical physics, and I don't have time coding all day.

**Comment by Sciroccogti** [comment]
> How to use it? I can't find the document of it. I have to write a component myself.

Just set the project type as `friend` here (although the doc hasn't introduced it yet): [项目](https://vuepress-theme-hope.github.io/v2/zh/guide/blog/home.html#%E9%A1%B9%E7%9B%AE)

**Comment by Mister-Hope** [comment]
Wow, I forgot that, I will add it soon in docs.

**Comment by lixiang810** [comment]
Anyway, I've implemented a [friend component](https://github.com/lixiang810/comb/blob/main/src/Friends.vue) myself. It works well with dark / light theme. The page example is [here](https://stblog.penclub.club/links/).

**Comment by luzhe0359** [comment]
> Wow, I forgot that, I will add it soon in docs.

Is friend link supported now

**Comment by Mister-Hope** [comment]
Track https://github.com/vuepress/ecosystem/issues/400
