### ISSUE TITLE
[Bug]V1无法使用vssue评论系统

### ISSUE THREAD

**Issue by QuinnTian** [vuepress-theme-hope/vuepress-theme-hope#1429]
## Describe the bug

按照文档配置号vssue插件后页面不显示，打开浏览器调试模式显示报错Unknown custom element: <CommentService> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

### 配置截图
![2022-01-27_13-03-06](https://user-images.githubusercontent.com/29975541/151295279-7e730221-3f69-4e31-a419-5288a8dd1e95.png)
### 报错截图
![2022-01-27_13-02-32](https://user-images.githubusercontent.com/29975541/151295315-f21583ac-3424-4f47-bb05-4e5387514910.png)
另外发现配置vssue后，运行时会多出下面框中警告
![2022-01-27_13-03-32](https://user-images.githubusercontent.com/29975541/151295334-3c80fec9-afb5-4c96-809b-c5d479940b43.png)

## Additional context

主题版本：vuepress-theme-hope@^1.27.2:
vuepress版本：vuepress@1.9.7

**Comment by Mister-Hope** [comment]
Fixed, will be released very soon
