### ISSUE TITLE
[Bug]FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by wyw-s** [vuepress-theme-hope/vuepress-theme-hope#1462]
## Describe the bug

我在githup上使用CI部署时，在build阶段出现js内存泄漏，在尝试使用 --max_old_space_size=4096后仍未解决

## Screenshots

![image](https://user-images.githubusercontent.com/56751617/153316993-9779a923-6490-40b8-8132-b819c6ea2900.png)

## Additional context

Add any other context about the problem here. Especially the issue occurs in certain OS, browser or configuation.

**Comment by Mister-Hope** [comment]
No responces, and command not increasing old space: https://github.com/wyw-s/documents/blob/master/.github/workflows/deploy.yml

**Comment by Mister-Hope** [comment]
请自行解决吧，我的博客页数和字数都应该是比你的多的。请自行参考workflow：https://github.com/Mister-Hope/Mister-Hope.github.io/blob/main/.github/workflows/deploy.yml
