### ISSUE TITLE
active-hash插件的一个小建议

### ISSUE THREAD

**Issue by kk305cs** [vuepress-theme-hope/vuepress-theme-hope#1485]
# 问题描述
点击右侧导航第一个标题后，页面会先滚动到第一个标题处，之后自动回滚到顶部，同时地址栏的hash也会清除掉
# 需求
点击第一个标题后，页面会滚动到第一个标题处，此时停止，不会自动滚动到顶部，地址的hash为第一个标题
# 插件源代码
vuepress-plugin-active-hash的rootMixin.js -》 // try to remove hash处
![image](https://user-images.githubusercontent.com/26682400/154662005-f9fe1591-d808-4dff-b5c5-5f8760dc18ac.png)
# 建议
在此做一个判定，如果scrollTop为0是再清除地址栏的hash
> 只是一个小建议，思路仅做参考

**Comment by Mister-Hope** [comment]
有复现地址么？

https://user-images.githubusercontent.com/33315834/154682242-d15cf940-1ab1-4229-bca9-a122251c7e12.mp4

我似乎不能复现你说的情况。

**Comment by kk305cs** [comment]
> 有复现地址么？
> 
>  1645186903625.mp4 
> 我似乎不能复现你说的情况。

我们目前没有上线 所以没有地址

**Comment by Mister-Hope** [comment]
你可以自己调offset，插件提供了相关选项

另外vue2无关的项目建议用v2项目。v2发布后，v1只提供安全修复。

**Comment by Mister-Hope** [comment]
欢迎你尝试自己去调整插件提供的offset 选项来看看能不能解决此问题，欢迎进一步反馈，如果可以，那你可以调整一下，也许是你页面布局高度的问题。至少主题和插件文档的确没有这个问题。

**Comment by Mister-Hope** [comment]
Closed as no further response for a week
