### ISSUE TITLE
[Feature Request] Add markdown-it-pangu

### ISSUE THREAD

**Issue by lixiang810** [vuepress-theme-hope/vuepress-theme-hope#1505]
## Describe the feature and why you wanted

[markdown-it-pangu](https://github.com/Shigma/markdown-it-pangu) is a plugin that adds spaces between CJK texts and latin texts. Although we can apply it to markdown-it manually in config file, add it to theme options would be better for those who are new users.

As it contains some bugs, you can add a option for users to enable or disable it.

**Comment by Mister-Hope** [comment]
You are free to use any markdown-it plugins yourself by creating a local plugin, and we already provide docs about that, See https://v2.vuepress.vuejs.org/reference/plugin-api.html#extendsmarkdown

**Comment by Mister-Hope** [comment]
This is out of my consideration because it's not useful to non-Chinese people.

Also, prettier is providing this. Try it if you like.

**Comment by Mister-Hope** [comment]
Here is a demo: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABIcNNDq2gRgDpSGC0cpoDEqCA5gDYCWAzgBboDuEATgCaDvtoEnGAtrQAetKJRAAaEBAAOMWtHrJQAQ3bsILAApqESlCuosVATyVSARuxVgA1nBgBlFfzgAZUXGQAzQ-TiW1nYOjjI2ouJIMOwArgEgcPwWcJycKW4qYjEqlHAAYhz8KjDyYsggKjEwEJIgjDD81ADqjLTw9GFgcI56bbQAbm0m5WD05iCi-uwwWtaURT5+8QBW9EKOEdRwAIoxEPCL1P5SYexT5UXstpyaULUy7KIwTbScMIzIABwADCca-k1rDJyg84FN+l4pABHPbwWayfQVegAWigcBSKVq7DgMNo2NmOQWSF8R3i-kEyGicSk9E2O1hXmJSykMBUFhebw+SAATCzrLQ6GIAMIQfhEhL0ACstRi-gAKmz9CTjiB+nEAJJQNKwRxgR5yACCWscMBMW0O-gAvpagA
