### ISSUE TITLE
[Feature Request] Articles about how to write a component

### ISSUE THREAD

**Issue by scil** [vuepress-theme-hope/vuepress-theme-hope#1529]
我正在改写一个编辑md的插件 https://github.com/scil/vuepress-plugin-editable2/ 
但现在运行出错。我觉得有几个地方不明白，可能导致了出错：
1. [rollup.config.js](https://github.com/scil/vuepress-plugin-editable2/blob/main/rollup.config.js) 
2. [appEnhance]([appEnhance.ts](https://github.com/scil/vuepress-plugin-editable2/blob/main/src/client/appEnhance.ts))

如果能发布一篇如何写插件的文档，我想可以尽快解决问题。

**Comment by Mister-Hope** [comment]
I would like to help. But this feature request will probably be posted [here](https://github.com/Mister-Hope/Mister-Hope.github.io).

**Comment by Mister-Hope** [comment]
Also, do not expect too much, this task will have a every low priority, you may not even see the article in March.

**Comment by Mister-Hope** [comment]
I am not sure, but I think current contribution guide is enough to explain what I am doing.

https://vuepress-theme-hope.github.io/v2/zh/contribution.html

Also appEnhance cookbook is already at https://v2.vuepress.vuejs.org/zh/advanced/cookbook/usage-of-client-app-enhance.html.

I will close this one if there is no further reponse in 7 days.
