### ISSUE TITLE
[Bug] 生成的静态首页features区块点击不跳转

### ISSUE THREAD

**Issue by hjue** [vuepress-theme-hope/vuepress-theme-hope#1534]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-theme-hope

### Version

v1

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

dev模式下features区块点击可以跳转，但生成的静态首页features区块点击不跳转。 hope版本是1.28.1。

请问有什么思路排查这个问题？

**Comment by Mister-Hope** [comment]
给一个复现地址吧

**Comment by hjue** [comment]
网站地址是：[https://hjue.top/cloud/](https://hjue.top/cloud/)

另有侧边栏也有同样的问题，根菜单链接点击不跳转。

本机dev下都是正常的

**Comment by Mister-Hope** [comment]
你好，你部署的网站并未成功启动 VuePress App 实例，无论是搜索、代码块复制、外观弹窗、侧边栏等均为工作，换句话说你看到的页面只是纯 HTML 和 CSS 渲染的结果。

建议：

1. 使用 `npm create vuepress-theme-hope [dir]`  创建新模板，并确认模板在你的环境下能否正常工作
2. 如 1 正常，请自行重新逐步迁移你的文档，并尝试自查问题
3. 如 1 不正常，请打开一个新的issue，并贴出你的模板仓库 （需要将依赖 lock 文件上传），并给出有问题的模板部署地址 （你可以用 Github Pages或者netlify之类的）。

**Comment by Mister-Hope** [comment]
@hjue https://vuepress-theme-hope.github.io/v1-demo/ 另外由于主题目前 V1 Demo 一切正常工作，应该可以排除是主体的问题，可以检查自己环境，或者考虑是否依赖树上某个新的版本引发了故障。

**Comment by hjue** [comment]
问题解决了。

我把demo项目里package.json覆盖了我项目里的package.json，build后竟然问题解决了。

就是没想明白为什么会这样？
