### ISSUE TITLE
[Bug] docsSeach's popup does not disappear

### ISSUE THREAD

**Issue by Zhengqbbb** [vuepress-theme-hope/vuepress-theme-hope#1562]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-theme-hope

### Version

v2

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

Using **keyboard** .The docsSeach plugin popup does not disappear.

https://user-images.githubusercontent.com/40693636/157870217-49b3a7f4-2adc-4199-86ff-7c184da294f5.mp4

### Additional context

I initially suspect that this is not a bug of the theme. It's on the plugin. But I have already debugged this problem, it is very strange, please take a look at Mr. Hope🤔

issue: [vuepress-next/issues/607](https://github.com/vuepress/vuepress-next/issues/607)

**Comment by Mister-Hope** [comment]
Closed as bug comming from upper chain.
