### ISSUE TITLE
article detail is not render

### ISSUE THREAD

**Issue by maclxf** [vuepress-theme-hope/vuepress-theme-hope#1569]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-theme-hope

### Version

v2

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### article not render

when chose no mutiple languages, `npm run docs:dev` article detail will not render
![image](https://user-images.githubusercontent.com/16398708/158136492-b63a4cd2-a79b-468c-a1ec-599cba482eae.png)
![image](https://user-images.githubusercontent.com/16398708/158136389-f878ea82-9ca0-4427-aa67-0c7d8382fce9.png)

**Comment by artjourney** [comment]
同样的错误

**Comment by Mister-Hope** [comment]
try removing structure keyword in sidebar, it will be fixed in next version

**Comment by artjourney** [comment]
Thanks, I have resolved the issue now.
