### ISSUE TITLE
themeConfig.git.contributor设置成false后，依然显示 “贡献者”，不起作用？

### ISSUE THREAD

**Issue by xlvchao** [vuepress-theme-hope/vuepress-theme-hope#1592]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-theme-hope

### Version

v1

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

themeConfig.git.contributor设置成false后，依然显示 “贡献者”，不起作用？

![image](https://user-images.githubusercontent.com/33950671/159085477-f1337ac5-1b6c-455a-84b1-94ac7d856888.png)

![image](https://user-images.githubusercontent.com/33950671/159085579-a17e82c6-a980-416a-8ab2-3e0d3f3e041b.png)

**Comment by Mister-Hope** [comment]
Typos in docs is fixed
