### ISSUE TITLE
没有配置评论插件，并且页面配置了visitor: false，但是浏览量图标依然存在，盼修复

### ISSUE THREAD

**Issue by xlvchao** [vuepress-theme-hope/vuepress-theme-hope#1594]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-theme-hope

### Version

v1

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

![image](https://user-images.githubusercontent.com/33950671/159111969-d21fee33-6448-4f04-807a-e9cf87e7eaad.png)

上图，我没有配置评论插件、并且页面配置了visitor: false，但是如图所示浏览量图标依然存在

理论上只有当我配置了 Valine  它才应该存在，没有配置评论插件或是配置的是其他评论插件，浏览量都不应该存在

**Comment by Mister-Hope** [comment]
Remove `'visitor'` in `themeConfig.pageInfo` is a possiable workaround.

**Comment by Mister-Hope** [comment]
Closed as no Contribution and having workaround

**Comment by Mister-Hope** [comment]
This issue should be fixed.
