### ISSUE TITLE
[Bug] Import css/scss from node_modules

### ISSUE THREAD

**Issue by jannikbuscha** [vuepress-theme-hope/vuepress-theme-hope#1630]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-theme-hope

### Version

v2

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

how can i load a css/scss from a third-party framework?

i tried it via the head stylesheet import, which just didn't work (gave 404 in the console)
and simply via import `"remixicon/fonts/test.css";` which causes this error:
![image](https://user-images.githubusercontent.com/74017697/161387471-990f5fd1-39bb-44a7-bc52-1764d6711e35.png)

the only way that worked for me was to drop it directly into /public but it would be cool to load it directly from the node_modules.

**Comment by Mister-Hope** [comment]
Please ask vuepress related questions in vuepress repo dicussion.

You should import that in app client enhance files.

**Comment by Mister-Hope** [comment]
See https://v2.vuepress.vuejs.org/advanced/cookbook/usage-of-client-app-enhance.html
