### ISSUE TITLE
[Bug] custom themeConfig.blog.medias not work.

### ISSUE THREAD

**Issue by oldshensheep** [vuepress-theme-hope/vuepress-theme-hope#1631]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-theme-hope

### Version

v2

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

配置例子
```
    medias: {
      'abc': ["https://abc.com", 'svg string'],
    },
```
log警告： ⚠ abc icon in blog media config not found!

debug了一下初步定位到问题出在https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/17c43e7df9d5f5adc97d32b8f7b047c5556b398c/packages/theme/src/node/socialMedia.ts#L66
打印themeConfig.locales['/'].blog.medias的结果
```
    medias: {
      'abc': "https://abc.com",
    },
```
Array变成了Array的第一个元素

**Comment by Mister-Hope** [comment]
用脑子或者用心看文档

**Comment by oldshensheep** [comment]
配置没问题，svg string是一个有效的svg字符串。

**Comment by Mister-Hope** [comment]
你把你配置贴过来

**Comment by Mister-Hope** [comment]
See https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/68c21ef41e438f70a7fb3a1136c27b96a9b1e2c2 to learn how to config, and see https://vuepress-theme-hope.github.io/v2-demo/ for a living demo

**Comment by Mister-Hope** [comment]
Try not to waste others time, provide reproduction repo when opening issues helps you find your problem, or can save open source project contributor time to see your mistake.
