### ISSUE TITLE
[Bug] custom themeConfig.blog.medias not work. #1631 

### ISSUE THREAD

**Issue by oldshensheep** [vuepress-theme-hope/vuepress-theme-hope#1641]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-theme-hope

### Version

v2

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

昨天睡觉了就没有回。
具体复现步骤
```
git clone https://github.com/oldshensheep/demo.git
cd demo
yarn install
yarn docs:dev
```
output
```
……
vuepress-theme-hope:  ⚠ MrHope icon in blog media config not found!
……
```

**Comment by Mister-Hope** [comment]
Fixed in https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/62430044e8e010f83012c0466f33b88249a8c4ae

**Comment by Mister-Hope** [comment]
Workaround:

```ts
export defauilt defineThemeConfig({
  locales: {
    "/": {
      blog: {
        // ...
        media: {
          // ...
        }
      }
    }
  }
}):

```

**Comment by Mister-Hope** [comment]
You can config like this before new version, thanks for pointing out this.
