### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by karani12** [vuepress-theme-hope/vuepress-theme-hope#1646]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-theme-hope

### Version

v2

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

Hello, I have been working with the vuepress and it's theme.
I followed this process:

- Cloned vuepress next

- Added blog plugin-2

-  Followed the example given 

- Added all the files and configurations

- Ended up with this: [Error recreated](https://github.com/karani12/vuepress-next/tree/recreate-error/docs). 

- Tried accessing /article/ page and I get an error.

### Additional context

I'm not sure if it's a bug but you can check the repo where I recreated the problem.

Thanks.

**Comment by Mister-Hope** [comment]
Is there any special reason that you must use vuepress fron main branch instead of latest `next`?

**Comment by Mister-Hope** [comment]
Also, you are supposed to meet issues because dumplicate vue version installed in the repo.

**Comment by karani12** [comment]
> I would expected a simple demo with only a few files to debug with.slightly_smiling_face

Sorry but that is the only way the bug appears.

**Comment by Mister-Hope** [comment]
Allways run `yarn install && yarn upgrade` instead of simple `yarn install` . `yarn upgrade` makes sure that you are not using a wrong deps tree.

**Comment by Mister-Hope** [comment]
A dumplicate vue version will probably lead to different vue instance in VuePress App, so that the app probably won't work. vue3 has `vue` and `@vue/xxx` package, and also you may check `vue-router` as well.

**Comment by karani12** [comment]
> A dumplicate vue version will probably lead to different vue instance in VuePress App, so that the app probably won't work. vue3 has `vue` and `@vue/xxx` package, and also you may check `vue-router` as well.

The error occurs even when I install it in a workspace

**Comment by Mister-Hope** [comment]
I will closed this one as there are already issues on your side. I will only make sure that I am compatable when meteorlxy releasae a new vuepress version, so as long as the plugin works with latest vuepress@next released.

You'd better double check that only 1 version of `@vue/xxx` `vue` `vue-router` `@vuepress/xxx` are installed in your repo.

Free free to open a new isssue if you make sure that.
