### ISSUE TITLE
[Feature Request]Customize sidebar title

### ISSUE THREAD

**Issue by FuckDoctors** [vuepress-theme-hope/vuepress-theme-hope#1647]
### Describe the feature

![image](https://user-images.githubusercontent.com/1180450/161791586-739dc7bf-6b1f-481c-a353-57d43fc600bc.png)

能否提供一个控制侧边栏标题的功能，比如`frontmatter`的`sidebarTitle`或`siderbar.title`?

目的：
如上图所示，JavaScript深入浅出下面的`README.md`的文档名，在侧边栏中显示目录或概述，在右侧内容区还是显示原来的`title`，即“JavaScript深入浅出”。
注：上图中的侧边栏是自动从目录结构中生成的。

已知可以通过`dir.text`可以控制目录名的显示，但是右侧内容区的标题和面包屑导航内的标题不是`dir.text`的内容。
另外，虽然可以通过`index: false`设置隐藏，但是还是希望能显示。

**Comment by Mister-Hope** [comment]
> 能否提供一个控制侧边栏标题的功能，比如frontmatter的sidebarTitle或siderbar.title?

我们支持对象式的配置，详见文档

**Comment by FuckDoctors** [comment]
对象式是可以，想省事，能提供在自动生成的结构的基础上，自己在定制的能力吗
比如对象式里的`siderbar.text`在frontmatter中可以定制的能力？

**Comment by FuckDoctors** [comment]
好的，那自己自定义吧，谢谢

**Comment by Mister-Hope** [comment]
We will add this in next version. As some people would like to config this in pages.

**Comment by Mister-Hope** [comment]
我重新读了一下，我觉得你的需求可能跟侧边栏还没有关系。

你可能需要的是 `title` 和 `shortTitle`，然后在页面标题和SEO使用title，而在路径导航，侧边栏中使用shortTItle是吧。

**Comment by FuckDoctors** [comment]
> 我重新读了一下，我觉得你的需求可能跟侧边栏还没有关系。
> 
> 你可能需要的是 `title` 和 `shortTitle`，然后在页面标题和SEO使用title，而在路径导航，侧边栏中使用shortTItle是吧。

是这个意思 :sweat_smile:
我想的可能跟你想要做的不是一个意思。。

我想要的下面这样，原来左侧默认显示title，我改成可以自定义了，右侧还是原来的title
![image](https://user-images.githubusercontent.com/1180450/163393699-12b07945-dfe8-45e5-864d-cc606a794f89.png)

**Comment by Mister-Hope** [comment]
> > 我重新读了一下，我觉得你的需求可能跟侧边栏还没有关系。
> > 你可能需要的是 `title` 和 `shortTitle`，然后在页面标题和SEO使用title，而在路径导航，侧边栏中使用shortTItle是吧。
> 
> 是这个意思 😅 我想的可能跟你想要做的不是一个意思。。
> 
> 我想要的下面这样，原来左侧默认显示title，我改成可以自定义了，右侧还是原来的title ![image](https://user-images.githubusercontent.com/1180450/163393699-12b07945-dfe8-45e5-864d-cc606a794f89.png)

那请问你把这样一个页面放在侧边栏里的用意何在？

**Comment by FuckDoctors** [comment]
意义不是太大。。
我考虑主要用来写笔记时，文件夹名显示类似“书名”，README.md的在左侧显示类似“前言”的东西，首页上在显示类似“目录”
虽然左侧菜单也会出来所谓的“目录”。。

![image](https://user-images.githubusercontent.com/1180450/163395290-10168a6b-14e2-41ef-b3e8-b52607d33ebc.png)

**Comment by Mister-Hope** [comment]
Use another implementation in https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/5bbf82391cff16a95bea68e6fcd4929a0ae01820.

Related docs will be updated later.
