### ISSUE TITLE
[Feature Request] SEO: Add canonical tag option

### ISSUE THREAD

**Issue by vmihailenco** [vuepress-theme-hope/vuepress-theme-hope#1663]
### Describe the feature

The plugin should automatically add a self-referencing canonical tag, .e.g.

```html
<link rel=“canonical” href=“https://example.com/sample-page.html” />
```

I suggest to add it to vuepress-plugin-sitemap2 instead of SEO plugin, because sitemap2 plugin already knows about the `hostname` so it can generate the absolute URL.

```ts
['vuepress-plugin-sitemap2', { hostname: 'https://get.uptrace.dev', canonicalTag: true }],
```

See [this](https://www.botify.com/blog/the-top-10-questions-about-canonical-tags-answered) about why canonical tags are useful.

**Comment by Mister-Hope** [comment]
Thanks for the idea, but I would refuse to add this feature. Busy now, I will explain later.

**Comment by Mister-Hope** [comment]
Hi, here is the detailed descrption:

> Yes, it’s normally considered best practice to add a self-referencing canonical tag. A self-referencing canonical tag, as it sounds, is one that canonicals to itself. This ensures that multiple versions of the page (duplicates) don’t get indexed separately.
>
> For example, the page https://www.example.com would have a rel=”canonical” tag that points to https://www.example.com (the same URL). This would prevent alternate versions of the same page such as https://example.com from getting indexed.
>
> It’s also OK to not have a self-referencing canonical tag. Just keep in mind that Google will then choose one URL as the canonical and it may not be the version you prefer.

Google and other search engine always prefer to choose the one indexed earlier, and have more visitors.

This is obvious because the expected behavior or search engine is to remain index an original site (e.g.: React document) 
 without Canonical Tag covered by a mirror site with canoical tag referencing itself. As far as I now, adding a canonical tag to another page is a very strong behavior lowing priority of oneself, but little or no priority increasement refering others.

In another word:

- a -> b
- b

works effectively while:

- a
- b -> b

has very little effect.

So, IMO, only if you need this tag, shall you add a  canonical tag referencing original one in other pages.

2. Canonical Tag is not related to sitemap at all, it must be added in the seo plugin.

I may add a new option `canonicalTag` supporting function and string, so that users can do the following thing:

```ts
// when building https://vuepress-theme-hope.gitee.io/v2/ for v2 docs
['seo2', { 
  // ...
  canonicalTag: 'https://vuepress-theme-hope.github.io/v2/'
}],
```

or

```ts
// when building https://vuepress-theme-hope.gitee.io
['seo2', { 
  // ...
  canonicalTag:  (page) => 'https://vuepress-theme-hope.github.io/v2' + page.path
}],
```

**Comment by vmihailenco** [comment]
>Google and other search engine always prefer to choose the one indexed earlier, and have more visitors.

This is a common recommendation - just google "self-referencing canonical tag" and you'll get lots of results from reputable sources.

>So, IMO, only if you need this tag, shall you add a canonical tag referencing original one in other pages.

This is usually not possible when you do reposts on 3-rd party platforms / blogs.

>I may add a new option canonicalTag supporting function and string, so that users can do the following thing:

The 2nd option looks nice :+1: 

```
// when building https://vuepress-theme-hope.gitee.io
['seo2', { 
  // ...
  canonicalTag:  (page) => 'https://vuepress-theme-hope.github.io/v2' + page.path
}],
```

**Comment by Mister-Hope** [comment]
> This is a common recommendation - just google "self-referencing canonical tag" and you'll get lots of results from reputable sources.

Nope, bing,com even do not recommand self refernce canonical  tag.

I searched bing, google and other search engines guideline, NONE of them says that people should adding a self refernce canonical  tag pointing to current link, and NONE of them says that setting this as ANY effects. (e.g.: https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls)

So I prefer "Addning a self refernce canonical  tag has no effect and not needed".

You need to proof this by any W3C spec, profession docs like MDN, or any search engine guide book, instead of "google and see what other guys are taling"

A lot of content  may actually be wrong by a simple google . I met this before in building PWA plugin, so I do not trust any 3rd party article.

**Comment by Mister-Hope** [comment]
Also, when people deploy same content in differnt domains or under https(s), with or without `www.`, your original idea will lead to a wrong result, or in another word, a pretty bad practice.

**Comment by Mister-Hope** [comment]
> I may add a new option canonicalTag supporting function and string

You will see this in next release, and if you inist Addning a self refernce canonical tag with current link is a better practice, prove me with some authoritative contents.

**Comment by vmihailenco** [comment]
>You will see this in next release

Thanks.

>google and see what other guys are talking

ahrefs is not "some other guys".

**Comment by Mister-Hope** [comment]
They are, everyone except w3c are other guys, but search engine is the boss so if they do not follow, we care about them either.

**Comment by Mister-Hope** [comment]
Let me show you to correct way discussing this:

1. Visit w3c and find html spec then open it
2. Search related link ref=canonical, and you will find https://html.spec.whatwg.org/multipage/links.html#link-type-canonical
3. Dig into related rfc(i.e.: rfc6596)


This is the way I insist talking technology things.

**Comment by Mister-Hope** [comment]
I am serious about any tech things, and your idea already costs me more than an hour.

So it's better that you make sure what you are reporting, rather then making a couple of minutes google and find some content then pasting in.

**Comment by vmihailenco** [comment]
It is not my idea. There are tons of materials from experts in this area saying that this thing may help. If you don't want to use - just don't. What's the problem?

>Your replys are all plain and week to me

I thought we agreed on adding this so users can decide themselves

```ts
['seo2', { 
  // ...
  canonicalTag:  (page) => 'https://vuepress-theme-hope.github.io/v2' + page.path
}],
```

So about what we are arguing now?

>but currently I not seeing related content

Perhaps you have not seen the link in the first post, so here are 3 more

- https://ahrefs.com/blog/canonical-tags/
- https://moz.com/learn/seo/canonicalization
- https://yoast.com/rel-canonical/#self-referencing

And [thousands more](https://www.google.com/search?q=self-referencing+canonical+tag)

**Comment by Mister-Hope** [comment]
Again, you waste my another half hour.

---

The first link you provided quote a sentence says 

![image](https://user-images.githubusercontent.com/33315834/162613998-2fe9c178-f323-441e-9a5c-0f1630cd3f15.png)


But it's only a google Analyst or expert, while he said that in a video, see https://www.youtube.com/watch?v=XOGOhWyNSf8&t=484s 

If you watch the full video, you will find out he is trying to explain that it's necessary when you have parameters which influence the page content, such as pangination. Which is the same as the third one.

---

The second one only says slefrenference is allowed., while says nothing that we should do that and it's recommanded. 

---

The third one is referencing this artilce, which renfernce the same video (which actually a video talk) http://www.thesempost.com/using-rel-canonical-on-all-pages-for-duplicate-content-protection/

and the centerual point is:

> Sometimes URLs with URL parameters – such as parameters used for tracking or advertising – end up being indexed.  And while duplicate content isn’t a penalty per say, there is the possibility it can cause issues, particularly if a URL parameter URL ends up being linked, which often happens when others link to a page they may have originally clicked through from a social media site or ad campaign.   Other reasons we see this being used is for www versus non-www (although preferred domain in Google Search Console should definitely be used for this), pagination, depending on how your server handles upper and lower case characters within the URL, as well as for PageRank reasons.

Which is something I agreed, but don't mean that adding a self renference tag has any meaning to any search engine including google itself.

---

And, I strongly doubt that a google webmaster Trends Analyst 's desription in a video talk has so strong meaning, that beyonds all people around the world to do this, well this is totally not seen in any search engine seo guidebook or w3c sepc and related RFC.
---

### In another word, you still failed to show any preciseness research and materials proofing that self reference is needed.

For other tag, I can give you related sepc or RFC why we need those, but not this one.

**Comment by Mister-Hope** [comment]
Actually back to 2 years I started building seo plugin for vuepress1, I had noticed this tag, and I finally give up adding that tag because it's really not necessary to have one in a normal page.
