### ISSUE TITLE
[Feature Request] SEO: add SEO-friendly redirects

### ISSUE THREAD

**Issue by vmihailenco** [vuepress-theme-hope/vuepress-theme-hope#1664]
### Describe the feature

For example, when URL is changed from `/foo/` to `/bar/`, vuepress should redirect users accordingly. There is an [existing issue](https://github.com/vuejs/vuepress/issues/239) that recommends doing something like this:

```ts
export default defineClientAppEnhance(({ app, router }) => {
  router.beforeResolve((to, from, next) => {
    const redirectMap = {
      '/foo/': '/bar/,
    }

    const redirect = redirectMap[path]
    if (redirect) {
      window.location.href = redirect
    } else {
      next()
    }
  })
})
```

That is better than nothing, but is not SEO-friendly and does not work if `/foo/` is cached or the generated page is not removed when deploying (s3 sync does not do that by default).

A better approach is to copy what https://github.com/mkdocs/mkdocs-redirects are doing. Basically, they generate a HTML page with a canonical rel tag and a redirect, for example:

```html
curl https://pg.uptrace.dev/zfs/

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Redirecting...</title>
    <link rel="canonical" href="https://bun.uptrace.dev/postgres/tuning-zfs-aws-ebs.html">
    <meta name="robots" content="noindex">
    <script>var anchor=window.location.hash.substr(1);location.href="https://bun.uptrace.dev/postgres/tuning-zfs-aws-ebs.html"+(anchor?"#"+anchor:"")</script>
    <meta http-equiv="refresh" content="0; url=https://bun.uptrace.dev/postgres/tuning-zfs-aws-ebs.html">
</head>
<body>
Redirecting...
</body>
</html>
```

Is this something that vuepress plugin could do?

**Comment by Mister-Hope** [comment]
Possible I think, will be added in next release.

**Comment by vmihailenco** [comment]
Thanks, let me know if you need help with testing.

**Comment by Mister-Hope** [comment]
I would like to make this a new plugin

Options proposal would be nice if you can add one.

**Comment by vmihailenco** [comment]
If I understand correctly, something like this:

```js
['vuepress-plugin-redirects', {
    redirectTo: ''https://domain.com'',
    redirects: {
        // generates /guide/foo.html that redirects to https://domain.com/guide/bar.html
        "/guide/foo.html": "/guide/bar.html",

        "/guide/foo/index.html": "/guide/bar/",
        "/guide/foo.html": "https://other-domain.com/guide/bar.html",

        // Optional; first version does not need to support this
        // without clean urls: /guide/foo.html => https://domain.com/guide/bar.html
        // with clean urls: /guide/foo/ => https://domain.com/guide/bar/
        "/guide/foo.md": "/guide/bar.md",
    },
}]
```

**Comment by vmihailenco** [comment]
PS The plugin should also set `sitemap.exclude = true` on the generated pages to exclude them from the sitemap. That probably requires some specific plugin init order - not sure.

**Comment by Mister-Hope** [comment]
Nope. this is not the api, I want. First, the plugin should suppot a simple map, as you describe. But the plugin should at least support a function, which can return a map with app as parameter. (So that we can get pages)

E.g.:  when user rename `post` folder to `posts` they could have ability to generate a `post/xxx` redirection to `posts/xxx` for all pages.

Also, we may provide addtional options ( which probably can achiveve by the function, but can benifit the user). This is the part we need to think.

So the option design needs to be worked out first.

> The plugin should also set sitemap.exclude = true on the generated pages to exclude them from the sitemap. 

Nope, that's not something this plugin should do. Each plugin should complete its own job, without trying to couple with others.

My idea is that I will generate html files for these pages in the `onGenerated` hook,. so that they won't actually be vuepress pages at all.

**Comment by vmihailenco** [comment]
Any reasons you've removed `meta refresh` redirects? That is the recommended way by Google that should be preferred and used with JS redirects - https://developers.google.com/search/docs/advanced/crawling/301-redirects#overview-of-redirect-types

**Comment by Mister-Hope** [comment]
I will add that in next version.

Also I will provide a cli tool to generate a redirect site when people changed their base.

**Comment by vmihailenco** [comment]
Thanks :+1:

**Comment by Mister-Hope** [comment]
This is just the first edition, this plugin needs to be improved with more useful features.

**Comment by vmihailenco** [comment]
I also noticed that you use backticks formatting in the generated JS which may not work in some browsers - https://caniuse.com/template-literals. Is that an overlook or was intended?

**Comment by Mister-Hope** [comment]
If you want to use VuePress2 based on Vue3, browsers MUST support proxy

![image](https://user-images.githubusercontent.com/33315834/163529404-bc5cb34f-9c66-4e1a-9125-d58d2c41e302.png)
![image](https://user-images.githubusercontent.com/33315834/163529428-c66ec463-67cf-431a-8557-b8627d30e103.png)

So what's the problem?

**Comment by vmihailenco** [comment]
Thanks for claryfying.
