### ISSUE TITLE
[Query] Dim non focused area.

### ISSUE THREAD

**Issue by e0lithic** [vuepress-theme-hope/vuepress-theme-hope#168]
Hi,

First of all thanks for the great work. 

Is there a way we can dim other areas of the screen when the user is reading or scrolling through the main content. As is done in the case of nuxt.js [documentation](https://nuxtjs.org/guide).

Thanks

**Comment by Mister-Hope** [comment]
Great advice, I will add this function in 0.2.0

**Comment by Mister-Hope** [comment]
#438 will probably add this feature.

**Comment by Mister-Hope** [comment]
Nuxt no longer uses this, and I am not finding any other docs which is currently using this. So I will close this.
