### ISSUE TITLE
[Bug] redirect2: plugin does not create directories

### ISSUE THREAD

**Issue by vmihailenco** [vuepress-theme-hope/vuepress-theme-hope#1683]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-plugin-redirect2

### Version

v2

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

For example, when I migrate from other doc generator I want to redirect `/cluster/` to `/guide/cluster.html`:

```js
config: {
  // redirect /cluster/ to /guide/cluster.html
  '/cluster/index.html': '/guide/cluster.html',
}
```

The error:

```
Error: ENOENT: no such file or directory, open '[STRIPPED]/docs/.vuepress/dist/cluster/index.html'
```

Looks like the plugin must create the directory first before writing to the file.

**Comment by Mister-Hope** [comment]
Nice catch
