### ISSUE TITLE
[Bug] redirect2 beta.42: Cannot find module './extends'

### ISSUE THREAD

**Issue by vmihailenco** [vuepress-theme-hope/vuepress-theme-hope#1684]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-plugin-redirect2

### Version

v2

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

After upgrading to vuepress-plugin-redirect2 v2.0.0-beta.42 from beta.41 I get the following error:

```
Error: Cannot find module './extends'
Require stack:
- /my-docs/node_modules/vuepress-plugin-redirect2/lib/node/plugin.js
- /my-docs/node_modules/vuepress-plugin-redirect2/lib/node/index.js
- /my-docs/node_modules/@vuepress/core/lib/app/resolvePluginModule.js
```

/lib/node/plugin.js looks like this:

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.redirect = exports.redirectPlugin = void 0;
const extends_1 = require("./extends");
const generate_1 = require("./generate");
const utils_1 = require("./utils");
const redirectPlugin = (options) => {
...stripped...
```

And there is no `extends.js` file in the plugin directory.

Is it the same for you or I've broken my setup somehow?

**Comment by Mister-Hope** [comment]
Oh, the release is probably broken.....

**Comment by Mister-Hope** [comment]
Beta.43 published.
