### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Jarvis2018** [vuepress-theme-hope/vuepress-theme-hope#1698]
### Describe the feature

问题：在宽屏中，内容区域有点窄，导致和右侧导航栏间距很大。当我文档中有个内容很多的表格时，内容不会自动撑开。
建议：文档的内容宽度能够适应宽屏；

**Comment by Mister-Hope** [comment]
你可以自行更改content-width css变量。

目前的最大内容宽度符合网页设计规范。太宽的文字段落会导致人在正常阅读到右侧时很难回头准确找到下一行，而且可能涉及到频繁转头的问题。
