### ISSUE TITLE
[Bug report] logoDark src property take the logo src property

### ISSUE THREAD

**Issue by a670485** [vuepress-theme-hope/vuepress-theme-hope#1729]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-theme-hope

### Version

v2

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Hello ,
you have a mistake in the module "NavbarBrand.ts". The src property of logoDark take the value of src property of the logo.

See you below the correction
![bug logoDark](https://user-images.githubusercontent.com/37690211/165707026-8de48ac7-c2d7-4e9d-b495-5a756efd7d00.png)

**Comment by Mister-Hope** [comment]
Bug confirmed, thanks for pointing out.

Currently new verions are blocked by #1717, and #1717 is blocked by https://github.com/vuepress/vuepress-next/issues/795, so please be patient.

You can currently make a workaround with https://vuepress-theme-hope.github.io/v2/cookbook/advanced/replace.html#replace-components

**Comment by Mister-Hope** [comment]
Fixed in https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/1df15f043188764bd3dd0dad3d16961aea61be6b
