### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by raisty** [vuepress-theme-hope/vuepress-theme-hope#1756]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-theme-hope

### Version

v2

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

```
[plugin:vite:import-analysis] Failed to resolve import "@vuepress/client/app" from "blog/.vuepress/.temp/vite-root/index.html?html-proxy&index=0.js". Does the file exist?

/Users/whatever/whatever/web-testblog/blog/.vuepress/.temp/vite-root/index.html:10:9

1  |  
2  |  import '@vuepress/client/app'
   |          ^
3  |
```

Seems like related to Vuepress and Vite as described here: https://theroadtoenterprise.com/blog/how-to-set-up-path-resolving-in-vite

Tested with:

```
"devDependencies": {
    "vuepress": "^2.0.0-beta.41",
    "vuepress-theme-hope": "^2.0.0-beta.47"
  }
```

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/1725
