### ISSUE TITLE
Inline math not supported[Bug]

### ISSUE THREAD

**Issue by raisty** [vuepress-theme-hope/vuepress-theme-hope#1758]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-theme-hope

### Version

v2

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

Math formulas are not working inline.

Example:

not working

```md
Crandall primes $$(2^k-c)$$
```

working

```md
Crandall primes
$$(2^k-c)$$
```

**Comment by Mister-Hope** [comment]
![Screenshot_2022-05-02-03-28-09-85_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/33315834/166161557-f25b13a1-5d01-46c3-8609-4d588b77fdda.jpg)

Plz read docs carefully.
