### ISSUE TITLE
[Bug] 將語言設置為 zh-TW 導致閱讀時間不顯示

### ISSUE THREAD

**Issue by nnn950711** [vuepress-theme-hope/vuepress-theme-hope#1809]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-theme-hope

### Version

v2

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

將公用路徑的預設語言定為 zh-TW 會導致 閱讀時間不顯示
![螢幕擷取畫面 2022-05-10 131058](https://user-images.githubusercontent.com/41001774/167546899-c5f27815-8366-49e5-839c-ea4e4bd24d07.png)
![螢幕擷取畫面 2022-05-10 131129](https://user-images.githubusercontent.com/41001774/167546905-df0693b8-424a-41eb-b726-32a93483f6eb.png)

配置文件
[config.txt](https://github.com/vuepress-theme-hope/vuepress-theme-hope/files/8657570/config.txt)

**Comment by Mister-Hope** [comment]
bug confirmed, will be fixed in next version

**Comment by Mister-Hope** [comment]
You can set locale option for reading time plugin as a workaround now.

**Comment by Mister-Hope** [comment]
Besides, could you help me check (and maybe improve) zh-TW locales among all plugins and themes? 🙂I think there might be differences between the two chinese language when expressing specific things.

Just search `locales.ts` in this repo (or `locales` folder).

**Comment by nnn950711** [comment]
> Besides, could you help me check (and maybe improve) zh-TW locales among all plugins and themes? 🙂I think there might be differences between the two chinese language when expressing specific things. Always feel free to open PRs or dicussions if you think that some locales can be improved.
> 
> Just search `locales.ts` in this repo (or `locales` folder).

ok
