### ISSUE TITLE
[Feature Request] support <Icon> Component 

### ISSUE THREAD

**Issue by trydofor** [vuepress-theme-hope/vuepress-theme-hope#1844]
### Describe the feature

like `<Badge>` component, support `<Icon>` to show iconfont/fontawesome

**Comment by Mister-Hope** [comment]
Unlike `<Badge>` is standalone with theme, `<Icon>` is coupled with theme, and needs global configuration.

Also I personally not found this useful, anyway thanks for your idea, and I extract the icon logic in to a component in https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/7b14c2d6d5fd53a742570955ab5e69f58c5335ea and you should be able to import `@theme-hope/components/Icon` and register it globally by your own, see https://vuepress-theme-hope.github.io/v2/cookbook/advanced/component.html for more details.

**Comment by trydofor** [comment]
temporarily use `@vuepress/plugin-register-components` register a Component like following
```vue
<template>
  <i :class="['icon',  iconPrefix + icon]"></i>
</template>

<script setup lang="ts">
import { defineProps } from 'vue';
import { themeOption } from '../configs/theme';

defineProps<{
  icon: string;
}>();

const iconPrefix = themeOption.iconPrefix || '';
</script>

<style scoped>
</style>
```
