### ISSUE TITLE
Adding more components

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress-theme-hope/vuepress-theme-hope#1847]
### Describe the feature

Adding more components, including:

- [x] codepen @Mister-Hope 
- [x] pdf @Mister-Hope 
- [x] icon @Mister-Hope 
- [x] stackblitz @Mister-Hope 
- [x] audio player @Mister-Hope 
- [x] video player @Mister-Hope including bilibili and youtube special support

   Bilibili ref: https://www.bilibili.com/blackboard/webplayer_history.html#html5

- [x] new video player using https://github.com/vidstack/player/ Related: https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/2499 @MonoLogueChi 
- [x] catalog
- [x] share button @Mister-Hope
- [ ] Global Music Player
- ...
- more

**Comment by MonoLogueChi** [comment]
@Mister-Hope I think using artplayer is a better choice than vidstack. If you want, I can submit a pr related to artplayer in the near future.

**Comment by Mister-Hope** [comment]
Sure, also you an or your Cigna and other components, as well as card, friendlink and so on

**Comment by AndersonHJB** [comment]
很高兴你开启此问题，感谢🙏。我说明一下原因哈，因为 GitHub 对于 ts 识别是代码的，所以视频在分割之后会生成 m3u8 and 诸多的 ts 文件，所以 GitHub 间接可以变成低成本的视频存储。虽然国内很慢......

**Comment by FuckDoctors** [comment]
add Replit component (#2759)

**Comment by Mister-Hope** [comment]
Closing it.

There are other projects related with "global music player, and it's not hard to mount them at root in browser.
