### ISSUE TITLE
[Bug] MD034 - no-bare-urls syntax link cause build failure

### ISSUE THREAD

**Issue by trydofor** [vuepress-theme-hope/vuepress-theme-hope#1877]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-theme-hope

### Version

v2

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

the following autolink syntax is defined as [GFM#6.8Autolinks](https://github.github.com/gfm/#links)
`<https://v2.vuepress.vuejs.org/zh/>`
`<https://vuepress-theme-hope.github.io/v2/>`

and works well in `vuepress dev docs`.
but failed in `vuepress build docs` with errors
```
✔ Compiling with vite - done
✖ Rendering pages - failed
TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:3179:15)
    at createComponentInstance (node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5690:23)
    at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:168:22)
    at Object.ssrRenderComponent (node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:605:12)
...
```

i guess `<.../>` links ended with `/`  is parsed as Vue component

**Comment by Mister-Hope** [comment]
Could you provide a reproduction using online demo ?

**Comment by trydofor** [comment]
https://github.com/moilioncircle/moilioncircle.java-code-review/actions/runs/2362899981
is it ok? 
just use `<https://vuepress-theme-hope.github.io/v2/>` in any markdown file, and build docs.

**Comment by trydofor** [comment]
use this syntax, because [MD034 - no-bare-urls](https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md034) suggest.

**Comment by Mister-Hope** [comment]
Closing as it definitely can not be the theme problem.

If you write autolink, it's markdown-it duty to tranform it to an achor link, so that vue and vuepress can not infer it has an empty tag.

I believe you can achieve autolink convertion by setting `linkify: true` in markdown-it, while you can do that by setting markdown option in vuepress config file.

See https://github.com/markdown-it/markdown-it#init-with-presets-and-options and https://v2.vuepress.vuejs.org/reference/config.html#markdown

If your problem exisits, open an issue at vuepress repo.

**Comment by trydofor** [comment]
> I believe you can achieve autolink convertion by setting `linkify: true` in markdown-it, while you can do that by setting markdown option in vuepress config file.

I will try these.
there is a weird thing that only `build docs` failed, `dev docs` well
