### ISSUE TITLE
[Bug] Flowchart not working in dev server

### ISSUE THREAD

**Issue by Guyutongxue** [vuepress-theme-hope/vuepress-theme-hope#1892]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-plugin-md-enhance

### Version

v2

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Using flowchart will cause a `require is not defined` error in dev server.

```
Uncaught (in promise) ReferenceError: require is not defined
    at index.js:1:1
```
This error occurs in `index.js` of `flowchart.js` package:
```js
require('./src/flowchart.shim');
var parse = require('./src/flowchart.parse');
require('./src/jquery-plugin');
...
```

(I also get some errors when visiting the page generated by `build`, but I can't reproduce it now.)

### Additional context

`package.json`
```json
{
    "scripts": {
        "dev": "vuepress dev docs",
        "build": "vuepress build docs"
    },
    "devDependencies": {
        "@vuepress/client": "2.0.0-beta.45",
        "vue": "^3.2.36",
        "vuepress": "2.0.0-beta.45",
        "vuepress-plugin-md-enhance": "2.0.0-beta.71"
    }
}
```
`vuepress.config.ts`
```ts
import { defineUserConfig } from "vuepress";
import { mdEnhancePlugin } from "vuepress-plugin-md-enhance";
export default defineUserConfig({
    plugins: [
        mdEnhancePlugin({
            flowchart: true
        })
    ]
})
```
`docs/README.md`
~~~md
# Test

```flow
st=>start: Start|past:>http://www.google.com[blank]
e=>end: End|future:>http://www.google.com
op1=>operation: My Operation|past
op2=>operation: Stuff|current
sub1=>subroutine: My Subroutine|invalid
cond=>condition: Yes
or No?|approved:>http://www.google.com
c2=>condition: Good idea|rejected
io=>inputoutput: catch something...|future

st->op1(right)->cond
cond(yes, right)->c2
cond(no)->sub1(left)->op1
c2(yes)->io->e
c2(no)->op2->e
```
~~~

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/170246995-f5ad381a-b33c-4c09-8e71-767050e83f55.png)

**Comment by Guyutongxue** [comment]
I re-install the dependencies with `npm`, and everything is OK now. Seems that the error occurs only when I'm using `pnpm`?

**Comment by Mister-Hope** [comment]
I believe that the issue comes from a broken deps tree, as this repo is using pnpm.

You are free to reopen it or recreate a new issue with a github reproduction repo based on https://vuepress-theme-hope.github.io/v2-new using pnpm.
