### ISSUE TITLE
[Bug] pageInfo cannot be disabled

### ISSUE THREAD

**Issue by imgradeone** [vuepress-theme-hope/vuepress-theme-hope#1914]
### Checklist

- [X] I am using the **latest version**
- [X] I have searched FAQ ([V1 Docs](https://vuepress-theme-hope.github.io/v1/FAQ/) | [V2 Docs](https://vuepress-theme-hope.github.io/v2/faq.html))

### Package name

vuepress-theme-hope

### Version

v2

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

While setting theme config `pageInfo` or frontmatter `pageInfo` to `false`, the theme still displays the page info.

> Happened on beta 73 / 74, not happened on beta 59

![image](https://user-images.githubusercontent.com/30969327/170853551-02b9603b-76cb-4e3a-9a92-1c459e4f441e.png)
![image](https://user-images.githubusercontent.com/30969327/170853563-cad777ee-1f9f-4eb0-b618-03d799b5bbd5.png)

### Additional context

Repo: https://github.com/imgradeone/wikimimo/tree/preview (preview branch)

Link: https://preview.wikimimo.com

**Comment by Mister-Hope** [comment]
Thanks for pointing this out, we will get it fixed soon
