### ISSUE TITLE
希望可以在MD增强内添加图片设置宽高功能

### ISSUE THREAD

**Issue by holajacky** [vuepress-theme-hope/vuepress-theme-hope#1929]
### Describe the feature

希望可以通过如下写法设置图片大小，满足强迫症
`![](https://xxx.com/xxx.png =280x320)`

### Additional context

![](http://oa.firstack.com/oa-files/bbs-files/1653985976879-image.png)

**Comment by Mister-Hope** [comment]
Reasonable, will add in future version

**Comment by Mister-Hope** [comment]
Released in beta76
