### ISSUE TITLE
[Bug] Reading time is calculated wrong for ru texts

### ISSUE THREAD

**Issue by viktorprogger** [vuepress-theme-hope/vuepress-theme-hope#1952]
### Checklist

- [X] I am using the **latest v2 version**
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-plugin-reading-time2

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

Reading time is calculated wrong for ru texts. There are more then 1500 words in my text, and displayed reading time is "about 1 minute". The `wordPerMinute` is explicitly set to 300. Calculation for the English version of the same text is OK.

Here is my text for example:
[how-to-start-develop-opensource.md](https://github.com/vuepress-theme-hope/vuepress-theme-hope/files/8838343/how-to-start-develop-opensource.md)

**Comment by Mister-Hope** [comment]
Thanks for the detailed infomation, it seems that currently we do not recognize ru letters. Could you please provide detailed infomation about ru letter unicode code point?

**Comment by viktorprogger** [comment]
Of course, here it is: https://en.wikipedia.org/wiki/Cyrillic_script_in_Unicode

**Comment by viktorprogger** [comment]
Many thanks for such a fast reaction for every ticket I create :heart:
