### ISSUE TITLE
[Bug] Missing dayjs locales

### ISSUE THREAD

**Issue by DZywolf** [vuepress-theme-hope/vuepress-theme-hope#1957]
### Checklist

- [X] I am using the **latest v2 version**
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

dayjs needs to have the locale defined for each language, which does not currently happen because only **zh** and **en** are defined, producing a warning message at build.

![warn-msg](https://user-images.githubusercontent.com/34007722/172104955-a0f43f3c-93f4-4955-837c-d0ec999786a9.png)

### Function to determine langcode
https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/4426946a64e7304e96e6ba716ecb9d3129763f6a/packages/shared/src/shared/utils/date.ts#L30-L41

### Default locales defined
https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/4426946a64e7304e96e6ba716ecb9d3129763f6a/packages/shared/src/shared/utils/dayjs.ts#L52

https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/4426946a64e7304e96e6ba716ecb9d3129763f6a/packages/shared/src/shared/utils/dayjs.ts#L116

**Comment by Mister-Hope** [comment]
Yes, this should be a bug, but if we include locales of a lot of language, we will need to process it on node side.

This function is not like other locales, which is tree-shakable.

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/e1cbbc977cb811d2af2ba5f535e5baaaad149f07
