### ISSUE TITLE
[Bug] Copy code button not working when navigating back

### ISSUE THREAD

**Issue by Jordan20190913** [vuepress-theme-hope/vuepress-theme-hope#2000]
### Checklist

- [X] I am using the **latest v2 version**
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Copy Code invalid：
1、visit： https://vuepress-theme-hope.github.io/v2/zh/
2、click any link on navbar，for example：https://vuepress-theme-hope.github.io/v2/config/
3、goback to the first page you visited, using the browser backward button
Bug:
Code can't be copyed now.

### Additional context

通过回退按钮访问历史记录，页面中的代码复制按钮，功能失效

**Comment by Jordan20190913** [comment]
路由跳转导致Vue组件实例销毁，自定义事件被解绑。
重新绑定事件来解决？
![image](https://user-images.githubusercontent.com/55272641/174263173-dc536d28-610f-4a64-9b90-464d5505caa6.png)

**Comment by Mister-Hope** [comment]
哦对了，我在南京旅游，修复会 delay 一段时间

**Comment by Mister-Hope** [comment]
Track https://github.com/vuepress/vuepress-next/issues/956 for more details

**Comment by JaneYork** [comment]
> 哦对了，我在南京旅游，修复会 delay 一段时间

这么潇洒吗，江苏偶遇一波？

**Comment by Mister-Hope** [comment]
I will rebuilt the logic to avoid this problem when I have time.

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/596c3c94cc562ba07f070231b4e7830198588090
