### ISSUE TITLE
[Bug] Markdown code block specified line highlighting invalid

### ISSUE THREAD

**Issue by ShangChien** [vuepress-theme-hope/vuepress-theme-hope#2001]
### Checklist

- [X] I am using the **latest v2 version**
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Markdown code block specified line highlighting invalid

![769A3488-553A-4383-86CB-BABE57827BD3](https://user-images.githubusercontent.com/48350636/174303644-de9bcbf0-bf37-4974-873a-af86a8c2b7f2.png)

The official website demo also not work.

### Additional context

current solution suggested by **_hope_** ：set `attrs: false` in **markdown-enhance**

**Comment by Mister-Hope** [comment]
Fixed in https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/6198b40c652367ac9fd168b7ab1c7152d6c589a2
