### ISSUE TITLE
Sort "structured" sidebar by filename

### ISSUE THREAD

**Issue by wycats** [vuepress-theme-hope/vuepress-theme-hope#2002]
### Describe the feature

I want the ability to sort my sidebar by filename, so I can have filenames like `1-cell.md` and sort based on the number in the file system. This allows me to get the same order in my file explorer in my editor and in the UI.

I can accomplish this today by adding an `order` in my frontmatter, but if I change the order, I need to change the number in two places and keep it in sync.

Another possibility: make it possible to configure the sort function of the `structure` sidebar in config.

**Comment by Mister-Hope** [comment]
We ever planned to support sort function, I will build this in future.

P.S. on vacation now

**Comment by wycats** [comment]
Enjoy your vacation!
