### ISSUE TITLE
[Bug]加密页的 title 不显示

### ISSUE THREAD

**Issue by itwanger** [vuepress-theme-hope/vuepress-theme-hope#2005]
### Checklist

- [X] I am using the **latest v2 version**
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

加密页面在多语言配置中设置了 title，但在页面上并不显示。

![image](https://user-images.githubusercontent.com/6011374/174412681-c8d6bcc0-b209-4d9b-b08b-02e56e5f11e6.png)

这是代码：

```
encryptLocales: {
    /**
     * Encrypt title
     */
    title: "初次访问，人机识别活动下筋骨",
```

**Comment by Mister-Hope** [comment]
After checking, title i18n is only used for lock icon a11y.

If you do want a default title, you may override this encrypted component.
