### ISSUE TITLE
[Bug] 側邊攔使用 activeMatch 沒有變化

### ISSUE THREAD

**Issue by nnn950711** [vuepress-theme-hope/vuepress-theme-hope#2007]
### Checklist

- [X] I am using the **latest v2 version**
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

使用 activeMatch 限制側邊攔的顯示貌似無效
![螢幕擷取畫面 2022-06-18 212511](https://user-images.githubusercontent.com/41001774/174439798-558ea91a-9ea5-4ec2-905e-a1d24983d569.png)
![螢幕擷取畫面 2022-06-18 212534](https://user-images.githubusercontent.com/41001774/174439801-c5f538ed-43e2-4d86-b7ba-e047f97b5b84.png)

**Comment by Mister-Hope** [comment]
辛苦把你截图里的demo传一下stackblitz吧

**Comment by nnn950711** [comment]
> 辛苦把你截图里的demo传一下stackblitz吧

https://stackblitz.com/edit/node-fandtm

**Comment by Mister-Hope** [comment]
Your demo is running with the expect behavior, however it does have some bugs here, fixed in https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/30065dc3a2cf93f3d5e0c878b963f12385965409
