### ISSUE TITLE
[Feature Request] Add configs to disable word break and text justification

### ISSUE THREAD

**Issue by qouteall** [vuepress-theme-hope/vuepress-theme-hope#2010]
### Describe the feature

I want to disable the word break and text justification (the default vuepress theme does not have word break or text justification). Although it can be done by overriding the style via `styles/palette.scss`
```
p {
    word-break: keep-all !important;
    hyphens: none !important;
    text-align: left !important;
}
```
But this solution is ad-hoc and it could be better if the theme has configs or sass variables for it.

**Comment by Mister-Hope** [comment]
1. As VuePress2 and this Theme both point out, you can use index.scss to customize styles. So you already have a solution.

2. Adding more config means longer sass compile time, and these kind of features can be hundreds.

So I won't add config like this, if you like to share your customize ideas with others, you are always welcomed to open a new discussion in "Show and Tell"

**Comment by qouteall** [comment]
So my override should be in `index.scss` instead of `palette.scss` right?

**Comment by Mister-Hope** [comment]
Yes, palette will I injected multiple times.
