### ISSUE TITLE
[Feature Request] nestingDepth option in structure sidebar

### ISSUE THREAD

**Issue by Hkr32** [vuepress-theme-hope/vuepress-theme-hope#2013]
### Describe the feature

What is the best way to implement a sidebar if there will be a large number of menu items and a lot of nesting? Make a multi sidebar and show only part of the sidebar at the specified nesting level?

**Comment by Mister-Hope** [comment]
I am trying to implement this one, but I cannot come up with a proper solution. Any ideas?

**Comment by Hkr32** [comment]
Can I set the display of nesting both in depth and up?
For example, there is a nesting:
`1.
    1.1.
        1.1.1.
               1.1.1.1.
                        1.1.1.1.1`
sidebarDepthUp: 1
sidebarDepthDown: 2
Then if we are at level 1.1.1 we will see one parent level, and two children
`1.1.
        1.1.1.
               1.1.1.1.
                        1.1.1.1.1`
Or is it very difficult?

**Comment by Mister-Hope** [comment]
We surely can do this, but yes, we have to concern about complexity.

You should know that the browser has no idea about source file structure.

We surely can extract a structure infomation and make a transformer from infomation to sidebar configuration with the options you requested, but I don't think that should be necessary.

The current behavior is that the theme generate Sidebar configuration in node side and provide them to client side, so we are not actually importing extra data and functions into runtime.

So the central point this how can we dynamically generates sidebar config at runtime after adding the options you want with reasonable extra lines.

**Comment by Hkr32** [comment]
If then make a parameter that for the menu item will say that it is the main one and you need to display starting from it to a given depth?
`sidebarMain = 1`
`sidebarDepth = 2`

**Comment by Mister-Hope** [comment]
I updated structure sidebar generation, and I will relook into this issue in the next few days to see if we can add some improvements according to your needs.

**Comment by Mister-Hope** [comment]
This still be a little complicated and seems only can be done at client runtime, however I would prefer things like this done at node side to reduce client computation work as this can be slow in large sites.

**Comment by Mister-Hope** [comment]
If I add this feature, here is my plan:

Add another value besides "structure" called "dynamic", which is based on actual page path, generating sidebar from routes path.

For the nestingDepth it shall be `[number, number]`, first controls how may depth of parent shall the sidebar includes. Second controls children depth if the currect route is a `index.html` with children. the value can be set both in themeLocaleOptions and frontmatter

But I am still afarid this is a bit complicated.

**Comment by Mister-Hope** [comment]
From the feedback, the current sidebar features are already complicated enough for newcomers
