### ISSUE TITLE
[Docs] Russian docs

### ISSUE THREAD

**Issue by Hkr32** [vuepress-theme-hope/vuepress-theme-hope#2014]
### Describe the feature

I am ready to help with the translation. Maybe there are others who want to? There is a desire?

**Comment by Mister-Hope** [comment]
The theme already supports Russian language, and you can open or if you found that some translation is missing or can be improved.

**Comment by Hkr32** [comment]
I'm talking about documentation. There is just a lot of translation work on the topic)

**Comment by Mister-Hope** [comment]
Oh, I found your original discussion in #1705. First just let you know that I am on vacation and having a long trip away at home, which means I wound probably reply late in the comming week or 2.

If you already finished translating the docs, and willing to sync the docs from en version in no more than 7 days (I would more prefer a  1-3 day delay with small changes) when we change something, I sincerely welcome you to contribute to this repo.

Just open a PR when you are ready, if this is fine, I will invite you as a collaborer of this repo, so you can open a branch and sync the docs anytime, and open PRs for me to merge it to main before publishing.

**Comment by Hkr32** [comment]
I started translating. But after your message that you are changing the documentation, I stopped. That's why I ask if it makes sense to resume the translation and continue? Immediately make a PR and fill it in as you transfer? Or when everything is ready?

**Comment by Mister-Hope** [comment]
I think you can open a pr when you finish any plugin or theme documatation then started to translate another one.

Also, since the theme docs are large, you can just copy the entrie en docs to `ru` folder, then translate by "parts", such as `guide/layout` `cookbook/advanced` one by one, I feel pretty fine about it.

**Comment by Mister-Hope** [comment]
Also, welcome to fix any en typos you found when you are translating, (I am not a native english speaker either) please open new prs about them.

**Comment by Hkr32** [comment]
Unfortunately, my English is still weak. But I'm working on it)

**Comment by Mister-Hope** [comment]
BTW, do you have plans to tranlate plugin docs?

**Comment by Hkr32** [comment]
I think yes, it is possible. Ready to help when I have free time.

**Comment by Mister-Hope** [comment]
Commits with docs that need sync

- [ ] https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/3e9967bd6991fc38047a22309df075b509bc6a57
- [ ] https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/1d7fa0d79e5454e85b0f2bd9d98760dd206f9cf0

**Comment by Mister-Hope** [comment]
Some new docs are added, so you may check your last commit and compare with latest commit.

**Comment by Hkr32** [comment]
There will be time at the end of the week. I will.

**Comment by Hkr32** [comment]
I watched. Everything is translated there. If I missed something, please send a link.

**Comment by Mister-Hope** [comment]
Where is your work? I am not seeing any branch update😶

**Comment by Hkr32** [comment]
Everything has already been translated.

**Comment by Mister-Hope** [comment]
I doesnot list the changes for you, a lot of part  is added, e.g.: https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/main/docs/theme/src/ru/config/plugins/md-enhance.md#playground

**Comment by Mister-Hope** [comment]
You may need to check locally in this way: https://github.com/vuepress-theme-hope/vuepress-theme-hope/compare/4f6f2ad3f3e104ccc97863dcbbf4e4620136d066...1cbe445f59197135be0750c48d8f23d403e07670 and fliter only `docs/theme/src/ru/`

**Comment by Hkr32** [comment]
I didn't look there. I'll check it out now.

**Comment by Mister-Hope** [comment]
Hi, could you correct the anchor in docs/theme/src/ru/guide/markdown/playground.md:124 ? Linter is throwing problems. I am not sure how to make a russian anchor correct.

**Comment by Mister-Hope** [comment]
Also, https://github.com/vuepress-theme-hope/vuepress-theme-hope/commits/main needed to be tranlated, and I didnot sync russian in this commit.

**Comment by Hkr32** [comment]
Please check.

**Comment by Mister-Hope** [comment]
- [ ] https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/e2bb6b6df7b6fb27c748e4b6529fb4e183ed5a04

**Comment by Hkr32** [comment]
![image](https://user-images.githubusercontent.com/12296392/195368355-69dd09ec-158f-4595-a6c1-e7c3353b226f.png)
![image](https://user-images.githubusercontent.com/12296392/195368634-52b62840-5b4c-4728-8586-c4649aec1598.png)

**Comment by Mister-Hope** [comment]
You may need this in settings:

```json
{
  "markdown.validate.enabled": true
}

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/19d23cd9e72c2b307148ffd1e3dda5ac963953a4

**Comment by Mister-Hope** [comment]
`Плагин фида` seems not be the correct translation.

Feed is not "feeding some animal", you should understand the word like "streaming", and it probably means "subscribe a stream"

**Comment by Hkr32** [comment]
It's more of a non-translation thing. It is the text of what the word sounds like in English. Because I don't know how to translate it correctly into Russian.
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/ecc860ca367656fe7c16f47938a227e25a2b0b5b

**Comment by Hkr32** [comment]
Everything seems to be fine

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/b27e77119ed847b504f06e5d53274aa2e7d69c4a

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/9c9818642c76377d817d7648d4df64fd771f6d83 https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/57f4ffb149404c415f547710a45b461ee6ff4bf2

**Comment by Hkr32** [comment]
I have difficulty with the translation of the Frontmatter, how can I translate it correctly? What is the best fit?

**Comment by Mister-Hope** [comment]
I am not translating it in Chinese, I think keeping it as is should be fine.

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/9a16af64c70aa733e67424901c5fb68dc54e658c

**Comment by Mister-Hope** [comment]
I will close this issue but still try to notice you in this thread, I am busy in the past few days yet I still make some documatation updates without notifying you. Could you check the recent prs? All content shall be updated in english.

**Comment by Hkr32** [comment]
Okay, I'll try it this week.

**Comment by Mister-Hope** [comment]
I will close this one, new updates will be at https://github.com/orgs/vuepress-theme-hope/projects/4/views/2
