### ISSUE TITLE
Users should be able to choose package manager 

### ISSUE THREAD

**Issue by 332lfgb6** [vuepress-theme-hope/vuepress-theme-hope#2018]
### Checklist

- [X] I am using the **latest v2 version**
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

如题

### Additional context

其实我想用的是yarn，但是只有npm和pnpm的安装介绍

**Comment by Mister-Hope** [comment]
Expected, I believed you have pnpm installed.

I will add a step for users to select package manager

**Comment by Mister-Hope** [comment]
> 其实我想用的是yarn，但是只有npm和pnpm的安装介绍

yarn 1 do not support @next flag.

You may execute :

```
yarn global add create-vuepress-theme-hope@next
create-vuepress-theme-hope <dir>
```
