### ISSUE TITLE
[Bug]文档内容勘误

### ISSUE THREAD

**Issue by Ackerven** [vuepress-theme-hope/vuepress-theme-hope#2054]
### Checklist

- [X] I am using the **latest v2 version**
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

原文：你可以前往前往 VuePress2 → 参考 → 配置 查看所有 VuePress 配置。
问题：“前往” 重复了
出处：https://vuepress-theme-hope.github.io/v2/zh/cookbook/tutorial/config.html#%E7%AB%99%E7%82%B9%E9%85%8D%E7%BD%AE

**Comment by Ackerven** [comment]
借楼问一下，大概啥时候能发布 v2 的 Release 版本 🙇
在网上转了一圈，发现 VuePress Theme Hope 特别适合我的需求
但这 beta 阶段更新的也太快了（dalao身上全是肝），其中还有很多 BREAKING CHANGES 的更新
这很难在生产环境中使用

**Comment by Mister-Hope** [comment]
目前不会进行非必要的breaking changes了，而且所有breaking changes都可以通过开启legacy mode进行兼容。

**Comment by Mister-Hope** [comment]
V2 stablerelease 会跟随VuePress 2

**Comment by Mister-Hope** [comment]
这种类似的issue，你直接发个pr就好了
