### ISSUE TITLE
[Bug] C++ 代码无法高亮显示

### ISSUE THREAD

**Issue by Ackerven** [vuepress-theme-hope/vuepress-theme-hope#2068]
### Checklist

- [X] I am using the **latest v2 version**
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

如图：
![image.png](https://s2.loli.net/2022/07/14/7RYS4qjbAMPfial.png)

markdown 文件：
![image.png](https://s2.loli.net/2022/07/14/YNz9lVFqofPAIH1.png)

**Comment by yzqdev** [comment]
You may have the wrong tag, my c++ code highlight well.

![image](https://user-images.githubusercontent.com/20037151/178927595-876ad0a3-c9ee-4c1e-8b8b-5e80dfbeb05c.png)

My md file 

 
![image](https://user-images.githubusercontent.com/20037151/178928003-dfdfbf20-f899-4430-a91d-d0628814ab35.png)

**Comment by Ackerven** [comment]
You can say that again! ! !
