### ISSUE TITLE
[Feature Request] suggested add mathjax as latex renderer

### ISSUE THREAD

**Issue by MonoLogueChi** [vuepress-theme-hope/vuepress-theme-hope#2079]
### Describe the feature

It is suggested that md-enhance can choose latex renderer between mathjax and katex

### Additional context

Has md-enhance considered choosing to configure mathjax or katex? This plugin is great, but it's a pity that there is no mathjax, it would be nice if you could choose a latex renderer between mathjax and katex, I think it can be quickly ported from [markdown-it-mathjax3](https://github.com/tani/markdown-it-mathjax3)

**Comment by Mister-Hope** [comment]
I personally do not have any plans to support mathjax.

If you want it, use another plugin which can support that.

**Comment by Mister-Hope** [comment]
A detailed reason:

- mathjax is slower than katax in benchmark
- mathjax package is huge in size, and I am not willing to bundle this.

I understand that mathjax support SVG output comparing with katax, but I do not think we should actually use that in docs.

**Comment by Mister-Hope** [comment]
A detailed reason:

- mathjax is slower than katax in benchmark
- mathjax package is huge in size, and I am not willing to bundle this.

I understand that mathjax support SVG output comparing with katax, but I do not think we should actually use that in docs.

**Comment by Mister-Hope** [comment]
Also if you insist that we'd better add this , list some advantages for mathjax , as I may reconsider this.

**Comment by MonoLogueChi** [comment]
In theory, katex should be very powerful, but I see that katex of markdown-it doesn't seem to support extended syntax. I don't know why, md-enhance also doesn't support chemical and physical formulas, such as \ce and \mathord, etc. syntax is not supported. If katex can also support chemical formulas well, then mathjax is really not a good choice.

**Comment by Mister-Hope** [comment]
I am not pretty interested about this, and I think that adding one could be easy. pr welcomed 

Also it may include a breaking change with Tex option.

**Comment by Mister-Hope** [comment]
Are you interested in adding it? @MonoLogueChi

**Comment by MonoLogueChi** [comment]
> Are you interested in adding it? @MonoLogueChi

i think i can do it.

I think it can be done in several steps. Katex has the mhchem extension, and a configuration option can be introduced to determine whether to enable mhchem, so that katex can have the ability to render chemical formulas, which should meet the needs of more than 95% of users. Then add a configuration option to switch the latex rendering engine. The default is katex. If necessary, you can switch to mathjax to obtain more powerful formula rendering capabilities.

I'll add this part of the functionality with 1-2 pr when I verify it.

**Comment by MonoLogueChi** [comment]
But adding options will destroy the original structure. Do you have any good suggestions to maintain the original compatibility and increase related configuration options?

The first configuration option is whether katex loads the mhchem extension (or I think it can be loaded directly, which has no effect on rendering the render output).
The second configuration item is to switch the rendering engine, you can choose katex or mathjax.

My opinion is

```js
tex: {
  render: KaTeX,
  plugins:['mhchem'],
  options: {}
}
```

When there are no render and plugins options at the same time, directly copy the entire configuration item to options to be compatible with previous configuration options

**Comment by Mister-Hope** [comment]
I think doing breaking changes here is find. Some plug-ins and the theme has a legacy mode, you can add a convert function there.
