### ISSUE TITLE
[Feature Request] Multi page config sidebar error

### ISSUE THREAD

**Issue by longyanjiang** [vuepress-theme-hope/vuepress-theme-hope#2080]
### Describe the feature

当配置多页面多sidebar的时候，配置为{  "/foo/": ["one"] }  会出现错误 TypeError: (useThemeLocaleData(...).value.navbar || []).map is not a function 对于多页面多sidebar的配置是否有其他地方需要同步呢

**Comment by Mister-Hope** [comment]
Sidebar 跟 navbar 的报错有什么关系

**Comment by longyanjiang** [comment]
https://vuepress-theme-hope.github.io/v2/zh/guide/layout/sidebar.html#%E5%A4%9A%E4%B8%AA%E4%BE%A7%E8%BE%B9%E6%A0%8F

当按对象形式配置的时候 就会报这个错误
