### ISSUE TITLE
[Enhancement] Dark Mode support for Chart.js

### ISSUE THREAD

**Issue by I-love-study** [vuepress-theme-hope/vuepress-theme-hope#2090]
### Checklist

- [X] I am using the **latest v2 version**
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-plugin-md-enhance

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

![image](https://user-images.githubusercontent.com/39652142/181220851-db9b78c4-8875-4880-94d1-bc0a38248164.png)
<img width="578" alt="image" src="https://user-images.githubusercontent.com/39652142/181220985-35a4b54a-ce0b-4d56-b655-e84d06825fd2.png">

It seems that there's no Dark Mode adapt for Chart.

**Comment by Mister-Hope** [comment]
I do think in most cases you should do that yourself.

just to be clear that I do not have any fix plan about this.

If anyone want this, A related pr would always be welcomed.
