### ISSUE TITLE
[Bug] Setting `iconPrefix` to `''` don't work

### ISSUE THREAD

**Issue by Ackerven** [vuepress-theme-hope/vuepress-theme-hope#2093]
### Describe the feature

When using the fontawesome icon in the theme, only the icon filtered by the `Solid`, `Free` condition can be used.
Like：
![image](https://user-images.githubusercontent.com/70303900/181502571-b42ccccd-8916-470d-a3cd-ed3096ff44f8.png)

However，the icons in the brands collection are also free, but cannot be used.
So icons like some languages cannot be used. 
For example：
![image](https://user-images.githubusercontent.com/70303900/181502931-36d2b003-3055-44d5-8c1f-0cefb9abe0c1.png)

![image](https://user-images.githubusercontent.com/70303900/181503007-bb819e52-21fd-4fc9-a8f7-ce2f5b1770c0.png)

**Comment by Ackerven** [comment]
Through the documentation I know how to replace it with my own fontawesome link. But the above problem remains unresolved.

Strangely, I tried to modify the class attribute in the browser and it successfully displayed.
![image](https://user-images.githubusercontent.com/70303900/181514373-0ae43520-0e46-4960-9439-38cdce3a86c8.png)

![image](https://user-images.githubusercontent.com/70303900/181514383-d30519d6-ecb5-46b4-a040-0bd14f8a8098.png)

**Comment by Mister-Hope** [comment]
We provide iconPrefix options, you should try to override it to empty string, then add full icon class in your config.

**Comment by Mister-Hope** [comment]
We provide iconPrefix options, you should try to override it to empty string, then add full icon class in your config.

**Comment by Mister-Hope** [comment]
Due to the iconPrefix is different I think I do make a good choice for the default value with `fas fa-` prefix and free sets.

If you do need brand or pro icons as well, set your own link and override to `''` for prefix.

**Comment by Ackerven** [comment]
**Thanks!** It worked.

By the way, if `iconPrefix` is set to `''`, it will still add a prefix. 

Need to write an empty character, such as `' '`.

**Comment by Mister-Hope** [comment]
Then that should be a bug
