### ISSUE TITLE
[Feature Request] Fontawesome Pro

### ISSUE THREAD

**Issue by Zhythero** [vuepress-theme-hope/vuepress-theme-hope#2094]
### Describe the feature

Fontawesome Pro support

### Additional context

Hi! We are currently using Fontawesome Pro in our projects and we would like to add Fontwesome Pro icons in our vuepress docs. Could this be added in the future? Or maybe this is possible currently?

**Comment by Mister-Hope** [comment]
You can generate your own links through font-awesome,. and set it to iconAssets.
