### ISSUE TITLE
[Bug]使用frontmatter后，frontmatter内容展示在了首页博文简介中

### ISSUE THREAD

**Issue by ackemaneva** [vuepress-theme-hope/vuepress-theme-hope#2098]
### Checklist

- [X] I am using the **latest v2 version**
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

![image](https://user-images.githubusercontent.com/17824405/182636727-f630b16a-45e0-4947-9147-b1c626f0f54d.png)
问题是，为什么frontmatter中的内容会显示在博文列表简介中。请问怎么去除，没有找到frontmatter的相关配置。请帮忙处理一下，3Q

**Comment by Mister-Hope** [comment]
Are you using the ＬＡＴＥＳＴ version？

**Comment by ackemaneva** [comment]
版本是`"vuepress-theme-hope": "^2.0.0-beta.80"`

**Comment by ackemaneva** [comment]
> 

3Q.version已经更新到了` "vuepress-theme-hope": "^2.0.0-beta.87"`，问题解决了~
