### ISSUE TITLE
[Feature Request]Make article sorting smarter

### ISSUE THREAD

**Issue by Ackerven** [vuepress-theme-hope/vuepress-theme-hope#2102]
### Describe the feature

I use this theme as my knowledge document website. In the process of writing notes, I will use `order` in frontmatter to sort the articles. But it would be cumbersome to insert one article in two articles, because the `order` field of all subsequent articles needs to be modified. This can make inserting an article very expensive, especially when there are many articles that follow, and also generate a lot of unnecessary **commit** information.

For this problem, I have a suggestion, that is to use **Double Linked List**. Each article has an ID, and there are two fields in the frontmatter, indicating the previous article and the next article of this article. In this case, inserting an article only needs to modify some fields in the two files before and after.

I konw it's possible to use `prev` and `next` to indicate the link to the previous article and the link to the next article, but this is only a button that acts on the end of the article. But I want the articles in the sidebar to be sorted.

**Comment by Mister-Hope** [comment]
TBH, try 1.5 between 1 and 2, and even 1.01

**Comment by Mister-Hope** [comment]
Sticking on the technical part, how should I find the beginning node and ending node efficiently (without reading every page?)

And How should I deal with problems that A reference B as next but B reference nothing (or maybe c)? also how do I deal with loops?

**Comment by Ackerven** [comment]
OMG, floatint point are also supported.

**Comment by Ackerven** [comment]
You're right, using Double Link List is really a big problem and I haven't thought about it. So for the problem you mentioned, I don't have a better idea.:joy:

**Comment by Mister-Hope** [comment]
So I will close this one, because order is actually a more easy way to understand it's behvaior for both users and developer.
