### ISSUE TITLE
[Bug]plugin.git Invalid configuration

### ISSUE THREAD

**Issue by loclink** [vuepress-theme-hope/vuepress-theme-hope#2117]
### Checklist

- [X] I am using the **latest v2 version**
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

![image](https://user-images.githubusercontent.com/106688231/184053804-4a56591f-92df-45ff-9b86-fef23f1c7a24.png)

1. The "plugin.git" described in the documentation has the wrong parameter type

![image](https://user-images.githubusercontent.com/106688231/184053957-312381be-0c6f-4497-ba48-f9afdd473ae5.png)

In addition, the configuration can not display the latest update date and dependent information such as the author even if the configuration is correct

I have tried to restart the run, but it is still useless

Is already theme-config:  { lastUpdated: true, contributors: true }

**Comment by Mister-Hope** [comment]
![Screenshot_2022-08-11-16-25-01-77_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/33315834/184093405-272a0108-5af5-44a0-8d56-ee8eb0a67805.jpg)

docs now are incorrect, you must use --debug flag to enable git plugin in dev mode.

I may improve this in next version.
