### ISSUE TITLE
[Bug]根据官网源码配置的，启动直接报错 useRouteLocale() is called without provider

### ISSUE THREAD

**Issue by 7foxx** [vuepress-theme-hope/vuepress-theme-hope#2123]
### Checklist

- [X] I am using the **latest v2 version**
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-plugin-comment2

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

useRouteLocale() is called without provider

### Additional context

为什么vuepress2这么垃圾，我真后悔用了

**Comment by Mister-Hope** [comment]
> 为什么vuepress2这么垃圾，我真后悔用了

那你可以圆润退去
