### ISSUE TITLE
The home page articles of title

### ISSUE THREAD

**Issue by JIeJaitt** [vuepress-theme-hope/vuepress-theme-hope#2132]
### Describe the feature

Add a more eye-catching title to the home page articles. 

### Additional context

Thank you for your hard work. Here I would like to make some suggestions for the theme article. Add a more eye-catching title to the home page articles. At the same time, I hope the author can improve the display of the home page articles. Referring to the display of the home page of hexo well-known blogs, hope's home page display is not particularly excellent. Finally, thank you again for your hard work

**Comment by Mister-Hope** [comment]
Pr welcomed about that(need some discussions first)

I personally do not like fancy styles, but yes, we can make the appearance better.

**Comment by Mister-Hope** [comment]
Should be improved in beta.100
