### ISSUE TITLE
[Bug]Error: useRouteLocale() is called without provider

### ISSUE THREAD

**Issue by leekihom** [vuepress-theme-hope/vuepress-theme-hope#2139]
### Checklist

- [X] I am using the **latest v2 version**
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

项目编译没问题，但是启动后console里面报错，Error: useRouteLocale() is called without provider[]
![image](https://user-images.githubusercontent.com/55677666/185601233-e5c73b08-85dd-4d39-a3ae-f1ffc7db2dcb.png)

**Comment by Mister-Hope** [comment]
>  I am using the latest v2 version

Check you are using the LATEST version

**Comment by luoyunchong** [comment]
可以 更新下版本，
update vue version  "vue": "^3.2.37", 然后就正常 了
