### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Buzhifanji** [vuepress-theme-hope/vuepress-theme-hope#2154]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

为了处理github page 出现如下的问题
![image](https://user-images.githubusercontent.com/28743253/186353731-84b19fad-5a80-433d-99e9-912183dd9073.png)
按照 https://vuepress-theme-hope.github.io/v2/zh/faq/common-error.html#usexxx-is-called-without-provider 指南，做了升级处理

升级前的依赖版本如下：
![image](https://user-images.githubusercontent.com/28743253/186354250-cdfe5197-363f-4868-ba29-e86fc89fcd08.png)

升级到最新版本
![image](https://user-images.githubusercontent.com/28743253/186354326-36895b35-c04f-40a0-a1d7-79b3180030e5.png)

pnpm dev 之后，就出现了如下问题：
![image](https://user-images.githubusercontent.com/28743253/186352090-2b915b7c-a550-4d24-af21-114b8bb0a040.png)

烦请帮忙处理一下，非常感谢❤

**Comment by Mister-Hope** [comment]
The theme do not support beta50 yet

**Comment by Buzhifanji** [comment]
我降级到 beta 49 版本，问题依旧存在

然后我尝试过 `pnpm create vuepress-theme-hope@next [dir]`  重建一个新的项目，启动后会报如下错误

![image](https://user-images.githubusercontent.com/28743253/186649621-ab5f9c7a-d63e-41a5-83d7-b25f48251db1.png)

之后尝试过删除 `node_modules` ，通过 npm i 重新安装依赖，启动会会报如下错误：

![image](https://user-images.githubusercontent.com/28743253/186650398-6dcf87d1-79d2-4815-9603-bbeae21db08b.png)

也尝试过到 beta 49 版本，还是报一下的错误信息

现在我的电脑已经跑不起来这个项目，劳烦帮忙处理一下，谢谢

**Comment by Mister-Hope** [comment]
minial reproduction

**Comment by Buzhifanji** [comment]
我根据 https://stackblitz.com/edit/vuepress-theme-hope-2vf4ky?file=package.json 这个，然后 npm i，项目可以正常启动了，但是用pnpm 还是行不通，安装依赖如下：
![image](https://user-images.githubusercontent.com/28743253/186663795-625bd63c-5b73-4b26-8af2-9157570cfb42.png)
pnpm run dev 之后，报错信息如下：
![image](https://user-images.githubusercontent.com/28743253/186663890-53f2c8e4-7edc-4dd3-81a8-3d71e711cfce.png)

**Comment by slgluo** [comment]
同样的问题，使用pnpm通过官方的安装命令运行会报错

**Comment by slgluo** [comment]
通过降级beta.49运行成功
