### ISSUE TITLE
[Bug] Error: useRouteLocale() is called without provider.

### ISSUE THREAD

**Issue by yuntian001** [vuepress-theme-hope/vuepress-theme-hope#2155]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

npm init vuepress-theme-hope@next [dir] 安装后启动

![image](https://user-images.githubusercontent.com/43692243/186794143-4f8eb7d4-e004-4fce-9574-771ce879bea5.png)

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/2152#issuecomment-1223927610
