### ISSUE TITLE
[Bug] vuepress-plugin-md-enhance v2.0.0-beta.92 Failed to resolve import "vuepress-shared/client" 

### ISSUE THREAD

**Issue by vmihailenco** [vuepress-theme-hope/vuepress-theme-hope#2162]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-plugin-md-enhance

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

Upgrading to v2.0.0-beta.92 results in the following error message

```
Failed to resolve import "vuepress-shared/client" from "node_modules/.pnpm/vuepress-plugin-md-enhance@2.0.0-beta.92_sass-loader@13.0.2/node_modules/vuepress-plugin-md-enhance/lib/client/components/icons.js". Does the file exist?
2:40:47 PM [vite] Internal server error: Failed to resolve import "vuepress-shared/client" from "node_modules/.pnpm/vuepress-plugin-md-enhance@2.0.0-beta.92_sass-loader@13.0.2/node_modules/vuepress-plugin-md-enhance/lib/client/components/icons.js". Does the file exist?
  Plugin: vite:import-analysis
  File: node_modules/.pnpm/vuepress-plugin-md-enhance@2.0.0-beta.92_sass-loader@13.0.2/node_modules/vuepress-plugin-md-enhance/lib/client/components/icons.js
  1  |  import { h } from "vue";
  2  |  import { IconBase } from "vuepress-shared/client";
     |                            ^
  3  |  export const BackIcon = () => h(IconBase, { name: "back" }, () => h("path", {
  4  |      d: "M1014.749 449.156v125.688H260.626l345.64 345.64-89.239 89.237L19.307 512l497.72-497.721 89.238 89.238-345.64 345.64h754.124z
```

v2.0.0-beta.91 worked fine. I am using vuepress 2.0.0-beta.50

**Comment by Mister-Hope** [comment]
beta92 is broken, please use beta93
