### ISSUE TITLE
[Bug] 2.0.0-beta.93 dayjs does not provide an export named 'default'

### ISSUE THREAD

**Issue by vmihailenco** [vuepress-theme-hope/vuepress-theme-hope#2163]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

After upgrading to 2.0.0-beta.93, I get the following error in the console (but the docs compile successfully)

```
Uncaught SyntaxError: The requested module 'node_modules/.pnpm/dayjs@1.11.5/node_modules/dayjs/dayjs.min.js?v=a9c36092' does not provide an export named 'default' (at dayjs.ts:1:10)
```

After removing vuepress-theme-hope plugins, the error goes away.

Do you need more details?

**Comment by Mister-Hope** [comment]
Fixed in https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/83336946b5ff1973b66e5a4b9566936af7ab958b
