### ISSUE TITLE
[Bug] Failed to resolve import "@theme-hope/components/SkipLink"

### ISSUE THREAD

**Issue by ziangtin** [vuepress-theme-hope/vuepress-theme-hope#2168]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Internal server error: Failed to resolve import "@theme-hope/components/SkipLink" from "..\node_modules\.pnpm\vuepress-theme-hope@2.0.0-beta.91\node_modules\vuepress-theme-hope\lib\client\layouts\Layout.js". Does the file exist?

### Additional context

   "vuepress": "2.0.0-beta.51",
    "vuepress-theme-hope": "2.0.0-beta.94"
    
![image](https://user-images.githubusercontent.com/27566264/187111668-8c53fffa-3f9b-4d2f-8c03-58380c11c48c.png)

**Comment by Mister-Hope** [comment]
Your log shows that you are importing beta.91, check again.
