### ISSUE TITLE
[Bug] Unknown file extension ".scss" for node_modules/.pnpm/vuepress-shared@2.0.0-beta.94/node_modules/vuepress-shared/lib/client/styles/message.scss

### ISSUE THREAD

**Issue by vmihailenco** [vuepress-theme-hope/vuepress-theme-hope#2171]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

When building for production I get the following error

```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".scss" for node_modules/.pnpm/vuepress-shared@2.0.0-beta.94/node_modules/vuepress-shared/lib/client/styles/message.scss
    at new NodeError (node:internal/errors:387:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:76:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:118:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:165:28)
    at ESMLoader.load (node:internal/modules/esm/loader:608:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:464:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:483:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:441:34)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Mister-Hope** [comment]
Probably a upstream bug

**Comment by vmihailenco** [comment]
Are you saying that vuepress-next should handle *.scss imports in 3rd party libraries?

**Comment by Mister-Hope** [comment]
yes, or more specifically, when a bundler found a .sass import in js files, it should call sass-loader(Webpack) or sass(vote) to handle that, instead of letting node to try to load that with esm loader

**Comment by Mister-Hope** [comment]
From the source code you can see tons of import like that, and I am not sure why in some situation the process failed to handle import correctly. This should not be an issue at my side.

**Comment by vmihailenco** [comment]
>From the source code you can see tons of import like that

I don't see such imports in vuepress-next. Only in this project.

But yes, for some reason it works in development build, but not in production build.

>yes, or more specifically, when a bundler found a .scss import in js files, it should call sass-loader(Webpack) or sass(vite) to handle that, instead of letting node to try to load that with esm loader

Yes, but that is only supposed to work for user code, not the code that comes from vuepress-theme-hope which is supposed to be already bundled. Otherwise, you would not need to bundle it at all.

**Comment by Mister-Hope** [comment]
> Yes, but that is only supposed to work for user code, not the code that comes from vuepress-theme-hope which is supposed to be already bundled. Otherwise, you would not need to bundle it at all.

## Why don't you install older version and "try" to figure out any difference?

## Now let's go staright: All the versions are importing scss files in the same way. So I don't think this is an issue belonging to this project. That package is nothing different from dev to build. But VuePress is.

If you want to have some techical dicussion, I welcome that, but if you only want to have some arguement and provide NO points or reason with your idea, I would like to "lock this conversation as spam"

**Comment by Mister-Hope** [comment]
> I don't see such imports in vuepress-next. Only in this project.

https://github.com/vuepress/vuepress-next/blob/main/ecosystem/theme-default/src/client/config.ts#L12

**Comment by Mister-Hope** [comment]
you can also see what VuePress default theme is outputting, Vue, js and scss files, as a VuePress core team member, I can be sure thatVuePress **should** handle those files

**Comment by Mister-Hope** [comment]
Upgrade to latest version and try again

**Comment by MoonLord-LM** [comment]
It seems fixed.

This works fine:

    "devDependencies": {
      "@vuepress/plugin-search": "^2.0.0-beta.50",
      "vuepress": "^2.0.0-beta.51",
      "vuepress-plugin-md-enhance": "^2.0.0-beta.97"
    }
