### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by properCase** [vuepress-theme-hope/vuepress-theme-hope#2173]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

After installation I got this error.  

```
    '✘ [ERROR] Could not resolve "./navbar.js"\n' +
    '\n' +
    '    docs/.vuepress/theme.ts:2:24:\n' +
    '      2 │ import * as navbar from "./navbar.js";\n' +
    '        ╵                         ~~~~~~~~~~~~~\n' +
    '\n' +
    '✘ [ERROR] Could not resolve "./sidebar.js"\n' +
    '\n' +
    '    docs/.vuepress/theme.ts:3:25:\n' +
    '      3 │ import * as sidebar from "./sidebar.js";\n' +
    '        ╵                          ~~~~~~~~~~~~~~\n' +
    '\n' +
    '\x1B[31mError: Build failed with 2 errors:\x1B[39m\n' +
```

I pointed those at "./navbar/index.ts" instead. Now I get the following:

```
Error: Missing "./browser/browser" export in "bcrypt-ts" package
```

### Additional context

I had my site working from the default theme just fine.

Using node 18.

Also, the v2 FAQ gives a 404: https://vuepress-theme-hope.github.io/v2/faq.html

**Comment by Mister-Hope** [comment]
Already fixed in latest commit https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/cc4e533b6f9e4176f559b907f36c99de68a43d40

**Comment by zeg-io** [comment]
You are amazing! nice!
