### ISSUE TITLE
[WARNING] beta.92+ packages are not recommanded to use in production

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress-theme-hope/vuepress-theme-hope#2174]
## All packages in this repo are only updated to be compatable with latest VuePress, and has a 5k+ lines refactor https://github.com/vuepress-theme-hope/vuepress-theme-hope/pull/2158 (+5,528 −9,026 lines) recently, so they are **unstable**. And these updates include only a few bug fixes in edge case and NO new features. So currenly I do not recommand to update docs or blogs which you are used in production.

So if you are using plugins and theme in production, you'd better stay on:

```json
{
  "vuepress": "2.0.0-beta.49",
  "vuepress-theme-hope": "2.0.0-beta.91"
}
````

Other packages in this repo is workable with version 2.0.0-beta.91 and should be used with `vuepress@2.0.0-beta.49` as well.

### Known upstream issues

- https://github.com/vuepress/vuepress-next/issues/1056:
  
  has workaround, do not use define variables directly in markdown `<script>` tags, instead, export them in a js files and import that js file using alias in markdown.

- https://github.com/vuepress/vuepress-next/issues/1061:

  has workaround, which is adding a `.nojekyll` in dist

- https://github.com/vuepress/vuepress-next/discussions/1058:

  beta50+ versions has serious preformance issue while building (not browser performance), mainly is about SSR.

  This has little influence in small sites, and due to performance improvements in vite3, maybe even faster.
  
  But in large documatation, the built time can increase more than 300% (i.e.: being more than 400%)

### Known project issues

- #2173:
  fixed

- esm related issues:
  - #2171
  - #2172
  - #2181 
  - #2182 
 
  fixed

**Comment by cpytiger** [comment]
how to rool back vuepress-theme-hope to 2.0.0-beta.91

**Comment by cpytiger** [comment]
how to roll back vuepress-theme-hope to 2.0.0-beta.91
