### ISSUE TITLE
[Bug] Error: Missing "./browser/browser" export in "bcrypt-ts" package

### ISSUE THREAD

**Issue by properCase** [vuepress-theme-hope/vuepress-theme-hope#2175]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

When attempting to run VuePress it throws this error:

```
Error: Missing "./browser/browser" export in "bcrypt-ts" package
```

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/cc4e533b6f9e4176f559b907f36c99de68a43d40

I think I replied you in your last issue.
