### ISSUE TITLE
[Bug] build error, Cannot find package '@internal/pagesData'

### ISSUE THREAD

**Issue by Trezedo** [vuepress-theme-hope/vuepress-theme-hope#2181]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Running `yarn  docs:build` after `npm init vuepress-theme-hope@next docs` makes error:

![image](https://user-images.githubusercontent.com/75014380/187355952-18344d5a-b577-4dd8-bacb-314d1093a474.png)

**Comment by Mister-Hope** [comment]
Is devServer working?

**Comment by Trezedo** [comment]
> Is devServer working?

devServer works normally with vite:

![image](https://user-images.githubusercontent.com/75014380/187359978-32166937-519a-458d-87ab-8a51e4175d74.png)

both vite and webpack bundling reported errors (the following uses bundler webpack):

![image](https://user-images.githubusercontent.com/75014380/187360315-7aec1cd5-2245-4a0a-b12e-939b648e3be8.png)

**Comment by Mister-Hope** [comment]
Upgrade to latest version and try again

**Comment by listenzz** [comment]
Same problem with 2.0.0-beta.235.

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@internal/pagesData' imported from /Users/listen/Developer/MyBook/node_modules/@vuepress/client/dist/chunk-IKARB3UY.js

**Comment by joseaquino5** [comment]
I got same issue, described here: https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/3534
