### ISSUE TITLE
[Bug] Cannot find package '@internal/pagesData'

### ISSUE THREAD

**Issue by Fatpandac** [vuepress-theme-hope/vuepress-theme-hope#2182]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-plugin-copy-code2

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

Throw err when building.

![A9D5F5C674D6D3EE8BECA38FAC54C151](https://user-images.githubusercontent.com/30423976/187355721-b5c6c542-88d5-4c53-9113-ebbe36e6c6a2.jpg)

**Comment by Mister-Hope** [comment]
Upgrade to latest version and try again

**Comment by Fatpandac** [comment]
No problem with the latest version. Thx.
