### ISSUE TITLE
[Bug] SideBar structure not work [已解决一半]

### ISSUE THREAD

**Issue by Yuelioi** [vuepress-theme-hope/vuepress-theme-hope#2186]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

呃...我一开始以为是bug,后面我研究了下,原来是每次运行run dev前必须删掉cache文件(.cache文件夹 .temp文件夹),不然就不会自动生成侧栏(估计是读了缓存)

---
目前有个问题, 虽然structure可以一键生成sidebar,但是不知道为啥,显示名称会带路径
```
"/zh/exp/":[
    {text: "",
    link: "/zh/exp/",
    prefix: "/zh/exp/",
    children:"structure"}
```

我还尝试了"/zh/exp/":structure",以及更改link 和 prefix,都不行,是我操作问题么

最终显示
/zh/exp/目录1.md
/zh/exp/目录2.md

期望显示:
目录1
目录2

**Comment by Mister-Hope** [comment]
侧边栏自动生成功能不支持热更新，如果你每次启动会更新那是正常的，但如果你必须去删除缓存目录才能更新的话，这可能是一个vuepress的bug（我不相信你描述的这个行为）。
如果你非要这么说给我mininal reproduction。

你说得第二个问题我没看懂。我建议你先重新仔细看一遍文档。

**Comment by Yuelioi** [comment]
> 侧边栏自动生成功能不支持热更新，如果你每次启动会更新那是正常的，但如果你必须去删除缓存目录才能更新的话，这可能是一个vuepress的bug（我不相信你描述的这个行为）。 如果你非要这么说给我mininal reproduction。
> 
> 你说得第二个问题我没看懂。我建议你先重新仔细看一遍文档。

比如官方示例:https://vuepress-theme-hope.github.io/v2/zh/guide/layout/sidebar.html#%E9%80%9A%E8%BF%87%E6%96%87%E4%BB%B6%E7%BB%93%E6%9E%84%E8%87%AA%E5%8A%A8%E7%94%9F%E6%88%90



官方目录结构
├─ foo/
│   ├─ README.md
│   ├─ one.md
│   └─ two.md
└─ bar/
    ├─ README.md
    ├─ three.md
    └─ four.md
配置项为
```
"/foo/": "structure",
"/bar/": "structure",
```


而我的目录
└─ zh/
    └─ exp/
          └─ 1.md
          └─ 2.md
          └─ README.md

而我的配置项为(这样没错吧)
```
"/zh/exp/":"structure"
```

生成的侧边栏为
/zh/exp/1.md
/zh/exp/2.md

**Comment by Mister-Hope** [comment]
说的很详细，reproduction please

**Comment by Mister-Hope** [comment]
![Screenshot_2022-08-31-02-06-02-72_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/33315834/187510960-9ed47ca2-3e0d-493d-8376-9997129feb7a.jpg)

你这里大多数文件都没标题啊

**Comment by Yuelioi** [comment]
ok 懂了,原来需要手动加title或者h1.  我以为是全自动~
