### ISSUE TITLE
[Bug] Absolute *.md links are reported as broken while they are not

### ISSUE THREAD

**Issue by vmihailenco** [vuepress-theme-hope/vuepress-theme-hope#2196]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

md-enhance

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

md-enhance reports links like `/foo.md` broken even though vuepress correctly resolves them and such links are useful, because they can be included from different directories, e.g.

- `/foo.md` always becomes `/base/foo.html`
- `foo.md` becomes `/base/curr/dir/foo.html` depending on the curr dir
- `/foo.html` always becomes `/foo.html`
- `foo.html` becomes `/base/curr/dir/foo.html` depending on the curr dir

### Additional context

I understand that relative links are recommended, but absolute links have some uses too.

**Comment by Mister-Hope** [comment]
so absolute markdown links are 
 reported as
 broken, this is the central point right?

**Comment by vmihailenco** [comment]
Yes, they are printed as broken in console, but vuepress-next correctly resolves them and you click them without an issue.

**Comment by vmihailenco** [comment]
For example, `/foo.md` is reported as broken but `foo.md` is not. Both links are resolved as `/base/foo.html`.

**Comment by Mister-Hope** [comment]
You'd better give me a reproduction, as I relook into my code and my debug result, I DONOT find anyting broken.

**Comment by vmihailenco** [comment]
Look like `base` option is required to trigger this - https://github.com/vmihailenco/theme-hope-abs-link

```shell
yarn install
yarn docs:dev
yarn run v1.22.19
$ vuepress dev docs
⠋ Initializing and preparing datawarning Broken links found in README.md: /foo.md
✔ Initializing and preparing data - done in 72ms
Port 8080 is in use, trying another one...

  vite v3.0.9 dev server running at:

  ➜  Local:   http://localhost:8081/base/
  ➜  Network: http://192.168.100.9:8081/base/
  ➜  Network: http://25.35.219.205:8081/base/
  ➜  Network: http://172.22.0.1:8081/base/
  ➜  Network: http://172.21.0.1:8081/base/
```

**Comment by SrChach** [comment]
Same problem over here!

With absolute paths and the use of urls like this `/path/to/file.md#demo`, it launches a broken URL error.
The URL really exists, but the use of `#` is triggering the error.

System: Windows
Plugins: Latest (Vuepress 2.0.0-beta.51, vuepress-plugin-md-enhance 2.0.0-beta.100)

Image of the demo error.

![image](https://user-images.githubusercontent.com/24685831/190012855-70094d65-7541-4720-b59e-13e8d82b3841.png)

Description of the image:
Upside left: The link to the "broken" url.
Upside right: The URL actually existing, and the file name
Down: The error launching "broken url" while not really broken.

**Comment by Mister-Hope** [comment]
This should work, will be release in new version.

If you need it now, you may apply a patch to `md-enhance` package.
