### ISSUE TITLE
[Bug]"通过文件结构自动生成" sidebar似乎不起作用

### ISSUE THREAD

**Issue by ShaoClean** [vuepress-theme-hope/vuepress-theme-hope#2201]
### Checklist

- [ ] I am using **LTS** version of Node.js.
- [x] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [ ] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [ ] I am following the docs and I am sure I am using the correct configuration.
- [ ] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

"通过文件结构自动生成" sidebar似乎不起作用。

### Additional context

我参照[这里](https://vuepress-theme-hope.github.io/v2/zh/guide/layout/sidebar.html#%E9%80%9A%E8%BF%87%E6%A0%87%E9%A2%98%E8%87%AA%E5%8A%A8%E7%94%9F%E6%88%90)设置了"structure",甚至没有出现侧边栏

我的目录结构是这样的
```md
.
├── .vuepress
├── README.md
├── essay
│   ├── 2022
│   └── README.md
├── project
│   ├── CYOU.md
│   ├── README.md
│   └── cyou-js.md
├── slides.md
├── study
│   ├── backend
│   └── frontend
└── teach
    ├── 1.md
    ├── 2.md
    └── 3.md
```
我想自动生成`teach`文件夹下的sidebar,我是这样写配置的：

```{5}
//sidebar.ts
export default sidebar({
  "/study/frontend":frontendSidebar,
  "/study/backend":backendSidebar,
  "/essay/": essaySidebar,
  "/teach/": "structure"
});
```
虽然可以通过这样的方式来生成我预期中的sidebar:
```
//sidebar.ts
export default sidebar({
  "/study/frontend":frontendSidebar,
  "/study/backend":backendSidebar,
  "/essay/": essaySidebar,
  "/teach/": [
    "1",
    "2",
    "3"
  ]
});
```

但每次添加一个`.md`文件我都需要手动的去配置一下路径，挺不方便的

**Comment by Mister-Hope** [comment]
README.md is required as it stores infomation for structure sidebar.

**Comment by Mister-Hope** [comment]
Have a relook, give me a reproduction.

**Comment by ShaoClean** [comment]
> Have a relook, give me a reproduction.

I've tried.,but it doesn't work.
```
.
├── .vuepress
├── README.md
├── essay
│   ├── 2022
│   └── README.md
├── project
│   ├── CYOU.md
│   ├── README.md
│   └── cyou-js.md
├── slides.md
├── study
│   ├── backend
│   └── frontend
└── teach
    ├── 1.md
    ├── 2.md
    └── 3.md
    └── README.md
```

```
//sidebar.ts
export default sidebar({
  "/study/frontend":frontendSidebar,
  "/study/backend":backendSidebar,
  "/essay/": essaySidebar,
  "/teach/": "structure"
});
```
But i change the default option `enableAll: true` to `enableAll: false` solve the problem

Anyway,Thank you !

**Comment by Mister-Hope** [comment]
I am not fully understand your reply, a reproduction can be a repo link or a stackblitz link generate from https://stackblitz.com/fork/vuepress-theme-hope

**Comment by ShaoClean** [comment]
> I am not fully understand your reply, a reproduction can be a repo link or a stackblitz link generate from https://stackblitz.com/fork/vuepress-theme-hope

It seems not a bug
Maybe i forgot change the default option `enableAll: true` 
when i set this option to `enableAll: false`  it work
