### ISSUE TITLE
[Bug]books/learngit do not have valid sidebar config

### ISSUE THREAD

**Issue by rumosky** [vuepress-theme-hope/vuepress-theme-hope#2205]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

I have the following error when configuring multiple sidebars:
![QQ图片20220912230831](https://user-images.githubusercontent.com/41993388/189692289-2e026aa4-7486-4fb4-adb1-c83e59a9ccb9.png)

I am sure that I operate according to the document, and I have tried all the methods shown in the following figure
![QQ图片20220912230839](https://user-images.githubusercontent.com/41993388/189692418-71010478-8e98-4fb0-b811-487df8b2f06c.png)

![QQ图片20220912230855](https://user-images.githubusercontent.com/41993388/189692431-be3cbb2b-d2ef-4c57-9383-1c0e4cce0f94.png)

![QQ图片20220912230904](https://user-images.githubusercontent.com/41993388/189692449-be40f32d-5e11-42b1-9b9e-11fc7b2bea59.png)

Other people in the QQ group are also configured in this way, but her sidebar is OK。
Here is the source code address：https://gitee.com/rumosky_admin/rumosky-docs

### Additional context

"@vuepress/client": "2.0.0-beta.51",
    "@vuepress/plugin-search": "2.0.0-beta.51",
    "vue": "^3.2.27",
    "vuepress": "2.0.0-beta.51",
    "vuepress-theme-hope": "2.0.0-beta.97"
nodejs: 16.15.0

**Comment by Mister-Hope** [comment]
What's the address of error page?

**Comment by rumosky** [comment]
> What's the address of error page?

https://rumosky_admin.gitee.io/rumosky-docs/books/learngit

and when you click the sidebar menu, it will flash once.

**Comment by Mister-Hope** [comment]
Can not reproduce, sidebar is working on that page.

Ensure you are providing a valid reproduction, otherwise I will leave it and let bot automatically close it.

**Comment by rumosky** [comment]
> Can not reproduce, sidebar is working on that page.
> 
> Ensure you are providing a valid reproduction, otherwise I will leave it and let bot automatically close it.

I know, It is no problem to open the link directly to the sidebar, however you can try to click the top navbar, then you will see the problem.

**Comment by Mister-Hope** [comment]
You'd better ensure you have the correct navbar configuration.

**Comment by rumosky** [comment]
> You'd better ensure you have the correct navbar configuration.

行了，我是真的服了，导航栏我试过了，还是不能解决这个路由问题，明明可以看一下源码就说问题在哪的，在群里问了几天都是没人理，唯一一个管理员回复还没比我强多少，行了，你们忙吧，打扰了。谢谢！

**Comment by Mister-Hope** [comment]
明明看一下源码？这是开源项目，爱用不用，我本来就没有义务看你代码给你查错。
