### ISSUE TITLE
[Bug]Cannot find package 'typescript' imported from xxx

### ISSUE THREAD

**Issue by ShaoClean** [vuepress-theme-hope/vuepress-theme-hope#2207]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

when i update the version from `v2.0.0-beta.97` to `v2.0.0-beta.98` appear the error

### Additional context

at first,i install the version `v2.0.0-beta.98` but it have error:
![SCR-20220913-enn](https://user-images.githubusercontent.com/98806795/189795454-6779a2ad-a95f-4a53-8dc8-4875854e84e1.png)

and then i reinstall the version `v2.0.0-beta.97`，it can work:
![SCR-20220913-eo5](https://user-images.githubusercontent.com/98806795/189795671-527ce178-8fad-481f-83fb-baebe3e5eefc.png)

**Comment by Mister-Hope** [comment]
I think installing typescript solves this issue.

**Comment by ShaoClean** [comment]
> I think installing typescript solves this issue.

Why can my previous version be used without typescript  QaQ

**Comment by Mister-Hope** [comment]
Because we add playground and vue-playground in new versions, don't worry, we will try to remove typescript as dependency in next version.

**Comment by ShaoClean** [comment]
> I think installing typescript solves this issue.

3Q！！It's really ts's problem.
