### ISSUE TITLE
[Feature Request] Support for sorting files by numeric prefixes to generate sidebars and remove it in url

### ISSUE THREAD

**Issue by northword** [vuepress-theme-hope/vuepress-theme-hope#2213]
### Checklist

- [X] I searched exising issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

The [documentation](https://vuepress-theme-hope.github.io/v2/zh/guide/layout/sidebar.html#%E9%80%9A%E8%BF%87%E6%96%87%E4%BB%B6%E7%BB%93%E6%9E%84%E8%87%AA%E5%8A%A8%E7%94%9F%E6%88%90) describes a feature that generates a sidebar for sorting files based on file names and numeric tags. 

In use, some users may sort files directly by numeric prefixes, which not only allows the sidebar to be sorted correctly, but also allows the files to be in the correct order in the file manager, for example:

```
src
├── README.md
├── 02-Tutorial Easy
│   ├── README.md
│   ├── 02-Second Part.md
│   └── 03-End.md
├── 03-Tutorial Hard
│   ├── README.md
│   ├── 02-Second Part.md
│   ├── 03-Third Part.md
│   └── 04-End.md
└── 04-End.md
```

In the current version of hope, the following html file will be generated:

```
src
├── README.md               // index.html
├── 02-Tutorial Easy
│   ├── README.md           // 02-Tutorial Easy/index.html
│   ├── 02-Second Part.md   // 02-Tutorial Easy/02-second Part.html
│   └── 03-End.md           // 02-Tutorial Easy/03-End.html
├── 03-Tutorial Hard
│   ├── README.md           // 03-Tutorial Hard/index.md
│   ├── 02-Second Part.md
│   ├── 03-Third Part.md
│   └── 04-End.md
└── 04-End.md
```

However, we don't expect the numbers used for sorting to appear in the url as well, the expected url should be as follows:

```
src
├── README.md               // index.html
├── 02-Tutorial Easy
│   ├── README.md           // Tutorial Easy/index.html
│   ├── 02-Second Part.md   // Tutorial Easy/second Part.html
│   └── 03-End.md           // Tutorial Easy/End.html
├── 03-Tutorial Hard
│   ├── README.md           // Tutorial Hard/index.md
│   ├── 02-Second Part.md
│   ├── 03-Third Part.md
│   └── 04-End.md
└── 04-End.md
```

While we can do this by specifying the `permalink` in the forntmatter of the markdown file, specifying the permalink one by one is inconvenient.

### Additional context

For reference: 

A similar feature has been implemented on docusaurus: https://docusaurus.io/zh-CN/docs/sidebar/autogenerated#using-number-prefixes

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/189897122-1c081a5b-b052-4308-8470-3262eebb1670.png)
I am negative to all the features which will convert url from the original file structure. If we hardly change the url, it can break plugins and other features in many cases. Also it’s pretty bad to make soft redirect in router as it not SEO friendly.
