### ISSUE TITLE
[Feature Request] 建议在tag上也显示文章数量

### ISSUE THREAD

**Issue by twgh** [vuepress-theme-hope/vuepress-theme-hope#2219]
### Checklist

- [X] I searched exising issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

我注意到在侧边栏的分类上显示的有文章的数量, 如果tag上也有显示的话, 看起来会更好

**Comment by Mister-Hope** [comment]
主要是样式的问题导致没加数字，欢迎pr，附样式截图
