### ISSUE TITLE
[Feature Request] Add loading page while open the site

### ISSUE THREAD

**Issue by flottant** [vuepress-theme-hope/vuepress-theme-hope#2223]
### Checklist

- [X] I searched exising issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

I have been noticed that some other themes like vuepress-reco has the feature of presenting a loading page when the user has a bad Internet connection. Your theme is the most satisfied theme I've been used, and the feature would make the theme more beautiful.
Thanks a lot.

**Comment by Mister-Hope** [comment]
We have ssg support, why does the theme need a loading component?

**Comment by flottant** [comment]
Sorry for my unclear description. I mean the feature like this: 
https://starlightunion.github.io/blog/other/aboutblog/vuepress-loading-mask.html
![](https://i.imgur.com/0wYCmxz.jpeg)

**Comment by Mister-Hope** [comment]
You'd better learn something about SEO, and understand what's important for most blog and docs site

**Comment by flottant** [comment]
Fine. Thanks anyway.
