### ISSUE TITLE
[download feature as the type of PDF]

### ISSUE THREAD

**Issue by xwzbupt** [vuepress-theme-hope/vuepress-theme-hope#2233]
### Checklist

- [X] I searched exising issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

I think the `download feature` is what a lot of people need, considering the network conditions are not everywhere, and the theme is very beautiful.
If clicking the download button, a pdf file with all the information such as content and theme-style will be downloaded.

**Comment by Mister-Hope** [comment]
Ctrl + P
Then select PDF

If you want to improve print style, PR welcome.
