### ISSUE TITLE
[Bug] The duplication contents rendered on CDN wrapped site

### ISSUE THREAD

**Issue by snowyu** [vuepress-theme-hope/vuepress-theme-hope#2236]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

The website appears duplicate content after the site enables the CDN acceleration.

* Visit the website directly: https://edu-minetest.github.io/zh/
  * The content is ok.
* Visit the website through CDN: https://edu.ihom.app/zh/ 
  * Duplication content here now.

**Comment by Mister-Hope** [comment]
I probably don't want to check your issue. If your original site is rendering properly, then the issue must comes from your CDN.

A REMINDER: Check your CDN settings, specially whether you enable something related to minify. Close them and try again.

**Comment by Mister-Hope** [comment]
Also something related is ALREADY warned at doc's FAQ part.

**Comment by snowyu** [comment]
There no any options to setting, It just forwards the data from one domain to another domain.

I thinks the data has been mixed from the two domains.

The cloudflare and github page's CNAME are the same error result.

**Comment by Mister-Hope** [comment]
> I thinks the data has been mixed from the two domains.

I see no assets comming from original domain

![image](https://user-images.githubusercontent.com/33315834/192433298-94edc783-4e9c-4552-9e61-5f248d7f4522.png)

Also, make sure you are closing this:

https://vuepress-theme-hope.github.io/v2/faq/common-error.html#hydration-completed-but-contains-mismatches

**Comment by Mister-Hope** [comment]
One last word, I inisit this issue belongs to your CDN. Stop wasting my time and dig it by your own.
