### ISSUE TITLE
[Feature Request]为 sidebar 添加自定义图标

### ISSUE THREAD

**Issue by BryanYin** [vuepress-theme-hope/vuepress-theme-hope#2239]
### Checklist

- [X] I searched exising issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

我们有一些菜单项，希望使用自己的 png 做图标。现在的 workaround 是：使用 iconfont 中不存在的一个，比如 `aaaa`，然后用 css 自定义 `icon-aaaa` 的样式，在 `::before` 里添加自定义图片。

但是这个方案如果用 fontawesome 就不行，fa 会用 `missing` 图标替换不存在的图标导致 `::before` 被遮盖。

所以看看主题中能否添加这个功能。

### Additional context

![image](https://user-images.githubusercontent.com/25950822/192927064-d15da1b0-852a-434b-8c8b-ee71a475df6b.png)

类似这样

**Comment by Mister-Hope** [comment]
一切需求都可以用主题组件替换来解决，autolink给你足够多的属性和插槽进行定制了

**Comment by Mister-Hope** [comment]
另外我回忆了一下，你也许可以直接将icon设置为图片，你可以试试

**Comment by BryanYin** [comment]
> 另外我回忆了一下，你也许可以直接将icon设置为图片，你可以试试

谢谢！刚试了下，确实可以。Hope 先生有时间的话，可以考虑把这个说明也加到文档中。
Hope 主题的文档相当不错，我选用 vuepress 才几天，已经配置出一个相当满意的 blog 了。
