### ISSUE TITLE
[Bug]包含日期的文件命名无法显示文章date属性

### ISSUE THREAD

**Issue by cysong** [vuepress-theme-hope/vuepress-theme-hope#2241]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

我创建了一篇文章，命名为：2022-08-05-hello-world.md，permalink可以正常生成，结果为/2022/08/05/hello-world/，但是文章的date没有展示，而且在博客首页该文章展示在列表的最后
期望：
当不设置Frontmatter.date属性时候可以从文件名读取date取值，与permalink保持一致

**Comment by Mister-Hope** [comment]
We never ever support this feature, if you want, you can set `fontmatter.date` using `extendsPage` lifecycle describe in https://v2.vuepress.vuejs.org/reference/plugin-api.html#extendspage
