### ISSUE TITLE
[Bug] 侧边栏点击会闪烁2次

### ISSUE THREAD

**Issue by oorzc** [vuepress-theme-hope/vuepress-theme-hope#2242]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

![](https://cdn.jsdelivr.net/gh/oorzc/public_img@main/img/2022/09/29/20220929212704.gif)
点开侧边栏会有一次动画，再点击子菜单还会出现，再次点击子菜单就没动画了
能把第一次点击子菜单的动画取消吗，感觉体验不是很好

**Comment by Mister-Hope** [comment]
我个人认为这可以是个bug，但我认为修不了。PR welcome

**Comment by qouteall** [comment]
如果很难修的话，可不可以直接关闭侧边栏的动画（主内容的动画仍然保留）。

**Comment by Mister-Hope** [comment]
你们可以继承组件来去掉动画
