### ISSUE TITLE
[Feature Request]About article encryption

### ISSUE THREAD

**Issue by zhangfanhang** [vuepress-theme-hope/vuepress-theme-hope#2245]
### Checklist

- [X] I searched exising issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

After testing the source file name of the encrypted article in the theme configuration item must be English or numeric to be judged as an encrypted article and appear in the "/encrypt/" page. Do I need to specify this in the documentation?

**Comment by Mister-Hope** [comment]
I may need a reproduction
