### ISSUE TITLE
[Bug] run `npm i -D vuepress-plugin-md-enhance@next` error

### ISSUE THREAD

**Issue by fengling68** [vuepress-theme-hope/vuepress-theme-hope#2271]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-plugin-md-enhance

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

run `npm i -D vuepress-plugin-md-enhance@next` error

<img width="584" alt="image" src="https://user-images.githubusercontent.com/88468872/194733923-4d37c019-121c-44ed-b43a-f8a10ef98a87.png">

**Comment by Mister-Hope** [comment]
https://www.npmjs.com/package/@vue/repl

Try not be too noob, if you use a mirror registry, try doubt whether it sync all deps first.
