### ISSUE TITLE
[Bug]WALINE_META is not defined

### ISSUE THREAD

**Issue by ShaoClean** [vuepress-theme-hope/vuepress-theme-hope#2277]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

WALINE_META is not defined at version 2.0.0-beta.108

i use version  2.0.0-beta.100 previously,when i update to version beta.108 my console show the error like this:
![SCR-20221010-wg](https://user-images.githubusercontent.com/98806795/194768851-04faec13-2945-45ed-a97f-439d38be47eb.png)
![SCR-20221010-10c](https://user-images.githubusercontent.com/98806795/194769304-8e165ab8-d00b-4399-a6a0-8f3709d2c3c2.png)

this is my config：
```
//them.ts

 plugins: {
    blog: {
      autoExcerpt: false,
    },
    comment: {
      provider: "Waline",
      serverURL: "https://doc.shaoclean.top/",
    },
```

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/main/packages/comment2/src/node/plugin.ts#L67-L67

**Comment by ShaoClean** [comment]
> https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/main/packages/comment2/src/node/plugin.ts#L67-L67

your means i missing icon？

**Comment by Mister-Hope** [comment]
REPRODUCTION is needed before further talk.

**Comment by ShaoClean** [comment]
> REPRODUCTION is needed before further talk.

https://stackblitz.com/edit/vuepress-theme-hope-eulv9f?file=blog/.vuepress/theme.ts
i changed the `serverURL` to my url:
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/98806795/194868603-6b19cac0-c2da-4ca0-b3d5-f85edd71fcac.png">

<img width="410" alt="image" src="https://user-images.githubusercontent.com/98806795/194868870-3d826393-4dca-4980-bf68-9b03ac024a84.png">

**Comment by ShaoClean** [comment]
> REPRODUCTION is needed before further talk.

sorry,`WALINE_META is not defined` is not a bug
but i got new `DevTools warning`
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/98806795/194870796-3ec4b164-99af-4c74-b54c-7c78f4191c70.png">

and this is my reproduction:
https://stackblitz.com/edit/vuepress-theme-hope-eulv9f?file=package.json
