### ISSUE TITLE
[Bug] 文章列表浏览量有问题

### ISSUE THREAD

**Issue by JQiue** [vuepress-theme-hope/vuepress-theme-hope#2278]
### Checklist

- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

关于 Waline 的配置是没有问题的，页面似乎不能展示访问量？

**Comment by Mister-Hope** [comment]
Need reproducion

**Comment by JQiue** [comment]
> 前往我的网站：https://jinqiu.wang

**Comment by JQiue** [comment]
补充：数据交互正常
![image](https://user-images.githubusercontent.com/45145407/194830855-d0d387c5-0ba2-46ef-8541-47bab1424848.png)
但文章信息栏没有访问量显示
![image](https://user-images.githubusercontent.com/45145407/194831190-3d9bf893-262f-46af-82a4-b080e1909415.png)

**Comment by Mister-Hope** [comment]
你开访问量显示了么？为何不自己多校对一下？

**Comment by Mister-Hope** [comment]
https://vuepress-theme-hope.github.io/v2/config/theme/layout.html#pageinfo

**Comment by JQiue** [comment]
> 你开访问量显示了么？为何不自己多校对一下？

已经开启了，在文章详情页显示正常，但在首页文章列表时似乎不显示，似乎忽略了列表的处理？我已经确定我的配置没有问题

比如：
![image](https://user-images.githubusercontent.com/45145407/194837591-0b3ca7ac-63d6-431f-907f-050046a03d59.png)
![image](https://user-images.githubusercontent.com/45145407/194837656-a82ef78a-d8e6-4402-a6ea-05ee96fa95d7.png)

**Comment by Mister-Hope** [comment]
那个功能自从v1就没支持过。如果需要的话可以当一个FR。V1 没实现的原因是因为当时的 @waline/client 还没有单独的浏览量分块。

**Comment by Mister-Hope** [comment]
不过这个功能需要评估一下，因为毕竟相当于直接为Waline加了一大段专属逻辑代码。

**Comment by Mister-Hope** [comment]
看了一下代码，原来这个部分已经重构完了，应该是修复了。
