### ISSUE TITLE
[Bug]Automatically jump to the search box

### ISSUE THREAD

**Issue by ShaoClean** [vuepress-theme-hope/vuepress-theme-hope#2279]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

when i press the `S` key of the keyboard
cursor automatically jump to the search box
<img width="380" alt="image" src="https://user-images.githubusercontent.com/98806795/194873364-266734da-6b54-45f9-89a6-c103ab830e9b.png">
this is reproduction：
https://stackblitz.com/edit/vuepress-theme-hope-eulv9f?file=blog/.vuepress/config.ts

**Comment by Mister-Hope** [comment]
https://v2.vuepress.vuejs.org/reference/plugin/search.html#hotkeys

**Comment by ShaoClean** [comment]
> https://v2.vuepress.vuejs.org/reference/plugin/search.html#hotkeys

ok，thanks
