### ISSUE TITLE
[Bug] 博客首页文章列表显示两次

### ISSUE THREAD

**Issue by fishool** [vuepress-theme-hope/vuepress-theme-hope#2294]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

博客模式  本地运行正常 ,
build部署到github page后首页文章列表会显示两次 .  从第二篇文章开始 
如果点击别的页面在通过navbar的主页返回 又正常了.  
Chrome浏览器无痕模式操作
![image](https://user-images.githubusercontent.com/20919225/195760660-f86cf730-9b48-47b4-90a8-b65c1230996f.png)
![image](https://user-images.githubusercontent.com/20919225/195760703-2e2c1c53-7fd1-4186-80e9-ae205bd99694.png)

### Additional context

= . =

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/a752754a8a55e2a8377e22e7f6bd5a7c7e5e2cbd
