### ISSUE TITLE
[Bug] A path navigation bug that I can't solve by myself

### ISSUE THREAD

**Issue by CriticalRange** [vuepress-theme-hope/vuepress-theme-hope#2316]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

I tried vuepress-theme-hope on GitHub actions. I managed to get it working (https://criticalrange.github.io) but now path navigation (aka breadcrumb https://vuepress-theme-hope.github.io/v2/guide/layout/breadcrumb.html) doesn't open in mobile devices.
Also same thing happens on Desktop site; sidebar cannot be closed.
Idk how to fix this one myself, and since I couldn't find a fix in anywhere.
My site is still WIP and if I can get this to work, I'll finish it faster.
Thank you for this lovely project!

### Additional context

This issue occurs in chrome version 105.0.5195.41 and I believe any other browser too.

**Comment by Mister-Hope** [comment]
1. No reproduction
2. If you found that everything is working at demo site, theme docs, my blog, etc., Then probably this is your own issue.

**Comment by Mister-Hope** [comment]
You may ask help in discussion if you can provide a reproduction repo and site.
