### ISSUE TITLE
[Feature Request] 能否以某种方式显示git的版本

### ISSUE THREAD

**Issue by trydofor** [vuepress-theme-hope/vuepress-theme-hope#2318]
### Checklist

- [X] I searched exising issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

通过文档首页，无法方便的得知当前文档对应的git版本，不知道文档新旧，最新更新日期等。
我想比较容易实现的方式是，设置一个全局变量，GIT_HASH, GIT_DATE，可被使用或自动替换。

**Comment by trydofor** [comment]
> 主题通过 @vuepress/plugin-git 插件在页面底部显示页面的最后更新时间与贡献者，并提供了“编辑此页”按钮的支持。
这个需求，只整个git的last commit，并非已经提供的单个页面的元数据

**Comment by Mister-Hope** [comment]
我没听懂，文档git的版本和更新时间，和文档有什么关系。。。。。

我猜你是想说，一个全局的文档更新时间？

**Comment by trydofor** [comment]
> 我猜你是想说，一个全局的文档最后更新时间？
是的，是整站，也就是整个git库的最新revision。

目前看到的文档，都是针对单个页面的last updated.
我感觉在首页readme.md表示整站的版本更好。

不想引入额外的插件，目前可以动手的时，

* 每次提交，动一下首页 readme
* 通过build脚本，获取git信息，脱离vue体系执行替换

**Comment by Mister-Hope** [comment]
你遍历一下所有页面，然后找到最新的时间不就得了？把它写回首页的页面数据，然后首页拿到数据渲染

**Comment by Mister-Hope** [comment]
关了啊，除了上面的之外，最后的commit id这种，你都可以在配置文件用 execa 调用 git 执行命令，并将结果格式化进行 define
