### ISSUE TITLE
[Bug] Feature broken due to bugs in vp2@beta.52

### ISSUE THREAD

**Issue by zhangfanhang** [vuepress-theme-hope/vuepress-theme-hope#2327]
Content from the author:

## ATTENTION: Due to bugs in vp2@beta.52, any version above beta.110 may not be workable.

_Original content:_

### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

The online document sidebar cannot be clicked

https://vuepress-theme-hope.github.io 

I tried to change different browsers, devices and mobile phones, but this problem occurred

**Comment by Mister-Hope** [comment]
Related to https://github.com/vuepress/vuepress-next/issues/1140

**Comment by Mister-Hope** [comment]
We will revert docs to beta.110 as a workaround

**Comment by Mister-Hope** [comment]
VP beta53 revert this, and we are upgrading to beta53, soon a new version will land
