### ISSUE TITLE
[Feature Request] Turkish language support

### ISSUE THREAD

**Issue by ngurmen** [vuepress-theme-hope/vuepress-theme-hope#2346]
### Checklist

- [X] I searched exising issues and no one else requests similar feature.
- [ ] I think that 25%+ users are positive towards this feature.

### Describe the feature

This feature will add "/tr/" language to all locales.ts files.  The translations have been finished and they are ready for a PR.  Just created this issue to learn about the process.  Thank you.

**Comment by Mister-Hope** [comment]
PR welcome 🤗

**Comment by Mister-Hope** [comment]
Any update about this? Any language related PR are welcomed, as we will only inject i18n config which are used by project. So there won't be any side effect adding new language support.

**Comment by ngurmen** [comment]
just raised the the PR #2357.  Thank you.
