### ISSUE TITLE
[Bug] Github Actions Deploy Error

### ISSUE THREAD

**Issue by SaraiNoQ** [vuepress-theme-hope/vuepress-theme-hope#2348]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

deploy-docs.yml 文件中 ”设置 Node.js“ 这个一步骤失败

### Additional context

初始化项目时启用了默认的Github Actions选项。提交代码后，GithubActions显示在”设置 Node.js“的时候失败，显示错误原因为”Error: Dependencies lock file is not found in /home/runner/work/vuepress-blog/vuepress-blog. Supported file patterns: pnpm-lock.yaml“

**Comment by Mister-Hope** [comment]
The temple should install deps for you and you should update your lock file.

**Comment by Mister-Hope** [comment]
I will add examples for yarn and npm on docs, also generate correct actions for users.

**Comment by Mister-Hope** [comment]
Improved in https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/c01573dda90fdad517ae300dd9821203994e7572 and https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/2693206c71d3dedea023f61ac401986b52d1cec0 If you still have issues, then probably you need to check your gitignore.

**Comment by SaraiNoQ** [comment]
> The temple should install deps for you and you should update your lock file.

How should I update the lock file? Use the .gitignore to make sure the file `pnpm-lock.yaml` doesn't get uploaded? Or run `pnpm update`? I tried both ways but still failed.

**Comment by SaraiNoQ** [comment]
> Improved in [c01573d](https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/c01573dda90fdad517ae300dd9821203994e7572) and [2693206](https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/2693206c71d3dedea023f61ac401986b52d1cec0) If you still have issues, then probably you need to check your gitignore.

my .gitignore file is as follows：
```
node_modules
# pnpm-lock.yaml

# Vuepress Cache
.cache/
# Vuepress Temp
.temp/
# Vuepress Output
dist/
```
how to set it?

**Comment by Mister-Hope** [comment]
1. I am not seeing actual repo and action logs
2. The logs says you doesn't upload lock file, if you believe you did this, provide actual repo and actual logs.

**Comment by SaraiNoQ** [comment]
> 1. I am not seeing actual repo and action logs
> 2. The logs says you doesn't upload lock file, if you believe you did this, provide actual repo and actual logs.

I'm so sorry. I modified the directory structure of the project with reference to your project, and the problem of `lock file` has been solved. But Github Actions reported an error when `Build Docs` step. The error message is `/home/runner/work/_temp/e3d3fd56-d9f1-4ada-94f7-0fd2439e42c8.sh: line 2: **docs/src/.vuepress/dist/.nojekyll: No such file or directory**`. I did not find this file in the `/dist/` directory, so what I want to ask is how to solve this problem. Thanks!

**Comment by Mister-Hope** [comment]
If you change output folder, you need to edit the workflow command,**that's expected**. Update the path in error command  to your actual output folder

**Comment by Mister-Hope** [comment]
You may need to manually enable GitHub pages

**Comment by Mister-Hope** [comment]
Also, issue panel is not the correct place for help. You may need to go to discussion panel
