### ISSUE TITLE
[Bug]Too many tags will not wrap

### ISSUE THREAD

**Issue by Charlieconomy** [vuepress-theme-hope/vuepress-theme-hope#2364]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

I have a page that has many tags, or a few tags with much content each. The problem is they are all displayed in one line. Better to be wrapped.

And, with a too long tag line, when you click the sidebar item, it will automatically position to the horizontal center of the page. 

### Additional context

nothing

**Comment by Mister-Hope** [comment]
Need reproduction site

**Comment by Mister-Hope** [comment]
Also a little more explaination, it the layout is obviously broken, I may try to fix this, but if the long tags are not "displaying well", then you should override ArticleItem and PageInfo components and edit the layout by your own.

**Comment by Mister-Hope** [comment]
Closing as no response.

I would recommend you override article-info and page-info components and make tag-info be the last item and let it be at it's own line by setting it with `display: block`
