### ISSUE TITLE
[Bug] "Collapsable" isn't correct spelling and can lead to confusion

### ISSUE THREAD

**Issue by Daeraxa** [vuepress-theme-hope/vuepress-theme-hope#2377]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq.html)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

Not technically a bug as such but something that caused us a headache for a while trying to find out what we couldn't get the collapsible token to work.
The token for collapsing a sidebar item is `collapsable` but this isn't correct English which would be `collapsible`. 

This led to somebody writing the "correct" spelling into the sidebar configuration and it took a while to work out what the actual problem was.

See - https://github.com/pulsar-edit/pulsar-edit.github.io/pull/94

### Additional context

(FYI the link to check the FAQ in the template checkboxes takes you to a 404 page - https://vuepress-theme-hope.github.io/v2/faq.html)

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/7d3144c341bb75c4ceba33e0efff3c0146ce5c52
