### ISSUE TITLE
[Feature Request]能不能实现文章特定部分加密？

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#2399]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

[Feature Request]能不能实现文章特定部分加密？就是比如上半部分未加密，后半部分加密。类似使用特定 
::: password 123asd

:::

我觉得会不错～

### Additional context

[Feature Request]能不能实现文章特定部分加密？就是比如上半部分未加密，后半部分加密。类似使用特定 
::: password 123asd

:::

我觉得会不错～

**Comment by Mister-Hope** [comment]
建议自行实现。

前端加密都是伪加密，本身这东西就不牢靠。所以我觉得没有必要实现复杂的加密功能。
