### ISSUE TITLE
[Bug] v122 is generating "useDarkMode is called without provider" error

### ISSUE THREAD

**Issue by ngurmen** [vuepress-theme-hope/vuepress-theme-hope#2400]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [x] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [X] Linux

### Describe the bug

I just updated to v122 to be able to receive the latest updates on Giscus for tr lang support.  I updated the configs to change _collapsable_ to _collapsible_.  

On my local machine everything is working as expected with `yarn serve`.  `yarn build` completed as expected as well.  

I uploaded the build to server.  When I visit the page, the home page flashes for a millisecond but then only shows a dark theme background with the following errors on the console.

![image](https://user-images.githubusercontent.com/70996543/201191093-4d15dc9d-59ca-4d78-9a3a-bb85f756cea8.png)

### Additional context

I left our dev server broken overnight in case it helps your troubleshooting.  You can see it https://docs.dexalot-dev.com.

**Comment by Mister-Hope** [comment]
I am not sure whether you checked faq and ensure only **one Vue version** is existed in your project.

**Comment by ngurmen** [comment]
You are right.  I did not check FAQ careful enough.  Thanks.  All versions were the same in the package.json but I had not run `yarn && yarn upgrade` to fix the dependencies.  It is working as expected now.
