### ISSUE TITLE
[Bug] Cannot perwiev mermaid

### ISSUE THREAD

**Issue by harry-xi** [vuepress-theme-hope/vuepress-theme-hope#2403]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

本地预览无法正常渲染mermaid
但build生成结果正常
相关日志
```
Uncaught (in promise) SyntaxError: The requested module '/@fs/D:/xxx/项目根目录/node_modules/dagre/index.js?v=e68e26ac' does not provide an export named 'default' (at mermaid.core.mjs?v=e68e26ac:13:8)
```
> `/xxx/项目根目录/`是为了遮盖隐私而进行的替换

### Additional context

packge.json和package-lock.json
[npmPackageInfo.zip](https://github.com/vuepress-theme-hope/vuepress-theme-hope/files/9991056/npmPackageInfo.zip)
在我的本地环境中，这一bug可在任意vuepress-theme-hope项目的本地预览里复现

**Comment by Mister-Hope** [comment]
> - [x]  I am using the latest v2 version of vuepress-theme-hope and all plugins in this repo.

# YOU SHOULD BE RESPONSIBLE FOR THIS OPERATION!

**Comment by odranoelBR** [comment]
@harry-xi After update to vuepress-theme-hope@2.0.0-beta.125
It fixes this error.
