### ISSUE TITLE
图标问题[Bug]

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#2406]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

有些图标会和选择的图标显示的不一样，还有些的图标第一次进去显示的和设置的不一样。刷新后才一样，部分刷新也不一样。
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/48122016/201459624-60964b14-d423-4a71-90ab-531a4b0031ec.png">
刷新后：
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/48122016/201459636-9f912400-1637-4226-825d-67348d992513.png">

**Comment by Mister-Hope** [comment]
The screenshot is "localhost", I need reproducion.

**Comment by AndersonHJB** [comment]
https://bornforthis.cn/column.html

**Comment by Mister-Hope** [comment]
If you use more than 1 iconfont link, a private char might be used twice.

![image](https://user-images.githubusercontent.com/33315834/201647418-c0aed5c6-3f2b-4d3e-bc81-6ba59eae9bdc.png)

**Comment by AndersonHJB** [comment]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/48122016/201865086-fee3e10e-5d72-4fd1-8753-4efe28914522.png">
就一个哎，打扰了。不知道怎么找😂

**Comment by AndersonHJB** [comment]
解决了，感谢🙏辛苦了
