### ISSUE TITLE
[Bug]底部的footer 部分被隐藏掉了

### ISSUE THREAD

**Issue by itwanger** [vuepress-theme-hope/vuepress-theme-hope#2420]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

<img width="453" alt="image" src="https://user-images.githubusercontent.com/6011374/202328887-c9bc09a0-e81c-4d55-aae8-26c4d7b47ee1.png">

**Comment by Mister-Hope** [comment]
Give me the link of that page please

**Comment by Mister-Hope** [comment]
https://tobebetterjavaer.com/home.html#%E8%81%94%E7%B3%BB%E4%BD%9C%E8%80%85

Your website seems working fine.

**Comment by Mister-Hope** [comment]
Closing as no response, I will reopen it if you can give me a reproduction

**Comment by mcxinyu** [comment]
他说的是屏幕不够宽而footer太长的时候，例如网页不是全屏宽度的时候，就会出现footer被侧边栏覆盖。


> 我想喷一下，如果是开发人员，说话、描述问题应该说清楚点，不然在公司跟其他人交流也是很累的。别跟产品动不动动刀子。
