### ISSUE TITLE
[Bug] Some packages are missing beta.123 version

### ISSUE THREAD

**Issue by Sun-ZhenXing** [vuepress-theme-hope/vuepress-theme-hope#2423]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Install error cased by repo version, repo mirror still in `2.0.0-beta.122` but create version is `2.0.0-beta.123`：

```bash
pnpm create vuepress-theme-hope@next docs
```

Got this:

```console
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for vuepress-theme-hope@2.0.0-beta.123

This error happened while installing a direct dependency of D:\WorkSpace\VuePress2\vuepress-hope-blog

The latest release of vuepress-theme-hope is "1.30.0".

Other releases are:
  * beta: 1.31.0-beta.2
  * next: 2.0.0-beta.122

If you need the full list of all 425 published versions run "$ pnpm view vuepress-theme-hope versions".
Progress: resolved 2, reused 2, downloaded 0, added 0
```

Can we update the repo mirror first and then update the template, or is there another way?

### Additional context

```bash
pnpm --version
# 7.16.1

node --version
# v16.13.1
```

**Comment by Mister-Hope** [comment]
Thanks for reporting, but I am in China mainland, and it's hard for me to publish packages and takes long time. We are using ci to publish now, so the publish time will reduce to 1 min from 3min-30min

**Comment by Mister-Hope** [comment]
I got what you are reporting, some of the pacakges are not published to npm registry.

**Comment by Sun-ZhenXing** [comment]
Everything is fine now.

When I got the error, I tried the following with success:

```bash
pnpm create vuepress-theme-hope@2.0.0-beta.122 .
```

**Comment by Mister-Hope** [comment]
Yes, but some of the beta123 does not been published. I will republish them when I have time. My school network cannot connect nom registry

**Comment by Mister-Hope** [comment]
We republish those versions and ensure they exisits.
