### ISSUE TITLE
[Bug] 引入antd样式导致深色模式失效，样式被覆盖

### ISSUE THREAD

**Issue by NoeyNoi** [vuepress-theme-hope/vuepress-theme-hope#2424]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

组件或全局引入antdv（v2）样式导致深色模式背景色失效
如： import 'ant-design-vue/dist/antd.css'

**Comment by Mister-Hope** [comment]
That's your own problem.
