### ISSUE TITLE
[Bug]search-pro插件依赖错误

### ISSUE THREAD

**Issue by yorunning** [vuepress-theme-hope/vuepress-theme-hope#2428]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope/search-pro

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

见search-pro/package.json[第57行](https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/main/packages/search-pro/package.json#L57)，npm安装该插件会报错提示sass-loader没有13.3d.0这个版本。
```
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "^13.3d.0" of package "sass-loader@^13.3d.0": Tags may not have any characters that encodeURIComponent encodes.
```

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/79191565e0efb47bcb63992ed9ee27f94c8a05a3
