### ISSUE TITLE
[Upstream bug] vuepress-plugin-md-enhance flowchart feature is not working with pnpm under vite devServer

### ISSUE THREAD

**Issue by zc-r** [vuepress-theme-hope/vuepress-theme-hope#2429]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-plugin-md-enhance

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

单独引用vuepress-plugin-md-enhance插件，启动后控制台报错
> var FlowChart = require('./flowchart.chart');
require is not defined

**Comment by Mister-Hope** [comment]
This is a upstream problem.

Flowchart has raw require, and can not be force optimized by vite with pnpm.
