### ISSUE TITLE
vuepress-theme-hope 运行 `npm run docs:dev` 打包报错，版本2.0.0-beta.122，node.js 版本【v14.17.1】

### ISSUE THREAD

**Issue by Largefreedom** [vuepress-theme-hope/vuepress-theme-hope#2430]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

报错信息如下，显示是语法错误：

PS D:\Coding\PersonalDocumentWebsite\docs> npm run docs:build

> zero-docu-website@2.0.0 docs:build
> vuepress-vite build src

✔ Initializing and preparing data - done in 361ms
⠏ Compiling with vite"useScriptTag" is imported from external module "@vueuse/core" but never used in "node_modules/vuepress-plugin-components/lib/client/vueuse.js", "node_modules/vuepress-plugin-photo-swipe/lib/client/config.js", "node_modules/vuepress-plugin-md-enhance/lib/client/components/FlowChart.js", "node_modules/vuepress-plugin-md-enhance/lib/client/components/ECharts.js", "node_modules/vuepress-plugin-md-enhance/lib/client/components/CodeTabs.js", "node_modules/vuepress-plugin-md-enhance/lib/client/components/Tabs.js", "node_modules/vuepress-plugin-components/lib/client/components/BackToTop.js", "node_modules/vuepress-theme-hope/lib/client/composables/mobile.js", "node_modules/vuepress-theme-hope/lib/client/modules/outlook/composables/darkmode.js", "node_modules/vuepress-plugin-md-enhance/lib/client/SlidePage.js", "node_modules/vuepress-theme-hope/lib/client/components/CommonWrapper.js", "node_modules/vuepress-theme-hope/lib/client/modules/encrypt/composables/global.js", "node_modules/vuepress-theme-hope/lib/client/components/PageNav.js", "node_modules/vuepress-theme-hope/lib/client/modules/outlook/components/ToggleFullScreenButton.js", "node_modules/vuepress-theme-hope/lib/client/modules/outlook/components/OutlookButton.js", "node_modules/vuepress-theme-hope/lib/client/modules/encrypt/composables/path.js" and "node_modules/vuepress-theme-hope/lib/client/modules/navbar/components/NavScreen.js".
⠏ Compiling with vite
(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✔ Compiling with vite - done in 28.89s
✖ Rendering 27 pages - failed in 64ms
file:///D:/Coding/PersonalDocumentWebsite/docs/src/.vuepress/.temp/.server/app.5ce01d4f.mjs:4
import { strFromU8, unzlibSync, strToU8 } from "fflate/browser";
                                ^^^^^^^
SyntaxError: Named export 'strToU8' not found. The requested module 'fflate/browser' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'fflate/browser';
const { strFromU8, unzlibSync, strToU8 } = pkg;

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:120:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:165:5)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async file:///D:/Coding/PersonalDocumentWebsite/docs/node_modules/@vuepress/bundler-vite/dist/index.js:420:30
    at async file:///D:/Coding/PersonalDocumentWebsite/docs/node_modules/@vuepress/utils/dist/index.js:98:20    
    at async build (file:///D:/Coding/PersonalDocumentWebsite/docs/node_modules/@vuepress/bundler-vite/dist/index.js:408:3)
    at async CAC.<anonymous> (file:///D:/Coding/PersonalDocumentWebsite/docs/node_modules/@vuepress/cli/dist/index.js:228:3)

### Additional context

并且为了验证我自身项目的问题，重新创建了一个 vuepress-theme-hope 新项目 启动正常，打包时依旧报错，并且报错信息一样

**Comment by zc-r** [comment]
同问，我也遇到了

**Comment by Mister-Hope** [comment]
I need a reproduction.

I already take time to create one at https://github.com/Mister-Hope/vuepress-theme-hope-test with latest 124, but the ci passed.

To let me solve this issue, please make a mininal edit on this repo after forking it, then give me the repo link.

For example. if you tested and found out node 14 has this issue, change node-version in ci from 18 to 14.
