### ISSUE TITLE
[Feature Request] Describe how support for a new language can be added

### ISSUE THREAD

**Issue by iluwatar** [vuepress-theme-hope/vuepress-theme-hope#2436]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

The docs at https://vuepress-theme-hope.github.io/v2/config/i18n.html#setting-language list the supported languages. How can we add a new language to this list? What files need to be edited. Please describe it in the documentation.

**Comment by Mister-Hope** [comment]
https://vuepress-theme-hope.github.io/v2/config/theme/i18n.html

You'd better read docs more carefully.

**Comment by iluwatar** [comment]
Thank you for pointing it out. Sorry for bothering you.
