### ISSUE TITLE
[Upstream bug] Seo2 may cause issue with contents containing douuble quotes under devServer

### ISSUE THREAD

**Issue by 12Tall** [vuepress-theme-hope/vuepress-theme-hope#2448]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of vuepress and vuepress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

I have some unordered lists in my page, the first loading is normal, but when I refresh the page, it will report the following error in the console, while the ordered list is rendered well. Could you please help me to figure out the reason?   

`Uncaught (in promise) DOMException: Failed to execute 'querySelectorAll' on 'Document': 'head > meta[property="og:description"][content="..."]' is not a valid selector.`
   
![image](https://user-images.githubusercontent.com/29416757/203507274-c31b8b1d-0831-4066-a2eb-af79104994b4.png)

### Additional context

Here is the dependencies:   
```json  
{
  "devDependencies": {
    "@vuepress/client": "2.0.0-beta.53",
    "vue": "^3.2.45",
    "vuepress": "2.0.0-beta.53",
    "vuepress-theme-hope": "2.0.0-beta.125"
  },
  "dependencies": {
    "@vuepress/plugin-register-components": "^2.0.0-beta.53"
  }
}
```

**Comment by Mister-Hope** [comment]
Probably caused by complicated content in description.


I need that page link

**Comment by 12Tall** [comment]
Hello, the source file is located in <https://github.com/12Tall/12tall.github.io/blob/master/src/math/integral_transform/fourier-transform.md>, but the error occurs only in dev mode, so I think it's fine if you want to close this issue directly. Thanks :)

**Comment by Mister-Hope** [comment]
I will check it when I have time, it might be a upstream bug

**Comment by Mister-Hope** [comment]
I guess the problem is because of `[` and `]` brankets, could you check that?

**Comment by Mister-Hope** [comment]
Confirmed., see https://github.com/vuepress/vuepress-next/issues/1174

**Comment by windylaugit** [comment]
mark

**Comment by Mister-Hope** [comment]
There could be many workaround, such as replacing double quote wjth single quote.

**Comment by Mister-Hope** [comment]
Fixed upstream
