### ISSUE TITLE
这个作者根本就是个傲慢自大的喷子

### ISSUE THREAD

**Issue by sai18109** [vuepress-theme-hope/vuepress-theme-hope#2458]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

这个作者根本就是个傲慢自大的喷子， 问个问题搞不清楚状况就先喷一顿没看文档，看文档就三分钟之类得云云。

**Comment by WalterBrightHub** [comment]
?

**Comment by pokerjest** [comment]
？
