### ISSUE TITLE
日期问题貌似一直存在[Bug]

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#2465]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/48122016/204670641-6c9a4732-4b36-4cfa-9177-dd6c0d7e5c50.png">
之前写的文章也都莫名其妙的变成了 2022年11月28日
<img width="508" alt="image" src="https://user-images.githubusercontent.com/48122016/204670984-f893ac4a-e0ea-4893-a269-65f10c36b1e6.png">

**Comment by ToTryEveryThing** [comment]
@AndersonHJB 请问有解决办法吗

**Comment by AndersonHJB** [comment]
> @AndersonHJB 请问有解决办法吗

升级最新版本就行
