### ISSUE TITLE
[Bug] All pages being loaded at once

### ISSUE THREAD

**Issue by chaseconey** [vuepress-theme-hope/vuepress-theme-hope#2472]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

When building and deploying the statically generated site, it seems that all 1000 or so pages are loaded at once at various times when navigating through the site. Can't seem to figure out the root cause of this; any help would be great!

### Additional context

It looks to be caused by the index page having a `prefetch` for every single other page.

Example:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/1449463/205354992-7bba223b-b809-4819-a9ad-c14f28f29b2e.png">

_No response_

**Comment by Mister-Hope** [comment]
The you should open a discussion instead of an issue. I do think you are talking about pwa.
