### ISSUE TITLE
[plugin:vite:vue] Element is missing end tag.

### ISSUE THREAD

**Issue by YuyanCai** [vuepress-theme-hope/vuepress-theme-hope#2477]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

一些md文档不能解析成功，可能含有特殊标签之类的。
错误信息如下：

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/62503722/205451323-14f22c95-6678-4b32-8c8f-5759abade00b.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/62503722/205451253-69d75d19-7512-480b-be5c-7782512c4ccf.png">

**Comment by Mister-Hope** [comment]
Escapjng all tags format in markdown and html are expected
