### ISSUE TITLE
[Bug] `autoExcerpt` is disabled on docs:build

### ISSUE THREAD

**Issue by rockbenben** [vuepress-theme-hope/vuepress-theme-hope#2481]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Auto excerpt generation is not available both in devServer and build without hotReload. 

If I set `hotReload: true`, `autoExcerpt` is always enabled included in devServer.

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/62c9e38d1522cfb5497c2992f8f03d0b44c79006
