### ISSUE TITLE
[Bug] 显示语言不管选择English还是简体中文，打开的默认都是英文

### ISSUE THREAD

**Issue by meta-docs** [vuepress-theme-hope/vuepress-theme-hope#2488]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

显示语言不管选择English还是简体中文，打开的默认都是英文

**Comment by Cuteli12138** [comment]
抱歉我没有找到设置默认语言的选项，我想把根目录默认语言设为中文（考虑到主要受众是国内用户），采用了比较粗暴的办法，把建立/en目录，把生成的英文文件全扔进去，再把中文的文件移出来，更改config、theme等文件（很繁琐还是希望直接配置比较好），执行，然后终端一直显示`Initializing and preparing data`,电脑出现明显卡顿。
