### ISSUE TITLE
摘要图片显示问题[Bug]

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#2494]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

1. 运行、构建均未报错；
2. 问题描述：
摘要图片显示问题，正常显示：public 图片正常显示且加载；
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/48122016/205950104-81347025-8006-4f87-b34e-76658a1e1f20.png">
不能正常显示：
<img width="857" alt="image" src="https://user-images.githubusercontent.com/48122016/205950248-06a2041b-f8c8-40dd-a768-fe83e9340b93.png">
与文章一起的相对路径的图片。

**Comment by AndersonHJB** [comment]
确实，这确实是不好修复的问题，不过是否偷梁换柱呢？——比如，摘录遇到相对路径的图片，可以随机读取 public 下指定的图片目录呢？随机显示

**Comment by AndersonHJB** [comment]
或者，加一个判断？摘要生成的时候，如果判断是相对路径，那摘要就生成到此图片之前呢？会不会更好一些呢

**Comment by Mister-Hope** [comment]
Track https://github.com/vuepress/vuepress-next/issues/1179

**Comment by Mister-Hope** [comment]
Now excerpt is generated by vuepress-shared, and all non-supported elements will be removed.
