### ISSUE TITLE
视频能否添加一个 m3u8 解析呢？合成到 hope 主题呢[Feature Request]

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#2499]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

视频能否添加一个 m3u8 解析呢？合成到 hope 主题呢，有直接引入 mp4 的，能否引入 m3u8 呢？感谢🙏

**Comment by MonoLogueChi** [comment]
You can use [smplayer](https://smplayer.u2sb.com/) for the time being, and related functions of smplayer will be merged into hope in the future

**Comment by Mister-Hope** [comment]
Supported with ArtPlayer component.
