### ISSUE TITLE
[Bug] The component BlogHero not have slot heroInfo

### ISSUE THREAD

**Issue by init-qy** [vuepress-theme-hope/vuepress-theme-hope#2503]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

The component `BlogHero` not have slot `heroInfo`, [docs](https://vuepress-theme-hope.github.io/v2/cookbook/advanced/replace.html#using-slots)

https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/563e25769736d1ad3d233815490ff63d8ef0de6a/packages/theme/src/client/modules/blog/components/BlogHero.ts#L94-L98

**Comment by Mister-Hope** [comment]
Thanks for the feedback, since this component is simple, and normally people wound want a full rebuilt if the want to customize it, we decide to remove the other slot and remove it from docs.
