### ISSUE TITLE
VideoPlayer 未来支持 ts 视频加载么？[Feature Request]

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#2505]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

```url
<VideoPlayer src="https://github.aiyc.top/SQL-MySQL-Easy-Learn/01/02-SQL和NOSQL.ts" />
```

**Comment by Mister-Hope** [comment]
https://caniuse.com/?search=video%20format

**Comment by Mister-Hope** [comment]
我再把我的意思解释的明白点，我不关心视频格式支持的问题，这不是我需要头疼的东西。我只提供一个原生的 HTML 播放器，浏览器支持什么视频格式你就能放什么视频格式。

如果你有其他浏览器不支持或者部分支持的视频格式，请自己找解析库解析转换或者抹平，我做的是一个视频播放器组件，而不是一个 Web 视频播放器

**Comment by Mister-Hope** [comment]
Supported by APlayer
