### ISSUE TITLE
依赖版本冲突【vuepress-plugin-comment2】

### ISSUE THREAD

**Issue by gitHubDingGuo** [vuepress-theme-hope/vuepress-theme-hope#2513]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-plugin-comment2

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

 
 npm i -D vuepress-plugin-comment2@next
ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: vuepress@1.0.0
npm ERR! Found: vuepress@2.0.0-beta.53
npm ERR! node_modules/vuepress
npm ERR!   peerOptional vuepress@"2.0.0-beta.53" from vuepress-plugin-copyright2@2.0.0-beta.134
npm ERR!   node_modules/vuepress-plugin-copyright2
npm ERR!     vuepress-plugin-copyright2@"^2.0.0-beta.134" from the root project
npm ERR!   vuepress@"^2.0.0-beta.53" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev vuepress-plugin-comment2@"2.0.0-beta.136" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: vuepress@2.0.0-beta.54
npm ERR! node_modules/vuepress
npm ERR!   peerOptional vuepress@"2.0.0-beta.54" from vuepress-plugin-comment2@2.0.0-beta.136
npm ERR!   node_modules/vuepress-plugin-comment2
npm ERR!     dev vuepress-plugin-comment2@"2.0.0-beta.136" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\QDM\AppData\Local\npm-cache\eresolve-report.txt for a full report.

### Additional context

 
 npm i -D vuepress-plugin-comment2@next
ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: vuepress@1.0.0
npm ERR! Found: vuepress@2.0.0-beta.53
npm ERR! node_modules/vuepress
npm ERR!   peerOptional vuepress@"2.0.0-beta.53" from vuepress-plugin-copyright2@2.0.0-beta.134
npm ERR!   node_modules/vuepress-plugin-copyright2
npm ERR!     vuepress-plugin-copyright2@"^2.0.0-beta.134" from the root project
npm ERR!   vuepress@"^2.0.0-beta.53" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev vuepress-plugin-comment2@"2.0.0-beta.136" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: vuepress@2.0.0-beta.54
npm ERR! node_modules/vuepress
npm ERR!   peerOptional vuepress@"2.0.0-beta.54" from vuepress-plugin-comment2@2.0.0-beta.136
npm ERR!   node_modules/vuepress-plugin-comment2
npm ERR!     dev vuepress-plugin-comment2@"2.0.0-beta.136" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\QDM\AppData\Local\npm-cache\eresolve-report.txt for a full report.

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/releases

**Comment by gitHubDingGuo** [comment]
我知道了，@next 那个换成 2.0.0-beta134 就行了。
