### ISSUE TITLE
音频在不设置封面的时候，设置显示不正常。[Bug]

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#2523]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

<img width="859" alt="image" src="https://user-images.githubusercontent.com/48122016/206830551-e9e28709-8672-4fcf-84ac-ddcfddab2eff.png">
音频在不设置封面的时候，设置显示不正常。
官方文档，也就是你的文档也是这个问题[https://vuepress-theme-hope.github.io/v2/components/zh/guide/audioplayer.html#%E6%A1%88%E4%BE%8B](https://vuepress-theme-hope.github.io/v2/components/zh/guide/audioplayer.html#%E6%A1%88%E4%BE%8B)

**Comment by AndersonHJB** [comment]
添加封面或者标题，可以让设置显示正常。
<img width="882" alt="image" src="https://user-images.githubusercontent.com/48122016/206830652-602c925e-6ca6-4671-8f43-2fe75ee8041e.png">

**Comment by Mister-Hope** [comment]
nice catch
