### ISSUE TITLE
Markdown未来会支持渲染 SVG吗？[Feature Request]

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#2524]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

Markdown未来会支持渲染 SVG吗？xmind 可以导出 svg，所以想问问。

**Comment by AndersonHJB** [comment]
好像是支持的，但是大小不能限制：
<img width="670" alt="image" src="https://user-images.githubusercontent.com/48122016/206835400-00f865c7-13f7-4b3d-9f2f-4a13c15d76a8.png">
<img width="897" alt="image" src="https://user-images.githubusercontent.com/48122016/206835408-e8bd0944-d947-48c7-9af4-d6efcccc40e1.png">
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/48122016/206835416-337c70a3-ab8a-4c8c-b402-5910843918cd.png">

**Comment by Mister-Hope** [comment]
你直接用 image  标签渲染有什么问题么？如果你需要加载 SVG 中的脚本，自己写组件。

此问题无实际意义故关闭。

```md
![](./your.svg)
```
