### ISSUE TITLE
[Bug] dark mode, tag label text unreadable

### ISSUE THREAD

**Issue by jackhanyuan** [vuepress-theme-hope/vuepress-theme-hope#2536]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

In dark mode, the blog tag label text cannot be read clearly.
![Snipaste_2022-12-10_23-14-33](https://user-images.githubusercontent.com/24978318/206862276-77176613-ebae-40ac-b98c-48a24d045a35.png)

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/25401e6549b0684a11e5b1a6d56631e986607a31
