### ISSUE TITLE
[Bug] `_post` links have been changed

### ISSUE THREAD

**Issue by rockbenben** [vuepress-theme-hope/vuepress-theme-hope#2541]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

My blog articles are saved in the folder `_post`，but all the links are changed from `newzone.top/_post/xx.html` to `newzone.top/post/xx.html`.

**Comment by Mister-Hope** [comment]
This is a vp2 feature, as github omit folders and files starting with _ by default Jekyll, we ensure no file is affected by this .
