### ISSUE TITLE
主页表格能否自适应？[Bug]

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#2543]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/48122016/207097519-b4f9f059-ee49-4bc3-9b38-382870df3dc3.png">
表格太小了，有点丑，能否自适应呢？

**Comment by Mister-Hope** [comment]
This is what default table like.
