### ISSUE TITLE
[Bug] Code blocks containing long content breaks article list

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#2544]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

iPhone 13，
![image](https://user-images.githubusercontent.com/48122016/207210921-a181f27e-bc1f-4c69-8460-8802adb47dde.png)
图片是手机端没有放大的效果，左右两边被截掉了，突然出现的问题，dev 情况下没有问题。构建也没有报错、警告。

**Comment by Mister-Hope** [comment]
Any issues about layout like this should have a reproduction link included .

**Comment by AndersonHJB** [comment]
没有提交是我的问题，为此深感抱歉。[https://bornforthis.cn](https://bornforthis.cn)

**Comment by Mister-Hope** [comment]
You can add

```css
.blog-home {
  overflow: hidden;
}
```

in `.vuepress/styles/index.scss` as a workaround.
