### ISSUE TITLE
[Question] do not have valid sidebar config

### ISSUE THREAD

**Issue by jackhanyuan** [vuepress-theme-hope/vuepress-theme-hope#2549]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

- app-42b20751.js:57 /category/%E7%AE%97%E6%B3%95/ do not have valid sidebar config 
- Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

The url is here: https://findn.cn/category/%E7%AE%97%E6%B3%95/

![Snipaste_2022-12-14_13-09-31](https://user-images.githubusercontent.com/24978318/207511471-09a00689-a88c-47a5-acf2-31f7853abbfe.png)

**Comment by Mister-Hope** [comment]
Warnings are expected if you use "object sidebar config" and the currect path does not have a valid config.

- If you want to add sidebar to all pages, ensure you set a valid sidebar config for root locale path of each language.

- If you only want to show sidebar in certern pages, declare `'/': []` to tell theme that you do not want sidebar.

**Comment by Mister-Hope** [comment]
We may add this in faq.
