### ISSUE TITLE
[Bug] vuepress-plugin-lightgallery build issues

### ISSUE THREAD

**Issue by thanesh** [vuepress-theme-hope/vuepress-theme-hope#2568]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

I'm using the light gallery plugin. When trying to run `yarn run docs:build`, I get the below error. Seems to work fine when running `yarn run docs:dev`

```
export default lightGallery;
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)

```

### Additional context

my package.json file

```
  "devDependencies": {
    "vuepress": "^2.0.0-beta.59"
  },
  "scripts": {
    "docs:dev": "vuepress dev docs",
    "docs:build": "vuepress build docs"
  },
  "dependencies": {
    "@vuepress/plugin-docsearch": "^2.0.0-beta.59",
    "vuepress-plugin-lightgallery": "2.0.0-beta.143",
    "vuepress-theme-hope": "2.0.0-beta.143"
  }
```

_No response_

**Comment by init-qy** [comment]
@thanesh I notice the `^`, please make sure the package version,  https://github.com/vuepress/vuepress-next/issues/1195

**Comment by Mister-Hope** [comment]
See comment above, if you still think there are issues, reproducion is needed, if there is no updates I may close this tomorrow.

**Comment by thanesh** [comment]
@init-qy corrected, but that doesn't help with the issue. @Mister-Hope I have instead chosen to use vuepress-plugin-photo-swipe and it works without any issues. You can close this.
