### ISSUE TITLE
[Feature Request]support right anchor

### ISSUE THREAD

**Issue by stonebox1122** [vuepress-theme-hope/vuepress-theme-hope#2576]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

Add anchor navigation bar to the right of the document page
Simplify the structure of the left sidebar without losing the function of Title navigation within the page

**Comment by Mister-Hope** [comment]
Already supported.
