### ISSUE TITLE
[Bug] 2.0.0-beta.145博客主题首页文章列表没有配置projects时样式异常

### ISSUE THREAD

**Issue by SherryMW** [vuepress-theme-hope/vuepress-theme-hope#2584]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [X] Linux

### Describe the bug

2.0.0-beta.141升级到2.0.0-beta.145发现博客主题首页文章列表在没有配置projects配置项时样式显示异常
![A$HE{36Y17TYRDEH_R3U~84](https://user-images.githubusercontent.com/118236482/209636663-f4c8cea2-ef7a-4681-bcbf-11c6c51a0e14.jpg)

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/5b0fcf254c1f5c038c144bbfa44565068bc90d03
