### ISSUE TITLE
[Feature Request] Get LaTeX code when copying formulas

### ISSUE THREAD

**Issue by Sun-ZhenXing** [vuepress-theme-hope/vuepress-theme-hope#2597]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

use KaTeX:

```md
设 $a \in \mathbf{R},\, i = 1,\,2,\,\cdots,\,n$ 则

$$
\left(\sum_{i=1}^n a_i b_i\right)^2 \leqslant
\sum_{i=1}^n a_i^2 \sum_{i=1}^n b_i^2
$$

当且仅当 $a_i = kb_i$（$k$ 为常数，$i = 1,\,2,\,\cdots,\,n$）时取等号。
```

When copying the above, the user will get meaningless content:

```
设 a∈R, i=1, 2, ⋯ , na \in \mathbf{R},\, i = 1,\,2,\,\cdots,\,na∈R,i=1,2,⋯,n 则

(∑i=1naibi)2⩽∑i=1nai2∑i=1nbi2 \left(\sum_{i=1}^n a_i b_i\right)^2 \leqslant \sum_{i=1}^n a_i^2 \sum_{i=1}^n b_i^2
( 
i=1
∑
n
​
 a 
i
​
 b 
i
​
 ) 
2
 ⩽ 
i=1
∑
n
​
 a 
i
2
​
  
i=1
∑
n
​
 b 
i
2
​
 

当且仅当 ai=kbia_i = kb_ia 
i
​
 =kb 
i
​
 （kkk 为常数，i=1, 2, ⋯ , ni = 1,\,2,\,\cdots,\,ni=1,2,⋯,n）时取等号。
```

Suggested additions:
- Formula auto select all
- Automatic filling of formulas with LaTeX code when they are copied

Perhaps there should be uniformity between the different Tex plugins.

**Comment by Mister-Hope** [comment]
I never ever heard any other plugin support this feature, you are copying a website instead of a tex document. Moreover, pdf output by tex does not have any tex source metadata either.

I don't think there is any necessity here.

**Comment by Sun-ZhenXing** [comment]
In fact, Hexo Fluid has better performance, but is not fully supported.

Maybe I need to write my own plugin to implement this feature.

**Comment by Sun-ZhenXing** [comment]
Hi @Mister-Hope , I'm sorry to disturb you.

I found an official library that solves this problem perfectly, simply by importing:

```ts
import 'katex/dist/contrib/copy-tex.min.js'
```

or:

```html
<script src="https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/contrib/copy-tex.min.js" integrity="sha384-ww/583aHhxWkz5DEVn6OKtNiIaLi2iBRNZXfJRiY1Ai7tnJ9UXpEsyvOITVpTl4A" crossorigin="anonymous"></script>
```

I tested it and it works well.
