### ISSUE TITLE
[Feature Request]No default note or article list in /category or /tag path

### ISSUE THREAD

**Issue by YangXi2016** [vuepress-theme-hope/vuepress-theme-hope#2598]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

if user click 'category' or 'tag' inter corresponding. It's supposed to show  default note or article list.

![image](https://user-images.githubusercontent.com/20331378/210048198-652bbee8-aecd-4cb5-b440-a567ecd22a42.png)

the file is [/packages/theme/src/client/modules/blog/layouts/BlogCategory.ts]

**Comment by Mister-Hope** [comment]
> . It's supposed to show default note or article list.

I do not think that's reasonable.
