### ISSUE TITLE
菜单栏链接错误？[Bug]

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#2608]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/48122016/210222670-47c6088a-bdd2-4f67-b0fb-8e59a81fb6b1.png">
出现上面的图片效果，链接：https://bornforthis.cn/column/

我在尝试修改，不知道你看见这个问题的时候，链接是否还有效。如果这个不算 bug 打扰了，辛苦了。
<img width="591" alt="image" src="https://user-images.githubusercontent.com/48122016/210222829-3142b433-4572-41dc-a151-4df3d1f9d0b5.png">

**Comment by AndersonHJB** [comment]
原本是：

```js
{ 
    text: "专栏",
    icon: "columnszhuanlan",
    children: [
      { 
        text: "IT 文档主页",
        children: [
          "/column",
         ......
        ]
      },
```

修改后：

```js
{ 
    text: "专栏",
    icon: "columnszhuanlan",
    children: [
      { 
        text: "IT 文档主页",
        children: [
          "/column.md",
         ......
        ]
      },
```

不知道是不是这个问题，但是貌似能解决问题。

**Comment by AndersonHJB** [comment]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/48122016/210232551-3fab99e7-a8a8-4526-85cb-073227243605.png">
问题真的存在噢

**Comment by AndersonHJB** [comment]
解决方法貌似是，文件夹都要添加 README.md 才可以

**Comment by Mister-Hope** [comment]
这个插件的作用就是为每个页面添加 readme。

**Comment by Mister-Hope** [comment]
Should be fixed.
