### ISSUE TITLE
[Bug] Github pages double compiles the data

### ISSUE THREAD

**Issue by terminalsin** [vuepress-theme-hope/vuepress-theme-hope#2610]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://vuepress-theme-hope.github.io/v2/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

When deployed to github pages, the page renders twice the markdown? This does *not* happen locally and only via Github Pages.

Repository:
https://github.com/terminalsin/skidfuscator-website-new/

Github pages:
https://skidfuscator.dev/docs/

Image
![Wtf](https://i.imgur.com/WMcS4bd.png)

**Comment by terminalsin** [comment]
Fixed in 149 beta

**Comment by terminalsin** [comment]
This has begun persisting again completely out of the blue.

**Comment by terminalsin** [comment]
Bug found, keeping it here:

Cloudflare autominimize causes Vite.js to have hydration mismatch. To fix, disable autominimize

**Comment by Mister-Hope** [comment]
## Haven't I told you in docs? 

https://vuepress-theme-hope.github.io/v2/faq/common-error.html#hydration-completed-but-contains-mismatches

**Comment by Mister-Hope** [comment]
> 
<img width="509" alt="image" src="https://user-images.githubusercontent.com/33315834/210404674-8d127275-932a-4940-9030-8f8687004c22.png">

# ?
