### ISSUE TITLE
[Bug] headerDepth 设置项不生效

### ISSUE THREAD

**Issue by Pil0tXia** [vuepress-theme-hope/vuepress-theme-hope#2625]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

我参考了[这篇文档](https://vuepress-theme-hope.github.io/v2/zh/guide/layout/sidebar.html#嵌套的标题链接)
我在typora上写了一篇最多具有5级标题（即h5）的md，我需要在文档页的右侧显示 h2 ~ h5，所以我将`headerDepth`设置为了**4**。但是页面右侧的目录**仍然只提取了 h2 ~ h3 的标题**。
如图，`产生死锁的四个必要条件`是h3，在右侧目录有显示，但是**h4`互斥`就没有显示**。

![image](https://user-images.githubusercontent.com/41445332/210412721-0a8b8eef-5206-4848-aecc-15de0ecc9e7f.png)
![image](https://user-images.githubusercontent.com/41445332/210412926-36b23040-6f2a-41da-af9b-f4e9ea6011a4.png)

设置如图：

![image](https://user-images.githubusercontent.com/41445332/210413111-32401ec3-71f0-4bbc-afcb-bb9d5d84af59.png)

期待您的回复。感谢。

**Comment by Mister-Hope** [comment]
https://vuepress-theme-hope.github.io/v2/zh/guide/layout/sidebar.html#%E5%B5%8C%E5%A5%97%E7%9A%84%E6%A0%87%E9%A2%98%E9%93%BE%E6%8E%A5

**Comment by Pil0tXia** [comment]
只能在md文件中设置，不能全局生效吗？请问可否配置为全局生效呢？

**Comment by Mister-Hope** [comment]
![Screenshot_2023-01-04-02-01-36-81_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/33315834/210414844-f88367b0-fc88-4cdf-8910-0ab1f6931c0a.jpg)

So di you read this or not?

If you believe something is not working as expected, give ke a mininal reproduction.

**Comment by Pil0tXia** [comment]
I read. I changed default configs of `plugin-headers` to [2,5], with `theme.ts` and md file frontmatter both set `headerDepth` to 4, but it still doesn't works.

`plugin-headers` config:

![image](https://user-images.githubusercontent.com/41445332/210416031-4c4a7821-4770-479b-b512-b921678e0444.png)
![image](https://user-images.githubusercontent.com/41445332/210416089-abdc6abe-357d-4c10-9782-cbe2b881b6f9.png)
![image](https://user-images.githubusercontent.com/41445332/210416119-c30b7d9c-c455-4072-8377-d27c7718526c.png)

still only h2 ~ h3:
![image](https://user-images.githubusercontent.com/41445332/210416527-54e7159c-eba8-4e69-acca-c345522fe048.png)

**Comment by Pil0tXia** [comment]
What should I do to display level 5 headings?

**Comment by Pil0tXia** [comment]
请问该如何显示五级标题呢？
