### ISSUE TITLE
[Bug]When I jump with an A tag with an anchor, the anchor redirects to the first heading. 

### ISSUE THREAD

**Issue by OnlY0226** [vuepress-theme-hope/vuepress-theme-hope#2627]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

When I jump with an A tag with an anchor, the anchor redirects to the first heading.
Example:
click: < a href="/about/me#info">********< /a>
will auto redirects to /about/me#basic (the first heading)

**Comment by Mister-Hope** [comment]
https://user-images.githubusercontent.com/33315834/210503439-a61684ce-c321-43b5-bc4c-5d005c255b39.mp4

Reproduction site and screen records are needed.
