### ISSUE TITLE
[Bug] copyright2 demo link broken

### ISSUE THREAD

**Issue by olets** [vuepress-theme-hope/vuepress-theme-hope#2629]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

The demo linked at https://vuepress-theme-hope.github.io/v2/copyright/demo.html (source https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/main/docs/copyright2/src/demo.md?plain=1#L9) is broken.

<img width="502" alt="image" src="https://user-images.githubusercontent.com/3282350/210601494-0a46a36f-27e1-4cb6-a2b3-fd5b82e72456.png">

**Comment by Mister-Hope** [comment]
Thanks for letting us know, we already add the missing demo site
