### ISSUE TITLE
代码演示增加可选配置建议

### ISSUE THREAD

**Issue by yn-zxj** [vuepress-theme-hope/vuepress-theme-hope#2649]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/44137601/211196119-f907f6ce-5165-42fb-856d-e676c10e1ce4.png">
<img width="916" alt="image" src="https://user-images.githubusercontent.com/44137601/211196464-17f53982-15f6-44ef-be80-b96e752811b9.png">
1.希望在代码演示中json配置里加一个demo.code-header的配置项，类型当然是布尔型咯，我在页面仅仅需要一个代码演示，我不需要展示代码演示的header，也不需要展开看这个演示的代码，并且jsfiddle，codepen也是不需要展示了；还有一个原因是我此时真实的实现代码和这个展开里的代码其实实现不同，有一点点的差异，比如说：我真实的演示其实是用下图这样实现的，至于下面这个代码我要怎么展示，我可以用选项卡或者用自定义容器展示；
<img width="910" alt="image" src="https://user-images.githubusercontent.com/44137601/211196888-4c17d0c6-b33e-4179-b113-370beecd4982.png">

2.代码演示的样式`.code-demo-container`设置`max-height:400px`，可以考虑默认400px，同时增加可配置项，让用户自行配置需要的高度；
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/44137601/211196599-a9b75be9-8ce5-43f3-a112-011e4d4b2b33.png">

打扰大佬了，望大佬采纳，谢谢！

**Comment by Mister-Hope** [comment]
> 1.希望在代码演示中json配置里加一个demo.code-header的配置项，类型当然是布尔型咯，我在页面仅仅需要一个代码演示，我不需要展示代码演示的header，也不需要展开看这个演示的代码，并且jsfiddle，codepen也是不需要展示了；还有一个原因是我此时真实的实现代码和这个展开里的代码其实实现不同，有一点点的差异，比如说：我真实的演示其实是用下图这样实现的，至于下面这个代码我要怎么展示，我可以用选项卡或者用自定义容器展示；

那你为什么不直接iframe？

**Comment by Mister-Hope** [comment]
400px 属于 personal taste，没人阻止你自行覆盖这一css。

**Comment by yn-zxj** [comment]
学到了  谢谢！
