### ISSUE TITLE
[Bug]Cannot find package 'vuepress-plugin-sass-palette'

### ISSUE THREAD

**Issue by rockbenben** [vuepress-theme-hope/vuepress-theme-hope#2659]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

From v2.0.0-beta.150 through v2.0.0-beta.155, both `docs:dev` and `docs:build` result in the error `Cannot find package 'vuepress-plugin-sass-palette'` despite placing it in package.json. However, using v2.0.0-beta.149 yields normal results.

stackblitz test：https://stackblitz.com/edit/github-ixywnm

![image](https://user-images.githubusercontent.com/28252913/211711081-ada8728a-3446-4495-9010-fd6cce73cd64.png)

**Comment by Mister-Hope** [comment]
I do not think you have correct deps tree, check package-lock.json in your reproduction link, all versions are still at beta.149

Provide a valid one and I would like to relook

**Comment by Mister-Hope** [comment]
All I did is to remove pacakge-lock.json and reinstall all deps.

> [x]  I am using the latest v2 version of vuepress-theme-hope and all plugins in this repo.

Try to make sure you are doing the right thing next time:


https://stackblitz.com/edit/github-ixywnm-pcxsx1?file=package-lock.json

**Comment by rockbenben** [comment]
I retested in a local environment. Even after removing the node_modules and lock files and reinstalling the dependencies with `pnpm i && pnpm up && pnpm docs:dev`, the error persists. 

Only by first using `npm install` to install the dependencies and then using `pnpm docs:dev` is the website able to start normally.

**Comment by rockbenben** [comment]
repo：https://github.com/rockbenben/LearnData

The current version of the repo is 149. Updating the version to 155 in package.json and then using `pnpm i && pnpm up && pnpm docs:dev` to reinstall dependencies results in failure.

**Comment by Mister-Hope** [comment]
That's not a repro, create a branch and show the wrong result plz.

**Comment by rockbenben** [comment]
no `npm install`: https://github.com/rockbenben/vth_test/actions/runs/3894697931/jobs/6649041807
![image](https://user-images.githubusercontent.com/28252913/211862332-be89ebb3-0854-4dc4-a7a2-2bfb21049929.png)

with `npm install`: https://github.com/rockbenben/vth_test/actions/runs/3894656586/jobs/6648947306
![image](https://user-images.githubusercontent.com/28252913/211862427-4a5118ea-4686-4e78-8b7a-41d78eb019c3.png)

campare of branch: [https://github.com/rockbenben/vth_test/compare/npm...no](https://github.com/rockbenben/vth_test/compare/npm...no)
![image](https://user-images.githubusercontent.com/28252913/211862605-fdc1ccee-42f9-45da-b919-12d6006eebfa.png)

**Comment by rockbenben** [comment]
> I still think you get a broken lock file and deps tree.

Thank you, your assessment is correct. I placed the package.json in a new vuepress-theme-hope demo project, and the generated lock file was over 200kb, but in the old project the generated lock file was only 80kb. I am uncertain as to where the problem lies. I am now able to generate the pages normally by directly copying the demo lock to the old project.
