### ISSUE TITLE
[Bug] 博客文章数少于10时，首页样式出现异常

### ISSUE THREAD

**Issue by SherryMW** [vuepress-theme-hope/vuepress-theme-hope#2675]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

博客文章数少于10时，首页当点击时间轴时页脚样式闪烁一下，从时间轴选择到标签时也会出现该问题

**Comment by Mister-Hope** [comment]
The content at the bottom is supposed to shrink if you change page content height
