### ISSUE TITLE
Roadmap: Rebuild in vitepress

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress-theme-hope/vuepress-theme-hope#268]
Vite is stable now and Evan You is developing vitepress now.

Vitepress is using Vue3 and vite, and it's performance is quite good.

I am going to migrate to vitepress as soon as it's stable.

**Comment by Mister-Hope** [comment]
Since VuePress@v2 is supporting vite, I will no longer build vitepress-theme-hope

**Comment by ezzle** [comment]
Hi.

Can I use it with vitepress ? How to Configure and use it ?

**Comment by aaronlippold** [comment]
Given Vue2 is now end of life, does it make sense to reopen this issue and reconsider migration to vitepress?

**Comment by Mister-Hope** [comment]
The v2 is using vue3.

Basically VuePress is special at:

- Generates all page data at node side first for plugins and themes
- provides a powerful plugin api and theme api
- support multiple bundlers by providing a unified interface among them. 

But these trade off affect its performance and memory cost, specially comparing to VitePress.
