### ISSUE TITLE
加密时，渲染问题，本地调试出现bug[Bug]

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#2687]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

<img width="1539" alt="image" src="https://user-images.githubusercontent.com/48122016/213181646-e74f5fa9-8675-4420-8773-be3f2ee81595.png">

没有任何报错，输入密码后就正常了。

**Comment by AndersonHJB** [comment]
谷歌浏览器、苹果浏览器本地都出现此问题，我稍后部署看看有没有问题。

**Comment by AndersonHJB** [comment]
部署也有问题，链接：[https://bornforthis.cn/column/Python-core-technology-and-practice/19.html](https://bornforthis.cn/column/Python-core-technology-and-practice/19.html)

**Comment by it985** [comment]
> 谷歌浏览器、苹果浏览器本地都出现此问题，我稍后部署看看有没有问题。

![1](https://user-images.githubusercontent.com/62421120/213335854-d259201b-475c-47c8-825c-beeba7673c7c.png)

**Comment by it985** [comment]
> > 谷歌浏览器、苹果浏览器本地都出现此问题，我稍后部署看看有没有问题。
> 
> ![1](https://user-images.githubusercontent.com/62421120/213335854-d259201b-475c-47c8-825c-beeba7673c7c.png)

Microsoft Edge
