### ISSUE TITLE
[Bug] permalink not work

### ISSUE THREAD

**Issue by luweizheng** [vuepress-theme-hope/vuepress-theme-hope#2695]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

I want to use the `permalink` described in [VuePress doc](https://v2.vuepress.vuejs.org/zh/reference/frontmatter.html#permalink). When I add the `permalink` in frontmatter, nodejs cannot build successfully.

"node": v18.3.0
"vuepress-theme-hope": "2.0.0-beta.165" 
"vuepress": "2.0.0-beta.60".

**Comment by northword** [comment]
![image](https://user-images.githubusercontent.com/44738481/213903210-2bf88f2d-c8c4-4d2b-b70a-2c2eb5d54492.png)

In fact, permanent links are available, perhaps you need to give error logs or minimal reproduction. 
example: [dist](https://northword.cn/dft-learning/pages/69b75c/), [source](https://github.com/northword/wiki/blob/main/src/dft-learning/05.VASP/01.VASP%E8%BE%93%E5%85%A5%E8%BE%93%E5%87%BA%E6%96%87%E4%BB%B6/01.vasp-input-files.md). 

However, permanent links seem to cause exceptions in the auto-catalog plugin, which I will report later when I have confirmed.

**Comment by luweizheng** [comment]
> northword

Hi, thank you for your reply. Here is my repo. Source code is in `main` branch and dist is in `gh-pages` branch.

**Comment by northword** [comment]
> > northword
> 
> Hi, thank you for your reply. Here is my [repo](https://github.com/luweizheng/zh-wiki/). Source code is in `main` branch and dist is in `gh-pages` branch.

But you seem not to have added the `permalink` to the markdown file.

**Comment by luweizheng** [comment]
> > > northword
> > 
> > 
> > Hi, thank you for your reply. Here is my [repo](https://github.com/luweizheng/zh-wiki/). Source code is in `main` branch and dist is in `gh-pages` branch.
> 
> But you seem not to have added the `permalink` to the markdown file.

I do not add. Because if I add it, the CPU will reach 100% utilization and it cannot stop. I have to manual kill the build process.
I mean in the blog posts not the doc item, like [this one](https://github.com/luweizheng/zh-wiki/blob/main/src/blog/2022/2022-01-15-open-source-developer-payoff.md). I comment the `permalink` attribute.

**Comment by northword** [comment]
1. base should start with `/` and end with `/`, [base](https://github.com/luweizheng/zh-wiki/blob/main/src/.vuepress/config.ts#L6) should be `/zh-wiki`. 
2. Route paths should start with a "/", [permalink](https://github.com/luweizheng/zh-wiki/blame/main/src/blog/2022/2022-01-15-open-source-developer-payoff.md#L6) should be `/open-source-developer-payoff` or `/open-source-developer-payoff/`.

**Comment by northword** [comment]
> 1. base should start with `/` and end with `/`, [base](https://github.com/luweizheng/zh-wiki/blob/main/src/.vuepress/config.ts#L6) should be `/zh-wiki`.
> 2. Route paths should start with a "/", [permalink](https://github.com/luweizheng/zh-wiki/blame/main/src/blog/2022/2022-01-15-open-source-developer-payoff.md#L6) should be `/open-source-developer-payoff` or `/open-source-developer-payoff/`.

![image](https://user-images.githubusercontent.com/44738481/213905431-54300e50-eeee-4a32-9ab9-62918e392b37.png)

**Comment by luweizheng** [comment]
@northword thank you so much!
Another question.
Could you tell me If this is right: https://github.com/luweizheng/zh-wiki/blob/main/src/.vuepress/theme.ts#L57
I want to filter files with `/blog/` and show them in the blog home. The `dev` mode works and it shows like this:

<img width="725" alt="image" src="https://user-images.githubusercontent.com/57242864/213905845-fc3333eb-e370-4c96-b190-fd2a99e9fd9f.png">

But the build mode does not work. The theme includes other docs that I do not want to show in `/blog/` path. Both with my local mac and the CI on GitHub actions. I got the following:

<img width="729" alt="image" src="https://user-images.githubusercontent.com/57242864/213905866-205dbb8e-91e7-49ea-92f5-bda80787cdd5.png">

**Comment by northword** [comment]
may be https://theme-hope.vuejs.press/zh/config/frontmatter/info.html#article

**Comment by LarryDpk** [comment]
@luweizheng Hi, did you fix the issue? I hit this `permalink` issue while `Initializing and preparing data`, it stuck forever. 
```json
"devDependencies": {
    "@vuepress/client": "2.0.0-beta.61",
    "vue": "^3.2.47",
    "vuepress": "2.0.0-beta.61",
    "vuepress-theme-hope": "2.0.0-beta.201"
  }
```

```bash
$ yarn -v
1.22.19

$ npm -v
9.2.0
```

**Comment by luweizheng** [comment]
Just do what @northword wrote before.
