### ISSUE TITLE
[Feature Request]图标支持功能的建议

### ISSUE THREAD

**Issue by Ackerven** [vuepress-theme-hope/vuepress-theme-hope#2705]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

对于选择困难户来说，每写一篇文字都需要选一个图标是非常痛苦的，尤其是存在大量文章的时候。
我尝试把 `iconAssets` 和 `iconPrefix` 改成 `" "` 后，整个网站的图标都没有了，包括首页的。
能否可以只是单独关闭侧边栏和导航栏的图标，保留首页的图标。
另外，除了图标没有了，样式也有一些问题，不知道是bug导致的还是其他原因
我使用的版本是 2.0.0-beta.91
![image](https://user-images.githubusercontent.com/70303900/214514543-72aa45d8-7f55-40d4-955e-dfa1cc532dce.png)

**Comment by northword** [comment]
你只配置首页图标，文章和侧边栏图标不配置就好嘛

**Comment by Mister-Hope** [comment]
> 你只配置首页图标，文章和侧边栏图标不配置就好嘛

See here
