### ISSUE TITLE
[Bug]Home page layout error after refresh

### ISSUE THREAD

**Issue by Ackerven** [vuepress-theme-hope/vuepress-theme-hope#2716]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

It is normal when you visit for the first time, 

![image](https://user-images.githubusercontent.com/70303900/215243139-71261f41-f3f2-4b20-af74-e37aac9e6c8c.png)

and it will become like this after refreshing once.

![image](https://user-images.githubusercontent.com/70303900/215243149-2adef554-957f-44dc-8136-ac39d596989f.png)

In this case, if you checked "Remember Password" before, it will be the same when you reopen a new window, unless you enter the password again and enter.
When you open other pages, and then click the logo to return to the home page, it will return to normal.

![image](https://user-images.githubusercontent.com/70303900/215243216-3eb28470-048d-475b-8f4f-2911aa2bffa4.png)

This problem does not occur when you use the `pnpm docs:dev`. It will appear when the project is built and deployed using `pnpm docs:build`.

### Additional context

My website is accessible via [https://emois.fun](https://emois.fun). The password is `admin`

**Comment by Ackerven** [comment]
I tried using Chrome (Windows 10), Microsoft Edge (Windows 10), Firefox (Ubuntu 20.04) and this problem occurs.

**Comment by Mister-Hope** [comment]
Nice catch
