### ISSUE TITLE
[Feature Request]求支持waline的imageUploader

### ISSUE THREAD

**Issue by undefined-hestudio** [vuepress-theme-hope/vuepress-theme-hope#2717]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [x] I think that 25%+ users are positive towards this feature.

### Describe the feature

https://waline.js.org/reference/client/props.html#imageuploader

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/vuepress-next/pull/1052

**Comment by Mister-Hope** [comment]
Track https://github.com/vuepress/vuepress-next/pull/1286

We will support this after vuepress support client data.

**Comment by Mister-Hope** [comment]
This is now supported through `defineWalineConfig`
