### ISSUE TITLE
导出整个文档为 PDF这个功能呢？[Feature Request]

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#2721]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

就是现在不是有打印功能，这个功能也可以导出页面为 pdf，那有没有可能导出文档呢？变成 PDF 电子书？

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/48122016/215308592-8d77b7ce-5566-4095-82c0-b1be062abea9.png">

**Comment by Mister-Hope** [comment]
请自行寻找其他工具链，如 pandoc。

VuePress is a static site generator.

**Comment by Mister-Hope** [comment]
See https://github.com/condorheroblog/vuepress-plugin-export-pdf/tree/main/packages/vuepress-plugin-export-pdf-v2
