### ISSUE TITLE
[Feature Request] Fixed catalog order or customized

### ISSUE THREAD

**Issue by Sun-ZhenXing** [vuepress-theme-hope/vuepress-theme-hope#2728]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

The current catalog plugin brings uncertainty in each update, and unless order is specified, the following situation may occur.

![image](https://user-images.githubusercontent.com/44517244/215796071-c0546063-c3d8-40e2-ac6d-968cc01cfb27.png)

Is a custom method for global customization better?

```ts
(page_a: Page): string => {}

// or

(page_a: Page, page_b: Page): number => {}
```

**Comment by Mister-Hope** [comment]
Page is not available at client, only current page canbe accessed
