### ISSUE TITLE
[Feature Request] 评论插件考虑支持 artalk 吗

### ISSUE THREAD

**Issue by L-cw** [vuepress-theme-hope/vuepress-theme-hope#2733]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

最近看一个不错的评论项目，[artalk](https://artalk.js.org/)，独立部署很方便，评论插件有考虑支持这个么🤔

**Comment by Mister-Hope** [comment]
I would like to, but I need a demo env, the official docs cannot load comment correctly.

**Comment by L-cw** [comment]
> I would like to, but I need a demo env, the official docs cannot load comment correctly.

我现在在我的服务器上独立部署了一个Artalk
前端demo地址：https://jjdxb.top/demo.html
后台地址：https://comment.jjdxb.top/

emmm, 看下需要我提供什么可以帮助你实现demo环境呢

**Comment by Mister-Hope** [comment]
The problem is that I would like to have a env as demo if I add artalk, but I prefer not to deploy one on my server, if you can provide a stable demo env(backend), and I would like to use that.

**Comment by L-cw** [comment]
> The problem is that I would like to have a env as demo if I add artalk, but I prefer not to deploy one on my server as they have other services, if you can deploy provide a artalk instance for me, and I would like to use that as demos in documatation.

这样啊，那只好先这样了，我这个也没法保证稳定😂

**Comment by Mister-Hope** [comment]
We will see if we can get a reply from artalk team and if we can deploy a instance free at somewhere. Track https://github.com/ArtalkJS/Artalk/discussions/365

At least for me I refuse to use my own resources to deploy open source projects.

**Comment by Mister-Hope** [comment]
If you don't mind, I would like to use your instance before artalk itself adds vercel support.

Can you add `localhost:8080` and `https://plugin-comment2-demo.vuejs.press/` here?

- https://artalk.js.org/guide/backend/config.html#%E5%8F%AF%E4%BF%A1%E5%9F%9F%E5%90%8D-trusted-domains

**Comment by L-cw** [comment]
> If you don't mind, I would like to use your instance before artalk itself adds vercel support.
> 
> Can you add `localhost:8080` and `https://plugin-comment2-demo.vuejs.press/` here?
> 
> * https://artalk.js.org/guide/backend/config.html#%E5%8F%AF%E4%BF%A1%E5%9F%9F%E5%90%8D-trusted-domains

emm, 我部署一个新的给你当demo用吧，配置完成之后我把账号和API信息发到你的邮箱 mister-hope@outlook.com。

**Comment by Mister-Hope** [comment]
好的感谢

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/94a14888346ad92ce6d7c9f8bf88f9901077e7b4

**Comment by Mister-Hope** [comment]
I am not getting it worked, see details at https://github.com/ArtalkJS/Artalk/discussions/367. New version will not be landed unless this is fixed.
