### ISSUE TITLE
[Bug] build error

### ISSUE THREAD

**Issue by reonce** [vuepress-theme-hope/vuepress-theme-hope#2741]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

If the md document contains tags, styles, or other js events, packaging errors will occur
如果 md 文档中 包含 标签 、 样式 或者其他 js 事件，会导致打包报错

![image](https://user-images.githubusercontent.com/54665062/216772562-e16bca1f-f033-4d11-82e5-4f7f01c15dbf.png)

### Additional context

It is hoped to desensitize md documents
希望可以对 md 文档进行脱敏处理

**Comment by Mister-Hope** [comment]
```md
<a>

`<a>`

\<a>
```

will be

<a>

`<a>`

\<a>
