### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by patryk1979** [vuepress-theme-hope/vuepress-theme-hope#2751]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

When I set locale: 
`lang: "pl-PL"`
my browser (chrome 109.0.5414.119) stops rendering vuepress website and there is an error in console as below:
![pl-locale-problem](https://user-images.githubusercontent.com/111091273/217267045-fd17ced9-3f04-4350-bd18-6015612fb1ac.jpg)

**Comment by Mister-Hope** [comment]
<img width="359" alt="image" src="https://user-images.githubusercontent.com/33315834/217269661-b62e47b4-7a17-4a2f-83e2-ce4904da8b35.png">

skipToContent exisits in pl-PL as same as other language, you need to give me a reproduction

**Comment by patryk1979** [comment]
https://stackblitz.com/edit/vuepress-theme-hope-eybwck?file=docs/.vuepress/config.ts

**Comment by Mister-Hope** [comment]
Werid, thanks for providing detailed information

**Comment by Mister-Hope** [comment]
Shit, I forgot to add this in entry file.😅

**Comment by patryk1979** [comment]
thanks a lot :)
