### ISSUE TITLE
[Bug]mindmap有bug

### ISSUE THREAD

**Issue by topabomb** [vuepress-theme-hope/vuepress-theme-hope#2758]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

使用mermaid 的mindmap时，首次打开该页面loading后不展示图形，跳转其他页面再跳转回来之后，显示正常。

使用mermaid 的其他图形没这个问题。

包含mindmap的页面 刷新时同样不显示图形。

**Comment by Mister-Hope** [comment]
Working expected in my local env and https://plugin-md-enhance.vuejs.press/guide/mermaid.html#mindmap
