### ISSUE TITLE
[Bug] 优化一下打印模式中的代码块展示

### ISSUE THREAD

**Issue by JQiue** [vuepress-theme-hope/vuepress-theme-hope#2763]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

如果第一页中的内容很短，但不能容纳代码块，则会放到第二页，这导致第一页有大量的留白，至少应该是延续的？
![image](https://user-images.githubusercontent.com/45145407/218250459-2b2f4780-c5b1-4ccd-ab72-d3939cbb686b.png)

**Comment by Mister-Hope** [comment]
This is an expected behaviour, you can manually override css as you like.
