### ISSUE TITLE
[Feature Request] support plantuml

### ISSUE THREAD

**Issue by shirayner** [vuepress-theme-hope/vuepress-theme-hope#2773]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

we can support plantuml by using the following plugin:

- https://github.com/XhinLiang/markdown-it-plantuml-ex
- https://github.com/gmunguia/markdown-it-plantuml

**Comment by Mister-Hope** [comment]
You can build a plugin yourself, I didn't see much difference with mermaid, and I am not interested in any tools which requires other env.

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/913bbe7e077d38bd3f052c70184686cb03ddc5f6
