### ISSUE TITLE
[Bug] extendMarkdown not work

### ISSUE THREAD

**Issue by shirayner** [vuepress-theme-hope/vuepress-theme-hope#2774]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### 一、问题描述
按照如下流程集成 plantuml，在vuepress-theme-reco主题中，能正常展示plantuml，但是在vuepress-theme-hope 中无法展示。

### 二、问题复现

（1）安装 markdown-it-plantuml

```node
pnpm add -D markdown-it-plantuml
````

（2）config中配置extendMarkdown

```node
  markdown: {
    lineNumbers: true,
    extendMarkdown: (md) => {
      md.set({ breaks: true });
      md.use(require("markdown-it-plantuml"));
    },
  },

```

![image](https://user-images.githubusercontent.com/11574340/218381524-2a2f5fca-7b0c-4482-aa91-f316b8476f91.png)

![image](https://user-images.githubusercontent.com/11574340/218381571-46734352-f441-4150-bd99-0a16742aa89f.png)

（3）在任意一篇md中添加 plantuml代码块，不生效

**Comment by Mister-Hope** [comment]
https://theme-hope.vuejs.press/zh/cookbook/vuepress/config.html
