### ISSUE TITLE
侧边栏显示问题[Bug]

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#2781]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

侧边栏最底下的目录无法继续向上滑动到正常位置：

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/48122016/218677280-51b39f3f-9133-42d0-a733-429d05255401.png">

链接：[https://bornforthis.cn/1v1/06-KAI/18-Data-Structures-Programming-Assignment-1-OOP-Review.html](https://bornforthis.cn/1v1/06-KAI/18-Data-Structures-Programming-Assignment-1-OOP-Review.html)

**Comment by Mister-Hope** [comment]
You should manually adjust sidebar padding-bottom based on footer height.
