### ISSUE TITLE
Share[Feature Request]

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#2799]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

我觉得分享可以自动嵌套到每个页面，设置当中可以选择设置开启或关闭～

**Comment by Mister-Hope** [comment]
You can use alias and slots to do this.
