### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by mi-saka10032** [vuepress-theme-hope/vuepress-theme-hope#2805]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

本地搜索插件 vuepress-plugin-search-pro 从version@2.0.0-beta.167版本开始报这个错误，2.0.0-beta.166及之前是正常的
![image](https://user-images.githubusercontent.com/92041418/219922108-2542adf8-7b30-4f1d-a329-ae68f8dcc804.png)

另外一个本地搜索插件 @vuepress/plugin-search，从version@2.0.0-beta版开始就没有效果了，首页没有搜索按钮，最新版的控制台报错是这个
![image](https://user-images.githubusercontent.com/92041418/219922434-3f0fbb94-0ac0-44f2-8cec-3844c47f05d4.png)

建议标记一下，修复可用之后更新

**Comment by Mister-Hope** [comment]
Are you SURE you have read FAQ and do as it mentioned?
