### ISSUE TITLE
[Bug]搜索框不支持暗色主题了（这应该是个很严重且紧急的bug）

### ISSUE THREAD

**Issue by WangJincheng4869** [vuepress-theme-hope/vuepress-theme-hope#2810]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

![image](https://user-images.githubusercontent.com/41162158/219997662-8b071c5e-8dab-45dd-b70d-85c7f6c1ffbe.png)
![image](https://user-images.githubusercontent.com/41162158/219997680-827b69ef-daf2-4ea0-8238-064134a6eb35.png)
官网已经boom！
![image](https://user-images.githubusercontent.com/41162158/219998171-3106aaa0-2f8a-45c7-9138-bcb786955b3f.png)

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/1549e515e9cf1c5b637fcae8667b5e5477951d39
