### ISSUE TITLE
[Bug] Vue-Playground inconsistencies

### ISSUE THREAD

**Issue by kefniark** [vuepress-theme-hope/vuepress-theme-hope#2811]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Using the `vue-playground`, I run into some weird behavior

With the following settings I get the expected result:
```json
{
  "showCode": true,
  "showImportMap": false,
  "layout": "horizontal"
}
```
So I have code on the left, demo on the right, everything OK.
![image](https://user-images.githubusercontent.com/4903529/220005117-5d702e99-2575-4da2-850b-d4f04c3761c1.png)

But It's really verbose, so I would like to reveal the code only when user click on the action button.
```json
{
  "showCode": false,
  "showImportMap": false,
  "layout": "horizontal"
}
```

But when I try to do that, I run into some weird things:
* The code file doesn't open after clicking on the action button. The filename do appear, but the code block seems empty, and a second click on that empty container is necessary to show the code as expected (the red arrow show the container where to click to show the code). It feel like this block is not initializing properly.
![image](https://user-images.githubusercontent.com/4903529/220005504-7fcce45f-1d0d-4c18-9337-af6dcf9d464d.png)

* Less important but using "Horizontal" layout, the preview initially start with `width: 50%`, which kinda make sense but looks super strange. A big gray area, the preview would look better extending to 100%
![image](https://user-images.githubusercontent.com/4903529/220005774-60269c3c-2303-485b-a147-fc560c5a442f.png)

The first issue is even visible in the official documentation
https://theme-hope.vuejs.press/guide/markdown/vue-playground.html#usage

**Comment by Mister-Hope** [comment]
cc @FuckDoctors

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/916792a3a5e68484e3d1567645c697817db3ddcb

**Comment by kefniark** [comment]
Thanks 👍
Removing `showCode` was a bit drastic 😄, there is definitely a usage for it.
Based on the code in the demo and the type of documentation, it can be quite verbose to always display it.

**Comment by Mister-Hope** [comment]
The problem is that `@vue/repl` does not expose detailed editor instance, so reverting back to its default render behaviour solves this.

I am not actually interested in forking and maintaining a version of this package, if you have needs, maybe you can create feature request upstream.

**Comment by kefniark** [comment]
Yes I will probably submit few feature requests.
So far I'm quite happy with hope theme, just struggling a bit with playground/demo to get a result I'm fine with.

My other idea to make doc more readable was to use multiple files, like you have in the last example of https://theme-hope.vuejs.press/guide/markdown/vue-playground.html#demo
Hiding the bootstrap and noisy code in a `App.vue` and extracting just the 5-10 lines to showcase in another file or component. Easy to do, but sadly I can't find a way to select which file is open by default. An equivalent of `@tab:active code`, like `@file:active demo.ts`

**Comment by Mister-Hope** [comment]
You can read the source code of `<VuePlaygound>` in my repo and `<Repl>` in `@vue/repl`, honestly we are not doing much fancy things.
