### ISSUE TITLE
[Upstream Bug] Externalink sr-only breaks layout

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#2812]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

![IMG_0284](https://user-images.githubusercontent.com/48122016/220067032-4abe0f5e-aa74-42ba-b819-af26d462335b.PNG)
![IMG_0286](https://user-images.githubusercontent.com/48122016/220067050-04bd380b-cc14-42b1-8c39-a00055aacbf6.PNG)

链接：[https://bornforthis.cn/home.html](https://bornforthis.cn/home.html)

貌似只有这个页面才有问题。。。

**Comment by Mister-Hope** [comment]
Track https://github.com/vuepress/vuepress-next/issues/1266

**Comment by AndersonHJB** [comment]
receive
