### ISSUE TITLE
[Bug] Waline Comment affects page scroll behavior

### ISSUE THREAD

**Issue by SherryMW** [vuepress-theme-hope/vuepress-theme-hope#2814]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

在更新到2.0.0-beta.178后，从博客首页访问文章后页面滚动条并不是在最顶部，去除底部评论插件Waline后发现正常。2.0.0-beta.166没有这个问题

**Comment by SherryMW** [comment]
补充一下配置文件：
"devDependencies": {
    "@vuepress/client": "2.0.0-beta.60",
    "@vuepress/plugin-container": "2.0.0-beta.60",
    "@vuepress/plugin-docsearch": "2.0.0-beta.60",
    "element-plus": "^2.2.32",
    "js-yaml": "^4.1.0",
    "markdown-it": "13.0.1",
    "vue": "^3.2.47",
    "vuepress": "2.0.0-beta.60",
    "vuepress-theme-hope": "2.0.0-beta.178"
  }

**Comment by Mister-Hope** [comment]
Should be related to https://github.com/vuepress/vuepress-next/issues/1252

**Comment by SherryMW** [comment]
我的项目存储库地址是：https://github.com/SherryMW/Blog

**Comment by SherryMW** [comment]
> 应该与 [vuepress/vuepress-next#1252](https://github.com/vuepress/vuepress-next/issues/1252) 相关

收到

**Comment by Mister-Hope** [comment]
Should be fixed in https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/1bf15b866301d805d2d69d728435a6b39a496a43

**Comment by Mister-Hope** [comment]
I am not sure how to fix this, pr welcome

**Comment by OrageKK** [comment]
我找到了问题出在哪里
vuepress-plugin-comment2/lib/client/components/Waline.js下
```js
await import("@waline/client/dist/component.mjs")).Waline
```
引用的`@waline/client/dist/component.mjs`文件中，问题代码在解压缩后的623-626行，注释掉就好了
```js
const n = window.scrollY;
await C(0), window.scrollTo({
    top: n
})
```

**Comment by Mister-Hope** [comment]
Thanks I will review that later

**Comment by Mister-Hope** [comment]
Should be fixed in @waline/client@2.15.1, feedback welcomed. @OrageKK @SherryMW

**Comment by OrageKK** [comment]
Theme 205 version has fixed this problem, thank you

**Comment by OrageKK** [comment]
@Mister-Hope 最近又出现了这个问题，不过在本地dev没有问题，部署后还是出现了，
我的依赖版本
```json
 "vuepress-theme-hope": "2.0.0-beta.219",
 "@waline/client": "2.15.5"
```
