### ISSUE TITLE
[Feature Request]增加代码标记序号功能

### ISSUE THREAD

**Issue by WangJincheng4869** [vuepress-theme-hope/vuepress-theme-hope#2819]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

可以在代码区域选项中可以加入序号，如图这种功能，我可以详细解释这段代码的作用。或者在介绍中强调注意哪部分代码，这在一段代码中有多个标记的时候应该会比较有用。虽然功能可能有些鸡肋，但部分情况应该还是能够用到
![image](https://user-images.githubusercontent.com/41162158/220505105-d5b96239-e794-4b85-999e-4f1e2d90f39c.png)

**Comment by Mister-Hope** [comment]
I am not expecting this.

1. The implementation will be quite hacky:

 The original code fence has high priority in markdown-it, so a full rewrite for code block render is needed, however VuePress has already customize the part.

2. I don't think this is a common need.

In most languages you can use comment to describe what yiu are doing, and this is indeed most docs are doing.
