### ISSUE TITLE
[Bug]Layout Frontmatter configuration :dir.link failed

### ISSUE THREAD

**Issue by zhangfanhang** [vuepress-theme-hope/vuepress-theme-hope#2821]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

I tested the link configuration under dir for version 179 and it did not set the group links as README.md links, when I rolled back to version 159 it worked correctly

example:
---
title: Graph
dir:
  link: true
  order: 5
---

**Comment by Mister-Hope** [comment]
Could you provide a reproduction?

**Comment by zhangfanhang** [comment]
@Mister-Hope Next time I will be careful to provide demo, I just tested the latest version 180 seems to solve this problem.

**Comment by zhangfanhang** [comment]
https://stackblitz.com/edit/vuepress-theme-hope-yvecn8?file=docs/guide/bar/README.md ，I configured dir.link in README.md in the guide bar directory but it is still not clickable

**Comment by zhangfanhang** [comment]
@Mister-Hope
