### ISSUE TITLE
[Bug]plugin-auto-catalog插件在嵌套目录内存在README.md文件时不生成目录索引

### ISSUE THREAD

**Issue by gitsheny** [vuepress-theme-hope/vuepress-theme-hope#2822]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

在config.js中我配置目录自动生成侧边栏
```
    sidebar: {
      "/guide/": "structure",
    },
```
guide目录下有若干子目录，为了对目录进行排序，我在每个子目录/guide/xx/内放了一个README.md文件进行排序
```
---
index: false
dir:
  text: 目录
  order: 1
---
```
最后我在首页放了`<AutoCatalog base='/guide/' />`标签，但是不显示对应的索引，删除子目录内的README.md后正常

**Comment by Mister-Hope** [comment]
Working as expected, all pages without a valid title will be dropped as the plugin as no idea how to display them
