### ISSUE TITLE
[Bug]侧边栏没有收起功能

### ISSUE THREAD

**Issue by Soulballad** [vuepress-theme-hope/vuepress-theme-hope#2829]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

sidebar.ts 中内容如下：
```typescript
import { backend } from './sidebar/backend';
// ... 很多导入的包
export const zhSidebar = sidebar({
  '/backend/': backend,
  '/frontend/': frontend,
  '/database/': database,
  '/environment/': environment,
  '/algorithm/': algorithm,
  '/distribute/': distribute,
  '/mservices/': mservices,
  '/architecture/': architecture,
  '/interview/': interview,
});
```

config.ts 中配置侧边栏:
```typescript
sidebar: zhSidebar,
```

页面上侧边栏可以正常显示，但是没有收起功能
![image](https://user-images.githubusercontent.com/19262272/221401322-a4a7a200-e780-4910-976f-4c31956335ae.png)

**Comment by Mister-Hope** [comment]
Expected, layout changed in recent versions, only tablet / desktop view has collapsed button. Ahead official docs and change browser width to understand it.

**Comment by Soulballad** [comment]
> Expected, layout changed in recent versions, only tablet / desktop view has collapsed button. Ahead official docs and change browser width to understand it.

目前是在桌面端使用，这个必须要降级吗？后面的版本会恢复这个功能吗
