### ISSUE TITLE
[Feature Request] vuepress-plugin-search-pro 两个小需求

### ISSUE THREAD

**Issue by WangJincheng4869** [vuepress-theme-hope/vuepress-theme-hope#2830]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

1. 搜索框能否去除浏览器自带的历史记录功能，即关闭自动完成功能，添加`autocomplete="off"`或者可以配置搜索框是否关闭`autocomplete` 也可以，真的有些丑。
![image](https://user-images.githubusercontent.com/41162158/221405601-320cf60b-47cd-4c47-b3ed-517d68383eb4.png)
2. 打开搜索后自动选中搜索框，不用再次点击。
![image](https://user-images.githubusercontent.com/41162158/221405650-1fdaaad7-477b-490a-b153-29d22a90a493.png)

**Comment by Mister-Hope** [comment]
Reasonable, will be supported in next version.

**Comment by WangJincheng4869** [comment]
> Reasonable, will be supported in next version.

还有一个小小的需求：就是当搜索框已经呼出的时候，使用快捷键`Ctrl + K`时会触发浏览器的搜索，第二次按并不是关闭搜索。可以考虑添加第二次关闭搜索框。就像 `plugin-docsearch` 那样。
![image](https://user-images.githubusercontent.com/41162158/221405878-f2e4a74d-0824-46b5-a6cf-1c845ce264e5.png)

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/670234ca9e878f9c813e742ff4ba9bc9dc1d6337

**Comment by Mister-Hope** [comment]
> 还有一个小小的需求：就是当搜索框已经呼出的时候，使用快捷键Ctrl + K时会触发浏览器的搜索，第二次按并不是关闭搜索。可以考虑添加第二次关闭搜索框。就像 plugin-docsearch 那样。

无法实现，因为搜索的快捷键可以自定义，比如 S，在这种情况下默认聚焦搜索框时不可能输入S就直接关闭。

默认的关闭行为是 ESC
