### ISSUE TITLE
[Feature Request]  ToggleNavbarButton 希望可以配置隐藏

### ISSUE THREAD

**Issue by gitsheny** [vuepress-theme-hope/vuepress-theme-hope#2834]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

当我顶部导航栏只保留logo和搜索时，在移动端模式下，右侧仍有个ToggleNavbarButton 按钮，点击后下拉页面是空的

**Comment by Mister-Hope** [comment]
<img width="463" alt="image" src="https://user-images.githubusercontent.com/33315834/221537689-2ca1ee0b-00d7-4c70-a5bc-59ad06165914.png">

https://theme-hope-blog-demo.vuejs.press/

NavScreen can contain other contents, also it has slots, where the toggle button component has no idea whether NavScreen slots have contents or not.

You can just hide it with css if you want to disable it.
