### ISSUE TITLE
[Bug] lacks the HTML suffix with `/_posts`

### ISSUE THREAD

**Issue by rockbenben** [vuepress-theme-hope/vuepress-theme-hope#2836]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

If the value of the prefix contains an underscore, such as `/_posts/`, the generated article link is incorrect and lacks the HTML suffix.

```ts
  {
    text: "博客文章",
    icon: "blog",
    prefix: "/_posts/",
    link: "/blog",
    collapsible: true,
    children: "structure",
  },
```
![image](https://user-images.githubusercontent.com/28252913/221627155-93ad8c11-e49f-4397-af8e-361c9d26c751.png)

**Comment by Mister-Hope** [comment]
We filter some special characters while inferring path.

In your case, there is no route path containing `_post`

**Comment by rockbenben** [comment]
Yes, the links on the blog page have already been correctly redirected to the post links. However, in v2.0.0-beta.183, the links generated in the sidebar have not had the underscores removed.

example:
blog site：`/posts/2023-01-26-whiteboard_gtd.html`
sidebar：`/_posts/2023-01-26-whiteboard_gtd`
