### ISSUE TITLE
[May be a Bug] Error generating favicon path for a full URL

### ISSUE THREAD

**Issue by DynamicLoader** [vuepress-theme-hope/vuepress-theme-hope#2839]
### Checklist

- [x] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

当使用完整URL作为favicon路径时(e.g. `https://r.dyldr.top/imgs/favicon-32x32.png`)，输出的路径带上了hostname导致无法获取图片。使用pwa插件指定的就正常。

望排查。

### Additional context

Nope

**Comment by Mister-Hope** [comment]
Seems like a bug, `favicon` in theme options right?
