### ISSUE TITLE
[Bug]从博客主页进去文章时，会记录滚动条在首页时离顶部的距离，从而导致查看文章不会从最上方开始。

### ISSUE THREAD

**Issue by Stephen-wzw** [vuepress-theme-hope/vuepress-theme-hope#2843]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

1. 从博客首页文章列表查看文章详情 
![image](https://user-images.githubusercontent.com/72367140/221785191-17184722-c282-4342-9a0b-c2742be1d962.png)
2. 文章会离顶部有一定距离
![image](https://user-images.githubusercontent.com/72367140/221785450-8afe123f-81c7-4174-9899-8e6b7a807c31.png)

**Comment by Mister-Hope** [comment]
See https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/2814, please check if your case is related with WalineComment

**Comment by Stephen-wzw** [comment]
Yes, I used WalineComment, and according to [#](https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/2814#issuecomment-1446273617), I uptated the dep, but it still doesn't seem to work.

**Comment by Mister-Hope** [comment]
Then please check the original one, I will check later to see why it's affecting scroll when I have time.
