### ISSUE TITLE
[Bug] Cannot find module 'vuepress/package.json' when using version` 2.0.0-beta.184` or higher

### ISSUE THREAD

**Issue by DreamOfIce** [vuepress-theme-hope/vuepress-theme-hope#2847]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

# 概述
今天更新到版本`2.0.0-beta.184`后出现了这个问题，测试发现最新的`beta.185`问题仍然存在，回退到`beta.183`后问题解决
具体报错如下：
``` console
PS E:\documents\repo\core-js> npm run docs:dev

> core-js@3.28.0 docs:dev
> npm run --workspace=docs dev


> dev
> vuepress dev

Error: Cannot find module 'vuepress/package.json'
Require stack:
- E:/documents/repo/core-js/docs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at file:///E:/documents/repo/core-js/docs/node_modules/vuepress-theme-hope/lib/node/index.js:1:6653
    at Array.forEach (<anonymous>)
    at ca (file:///E:/documents/repo/core-js/docs/node_modules/vuepress-theme-hope/lib/node/index.js:1:6624)
    at file:///E:/documents/repo/core-js/docs/node_modules/vuepress-theme-hope/lib/node/index.js:83:171
    at resolvePluginObject (file:///E:/documents/repo/core-js/node_modules/@vuepress/core/dist/index.js:633:65)
    at resolveThemeInfo (file:///E:/documents/repo/core-js/node_modules/@vuepress/core/dist/index.js:925:23)
npm ERR! Lifecycle script `dev` failed with error: 
npm ERR! Error: command failed
npm ERR!   in workspace: corejs-doc
npm ERR!   at location: E:\documents\repo\core-js\docs
```
# 问题追踪
根据关键词在src/node中查找，最后查找到这个commit: 
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/3e8f1c80253839c1b87f7571c30b65efd85b0102 创建了`packages/theme/src/node/check/vuepress.ts`，问题代码在第48行:
``` ts
mainPackages.forEach((pkg) => {
    const { version } = <PackageJSON>require(`${pkg}/package.json`);

    mainPackagesVersions.push(version);
  });
```

**Comment by DreamOfIce** [comment]
稍等

**Comment by DreamOfIce** [comment]
暂时没空研究最小复现demo，以下直接用发生此错误的项目来复现：
1. 克隆 https://github.com/DreamOfIce/core-js.git
2. 将docs/package.json中的vuepress-theme-hope改为`2.0.0-beta.184`版本
3. npm install
4. npm run docs:dev

**Comment by Mister-Hope** [comment]
Add type: module in docs/package.json and try again?

**Comment by Mister-Hope** [comment]
Hi, is the solution worked for you?

**Comment by Mister-Hope** [comment]
Workaround: You can move all docs to a folder like docs or sec, that could solve it.

**Comment by DreamOfIce** [comment]
> Hi, is the solution worked for you?

Sorry I've been a bit busy today, and I've missed it because of the email cramp.
I tried it just now but it didn't work, I'll try again when https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/e8dc4ff853f5645218f1afd03625d8977c07bb3c is released

**Comment by Mister-Hope** [comment]
So the final workaround is not wokring in your case?

**Comment by DreamOfIce** [comment]
I just try to use `beta.185` and add "type": "module" to package.json, and find it doesn't work. I will try to build and install from branch main when I have time

**Comment by Mister-Hope** [comment]
Nope, try comment above

**Comment by DreamOfIce** [comment]
我去试试，不过套娃docs目录实在不太美观（

**Comment by Mister-Hope** [comment]
嗯，你也可以试试我的修复是不是有效，就在createRequire 那里给源文件目录加一个 `/` 后缀，我本地测试是有效的，这会让 node require sourceDir/noop.js，应该就可以require到 vuepress 了。

**Comment by DreamOfIce** [comment]
试了下最新版本(beta.186)，还是不行

**Comment by Mister-Hope** [comment]
错误信息？

**Comment by DreamOfIce** [comment]
还是和以前一样，明天我构建一个没有最小化的版本调试一下

**Comment by DreamOfIce** [comment]
本地调试了一下，完全import不到vuepress
我去看看怎么回事

**Comment by DreamOfIce** [comment]
是我没看清楚，这个修复是有效的
后来报错的变成了`vuepress-reading-time2`
因为packages/shared里面也有一份一样的没改
