### ISSUE TITLE
[Bug]侧边栏会自动将某些字母大写、在某些文本前添加上路径前缀

### ISSUE THREAD

**Issue by bkk1024** [vuepress-theme-hope/vuepress-theme-hope#2856]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

1. <span style="color: red">自动将字母转换为大写</span>

   ![image-20230302235414699](https://bkk1024.github.io/docs/assets/image-20230302235414699-5e50ea7d.png)

   配置如下：

   ![image-20230302235527856](https://bkk1024.github.io/docs/assets/image-20230302235527856-7485f70b.png)

2. <span style="color: red">自动添加路径前缀</span>

   ![image-20230302235646953](https://bkk1024.github.io/docs/assets/image-20230302235646953-6e910b19.png)

   ![image-20230302235753921](https://bkk1024.github.io/docs/assets/image-20230302235753921-84857a34.png)

   配置如下

   ![image-20230302235818950](https://bkk1024.github.io/docs/assets/image-20230302235818950-ab8f2b9f.png)

   ![image-20230302235838983](https://bkk1024.github.io/docs/assets/image-20230302235838983-96d71127.png)

   不知道是不是我配置写得有问题。

**Comment by bkk1024** [comment]
- 配置如下：

  ```js
  import { defineUserConfig } from 'vuepress'
  import { hopeTheme } from "vuepress-theme-hope"
  
  export default defineUserConfig({
    base: '/',
    theme: hopeTheme({
      navbar: [
        {
          text: 'demo',
          link: '/demo/demo1.md',
        },
      ],
      sidebar: {
        '/demo/': [
          {
            text: 'DEMO',
            collapsible: true,
            children: ['demo1', 'demo2', 'demo3',],
          }
        ]
      },
    })
  })
  ```

当`md`文件中有一级标题，不会出现路径前缀问题

```markdown
## demo1.md

# demo1

这个文件有一级标题，因此在侧边栏中展示为 demo1
```

当`md`文件中没有一级标题，则侧边栏会使用`/路径/children名称`开头

```markdown
## demo2.md

## demo2

这个文件没有一级标题，在侧边栏中展示即为 /demo/demo2
```

不知道这算不算bug，也许是我书写文档的习惯有问题。😂

**Comment by Mister-Hope** [comment]
### If there is no title filed in frontmatter, and the page doesnot have a title, then the page has no title.
