### ISSUE TITLE
[Feature Request] 希望search-pro插件能提供结果筛选功能

### ISSUE THREAD

**Issue by gitsheny** [vuepress-theme-hope/vuepress-theme-hope#2862]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

例如给页面的Frontmatter提供某个属性，然后搜索结果列表最上方显示该属性所有值，点击后能筛选出只包含该属性的内容

**Comment by Mister-Hope** [comment]
The other requests may still seem reasonable, as we do have search database principle in other similar tools, but for custom filter or grouper, I do not think this is realistic to build similar feature for searching.
