### ISSUE TITLE
[Feature Request] Is there any option to covert the generated HTML back to .md Format ?

### ISSUE THREAD

**Issue by santhanakrishnanstark** [vuepress-theme-hope/vuepress-theme-hope#2876]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

Hi, I wanted to convert the current html to markdown because I have added some extra content using JavaScript which is I needed to be updated in the markdown file as well. So how should I convert the current HTML to markdown again ?

**Comment by Mister-Hope** [comment]
All markdown content parsing is done at node, the client just receives a vue component generated from markdown, i.e.: VuePress.

You can access markdown content in extendsPage hook.

**Comment by Mister-Hope** [comment]
Also, please post questions in discussion
