### ISSUE TITLE
[Feature Request] 使 vuepress-plugin-search-pro 支持搜索标题中内嵌的 <code>

### ISSUE THREAD

**Issue by Dilant** [vuepress-theme-hope/vuepress-theme-hope#2878]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

目前 `vuepress-plugin-search-pro` 本地搜索插件搜索不到标题中内嵌的 `<code>`，例如：

### 标题中的代码 `def some_function(x: str) -> bool`

```markdown
### 标题中的代码 `def some_function(x: str) -> bool`
```

此时搜索 `some_function` 没有搜索结果。而在一些场合下（例如 API 文档 [页面范例](https://github.com/Dilant/B2METutorial/blob/master/src/advanced/executor.md)），会出现大量这样的用法，因此希望能够支持搜索到标题中内嵌 `<code>` 的内容。

### Additional context

<details>

<summary>系统环境</summary>

- 系统：Windows 11
- Node：`19.7.0`
- pnpm：`7.27.1`
- 依赖：

```json
"devDependencies": {
  "@vuepress/client": "2.0.0-beta.61",
  "@vuepress/plugin-shiki": "2.0.0-beta.61",
  "check-md": "github:Dilant/check-md#master",
  "prettier": "^2.8.4",
  "vue": "^3.2.47",
  "vuepress": "2.0.0-beta.61",
  "vuepress-plugin-search-pro": "2.0.0-beta.189"
}
```

</details>

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/bae520ba723284f7f541050574954f334e3fc3c0
