### ISSUE TITLE
[Bug] search-pro 插件图标在iphone手机上显示异常

### ISSUE THREAD

**Issue by gitsheny** [vuepress-theme-hope/vuepress-theme-hope#2879]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

hope主题启用search-pro插件，在苹果手机上搜索框左边会出现两个搜索图标。目前已知iphone6正常，7、13、14不正常。
![20230307](https://user-images.githubusercontent.com/38645979/223420966-1b3daf3e-275e-4379-968b-e38e0fb39650.jpg)

**Comment by Mister-Hope** [comment]
Should be the same problem with https://github.com/vuepress/vuepress-next/issues/1004

**Comment by gitsheny** [comment]
感谢。明天拿设备看下效果。

**Comment by Mister-Hope** [comment]
Please check https://vuepress-theme-hope.github.io/search-pro/ once the worklow finishes.
