### ISSUE TITLE
[Bug] order between siderbar with catalog page is not match

### ISSUE THREAD

**Issue by xyz3282836** [vuepress-theme-hope/vuepress-theme-hope#2880]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

order between siderbar with catalog page is not match
siderbar conf below
`sidebarSorter:` ["readme", "order", "date-desc", "title", "filename"]`

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/8153727/223460482-95c0241c-d6f6-4b76-a5ba-b1c9f27b90e6.png">

**Comment by Mister-Hope** [comment]
The catalog plugin is a client side component and do not read sidebarSorter.

Also `isdebarSorter` is a property named "Sidebar" Sorter.
