### ISSUE TITLE
[Feature Request] #2879验证成功

### ISSUE THREAD

**Issue by gitsheny** [vuepress-theme-hope/vuepress-theme-hope#2881]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

vuepress-theme-hope#2879 验证成功，建议对search-pro 搜索框添加appearance样式

**Comment by Mister-Hope** [comment]
新版本我不是已经修了么？

**Comment by gitsheny** [comment]
抱歉没注意到发新版了
