### ISSUE TITLE
[Bug] @include多层引用时只能显示第一层

### ISSUE THREAD

**Issue by ebdmn** [vuepress-theme-hope/vuepress-theme-hope#2883]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

在使用@include对文件进行引入时，只能正常显示第一层， 例如  A @include B , B @include C ,在A页面中只显示B的内容， C不分不能正常显示， 在B页面就可以正常显示C页面内容

**Comment by Mister-Hope** [comment]
> - [x] I am following the docs and I am sure I am using the correct configuration.

https://theme-hope.vuejs.press/zh/guide/markdown/include.html#%E9%AB%98%E7%BA%A7%E7%94%A8%E6%B3%95

<img width="595" alt="image" src="https://user-images.githubusercontent.com/33315834/223742040-f05d3331-0ec4-4c0d-b3f0-f4788f05209c.png">
