### ISSUE TITLE
[Feature Request]插件vuepress-plugin-auto-catalog

### ISSUE THREAD

**Issue by wangyongtest** [vuepress-theme-hope/vuepress-theme-hope#2885]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

这个插件在根目录下查找 readme.md文件，如果分类会出现找不到报错，程序退出，是否修复成可配置或者根据配置项查找

**Comment by Mister-Hope** [comment]
https://vuejs.press/guide/i18n.html#site-i18n-config
