### ISSUE TITLE
Beta191 not working 

### ISSUE THREAD

**Issue by frederik-sandfort** [vuepress-theme-hope/vuepress-theme-hope#2886]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

I have a documentation which is using vuepress2 and vuepress-theme-hope for a couple of months now without problem. Since yesterday, when trying to run `vuepress dev` or `vuepress build`, I get the following error: 
`Error: ENOENT: no such file or directory, scandir '<docs_dir>/node_modules/.pnpm/vuepress-theme-hope@2.0.0-beta.191_44bug2q4gvgfsg4b36ccgweufe/node_modules/vuepress-theme-hope/lib/client/modules/encrypt/layouts'`

This was done using pnpm as package manager. I also tried npm:
`Error: ENOENT: no such file or directory, scandir '<docs_dir>/node_modules/vuepress-theme-hope/lib/client/modules/encrypt/layouts'`

I am using following dependencies:
```json
{
    "dependencies": {
        "@vuepress/client": "2.0.0-beta.61",
        "vue": "^3.2.47",
        "vuepress": "2.0.0-beta.61",
        "vuepress-plugin-full-text-search2": "^0.4.0",
        "vuepress-theme-hope": "2.0.0-beta.191"
    }
}
```

Note that I alos tried installing older package versions which worked previously. However, I get the same error.

In addition, I tried to setup a new documentation using the vuepress theme hope tutorial. This results in the same error.

Thanks a lot for your help!

**Comment by Mister-Hope** [comment]
Use beta 190

**Comment by janker0718** [comment]
same problem

**Comment by frederik-sandfort** [comment]
Thanks a lot for fixing, everything works fine now
