### ISSUE TITLE
[Feature Request] can plugin-comment2 be added add to the `page-bottom` by default?

### ISSUE THREAD

**Issue by ronny1020** [vuepress-theme-hope/vuepress-theme-hope#2894]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

Hi, Could I ask if plugin-comment2 can be added to the `page-bottom` by default?

Most users will add the comment input to the  `page-bottom`.

Is it possible to add it to the page button by default like other plugins such as search and so on, so the user won't have to add a  Layout vue file in the repo?

Thanks for your hard work!

**Comment by Mister-Hope** [comment]
Nope, plugin has no ability modifying  layouts
