### ISSUE TITLE
[Bug] 当内容中出现<xxxx>会渲染出错

### ISSUE THREAD

**Issue by ylyhappy-hello** [vuepress-theme-hope/vuepress-theme-hope#2896]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

![image](https://user-images.githubusercontent.com/54216974/224592941-6ed528bd-08af-495a-be91-f0ce8212d1bc.png)

**Comment by Mister-Hope** [comment]
#2477
