### ISSUE TITLE
切换页面时head里的js重复加载

### ISSUE THREAD

**Issue by yanhom1314** [vuepress-theme-hope/vuepress-theme-hope#2898]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [X] Windows
- [X] Linux

### Describe the bug

切换页面时head里的js重复加载

**Comment by Mister-Hope** [comment]
Try not post everything here.

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/vuepress-next/issues/1268

**Comment by jcwangxp** [comment]
@Mister-Hope I met this issue recently also. When run docs:dev it works well, but when run docs:build then start http server, it behaves weird, I debugged and found it's because js is reloaded again and caused the trouble. Hope this issue can be resolved soon.

**Comment by Mister-Hope** [comment]
I already opened https://github.com/vuepress/vuepress-next/pull/1314. The best way to solve it is to review it and leave ideas, or notify meteorlxy to review it

**Comment by Mister-Hope** [comment]
Closing this as this is an upstream bug and we will probably fix this in next RC version
