### ISSUE TITLE
[Bug] `vuepress-plugin-comment2` get '@internal/pagesData' imported error during build

### ISSUE THREAD

**Issue by ronny1020** [vuepress-theme-hope/vuepress-theme-hope#2899]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-plugin-comment2

### Which operating system are you using?

- [X] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

building got the following error with `vuepress-plugin-comment2": "2.0.0-beta.193` and`"vuepress": "2.0.0-beta.61"`. BTW, running dev works properly. 

I use npm in both windows and mac os, and it also happens on the GitHub action.

```bash
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@internal/pagesData' imported from .......\node_modules\@vuepress\client\dist\chunk-X6BS2PXP.js
    at new NodeError (node:internal/errors:399:5)
    at packageResolve (node:internal/modules/esm/resolve:889:9)
    at moduleResolve (node:internal/modules/esm/resolve:938:20)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)
```

### Additional context

BTW, if I remove the `provider` key in comment2, even though there would be a type error and the comment wouldn't be rendered. It can be built without this error.

I also use `vuepress-plugin-sitemap2: "2.0.0-beta.191`, which works properly.

I think it's related to https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/2326. Since the package is different and the issue is closed, I open a new one. Besides, The `addViteSsrNoExternal ` mentioned in the issue doesn't work for me.

**Comment by Mister-Hope** [comment]
If you want further discusson, provide a minimal reproduction first.

**Comment by ronny1020** [comment]
Thank you for your reply, here is the link https://stackblitz.com/edit/vuepress-theme-hope-kkvkex?file=docs/.vuepress/config.ts

Please run the `docs:build` and there is the same error.

**Comment by Mister-Hope** [comment]
# ?

<img width="296" alt="image" src="https://user-images.githubusercontent.com/33315834/224750775-b4b5d6b6-728d-4c8a-ba0f-47dcd109506d.png">

Could you try not to waste others time?

I did not see any issue here: https://stackblitz.com/edit/vuepress-theme-hope-jnenba?file=README.md

**Comment by ronny1020** [comment]
I'm sorry for your time. Please calm down, I think it does have a bug if it is installed with other plugins. Isn't the ` vuepress-them-hope` a collection of all of them?  

It also happens if I install them one by one. here is the link.
https://stackblitz.com/edit/vuepress-theme-hope-hajzbt?file=docs%2F.vuepress%2Fconfig.ts

**Comment by Mister-Hope** [comment]
Track https://github.com/vuepress/vuepress-next/issues/1283

**Comment by ronny1020** [comment]
Forget it. DON'T BOTHER. I'll just migrate to vitepress. Please don't waste your time.
