### ISSUE TITLE
网站文章的seo中摘要能否自动截取正文前xx字？[Feature Request]

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#2905]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

网站文章的seo中摘要能否自动截取正文前xx字？

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/48122016/225280974-bd2e767f-9490-4e9d-b5ca-b54091335019.png">

**Comment by Mister-Hope** [comment]
你可以自己实现这个功能，应该很简单，但断在哪能不能读通顺就不好说了。
