### ISSUE TITLE
[Feature Request] Don’t publish when demo deploy failed 

### ISSUE THREAD

**Issue by DreamOfIce** [vuepress-theme-hope/vuepress-theme-hope#2914]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

目前经常遇到某个新版本完全无法使用，能不能让CI在发布前先测试一下，或者把那些demo和文档的部署作为测试？
后者的话可以通过将`publish.yml`的触发条件改为依赖`release.yml`实现：https://docs.github.com/zh/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow
没问题的话我愿意去写个pr

**Comment by Mister-Hope** [comment]
> 目前经常遇到某个新版本完全无法使用

比如？

**Comment by DreamOfIce** [comment]
> > 目前经常遇到某个新版本完全无法使用
> 
> 比如？

https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/2874
https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/2847
https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/2886

**Comment by DreamOfIce** [comment]
@Mister-Hope ？不同意的话我就先关掉issue了

**Comment by Mister-Hope** [comment]
你提pr吧，我是觉得没必要，至少你举的例子里有一个就不影响ci

**Comment by Mister-Hope** [comment]
Any update?

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/928c1ded9dfc421c85504332e627d5a9a36c5ee9
