### ISSUE TITLE
[Bug] Failed to resolve component: Share

### ISSUE THREAD

**Issue by sakuhanachan** [vuepress-theme-hope/vuepress-theme-hope#2946]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Share component's icon not appear when I use tag ``<Share />`` in page and this error appear in both dev mode and when rendering page in build mode.

Build mode

```
[Vue warn]: Failed to resolve component: Share
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Component <Anonymous> is missing template or render function.
```

Dev mode

![image](https://user-images.githubusercontent.com/2475440/227122509-c444df56-03f4-4987-b888-cae01f468d84.png)

**Comment by Mister-Hope** [comment]
Enable any component before using it
