### ISSUE TITLE
[Bug]fontIcon的设置与iconAssets的设置

### ISSUE THREAD

**Issue by lyszxm** [vuepress-theme-hope/vuepress-theme-hope#2959]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

![image](https://user-images.githubusercontent.com/68858180/228116832-a184b092-73dd-457d-b470-5eb76d4da7b5.png)

- 这里的iconAssets不设置也是可以的

![image](https://user-images.githubusercontent.com/68858180/228116935-4d498d57-ac13-4c8b-b5a5-8a2ee12300fa.png)
这个是必须设置assets不然css类型相关的文件并不会被下载下来，

- 请问这两个有什么区别嘛，文档只是说啥都设置在第一张图的iconAssets中即可，🎃

**Comment by Mister-Hope** [comment]
主题选项中的 iconAssets和iconPrefix会直接传递给插件组件选项fonticon中的assets和prefix，所以你有什么问题？

**Comment by lyszxm** [comment]
对了，忘说了，mr。hope的小程序牛逼class😁
