### ISSUE TITLE
[Bug] Redirect plugin doesn't work with slideshow

### ISSUE THREAD

**Issue by TeddyHuang-00** [vuepress-theme-hope/vuepress-theme-hope#2963]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

vuepress-plugin-redirect

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

When using the slideshow feature provided by `vuepress-plugin-md-enhance` (see [this link for example](https://teddyhuang-00.github.io/zh/slides/JC/artifical-agents-tracking-odour-plumes.html)), and click the home button on the bottom left menu, it will route to a strange 'base' page without proper redirecting (Though I double-checked the index.html from build files and further verified that it works as expected even with a simple refresh).

_It brings me to:_
<img width="1517" alt="image" src="https://user-images.githubusercontent.com/64199650/228471957-1af82f96-e5a8-4ebb-a8e0-eeef2b711331.png">

_Refreshing the page or entering site as normal_
<img width="1517" alt="image" src="https://user-images.githubusercontent.com/64199650/228473439-79b2be42-fc11-4dd0-a271-144373d7f3d2.png">

### Additional context

The configuration for redirectPlugin:

```ts
redirectPlugin({
  autoLocale: true,
  localeConfig: {
    "/zh/": ["zh-CN", "zh-TW", "zh"],
    "/en/": ["en-US", "en-UK", "en"],
  },
}),
```

And this bug is stably reproducible at least on safari, firefox and edge browsers.

**Comment by Mister-Hope** [comment]
Nice catch, I will look into it when I have time.

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/f08e98c64d98efb35a3297b263a0d1f5674ec0d6
