### ISSUE TITLE
[Feature Request] Is it possible to design an API for updating tags that can be used by other plugins?

### ISSUE THREAD

**Issue by DreamOfIce** [vuepress-theme-hope/vuepress-theme-hope#2965]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

如题，我正在写一个Vuepress插件。其中一个feature是动态地向页面添加tag，但这必须在onInitialized之后才能实现（因为使用到了`app.pages`）。
但是vuepress-plugin-blog2会在`extendsPages`时向routemeta注入相关内容，并在`onInitialized`以及文件改变时重新生成tag页。

所以，当前有什么办法实现这个功能吗？或者未来有计划支持此类功能吗？

### Additional context

附插件链接（目前不包含tag相关实现）：
https://github.com/DreamOfIce/vuepress-plugin-i18n

**Comment by Mister-Hope** [comment]
也许尽可能推迟注入时间更合理一点，会在下个版本进行改进
