### ISSUE TITLE
[Bug] Bilibili Plugin Sometimes Will Not Mute

### ISSUE THREAD

**Issue by Masterain98** [vuepress-theme-hope/vuepress-theme-hope#2967]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I am following the docs and I am sure I am using the correct configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/)

### Package name

BiliBili

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

This happens on both [my site](https://hut.ao/zh/features/game-launcher.html) and [official demo site](https://plugin-components.vuejs.press/zh/guide/bilibili.html#%E6%A1%88%E4%BE%8B). 
By default, the video should be muted.
![image](https://user-images.githubusercontent.com/10614984/228706930-0eec4cc2-6952-42d3-a9d1-03079904e5aa.png)
But sometimes, after visiting multiple pages with videos, the fact becomes 
- Player shows unmuted but actually muted
- Not muted at all

This scares readers and causes distraction from the document. If possible, can we add options of 
- disable auto-play
- force mute audio

**Comment by Mister-Hope** [comment]
https://www.bilibili.com/blackboard/webplayer_history.html#flash

BIlibili realease a new major version of player these days. Contact here if you have any questions.

**Comment by Mister-Hope** [comment]
Now we support bilibili html v5 player well
