### ISSUE TITLE
[Bug]After Change the default local to zh the init time is solong

### ISSUE THREAD

**Issue by terwer** [vuepress-theme-hope/vuepress-theme-hope#2989]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

When I start to use hope theme, I change the default local to zh, but init time is solong

log like this

```
- Cleaning cache
✔ Cleaning cache - done in 7ms
- Initializing and preparing data
```

But when I use the default en local, it starts very quickly

My `config.ts`

```ts
import { defineUserConfig } from "vuepress"
import theme from "./theme.js"

export default defineUserConfig({
    base: "/",

    dest: "dist/packages/zhi-blog-vuepress",

    locales: {
        "/": {
            lang: "zh-CN",
            title: "浅海拾贝",
            description: "寻找未知的技术拼图",
        },
        "/en": {
            lang: "en-US",
            title: "Seek gold",
            description: "Find new piece of tech",
        },
    },

    theme,

    // Enable it with pwa
    // shouldPrefetch: false,
})
```

navbar/zh.ts

```ts
export const zhNavbar = navbar([
  "/",
  {
    text: "文章",
    icon: "edit",
    link: "/post/",
  },
  {
    text: "关于",
    icon: "discover",
    link: "/about/",
  },
  {
    text: "留言",
    icon: "note",
    link: "/guestbook/",
  },
])
```

navbar/en.ts
```ts
import { navbar } from "vuepress-theme-hope"

export const enNavbar = navbar([
  "/en",
  {
    text: "Posts",
    icon: "edit",
    link: "/en/post/",
  },
  {
    text: "About",
    icon: "discover",
    link: "/en/about/",
  },
  {
    text: "Guestbook",
    icon: "note",
    link: "/en/guestbook/",
  },
])

```

File structure

![image](https://user-images.githubusercontent.com/3259282/229731334-94af4382-c9f7-4184-9df0-934e4590076e.png)

**Comment by Mister-Hope** [comment]
Only a few lines of script is different when changing locale, do SOMETHING to proof what you are reporting.

Your feeling seems to be related with temp and cache files, as they could be reusable after running the first time.

**Comment by terwer** [comment]
I delete post and reconfig， it starts quickly.If i faced this issue later, i will back.
Thank you for prodividing such execullent theme.

**Comment by Mister-Hope** [comment]
Each page will increase startup time, as they will be converted into Page object and transformed to a Vue Component, and the more content a page has, the longer time and bigger size of memory are taken.
