### ISSUE TITLE
[Bug] Redirect plugin fail at build

### ISSUE THREAD

**Issue by TeddyHuang-00** [vuepress-theme-hope/vuepress-theme-hope#2993]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-plugin-redirect

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

The bug mentioned in #2963 seemed not to be fixed with the latest build (beta201), and encountered serious fallback.

The dev preview of the site works fine, as well as other pages (e.g. intro page still behave correctly). But the build version of `index.html` doesn't. This not only involves the main page, but also affects many other index pages (e.g. `category/index.html`, `tag/index.html`, `timeline/index.html`. These all appear to be theme-related index pages)

<img width="1836" alt="图片" src="https://user-images.githubusercontent.com/64199650/230368138-d763dfed-d991-4618-bc43-c1520acc3ed7.png">

⬆️An example from https://teddyhuang-00.github.io/

**Comment by TeddyHuang-00** [comment]
FYI, this seems to be related to the aforementioned issue and corresponding fix commit. Only index files that don't exist in the first place will get into such problems, while index.html generated from README.md will not have such issue. Sorry that's all I can help. Please fix this ASAP.

**Comment by TeddyHuang-00** [comment]
Forgot to mention: I did a temp fix to this problem last night by simply replacing all these failing index.html with ones that could properly redirect the page (see https://github.com/TeddyHuang-00/teddyhuang-00.github.io/commit/e4ed00c4f5c0ecac79895a28494ebe0b6084e8fc), so the site now should look normal. Here is an example of the files that are being replaced:

https://pastebin.com/TnRTGi4L

**Comment by Mister-Hope** [comment]
I still want a valid repro. I am not finding any issues on my code.

**Comment by TeddyHuang-00** [comment]
Sure, I will get one sometime later today

**Comment by TeddyHuang-00** [comment]
Hi @Mister-Hope , you can check out this repo for a stable reproduction (at least on my side): https://github.com/TeddyHuang-00/vp-plugin-redirect-bug . The steps to reproduction of the bug is listed in the README.

The deployed pages can be accessed through https://teddyhuang-00.github.io/vp-plugin-redirect-bug/ , compare this with https://teddyhuang-00.github.io/vp-plugin-redirect-bug/zh/ .

**Comment by TeddyHuang-00** [comment]
BTW, as I was playing around the deployed test site, I accidentally found out that the way redirect plugin works (parse `window.location` into `origin` and `pathname`, then appending language configuration to `origin`) doesn't work for sites that are being deployed to a sub-directory of the root (e.g. https://teddyhuang-00.github.io/vp-plugin-redirect-bug/intro is being redirected to https://teddyhuang-00.github.io/zh/vp-plugin-redirect-bug/intro instead of https://teddyhuang-00.github.io/vp-plugin-redirect-bug/zh/intro). I think this is somehow related and may be fixed by utilizing the `base` option in configuration?

**Comment by Mister-Hope** [comment]
Yeah, that's something I forgot

**Comment by Mister-Hope** [comment]
> Hi @Mister-Hope , you can check out this repo for a stable reproduction (at least on my side): https://github.com/TeddyHuang-00/vp-plugin-redirect-bug . The steps to reproduction of the bug is listed in the README.
> 
> The deployed pages can be accessed through https://teddyhuang-00.github.io/vp-plugin-redirect-bug/ , compare this with https://teddyhuang-00.github.io/vp-plugin-redirect-bug/zh/ .

I think this is a bug related to autocatalog plugin, as the pages which supposed to be handled by redirect plugin are generated with catalog page by plugin-auto-catalog already.

**Comment by Mister-Hope** [comment]
I believe https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/dee352639797d1aa21a96877c1583edb15aa265d fix the homepage issue about redirection.

**Comment by TeddyHuang-00** [comment]
That makes sense. Thank for your dedication. I will test this out in the next release.

**Comment by Mister-Hope** [comment]
Nope, I did not finish fixing it yet, some similar issues is there in blog plugin, as I totally forgot, even the user did not set root locale, there is still a `/404.html` page under locale `/`. That page should be manually excluded.

**Comment by Mister-Hope** [comment]
Also, there is a base issue you reported above, as you are posting them in same issue, wait for me to fix them one by one.

**Comment by TeddyHuang-00** [comment]
Oh I see. Please take your time. I will try to separate issues for clarity and better tracking next time. Should there be anything I can help, please let me know.

**Comment by Mister-Hope** [comment]
Blog related issue is fixed in https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/e3cbf0f0960cb108b8fb6367df55014a40386b26

**Comment by Mister-Hope** [comment]
Base issues should be fixed in https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/92dfdda467bea2ee3e2020194c4b4a3b84613f49
