### ISSUE TITLE
[Feature Request]希望可以在主题中增加图片查看丝滑般的

### ISSUE THREAD

**Issue by imnxg** [vuepress-theme-hope/vuepress-theme-hope#2994]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

在阅读文章时，点击图片查看
可以放大缩小，浏览
滚动鼠标滑轮时，自动收缩，与阅读下面的内容无缝衔接，并且图片衔接过程是丝滑般的动感。

这也是图片预览的另一种效果，去除了点击预览文章图片，不想看时，滚动滑轮看文章接下来的内容

### Additional context

图片查看效果：
[https://medium-zoom.francoischalifour.com/](https://medium-zoom.francoischalifour.com/)

参考GitHub仓库：[https://github.com/francoischalifour/medium-zoom](https://github.com/francoischalifour/medium-zoom)

**Comment by Mister-Hope** [comment]
Closed https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/6951c27ddf879c77f394cfffcbdab4f7ef7e5bd4

**Comment by Mister-Hope** [comment]
Added  as  scrollToClose option in https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/a792e5e288b6f8c76d7440f6329bbacc6ba8719a
