### ISSUE TITLE
主页icon 显示问题[Bug]

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#2995]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/48122016/230582195-1870b09b-b829-47f4-8d49-426515d7b472.png">

最新版本不能正常显示，可以参考：https://bornforthis.cn/

**Comment by Mister-Hope** [comment]
![Screenshot_2023-04-07-17-36-25-44_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/33315834/230585490-a35548b2-e446-4330-9621-441aba1f5d44.jpg)

？

**Comment by AndersonHJB** [comment]
有可能我描述问题，你看看这个图片：
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/48122016/230585913-0c3b7d65-5958-4535-a6c8-04d2cb512875.png">

**Comment by Mister-Hope** [comment]
![Screenshot_2023-04-07-17-39-23-97_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/33315834/230585995-7cb59351-766c-4958-84cd-798b00dbe090.jpg)

**Comment by AndersonHJB** [comment]
估计是谷歌浏览器的问题吧
