### ISSUE TITLE
[Feature Request]能不能整合markmap思维导图

### ISSUE THREAD

**Issue by jdysya** [vuepress-theme-hope/vuepress-theme-hope#3004]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

这个[`markmap`](https://markmap.js.org/)感觉功能更加全面，比`mermaid`里的思维导图支持更多的特性，例如`markmap`支持代码块，超链接，数学公式，通过简单的缩进就能快速生成对应的导图，目前文档中提出的方案是将`markmap`导图内容导出为`html`，然后再通过`iframe`标签引入，这种方式不利于我们对导图内容的管理，例如后期需要向脑图中添加内容，就得重新生成html，重新覆盖到已有文件对应的路径,个人认为应该像`幻灯片组件那种方式`，因为这个`markmap`中的代码块可能会和```这种语法冲突

### Additional context

<img width="907" alt="image" src="https://user-images.githubusercontent.com/73117213/230714069-94cb10ab-922f-4438-961f-17e8578aa098.png">

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/73117213/230714014-9e4c9406-6a5c-4f88-9753-ab89bafcb9e0.png">

**Comment by Mister-Hope** [comment]
Yes, it's possible, I will look into this later.

**Comment by 1912377458** [comment]
> Yes, it's possible, I will look into this later.

补充一下，还可以增加一个类似于现在文档中这种侧边栏目录的功能组件，因为`markmap`可以根据markdown内容生成脑图，也就意味着也可以起到目录导航的作用，即提供一个选项，用户点击可以根据当前文档内容生成脑图，或者是提供一个组件，类似`<AutoCatalog base='/note/' />`这种，在指定位置可以自动生成脑图

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/73117213/230755541-54bcc3ab-4865-4791-a7db-be77ba468038.png">

**Comment by Mister-Hope** [comment]
The markmap runtime is too heavy, and you may implement it as a standalone plugin.

**Comment by Mister-Hope** [comment]
Markmap will be supported in next version.
