### ISSUE TITLE
[Feature Request] deeper catalog level & squeeze auto-catalog path

### ISSUE THREAD

**Issue by liblaf** [vuepress-theme-hope/vuepress-theme-hope#3005]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

I set the `permalinkPattern` to something like `/xxx/:year/:month/:day/:slug`. So when I visit the generated catalog page `/xxx/`, I only see the items with the month and date, but no title. It would be much better if the auto-catalog plugin could go deeper and squeeze path to list items with title.

Here is an [example](https://blog.liblaf.me/demo/) of current catalog.

**Comment by Mister-Hope** [comment]
A three level depth catalog is already complicated enough, provide a living demo for a 4 depth catalog. I will accept that if the appearance LGTM

**Comment by liblaf** [comment]
Sorry, there may be some problems with my expression. A nested 4-depth catalog is indeed complicated. The solution I was wishing for is an optional flattened 4-depth catalog, like [this](https://blog.liblaf.me/demo/2023/04/08/catalog/) (which I created manually).

**Comment by Mister-Hope** [comment]
This is definitely not a common feature, you may implement it by yourself.

**Comment by liblaf** [comment]
I see. Sorry for your trouble.

**Comment by Mister-Hope** [comment]
You may set `/xxx/:year-:month-:day/:slug`
