### ISSUE TITLE
[Feature Request] iconify 图标样式问题

### ISSUE THREAD

**Issue by alomerry** [vuepress-theme-hope/vuepress-theme-hope#3006]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

- 使用 iconify ![image](https://user-images.githubusercontent.com/34118544/230718197-9114964f-f05c-427c-a145-5358cba1ac24.png)
- 使用 iconfont ![image](https://user-images.githubusercontent.com/34118544/230718233-b7a834d5-1871-49f7-8817-1e91da59b93a.png)

使用 iconify 图标时图标和文字不在同一水平线

### Additional context

vuepress-theme-hope 版本 2.0.0-beta.201

**Comment by Mister-Hope** [comment]
你最好提供一个 reproduction，并确认它不是图标周围边距造成的。

**Comment by alomerry** [comment]
> 你最好提供一个 reproduction，并确认它不是图标周围边距造成的。

@Mister-Hope 使用 `pnpm create vuepress-theme-hope [dir]` 安装完成后修改 iconAssets 为 iconify，并在 navbar 中添加一个 iconify 的图标（`{ text: "Space", icon: "cib:spacemacs", link: "/demo/" },`）

```ts
import { navbar } from "vuepress-theme-hope";

export const enNavbar = navbar([
  "/",
  { text: "Demo", icon: "discover", link: "/demo/" },
  { text: "Space", icon: "cib:spacemacs", link: "/demo/" },
 ...
]);

```

**Comment by Mister-Hope** [comment]
好的我看看
