### ISSUE TITLE
[Feature Request] Add Card support

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress-theme-hope/vuepress-theme-hope#3012]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

Add `@card` support.

Maybe something like

````md

@cardstart

```yml
title: xxx
description: xxx
image: xxx
```

@cardend
````

Or

````md
::: card

```yml
title: xxx
description: xxx
image: xxx
```

:::
````

**Comment by alomerry** [comment]
之前用 [vuepress-theme-gungnir](https://github.com/Renovamen/vuepress-theme-gungnir) 的时候有类似的功能，也许可以作参考 [commits](https://github.com/Renovamen/vuepress-theme-gungnir/pull/38/commits)。

**Comment by Mister-Hope** [comment]
d06e46b1e296b9a1c4465ff009bd38884fd9e3cc
