### ISSUE TITLE
[Feature Request] md-enhance 插件可以支持导入远程文件吗

### ISSUE THREAD

**Issue by alomerry** [vuepress-theme-hope/vuepress-theme-hope#3014]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

例如我想导入 `https://github.com/golang/go/blob/master/README.md` 这个文件或者是 `https://github.com/golang/go/blob/master/src/time/time.go` 中的代码，通过 [导入文件](https://plugin-md-enhance.vuejs.press/zh/guide/include.html) 好像做不到。

**Comment by Mister-Hope** [comment]
不可以，渲染 Markdown 是一个同步操作。
