### ISSUE TITLE
[Bug] markdown列表自带的换行没有了

### ISSUE THREAD

**Issue by Soulballad** [vuepress-theme-hope/vuepress-theme-hope#3016]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

![image](https://user-images.githubusercontent.com/19262272/231386323-d54ffe7a-5b61-47f3-b187-aca939b98249.png)
![image](https://user-images.githubusercontent.com/19262272/231386424-b8a946a8-c229-4bfc-b20a-014b93b7080c.png)
![image](https://user-images.githubusercontent.com/19262272/231386598-87ad0776-e67e-43ce-83db-6c4364f9f132.png)

如图所示，有序列表和无序列表后面的内容，在VSCode和Typora中显示时，都自带有换行，显示效果很好；
在Vuepress中显示时，自动合并到了一行，显示有点混乱。
如果要想显示和效果和Typora一致，需要怎么处理

**Comment by Soulballad** [comment]
1. 服务提供者
    服务提供者要向EurekaServer注册服务，并且完成服务续约等工作。
    - 服务注册
    服务提供者在启动时，会检测配置属性中的eureka.client.register-with-erueka，若它为ture，代表将自己的信息注册到EurekaServer。
    则会向EurekaServer 发起一个Rest请求， 并携带自己的元数据信息， Eureka Server会把这些信息保存到一个双层Map结构中。第一层Map的Key就是服务名称，第二层Map的key是服务的实例id
    - 服务续约(心跳机制)
    在注册服务完成以后，服务提供者会维持一个心跳（定时向EurekaServer发起Rest 请求）， 告诉EurekaServer ： “ 我还活着” 。这个我们称为服务的续约（renew），client 心跳线程http调用server的renew，增加心跳次数，修改注册表中对应InstanceInfo的最近心跳时间
2. 服务消费者

**Comment by Mister-Hope** [comment]
add break: true to markdownOptions, this is not the behavior of common mark
