### ISSUE TITLE
[Bug]  目录和菜单同级出现的问题

### ISSUE THREAD

**Issue by zuihou** [vuepress-theme-hope/vuepress-theme-hope#3019]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

![image](https://user-images.githubusercontent.com/8500410/231958246-4cbf4825-9e11-4c49-a71f-375dfc37fed7.png)

目录和菜单同级出现时，
1. 左侧缩进不一样
padding-inline-start 的设值不一致，导致缩进不一样
   
<img width="2236" alt="image" src="https://user-images.githubusercontent.com/8500410/231958865-0a12d6c9-50ac-4949-8e40-b92814c5c5ef.png">

<img width="2172" alt="image" src="https://user-images.githubusercontent.com/8500410/231958706-3b358b49-7e8f-42f1-a363-c88f34fb6380.png">

2. 字体大小不一样
菜单： 上图中的”注册“ 字体是1em
.sidebar-link { font-size: 1em; }
目录：上图中的 ”开发运营系统“字体是 1.1em
.sidebar-heading { font-size: 1.1 em; }

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/231960379-69e7364f-f4cd-4a65-8949-a28347b2bc62.png)
 So why am I getting constant result? See https://theme-hope.vuejs.press/faq/

Give me a reproduction first.

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/231961603-6e6faf08-6853-4635-9eca-45aa0d2aa6d1.png)

If you are talking about this, then this is expected to highlight togglable buttons, if you dislike this, provide a sidebar component by yourself.

VitePress and VuePress default theme has these kind of issues too.

**Comment by Mister-Hope** [comment]
Some feedback here:

## Why isn't that aligned

The normal link should indent 1.5em (1em is a bit small for links), while the heading decides how much a nesting level will indent, in our case, it should be small to avoid nesting take too much space and leave the title being wrapped. Most language heading (including English) is longer then Chinese ones, so we need to ensure that there is enough space for title text at sidebar. So both VuePress default theme and my theme use 1.5em to indent links, and 0.5em to indent nesting. As long as you are not mixing those levels, the appearance will look good.

If you do think that you need some customization, you can unify them to 1em.

**Comment by zuihou** [comment]
ok， i 自己改样式解决。

**Comment by Mister-Hope** [comment]
This is updated  result as your expected:

![image](https://user-images.githubusercontent.com/33315834/231966130-54b24ff5-c874-441c-9093-eed1cb98c300.png)

This is the original one:
![image](https://user-images.githubusercontent.com/33315834/231966305-9272f7c6-dfa4-4377-90ff-6b0e754703e9.png)

You can see that 1em indent for links does not look good (the beginning), while if we remain 1.5rem indent, then a 2 level nesting already indent too much space:

![image](https://user-images.githubusercontent.com/33315834/231966700-6f26a300-5039-40e1-8254-96e6587d3491.png)

**Comment by Mister-Hope** [comment]
Anyway thanks for your feedback, I tried 1.25rem and maybe it's better than original one.

**Comment by zuihou** [comment]
> Anyway thanks for your feedback, I tried 1.25rem and maybe it's better than original one.
> 
> ![image](https://user-images.githubusercontent.com/33315834/231967601-0504ab09-7836-4e07-ba8a-11f52956dfc0.png)

这个看起来是要好点
