### ISSUE TITLE
[Feature Request] Support reading progress

### ISSUE THREAD

**Issue by FuckDoctors** [vuepress-theme-hope/vuepress-theme-hope#3021]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

For example, Adding the reading progress over the `backToTop` button.

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/79d682d1ac5028689dfb37669e170c0c1d9113a5
