### ISSUE TITLE
是否考虑增加文档的版本，因为我的文档是一个长期迭代的内容

### ISSUE THREAD

**Issue by azrng** [vuepress-theme-hope/vuepress-theme-hope#3023]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

例如该功能：https://docusaurus.io/zh-CN/docs/versioning 谢谢

**Comment by Mister-Hope** [comment]
Wrong place, post at https://github.com/vuepress/vuepress-next. Honestly speaking, I don't think we will support features like this.

You can just use git to get docs with specific major version or tags, and deploy them in a "Version Based" subdirectory.
