### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by izhaorui** [vuepress-theme-hope/vuepress-theme-hope#3034]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

![image](https://user-images.githubusercontent.com/16451400/232505348-ca3733f3-6475-488c-9caa-bc7dced0b09c.png)

![image](https://user-images.githubusercontent.com/16451400/232505536-0598e62d-0fe4-41c2-a791-c394acda29e5.png)

选择的是简体中文的为什么生成的还是英文的

**Comment by alomerry** [comment]
这个是终端显示语言，和项目的语言没关系

**Comment by Mister-Hope** [comment]
我们默认生成的是一个双语 demo，你可以在导航栏切换到中文。
