### ISSUE TITLE
[Feature Request] Mermaid plugin support in slide.

### ISSUE THREAD

**Issue by AkagiYui** [vuepress-theme-hope/vuepress-theme-hope#3043]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

I noticed that there is a revealjs plugin make slide support mermaid.
https://github.com/zjffun/reveal.js-mermaid-plugin
Is it possible to add this plugin to `hope`?

**Comment by Mister-Hope** [comment]
NO, the whole markdown content is just handed by markdown plugin, and we do not actually passing any html elements to reveal.

**Comment by Mister-Hope** [comment]
Closing as we can not support this without dirty hak.

**Comment by Mister-Hope** [comment]
Update: With the new `defineRevealJsConfig` option, you are now able to use any plugin you like with reveal.js,
 so if your markdown contain this, it probably works:

```html
      <div class="mermaid">
        <pre>
          %%{init: {'theme': 'dark', 'themeVariables': { 'darkMode': true }}}%%
          flowchart TD
            A[Start] --> B{Is it?};
            B -- Yes --> C[OK];
            C --> D[Rethink];
            D --> B;
            B -- No ----> E[End];
        </pre>
      </div>
```

Note, the markdown code block may and may not work (depends on the plugin you reference). It's not a problem with the wrapper introduced in `vuepress-plugin-md-enhance`.
