### ISSUE TITLE
[Bug] 当文件夹内的 README.md 中设置 index: false 时，autocatalog 无法为该目录索引

### ISSUE THREAD

**Issue by northword** [vuepress-theme-hope/vuepress-theme-hope#3047]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

文档 https://theme-hope.vuejs.press/zh/config/frontmatter/layout.html#index 中提到，在某个文件的 frontmatter 中设置 `index: false` 可以在侧边栏中隐藏此页面。

目录结构
```
README.md
foo.md
quick-start/
    README.md
    install.md
    bar.md
```

README.md

```md
---
title: 手册
---

# 手册

<AutoCatalog />
```

quick-start/README.md

```md
---
title: 快速开始
order: 1
index: false
---
```

在 `quick-start/README.md `中设置 `index:false` 本意仅是想让侧边栏不显示 quick-start/README.md ，然而 README.md 中的 `<AutoCatalog />` 将 `quick-start/` 目录整个隐藏。

在我看来，应该仅是设置 `dir.index: false` 时，才是整个目录隐藏。仅设置 `index: false` 而没有设置 `dir.index：false` 时，仅在侧边栏隐藏，autolog 插件仍然索引该文件所在目录。

如果我有没有正确理解和使用目前设计逻辑的话还请指出，谢谢！

### Additional context

最小复现仓库：https://github.com/northword/vuepress-hope-autolog-minirepod/tree/main/src/user-guide/quick-start

最小复现仓库的dist：https://northword.github.io/vuepress-hope-autolog-minirepod/user-guide/

**Comment by Mister-Hope** [comment]
你理解的没问题，但是目录的父级标题依赖于你取消索引的这个页面，我回头看看这里的逻辑。

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/f16d644144a400bd40008576c2dddfe9e09dcd80
