### ISSUE TITLE
[Bug] siderbar 配置中如果使用 `collapsible: true` 字体设置会丢失

### ISSUE THREAD

**Issue by alomerry** [vuepress-theme-hope/vuepress-theme-hope#3058]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

[自定义字体](https://github.com/alomerry/blog/blob/5ef9b051c8/src/.vuepress/styles/palette.scss#L3)后，[在 siderbar 中设置 `collapsible: true`](https://github.com/alomerry/blog/blob/5ef9b051c8/src/.vuepress/configs/siderbar/digest.ts#L35) 会丢失自定义的字体： 

<img width="730" alt="image" src="https://user-images.githubusercontent.com/34118544/233794244-1ecd143d-948f-43f0-944c-4ff262303f33.png">

<img width="213" alt="image" src="https://user-images.githubusercontent.com/34118544/233794331-7581efd3-8f1f-4878-ba82-c3201fb221e1.png">

<img width="252" alt="image" src="https://user-images.githubusercontent.com/34118544/233794340-be58b468-7126-4fba-9898-778664020b80.png">

### Additional context

字体做过[切割](https://github.com/alomerry/blog/blob/5ef9b051c8/src/.vuepress/public/assets/fonts/lxgw-wenkai-gb-regular/result.css)，不清楚是否有影响。

**Comment by Mister-Hope** [comment]
可能是套了个button导致的？
