### ISSUE TITLE
[Feature Request] 首页图标会跳的动画在205版本取消了吗？

### ISSUE THREAD

**Issue by WangJincheng4869** [vuepress-theme-hope/vuepress-theme-hope#3066]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

首页图标会跳的动画在205版本取消了吗？

**Comment by Mister-Hope** [comment]
https://theme-hope.vuejs.press/zh/guide/advanced/presets.html#%E6%A0%B7%E5%BC%8F%E7%9B%B8%E5%85%B3

**Comment by WangJincheng4869** [comment]
> https://theme-hope.vuejs.press/zh/guide/advanced/presets.html#%E6%A0%B7%E5%BC%8F%E7%9B%B8%E5%85%B3

那个，文档写错了应该是scss

```
import "vuepress-theme-hope/presets/bounce-icon.scss"
import "vuepress-theme-hope/presets/shinning-feature-panel.scss"
```

![image](https://user-images.githubusercontent.com/41162158/233974481-bb186238-f7e4-4a84-aca6-afa1163d1f76.png)
