### ISSUE TITLE
icon渲染问题[Bug]

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#3068]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

在群里其实已经描述过了，测试很多遍了。现在再截图操作。

各个浏览器也测试过，不是谷歌浏览器的问题。

# 1. 访问主页显示正常「极少情况下，也不能显示」

主页链接：[https://bornforthis.cn/](https://bornforthis.cn/)

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/48122016/233913018-b421faba-ab86-4b29-95f8-de8d1e37b938.png">

# 2. 子页面无法显示

<img width="2304" alt="image" src="https://user-images.githubusercontent.com/48122016/233913897-2f3b5da1-8195-40ca-8512-4aea78d060ee.png">

<img width="2304" alt="image" src="https://user-images.githubusercontent.com/48122016/233914154-77f66042-2490-4cfb-b684-9a34ba156cc1.png">

<img width="2304" alt="image" src="https://user-images.githubusercontent.com/48122016/233914183-fed013d0-179e-4041-9bc0-d12f8fe17a29.png">

- [https://bornforthis.cn/column/py/basequestion/](https://bornforthis.cn/column/py/basequestion/)
- [https://bornforthis.cn/column/python60/10.html](https://bornforthis.cn/column/python60/10.html)

## 输入密码之前

<img width="2304" alt="image" src="https://user-images.githubusercontent.com/48122016/233914305-91f32439-c68a-4ece-a6c5-7085e924ad8a.png">

## 输入密码之后
<img width="2304" alt="image" src="https://user-images.githubusercontent.com/48122016/233914405-e923c3cd-677f-4671-879f-8872bafe1366.png">

# 上面演示了部署后的，我等待结果，不然我还是先回去退到 203版本。现在方便您研究。

# 为了证明不是网络问题，使用本地 css 也有这些问题

本地总不能是网络问题吧「这里的本地不仅仅是 dev 运行，icon 的我也使用本地。并且 本地 icon 使用在 203 版本显示正常。

<img width="2304" alt="image" src="https://user-images.githubusercontent.com/48122016/233914851-96f9449b-c924-49d3-85e1-b484f262b43c.png">

**Comment by AndersonHJB** [comment]
- [https://tcreograph.com/blog/notes-class21.html](https://tcreograph.com/blog/notes-class21.html)

也出现图标显示问题：

<img width="1563" alt="image" src="https://user-images.githubusercontent.com/48122016/233955904-e9b2f2e6-2e9a-4620-99d1-2264148d463f.png">

**Comment by OrageKK** [comment]
我也有同样的问题，回退203可以，试过chrome,edge,safari，都是一样的，去掉自定义icon的css，使用默认设置，还是会有同样的问题

**Comment by AndersonHJB** [comment]
> 已在 waline/client@2.15.2 中修复

如何使用？等待主题的下一次版本？

**Comment by Mister-Hope** [comment]
自己升级

**Comment by AndersonHJB** [comment]
升级命令：`pnpm install @waline/client`
