### ISSUE TITLE
[Feature Request]能否支持obsidian的一些链接语法

### ISSUE THREAD

**Issue by jdysya** [vuepress-theme-hope/vuepress-theme-hope#3069]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

 1. obsidian 中默认的链接方式是使用`wiki`的链接方式，即`[[]]`这种方式去链接，`markdown`中的链接方式是`[]()`这种方式，不过`obsidian`也可以关掉这个`wiki`链接，转而使用`markdown`的链接方式，不过没有默认的`wiki`连接方式好用
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/73117213/233924266-eb7bb2cc-298c-4d21-a321-f1eabb756f1a.png">

 2. obsidian中的链接方式支持链接到文本块，即不仅仅链接到`#`标题，实现方式就是给一个文本块生成一个唯一的id进行标识，即`^[id标识符]`这种方式
类似下面的这种链接方式
<img width="999" alt="image" src="https://user-images.githubusercontent.com/73117213/233923908-91c9ab3c-d2ba-4ba6-ab34-21b8c56fc205.png">
<img width="572" alt="image" src="https://user-images.githubusercontent.com/73117213/233923992-bf780a75-4211-4b43-85c2-a3cf8b236816.png">

**Comment by Mister-Hope** [comment]
The second syntax is already used by footnote in GFM, and the first one does not fit commonmark.

**Comment by 1912377458** [comment]
> The second syntax is already used by footnote in GFM, and the first one does not fit commonmark.
But the second syntax does not support usage everywhere, for example, I wanna jump to another paragraph from the current paragraph, not by the bottom footnote.
 In my opinion， the footnote just link the comment with the paragraph, however, I need to link two **Text block**  like what `obsidian` done

**Comment by jdysya** [comment]
I have writen a plugin to realize some idea, for detail you can go to https://github.com/jdysya/vuepress-plugin-obsidian
