### ISSUE TITLE
[Bug] 从文章列表点进去再后退会回到第一页

### ISSUE THREAD

**Issue by alomerry** [vuepress-theme-hope/vuepress-theme-hope#3077]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

访问某一页的一篇文章，使用 chrome 浏览器的后退按钮，返回文章列表页似乎没有加载页码

https://user-images.githubusercontent.com/34118544/234173268-ba4da5ca-87a5-42ff-aaf0-4f35f6fb84c7.mp4

**Comment by Mister-Hope** [comment]
Related: https://github.com/vuepress/vuepress-next/issues/1249

**Comment by Mister-Hope** [comment]
This should be fixed.
