### ISSUE TITLE
login模块

### ISSUE THREAD

**Issue by izhaorui** [vuepress-theme-hope/vuepress-theme-hope#3087]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

请问可以支持登录模块吗，比如为的文档系统登录了才能访问。

**Comment by Mister-Hope** [comment]
We have global encryption.

VuePress is a static generator

**Comment by izhaorui** [comment]
vue Press 可以用 v-dialogs 实现，我在hope里面使用好像不太行
