### ISSUE TITLE
[Feature Request] editLink直接设置Text内容

### ISSUE THREAD

**Issue by jellyqwq** [vuepress-theme-hope/vuepress-theme-hope#3117]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

你好, 希望在使用单语言时可以在`.vuepress/theme.ts`中直接设置editLink的Text, 目前设置这个需要通过`locales."lang-path".metaLocales.editLink`来间接设置, 这样能方便给单语言设置提供一点便利

```ts
import { hopeTheme } from "vuepress-theme-hope";

export default hopeTheme({
  // page meta
  locales: {
    "/": {
      metaLocales: {
        editLink: "还有什么想法吗",
      },
    }
  },
  // editLink: "还有什么想法吗",
  // 这层的editLink只有开关的功能, 希望在外层增加能直接设置的editLinkText
  // Type 'string' is not assignable to type 'boolean | undefined'.
});

```

**Comment by Mister-Hope** [comment]
So you mean this is not working?

```ts
export default hopeTheme({

      metaLocales: {
        editLink: "还有什么想法吗",
      },
});
```

**Comment by jellyqwq** [comment]
yes, it is not work for me.

> So you mean this is not working?
> 
> ```ts
> export default hopeTheme({
> 
>       metaLocales: {
>         editLink: "还有什么想法吗",
>       },
> });
> ```

**Comment by jellyqwq** [comment]
The code have not prompt error in vscode but it can't work
