### ISSUE TITLE
[Bug] 208手机端显示有bug，vuepress-theme-hope官方网站也有问题，我自己的网站改回207就可以了

### ISSUE THREAD

**Issue by luweizheng** [vuepress-theme-hope/vuepress-theme-hope#3118]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

208版本，手机端上下滑之后就白屏，导航栏也有问题，如下图。我自己网站也是这样，改成207貌似就没事了。

![image](https://user-images.githubusercontent.com/57242864/236671681-0d305977-fbbf-47da-b7bb-1c1219346684.png)

### Additional context

无

**Comment by Mister-Hope** [comment]
Unable to reproduce on:

- iPhone8.3 with iOS16.4.1
- iPad Pro 2021 with iPadOS 16.4.1

**Comment by luweizheng** [comment]
iPhone 12 Pro IOS 14.2： Safari & Chrome都不行

**Comment by Mister-Hope** [comment]
Can you try to debug your iOS device to see if there is any error thrown at runtime?

**Comment by luweizheng** [comment]
我的iPad也有问题。不知道如何在iOS上开启debug模式。看起来像是右上角和左上角的导航有问题。

**Comment by Mister-Hope** [comment]
I need detailed screenshots or screen record.

It maybe related with the usage of `Array.at`

**Comment by Mister-Hope** [comment]
packages/theme/src/client/modules/navbar/components/NavScreenDropdown.ts

**Comment by luweizheng** [comment]
虽然修了bug，但是感觉还有问题，用户体验和207版本不一样
