### ISSUE TITLE
[Feature Request] Card能否增加鼠标focus时悬浮效果

### ISSUE THREAD

**Issue by jcwangxp** [vuepress-theme-hope/vuepress-theme-hope#3121]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

类似主页的feature效果，或者下面这个[vuepress-theme-vdoing](https://github.com/xugaoyi/vuepress-theme-vdoing)做的效果
https://doc.xugaoyi.com/pages/d0d7eb/#%E6%99%AE%E9%80%9A%E5%8D%A1%E7%89%87%E5%88%97%E8%A1%A8

**Comment by Mister-Hope** [comment]
You can customize styles yourself, for me I refuse adding fancy styles in my theme.

Now you can add card custom container around card fence to enable flex layout.
