### ISSUE TITLE
使用Vue 交互演示基于antd做的组件时必须要将antd代码打包进组件才能运行

### ISSUE THREAD

**Issue by ynqq** [vuepress-theme-hope/vuepress-theme-hope#3122]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

在组件里面没有将antd等第三方库打包进来，然后通过importmap的方式引入会报错，antd会提示找不到vue的实例 可以将通过module引入vue那一段改为cdn吗？

**Comment by Mister-Hope** [comment]
> 可以将通过module引入vue那一段改为cdn吗？

你这段在说什么

**Comment by ynqq** [comment]
> > 可以将模块导入vue那一段改成cdn吗？
> 
> 你这段在说什么
就是希望可以在全局中获取到引入的Vue对象，这样一些其他的脚本就可以通过全局对象获取到Vue。
![PTO 9E3X `3E23PRW(BJ5KJ](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/45785987/d8331bf2-190d-4500-99fe-6699c91ab1c4)

**Comment by Mister-Hope** [comment]
我没有阻止你导入第一项吧？
