### ISSUE TITLE
[Bug] AutoCatalog not compatible with Vue 3.3.1

### ISSUE THREAD

**Issue by TeddyHuang-00** [vuepress-theme-hope/vuepress-theme-hope#3123]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-plugin-auto-catalog

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

As Vue 3.3.1 released hours ago, running `pnpm docs:update-package` will upgrade vue dependency version to this newer version, but using `<AutoCatalog />` component will complain "Symbol not found" when in production build. See https://github.com/TeddyHuang-00/SymbolNotFound for a minimal reproduction of the bug.

This might be due to an upstream issue with VuePress, but I'm not sure about that, so please correct me if this is beyond the scope of the plugin.

**Comment by TeddyHuang-00** [comment]
BTW, if anyone are seeing similar issue with the latest vue version 3.3.1, you can temporarily work this out by downgrading it in `package.json` as follows:

```diff
  "devDependencies": {
    "@vuepress/client": "2.0.0-beta.61",
-   "vue": "^3.3.1",
+   "vue": "~3.2.47",
    "vuepress": "2.0.0-beta.61",
    "vuepress-theme-hope": "2.0.0-beta.209"
  }
```

Then installing dependencies again should help you out before a proper fix can be adopted

**Comment by Mister-Hope** [comment]
> - [x]I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

https://theme-hope.vuejs.press/zh/faq/common-error.html#usexxx-is-called-without-provider

<img width="752" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/05b7c527-2735-4cc3-8765-f8e0e83e60bd">
