### ISSUE TITLE
[Bug]anchor link No synchronous modification with origin reference link

### ISSUE THREAD

**Issue by jdysya** [vuepress-theme-hope/vuepress-theme-hope#3130]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/73117213/5f6d7ac2-7691-497c-a17a-68d35c2de4af)
The origin link like following, some character did not be replaced
<img width="1621" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/73117213/2b415999-e8b0-442e-a740-a131a8a3a0e5">
However, the `anchor link` like this, wil convert some character automatically:
<img width="637" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/73117213/94153b4c-adcc-4609-aaa7-b968a838f637">

**Comment by Mister-Hope** [comment]
This is because we automatically slugify all header id, as some character are illegal in selector (e.g.: `>`)
