### ISSUE TITLE
[Bug]组件 back-to-top 淡入效果 bug

### ISSUE THREAD

**Issue by qian-shen** [vuepress-theme-hope/vuepress-theme-hope#3132]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

1. 我在尝试滑动页面时查看 back-to-top 插件的淡入淡出效果，但是淡出效果存在，淡入效果似乎没有生效，于是我查看了源码中的样式文件 node_modules\vuepress-plugin-components\lib\client\styles\back-to-top.scss，发现了其中的一个命名似乎有问题：
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/62203483/f6d6a7b4-436e-4797-b147-4e3c80233b22)
2. 我将其修改成如下：
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/62203483/40f8bd21-0521-4371-9010-0e6c611e34c4)
发现淡入效果恢复正常，以下是修改前和修改后的效果对比：
修改前：

https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/62203483/0073caf2-3ba1-468e-a5b1-559ba0a6bb71

修改后：

https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/62203483/1a8023b4-9a54-429f-ac63-c26d04efe942

**Comment by Mister-Hope** [comment]
nice catch, pr welcome
