### ISSUE TITLE
[Feature Request]能否增加复制文章内容能够一键粘贴微信公众号

### ISSUE THREAD

**Issue by lurj7988** [vuepress-theme-hope/vuepress-theme-hope#3137]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

直接粘贴到微信公众号无需排版

**Comment by Mister-Hope** [comment]
微信公众号文章需要内联样式，而任何主题都应该是尺寸和性能优先的（全局样式+class控制）

没人会因为你这个特殊需求去把所有样式内联到文章里。

**Comment by lurj7988** [comment]
可以通过juice来改成内联样式，不过要重新自定义CSS，不太会调
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/45491061/bbf515ae-87dc-4f94-9ba5-c041a87b7c8a)

**Comment by Mister-Hope** [comment]
We can add a preset adding a button which copies whole page while clicking.

I found an awesome library here: https://github.com/bernd-wechner/Copy-with-Style and we can import this via CDN.

**Comment by Louis-XIV** [comment]
> 微信公众号文章需要内联样式，而任何主题都应该是尺寸和性能优先的（全局样式+class控制）
> 
> 没人会因为你这个特殊需求去把所有样式内联到文章里，完全忽略尺寸和渲染性能。
> 
> 除非你找到了其他类似网站可以实现这个功能，可以发来参考再讨论一下，否则请自己实现。

这里提供了一个实现机制：https://github.com/doocs/md?tab=readme-ov-file

**Comment by Mister-Hope** [comment]
所以你已经有现成的工具了，自己搞吧。这本来就和这个项目是两个东西。
