### ISSUE TITLE
[Feature Request] Support Note and Warning blockquote as hint containter

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress-theme-hope/vuepress-theme-hope#3144]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

> **Note**
> Some text here

> **Note**

> **Note**: Some text here

> **Note**: Some text here
> Additional Content

> **Warning**
> Some text here

> **Warning**: Some text here

> **Warning**: Some text here
> Additional Content

```md
> **Note**
> Some text here

> **Note**

> **Note**: Some text here

> **Note**: Some text here
> Additional Content

> **Warning**
> Some text here

> **Warning**: Some text here

> **Warning**: Some text here
> Additional Content
```

They should be rendered with hint containers

**Comment by jcwangxp** [comment]
want it too :smile:

**Comment by Mister-Hope** [comment]
Update, GitHub update and narrow the support syntax, so we only need to support 2 cases
