### ISSUE TITLE
[Feature Request] Need to support local search for tabs or code-tabs

### ISSUE THREAD

**Issue by jcwangxp** [vuepress-theme-hope/vuepress-theme-hope#3146]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

::: code-tabs#language
@tab Define Schema
``` c
typedef struct {
	char 	name[20];
	char 	age;
	int		id;
	bool	sex;
} student_t;
```
@tab Create Database and Table
``` c
test_dbCreate ();
test_tblCreate ();
```
@tab  CURD Operation
``` c
test_getStudent ();
test_delStudent ();
```
:::

**Comment by Mister-Hope** [comment]
Can not be supported, the featue is supported by a Vue component
