### ISSUE TITLE
[Bug]文件未曾引入组件，说加载自定义组件异常。还有文件明明存在，确找不到路由

### ISSUE THREAD

**Issue by 752337625** [vuepress-theme-hope/vuepress-theme-hope#3153]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/46662524/04b2d276-062f-4fab-b7ab-2c76bcf9677c)
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/46662524/5aaff2ed-3cb1-4369-9e22-7435d732e852)

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/3154#issuecomment-1559348239
