### ISSUE TITLE
[Bug]404.html异常

### ISSUE THREAD

**Issue by 752337625** [vuepress-theme-hope/vuepress-theme-hope#3154]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

俩周前打包还正常，最近莫名奇妙又不能了。还原代码无济于事。
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/46662524/fef4a032-aa46-4a8f-bf59-fdc73307f865)

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/46662524/61b71fca-8859-43ab-adfa-b5455405138a)

**Comment by Mister-Hope** [comment]
>  I am using the latest v2 version of VuePress and VuePress official plugins.
>
>  I have searched FAQ and I did not find the answer.

If you refuse to do what checklist says, then I refise to provide any answers.

Ref: https://theme-hope.vuejs.press/zh/faq/troubleshooting.html
