### ISSUE TITLE
[Bug] dir.order doesn't work now

### ISSUE THREAD

**Issue by MaHe666** [vuepress-theme-hope/vuepress-theme-hope#3156]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

我今天尝试使用 dir.order 来给文件夹做排序，但是没有生效
我的sidebar设置是 "structure"
下面是我的截图
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/74131961/08606db6-c939-49a2-a775-547af860993c)

**Comment by MaHe666** [comment]
目前的效果是这样的
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/74131961/f3cf9160-832c-4505-971c-9111048cd394)

**Comment by Mister-Hope** [comment]
Learn some basics first. dot means object keys

**Comment by MaHe666** [comment]
What I want is making the folder order by the number which I set, but it doesn't work.

**Comment by Mister-Hope** [comment]
Agaim, understand object in yaml and js. a.b is a common representation, e.g.: https://vitejs.dev/config/shared-options.html#resolve-alias
