### ISSUE TITLE
[Bug] build failed after update v2.0.0-beta.213

### ISSUE THREAD

**Issue by alomerry** [vuepress-theme-hope/vuepress-theme-hope#3159]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

After upgrading `vuepress-theme-hope` from `v2.0.0-beta.211` to `v2.0.0-beta.213`, I encountered build failures and I am uncertain about how to resolve it. 

Thank you in advance for your assistance.

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/34118544/08ef6e47-3038-453b-a171-45ea435459a3)

### Additional context

- [repository commit](https://github.com/alomerry/blog/commit/34707d8e6a2e7960cd3c330e2724377cf7bd1909)
- [build logs](https://ci.alomerry.com/job/vuepress-blog/154/console)
- environment: 
  - pnpm 8.2.0 
  - node 16.16.0

**Comment by Mister-Hope** [comment]
> I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

? You have 2 vue versions in your repo. Unify them to 3.3.4
