### ISSUE TITLE
[Feature Request] Pagination for blog's ArticleList

### ISSUE THREAD

**Issue by vmihailenco** [vuepress-theme-hope/vuepress-theme-hope#3170]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

Large blogs that have many articles need some pagination or the index page becomes too large which causes issues for users & crawlers.

### Additional context

Doing pagination on the client is probably not that hard, but having SSR support would be nice.

**Comment by Mister-Hope** [comment]
Isn't there a pagination already?

What to you mean?

**Comment by Mister-Hope** [comment]
The blog plugin is designed to provide core blog features, and pagination is some kind of process of blog data at client data, which is not a part of core blogging feature.

VuePress Theme Hope already supports this by adding a pagination component. If you want blog plugin used with other themes, it's their job to create such a component fitting their own style.
