### ISSUE TITLE
[Bug]使用highlights时class="vp-highlight-wrapper"的样式丢失

### ISSUE THREAD

**Issue by firstack-it** [vuepress-theme-hope/vuepress-theme-hope#3177]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

按照官网文档新建了一个 vuepress-theme-hope 项目，直接复制[官网文档首页的配置案例](https://theme-hope.vuejs.press/zh/guide/layout/home.html#%E9%85%8D%E7%BD%AE%E6%A1%88%E4%BE%8B)，发现highlights的样式丢失，辛苦作者帮忙看下，谢谢，图式如下

![](https://ism.firstack.com/files/ism-files/微信截图_20230531205713.png)

**Comment by firstack-it** [comment]
> 将在下一个版本中修复。

: ）辛苦了，十分感谢

**Comment by Mister-Hope** [comment]
Forgot to include this in bundled version. You can add custom: true as an workaround by using alias
