### ISSUE TITLE
[Bug] Artalk评论上方图标一直处于加载状态

### ISSUE THREAD

**Issue by itwxe** [vuepress-theme-hope/vuepress-theme-hope#3179]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

Artalk评论上方图标一直处于加载状态，如下图

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/57243412/689d6c7b-3e16-41a3-92ab-9b93c773fd9a)

**Comment by itwxe** [comment]
@Mister-Hope 
示例地址：https://itwxe.com/dev-ops/software-installation/linux/73ea491a.html
git仓库地址：https://github.com/itwxe/blog

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/f2da175cc95b47d5d518cabbe14518c2a22021cb
