### ISSUE TITLE
[Feature Request] print style enhancement

### ISSUE THREAD

**Issue by jdysya** [vuepress-theme-hope/vuepress-theme-hope#3181]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

When print the web content to PDF file, I did not find the detail container. I think the detail container should be expanded in the PDF instead of vanishing.

**Comment by Mister-Hope** [comment]
When you folded something, usually they are not important to the whole doc, instead is a detailed information about something. You should add your own css to override this if you like to display them.

**Comment by jdysya** [comment]
> When you folded something, usually they are not important to the whole doc, instead is a detailed information about something. You should add your own css to override this if you like to display them.

Maybe it is just because the content detailed took up too much space, anyhow，though it is not important, actually it is the absolutely necessary part of the doc

**Comment by Mister-Hope** [comment]
Anyway, a preset expanding all of them is welcomed.

**Comment by Mister-Hope** [comment]
The changes is done 6 month ago, and it seems that css can not correct the "closed" detail block to be opened. If you want to display them, you may need to provide a print button as a preset which toggle all detail blocks to be opened while clicking.

**Comment by jdysya** [comment]
> The changes is done 6 month ago, and it seems that css can not correct the "closed" detail block to be opened. If you want to display them, you may need to provide a print button as a preset which toggle all detail blocks to be opened while clicking.
There are many related options involved，such as the code tabs which also has the same matter.

**Comment by Mister-Hope** [comment]
Contents like code tabs cnd be redesigned, and this kind of pr is welcomed

**Comment by jdysya** [comment]
> Contents like code tabs cnd be redesigned, and this kind of pr is welcomed

I just found the [code demo](https://vuepress-theme-hope.github.io/v2/zh/guide/markdown/demo.html#%E6%BC%94%E7%A4%BA) was actually the detail container, but it supported the PDF  print very well

**Comment by Mister-Hope** [comment]
> I just found the [code demo](https://vuepress-theme-hope.github.io/v2/zh/guide/markdown/demo.html#%E6%BC%94%E7%A4%BA) was actually as a instance of the detail container, but it supported the PDF print very well. Whether we can learn something from this.

Nope, we only apply same styles on totally different doms.

If you know nothing about front-end developing and you can not open a pr to make some improvements, then you can just close this because I am absolutely not interested in this.

If you want your markdowns to be a nice pdf containing all contents, then **probably you should stop using any web-based features**, in these case, the detailed container, tabs and code-tabs are. Rewrite them into sections of sperated pages, just like writing a book

**Comment by jdysya** [comment]
> > I just found the [code demo](https://vuepress-theme-hope.github.io/v2/zh/guide/markdown/demo.html#%E6%BC%94%E7%A4%BA) was actually as a instance of the detail container, but it supported the PDF print very well. Whether we can learn something from this.
> 
> Nope, we only apply same styles on totally different doms.
> 
> If you know nothing about front-end developing and you can not open a pr to make some improvements, then you can just close this because I am absolutely not interested in this.
> 
> If you want your markdowns to be a nice pdf containing all contents, then **probably you should stop using any web-based features**, in these case, the detailed container, tabs and code-tabs are. Rewrite them into sections of sperated pages, just like writing a book

To tell the truth, I'm just stating what I've found, I think I would consider the solution maybe I need a nice PDF one day(not now), the issue I hope continue to be open as I think someone would be interested in it.
