### ISSUE TITLE
[Bug] 升级至 2.0.0-beta.218 和 2.0.0-beta.219 文档首页样式混乱

### ISSUE THREAD

**Issue by herodotus-cloud** [vuepress-theme-hope/vuepress-theme-hope#3186]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope@next

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [X] Linux

### Describe the bug

升级至 2.0.0-beta.218 和 2.0.0-beta.219 后，文档首页的样式混乱。features hover 效果消失，布局改变。

这个问题是升级至最新版本才出现，2.0.0-beta.215 以前均为正常的

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11025512/d464f670-c1e7-4c5c-9580-e09fedc280b6)

现在的效果可以在线查看：https://www.herodotus.cn

**Comment by Mister-Hope** [comment]
https://theme-hope.vuejs.press/demo/project-home.html I don't think anything is broken

**Comment by herodotus-cloud** [comment]
最初我以为是因为我增加了自定义组件导致的这个问题。刚刚我又重新测试一下。首先把我自己增加的内容注释掉，避免干扰。

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11025512/10f3baa8-c169-4b77-9ead-c9dc9afa68c5)

其它所有的测试任何内容都没有变，只是升级 hope版本， 从 2.0.0-Beta.215开始

## 1. 2.0.0-beta.215
![微信截图_20230603173036](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11025512/a300053f-fcea-4a50-b351-2e7e95dcee25)
![微信截图_20230603173022](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11025512/3f19e7af-3b7b-4f09-b3a0-9606ed946126)

## 2. 升级至 2.0.0-beta.216
![微信截图_20230603173058](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11025512/143d6838-8877-431f-aff9-4b5adf7a419f)
![微信截图_20230603173158](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11025512/c18a14ad-d78f-4568-88b0-d314e63de437)
![微信截图_20230603173140](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11025512/8c23e3cf-740d-4a88-8c03-a217d7fcb7df)

## 3. 升级至 2.0.0-beta.217

![微信截图_20230603173224](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11025512/9b02f30e-0740-43f3-ae65-4837ce9f987d)
![微信截图_20230603173310](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11025512/53fb4c96-7555-4542-abdf-4cfe5bc92394)
![微信截图_20230603173254](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11025512/52b6bf3b-fe21-4178-8d3d-ce11695d1dbd)

## 4. 升级至 2.0.0-beta.218

![微信截图_20230603173338](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11025512/2b056485-ac4e-4986-82f6-7df9596ec42c)

![微信截图_20230603173426](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11025512/63482e26-49fc-474e-b551-ed766c84f54f)
![微信截图_20230603173415](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11025512/b57ed895-2abd-4133-b0ef-46f9eb5dc425)

## 5. 升级至 2.0.0-beta.219

![微信截图_20230603173508](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11025512/84b7d599-9d36-4f1e-8475-e128293ecde0)
![微信截图_20230603173547](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11025512/a109894f-15f6-4582-8296-3a5bc5865195)
![微信截图_20230603173528](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11025512/664416e4-f9e8-4117-9345-2010b0135a1e)

**Comment by herodotus-cloud** [comment]
找到问题了：

在 2.0.0-Beta.218 及 219 版本中，如果 features 下面条目，不包含 `link` 像下面一样，样式就会出问题。

```
features:
  - title: 方案成熟
    icon: slides
    details: 成熟的,完善的,全面的，基于 Spring Authorization Server 的,前后端分离的微服务架构解决方案。
```

全新建一个 hope 工程，修改 home 内容，删掉一个 link

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11025512/132f0760-f169-440a-81ae-b9338e85aa50)

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11025512/7698b0fb-616a-4cb5-acfc-7931f91259cf)
