### ISSUE TITLE
[Bug] 开启bug模式 打包的时候会卡主

### ISSUE THREAD

**Issue by xiao-peng-16** [vuepress-theme-hope/vuepress-theme-hope#3195]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/42399487/51f43c75-bde3-4e36-8551-2d1dd256968e)
不知道是不是我的问题，开启bug模式后 打包的时候会卡主，关掉就没问题

**Comment by Mister-Hope** [comment]
A minimal reproduction is needed
