### ISSUE TITLE
[Feature Request]the auto play component in the doc is noisy

### ISSUE THREAD

**Issue by jdysya** [vuepress-theme-hope/vuepress-theme-hope#3200]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

About the [bilibili](https://vuepress-theme-hope.github.io/v2/zh/guide/markdown/components.html#bilibili), when rendered the web page, the component would auto play, it was really annoying.

**Comment by Mister-Hope** [comment]
If you are talking about docs, then it's a documentation thing.

the BiliBili component won't autoplay unless you set `autoplay`. If your behaviour is different, provide a mininal reproduction, and this should be a bug.

**Comment by jdysya** [comment]
> it's a documentation thing.

it is just a doc thing, about [components.md](https://github.com/vuepress-theme-hope/vuepress-theme-hope/edit/main/docs/theme/src/zh/guide/markdown/components.md)
