### ISSUE TITLE
[Bug] `presentation.revealConfig` has no effect

### ISSUE THREAD

**Issue by liblaf** [vuepress-theme-hope/vuepress-theme-hope#3202]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-plugin-md-enhance

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

Configuring `presentation.revealConfig` according to the [Guide](https://theme-hope.vuejs.press/guide/markdown/presentation.html) has no effect.

### Additional context

Setting `reveal` to pass options to `reveal.js` per page in **frontmatter** works.

**Comment by Mister-Hope** [comment]
This documentation is accurate now: https://plugin-md-enhance.vuejs.press/zh/guide/presentation/#%E9%85%8D%E7%BD%AE.

We do miss some documentation updates.
