### ISSUE TITLE
[Feature Request] code highlight

### ISSUE THREAD

**Issue by jdysya** [vuepress-theme-hope/vuepress-theme-hope#3205]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

To support highlight everywhere, instead of  only the rows. Such as the [docs-zh.javascript.info](https://zh.javascript.info/default-browser-action#shi-li-cai-dan)
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/73117213/4730e5d7-65f8-4dca-a96c-be88a3ce0477)
Inspect [its source code](https://github.com/javascript-tutorial/zh.javascript.info/blob/master/2-ui/2-events/04-default-browser-action/article.md), I found the following syntax:
<img width="1064" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/73117213/c895cc54-6c31-4d85-81da-71cda8eb0ba0">

**Comment by Mister-Hope** [comment]
I am not interested in any features which breaks the original markdown behavior.

**Comment by Mister-Hope** [comment]
Just some update, we have supported shiki, which itself support some annotations,

https://ecosystem.vuejs.press/plugins/markdown/shiki.html#notationdiff
