### ISSUE TITLE
[Feature Request] markdown增强的tasklist功能支持不显示选项前那个点

### ISSUE THREAD

**Issue by SherkeyXD** [vuepress-theme-hope/vuepress-theme-hope#3213]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

如题，如果能有一个选项支持在渲染tasklist时支持不显示选项前那个点就好了
在某些情况下（比如展示选择题选项的时候）有这个点会影响观感
![${UPM84_)DM4E944VNHERUO](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/57581480/cb9d7387-fd6d-4f48-8452-47882241ecc3)

**Comment by Mister-Hope** [comment]
下个版本改为默认样式
