### ISSUE TITLE
[Feature Request] provide a break option for noob users

### ISSUE THREAD

**Issue by JIeJaitt** [vuepress-theme-hope/vuepress-theme-hope#3215]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

我在这个discussion详细的描述了需求：https://github.com/orgs/vuepress-theme-hope/discussions/3214

**Comment by Mister-Hope** [comment]
Answered in ref discussion

**Comment by Mister-Hope** [comment]
Maybe we can provide a break option for noob users in case they don't know how to config markdown-it

**Comment by JIeJaitt** [comment]
> Maybe we can provide a break option for noob users in case they don't know how to config markdown-it

Thank you and Based on your prompt, I found a document about line breaks: https://theme-hope.vuejs.press/cookbook/markdown/demo.html#line-break. But I don't understand the meaning of this design, why not just switch lines? Please provide guidance

**Comment by Mister-Hope** [comment]
https://commonmark.org/

**Comment by Mister-Hope** [comment]
https://commonmark.org/

**Comment by JIeJaitt** [comment]
> * [commonmark.org](https://commonmark.org/)
> * [spec.commonmark.org](https://spec.commonmark.org)
> 
> These sections are your concern:
> 
> * [spec.commonmark.org/0.30/#hard-line-breaks](https://spec.commonmark.org/0.30/#hard-line-breaks)
> * [spec.commonmark.org/0.30/#soft-line-breaks](https://spec.commonmark.org/0.30/#soft-line-breaks)

Thank you, I understand now. Do I need to close this issue or rename it to `provide a break option for noob users`?
