### ISSUE TITLE
[Bug] beta.224版本文章单独设置永久链接permalink不生效，beta.223版本正常

### ISSUE THREAD

**Issue by itwxe** [vuepress-theme-hope/vuepress-theme-hope#3217]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

beta.224版本文章单独设置永久链接permalink不生效，beta.223版本正常
使用beta.224版本配置
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/57243412/75462f73-2c62-42e0-adff-2be75c00ea3e)

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/57243412/543b15d7-ef2f-48f2-8957-a5d88fee4245)

路径错误

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/57243412/6f37aa8b-c32f-4a65-8d09-8c626085c3e3)

git仓库地址: https://github.com/itwxe/blog

**Comment by Mister-Hope** [comment]
Probably not a but my side, you need to provide a minimal reproduction and post it to vuepress/vuepress-next

**Comment by Mister-Hope** [comment]
Maybe caused by VPLink I think, so what part of link is not working?

**Comment by Mister-Hope** [comment]
I just triggered a beta.225 push, update to new version to see if it solves your problem. A valid fix may already been applied.

**Comment by itwxe** [comment]
> I just triggered a beta.225 push, update to newest version later to see if it solves your problem. A valid fix may already be applied.
> 
> If you are still meeting issues, provide a minimal reproduction would be grateful.

感谢回复，beta.255已解决此问题
