### ISSUE TITLE
[Bug] Unnormalized link can not be resolved

### ISSUE THREAD

**Issue by zuihou** [vuepress-theme-hope/vuepress-theme-hope#3222]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

"vuepress-theme-hope".  "2.0.0-beta.211" 升级到 "2.0.0-beta.225"后， 对 “permalink”参数支持不友好。

错误截图：
<img width="540" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/8500410/0219d663-7a65-405f-a086-ed74215e2fbf">

markdown：
```
---
title: 4.x功能蓝图
permalink: /upgrade/4.x功能蓝图
article: true
category:
  - 升级日志
tag:
  - 升级日志
  - 4.x功能蓝图
---
```

使用 2.0.0-beta.211 时， 在侧边栏能正常显示为title。

**Comment by Mister-Hope** [comment]
试图让permalink以.html或/结尾再重试

**Comment by zuihou** [comment]
> 试图让permalink以.html或/结尾再重试

/ 结尾不行

html结尾可以。


但211版本时，  没有任何结尾也是可以的。

**Comment by Mister-Hope** [comment]
/index.html 结尾有什么问题么？

**Comment by zuihou** [comment]
beta.211 版本，写成 `/upgrade/4.x功能蓝图` 能正常显示
```
---
title: 4.x功能蓝图
permalink: /upgrade/4.x功能蓝图
---
```

beta. 225 版本，只能写成 `/upgrade/4.x功能蓝图.html` 才能正常显示
```
---
title: 4.x功能蓝图
permalink: /upgrade/4.x功能蓝图.html
---
```

这是bug还是设计如此？   
设计如此我就自己改下写法就行了。

**Comment by Mister-Hope** [comment]
为了提升性能，我们会做路径推断以减少代码执行时间。这里可以看看能不能做兼容。

**Comment by Mister-Hope** [comment]
To get better performance, you should use normalized link, i.e.: `/path/a.html` or `/path/b/`.
