### ISSUE TITLE
[Bug] "ArtPlayer"无法使用

### ISSUE THREAD

**Issue by firstack-it** [vuepress-theme-hope/vuepress-theme-hope#3226]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

当我使用`ArtPlayer`时，会出现如下报错

![](https://ism.firstack.com/files/ism-files/1686892866876-image.png)

复现步骤

1. 使用`npm init vuepress-theme-hope [dir]`新建项目
2. 在`theme.ts`中加入如下代码
```ts
  plugins: {
    components: {
      // 你想使用的组件
      components: [
        "ArtPlayer",
      ],
    },

    // You should generate and use your own comment service
    comment: {
      provider: "Giscus",
      ...........................
```
3. 页面使用`ArtPlayer`
```md
---
title: 主要功能与配置演示
index: false
icon: laptop-code
category:
  - 使用指南
---

## 目录

- [Markdown 展示](markdown.md)

- [页面展示](page.md)

- [禁用展示](disable.md)

- [加密展示](encrypt.md)

<ArtPlayer
    src="https://vp-demo.u2sb.com/video/caminandes_03_llamigos_720p.mp4"
/>

```

**Comment by Mister-Hope** [comment]
Provide a reproduction at stackblitz

**Comment by Mister-Hope** [comment]
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/03ab942d-b3c9-4510-a0d9-71df14779ae6)

**Comment by firstack-it** [comment]
[这里提供了一个出问题的项目](https://github.com/firstack-it/test-project)

我尝试了切换语言、切换node版本（使用nvm管理），依旧是这个报错

最后我尝试了更换电脑，仍然无法解决

**Comment by firstack-it** [comment]
我尝试了`npm`、`yarn`、`pnpm`、`cnpm`，开发阶段依旧会出现这个报错

切换到`webpack`后，会有如下报错，网上查了下，自身能力不够，没办法解决

```
✔ Initializing and preparing data - done in 224ms
✔ Compilation finished in 8383ms
success VuePress webpack dev server is listening at http://localhost:8080/
WARNING in ./node_modules/typescript/lib/typescript.js 3055:91-112
Module not found: Error: Can't resolve 'perf_hooks' in 'xxx\node_modules\typescript\lib'
```

最后我想了想，这个问题会不会只存在于开发阶段，切换到`vite`，打包项目上传到服务器后，<kbd>ArtPlayer</kbd>可以正常使用，控制台也没有报错
<img width="1172" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/129273320/6dde063c-eeb5-407e-a863-3efb447e9291">

**Comment by gaozhao7** [comment]
遇到一样的问题：
<img width="1498" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/36031132/2b1041bd-dbac-4850-a02d-37a21857103f">

**Comment by firstack-it** [comment]
> 遇到一样的问题： <img alt="image" width="1498" src="https://user-images.githubusercontent.com/36031132/276047326-2b1041bd-dbac-4850-a02d-37a21857103f.png">

这个问题好像只存在开发阶段，你打包上传服务器就不会报错了，我是这样解决的

**Comment by brycenhe** [comment]
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/89619125/a0573411-fed5-47c9-ae50-ba4fe6ab67e4)
ke'neng's可能是路径的问题？ 不知道这个@fs指向那里
