### ISSUE TITLE
Markdown中手机端无法一键复制代码 [Bug] 

### ISSUE THREAD

**Issue by baelow** [vuepress-theme-hope/vuepress-theme-hope#3242]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

Operating system: Android,
浏览器： Via and MIUI 浏览器
测试网址： [https://vuepress-theme-hope.gitee.io/v2/cookbook/tutorial/deploy.html#unordered-list]()
问题描述：手机浏览器打开网站时无法使用markdown一键复制功能，然而选择电脑模式（即电脑UA）打开时却可以正常使用一键复制功能。图片如下
![](https://gitee.com/barlown/temp_test/raw/master/%E5%9B%BE%E5%BA%8A-%E9%9D%9E%E6%AD%A3%E5%BC%8F/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE1.png)
![](https://gitee.com/barlown/temp_test/raw/master/%E5%9B%BE%E5%BA%8A-%E9%9D%9E%E6%AD%A3%E5%BC%8F/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20.png)

总结： 希望修复手机端无法一键复制代码的问题。
感谢

**Comment by Mister-Hope** [comment]
https://theme-hope.vuejs.press/zh/guide/feature/copy-code.html#%E4%BD%BF%E7%94%A8

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/8bc2ec7e-d84d-4efa-9618-1a3817f09229)

# Try NOT to make others annoyed and throw Fxxx words to you
