### ISSUE TITLE
添加一些新的博主媒体图标支持（blog.medias）

### ISSUE THREAD

**Issue by songbaicheng** [vuepress-theme-hope/vuepress-theme-hope#3255]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

现在已经支持的社交媒体感觉大部分都是国外的，我想添加一个力扣的却发现没有支持的图标，所以能不能在丰富一些，或者提供支持自定义图标的功配置。

**Comment by Mister-Hope** [comment]
关于后者，能不能看文档，文档没教你自定义？

关于前者，欢迎，提供圆形含背景的力扣图标

**Comment by songbaicheng** [comment]
上次用自定义没成功，这一次发现是没有传完整路径导致的。

**Comment by Mister-Hope** [comment]
如果你的图标是svg的话，可以pr过来，单独在评论中粘贴svg代码也行。

目前抖音支持网页访问了，在最开始开发的时候不支持。力扣，小红书之类的，如果你可以列出更多也欢迎列出。这里是树摇的，不使用的图标也不会打包进去，所以多多益善。唯一的问题就是图标风格需要统一。
