### ISSUE TITLE
[Feature Request] 新增图片链接失效后的用户端提示方案

### ISSUE THREAD

**Issue by firstack-it** [vuepress-theme-hope/vuepress-theme-hope#3256]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

当md中引用的图片链接失效时，打包后的文档该图片长宽都为0，在用户阅览的时候，可能并不知道这里少了图片

<img width="167" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/129273320/1ec89fce-56d3-496a-8f9b-48fefab784a4">

是否可以添加一个配置项，当图片链接失效时，默认展示某张图片，或者通过其他方式告知用户这里缺失图片，类似这种，错误图片可以自己指定是最好了

<img width="129" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/129273320/360c3384-22b2-4c62-b090-2c1251b3a09b">

<img width="134" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/129273320/de2f01fd-f63f-4da1-9a41-bd58577f1549">

**Comment by Mister-Hope** [comment]
Out of scope, ask in VuePress plz
