### ISSUE TITLE
[Bug] Sidebar not working in safari

### ISSUE THREAD

**Issue by JinchaoLove** [vuepress-theme-hope/vuepress-theme-hope#3257]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

The sidebar, `class="toggle-sidebar-wrapper"`, cannot be wrapped successfully.

**Comment by JinchaoLove** [comment]
Specifically, the sidebar cannot be hidden or shown up with the button "<" or ">".

For example, the sidebar should be hidden in the below case, and shows up if we click the ">" button.

<img width="331" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/34153355/791cdb87-01eb-4bb9-b823-4ac62c26c60d">

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/482d7919-7f94-4615-ae88-5b60f9e2e505

?

**Comment by JinchaoLove** [comment]
> 
> ?

Thanks! I've tested on Chrome, it works. The bug appears on Safari.

**Comment by JinchaoLove** [comment]
It also works in previous version using `vuepress-theme-hope@2.0.0-beta.53` in a demo [website](https://igeekfan.cn/about) by Mr. @luoyunchong

**Comment by Mister-Hope** [comment]
That's really a long time ago, I do not have a Mac so that I cannot debug Safari easily.

**Comment by Mister-Hope** [comment]
The feature is running well on my iPad, I need a detailed reproduction environment

**Comment by JinchaoLove** [comment]
> The feature is running well on my iPad, I need a detailed reproduction environment

The versions:
- MacOS: Catalina 10.15.7 (19H2026)
- Safari: 15.6.1 (15613.3.9.1.16, 15613)

Maybe I need to use the latest version of Safari. But it's maybe not the issue of Safari version: the horizontal sidebar wrapper works, while the vertical wrapper not in my browser (as shown below).

<img width="326" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/34153355/cdbbee11-071a-41f0-8550-5f27c1c9d7a5">

**Comment by JinchaoLove** [comment]
I've tested on other versions of Safari in [lambdatest](https://app.lambdatest.com), the issue also occurs on Safari 15 and 16.

**Comment by Mister-Hope** [comment]
I am not sure about it, so I am afraid I will leave it here.

**Comment by JinchaoLove** [comment]
I set below configs and the problem solved.

```scss
// styles/config.scss
$sidebar-mobile-width: 100%;
$pc: 1920px;
$laptop: 1440px;
$pad: 959px;
$tablet: 959px;
$mobile: 959px;
```

Is it because `WindowSize` has higher priority than the `isDesktopSidebarCollapsed` in the `CommonWrapper.ts`?

**Comment by Mister-Hope** [comment]
Nope, there are real problems in safari, I reproduced your issue after releasing beta130

**Comment by JinchaoLove** [comment]
Okay, I see. Thanks for the answers. I'll close this as it may not be the issue of the theme.

**Comment by Mister-Hope** [comment]
Nope, you misunderstand me, this is a bug of theme (or vuepress), and should be tracked.

It would be great if you can spend sometime trying historical versions to see from which version the bug appears, so that I may locate the actual problem. I think everything is working fine at least up to beta222 with vp2beta62

**Comment by JinchaoLove** [comment]
> Nope, you misunderstand me, this is a bug of theme (or vuepress), and should be tracked.
> 
> It would be great if you can spend sometime trying historical versions to see from which version the bug appears, so that I may locate the actual problem. I think everything is working fine at least up to beta222 with vp2beta62.
> 
> The main problem is that I do not have Mac or Macbook, so I cannot debug Safari, yet I do not check safari behavior while coding.

The issue appeared after upgrading from beta156 (works fine) to beta157 (button not work).

**Comment by Mister-Hope** [comment]
You should be aware that starting from beta157, only vp2beta60 is supported. You should check the VuePress version requirement in changelog

**Comment by Mister-Hope** [comment]
Another good approach is that try to run the latest version devServer on safari, and see if you can trigger same bug (there should be error in console)

Provide the full log (with error stack) would help me checking the problem, clicking into stack links and provide screenshots about those lines (with 5-6 lines up and down) would be helpful either.

**Comment by JinchaoLove** [comment]
I track the versions from your [blog repo](https://github.com/Mister-Hope/Mister-Hope.github.io/commits/main) and `demo/theme-blog` in [vuepress-theme-hope repo](https://github.com/vuepress-theme-hope/vuepress-theme-hope/tags) with the `dev:vite-clean` script, the button is not work for all commits in recent 2 months, no error log in the console.

**Comment by JinchaoLove** [comment]
I think the major related change from beta156 to beta157 is from `useMobile` to `useWindowSize` in `CommonWrapper.ts`, is there any problem between these two versions?

**Comment by Mister-Hope** [comment]
We confirmed that latest safari 16/17 has no issue, so we are closing it.

We only ensure 2 latest major version for safari

**Comment by anwen-anyi** [comment]
原来2023年就有这个问题了呀? 我记得我2023年的时候展示正常，难道是现在 `WebKit`版本太低了导致的? 不然没办法[兼容/使用]最新版本的前端框架？

应该是最新的版本了，以官网示例 **https://theme-hope.vuejs.press/zh/guide/markdown/** 截图展示，图一为15.4.1，图二为16.2

```
<meta name="generator" content="VuePress 2.0.0-rc.31" />
<meta name="theme" content="VuePress Theme Hope 2.0.0-rc.109" />
```

| 图一：15.4.1 | 图二：16.2 |
| :---: | :---: |
| <a href="https://github.com/user-attachments/assets/c6e926e2-8224-46ef-b4ca-fc22610e7ace"><img src="https://github.com/user-attachments/assets/c6e926e2-8224-46ef-b4ca-fc22610e7ace" width="360" alt="图一：15.4.1"></a> | <a href="https://github.com/user-attachments/assets/4bfed7a2-70c3-4240-bb8e-4360c5244d8a"><img src="https://github.com/user-attachments/assets/4bfed7a2-70c3-4240-bb8e-4360c5244d8a" width="360" alt="图二：16.2"></a> |


------

图三，为 IOS 15.4.1 [非`WebKit`内核浏览器](https://github.com/minh-ton/reynard-browser)（巨魔安装的）展示正常，以及iOS27系统使用Safari浏览器展示正常就不放截图了

<img width="1280" height="2769" alt="Image" src="https://github.com/user-attachments/assets/e54a5794-fcb7-47fa-9f18-44d4ef02f126" />


同时我本地开发 `pnpm run docs:dev` 在 `iOS15.4.1 Safari浏览器` 展示也是正常显示的..

<img width="1284" height="2778" alt="Image" src="https://github.com/user-attachments/assets/f0420f70-aa99-48e9-8c21-06808332f2ae" />
