### ISSUE TITLE
[Bug]  tasklist 前面的 ✅ 无法在 Firefox 中显示

### ISSUE THREAD

**Issue by ben-yip** [vuepress-theme-hope/vuepress-theme-hope#3259]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

从规范来看，`<input>` 实际上并不支持 `::before` 和 `::after`。Chrome 支持应该只是一个 bug。在 Firefox 中就无效。因此在 Firefox 中并不能显示用伪元素构造的 ✅。要不换个方式实现一下？

**Comment by Mister-Hope** [comment]
I've searched these, but none of them have any description:

- https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements
- https://www.w3.org/TR/CSS22/selector.html#pseudo-element-selectors
- https://www.w3.org/TR/CSS22/generate.html
- https://html.spec.whatwg.org/multipage/input.html#the-input-element

I only agree pseudo-elements that can not be used on replaced elements, and ONLY `input[type=image]` is one of them.

Here is detail about it: https://developer.mozilla.org/en-US/docs/Web/CSS/Replaced_element

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/e663aa0d-d8ac-4d8e-bd66-e903c8e8a1bd)

Where DID you find and spec about `input[type=checkbox]` can not have `::before` and `::after`?

**Comment by ben-yip** [comment]
Put aside those specs, the task-list syntax in md-enhance plugin is just not rendered as expected in Firefox.

https://theme-hope.vuejs.press/guide/markdown/tasklist.html#demo

Firefox:
<img width="300" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11989595/8af1d5f9-9ee0-44c3-9cc0-8ffaa77b8c1e">

Chrome:
![chrome](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11989595/840d1bf7-7d4c-4bd1-8ee9-ad64fb2afaa5)

**Comment by Mister-Hope** [comment]
Please look carefully In your screen shot the marker is rendered as expected just with thewrong size

**Comment by Mister-Hope** [comment]
We just need to figure out why firefox choose to render the ::before element in the checkbox itself.  This should be a bug with firefox and I personally refuse to give any fixes for a browser bug.  But discussion about why this issue is happening is welcome in this thread

**Comment by Mister-Hope** [comment]
Does this issue still exist in latest firefox?

**Comment by ben-yip** [comment]
> Does this issue still exist in latest firefox?

Not fixed yet.

Still, latest Firefox(119.0) is not rendering `:before` and `:after` of `<input>`s. While checkbox type input now shows a tick by browser user agent default, which greyed out as disabled(see screenshot below), not that overlying customized ✅ with accent color by the theme.

![Snipaste_2023-11-01_13-44-20](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/11989595/0af66320-9d31-4864-a6d9-a934e7cf5cc5)

**Comment by Mister-Hope** [comment]
The workaround should at least showing a correct result, firefox does not allow to customize checkbox colors through css

**Comment by Mister-Hope** [comment]
Close as we have a valid work around while firefox doesn'thave any plan to fix this.
