### ISSUE TITLE
[Bug] 升级到 2.0.0-beta.228 版本后，pwa2 插件的更新提示弹窗无效

### ISSUE THREAD

**Issue by fanlins** [vuepress-theme-hope/vuepress-theme-hope#3280]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

版本从：
"vuepress": "^2.0.0-beta.51",
"vuepress-theme-hope": "2.0.0-beta.104"
升级到：
"vuepress": "^2.0.0-beta.63",
"vuepress-theme-hope": "2.0.0-beta.228"
后，vuepress-plugin-pwa2 插件无法在右下角弹出更新新内容按钮。pwa 使用的是默认配置，看文档默认的 update 是 "available"，这样有新的内容发布应该会有就绪弹窗提示，但是升级后没有；在升级前同样的配置是有就绪弹窗提示的。

**Comment by Mister-Hope** [comment]
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/81614aae-3fd7-47e5-bf13-e92e7f8d040f)
