### ISSUE TITLE
打包

### ISSUE THREAD

**Issue by xiao-2** [vuepress-theme-hope/vuepress-theme-hope#3287]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/59162043/8899680d-3132-4ee5-bc97-2645ef189291)

**Comment by Mister-Hope** [comment]
Use vue3.3 and ensure onlyba single version is in your project

**Comment by xiao-2** [comment]
thank you
