### ISSUE TITLE
[Bug] Hydration mismatch after reloading page

### ISSUE THREAD

**Issue by moonkey124** [vuepress-theme-hope/vuepress-theme-hope#3301]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Hello Mr. Hope,

First I want to thank you for the amazing theme you put together - it has been of great help so far.
Unfortunately, I encountered an error that I simply cannot fix. I have created a test repository for it and also a test site to comprehend as to what I mean.

Repository: https://github.com/moonkey124/testsite
Website: https://moonkey124.github.io/testsite/

**Steps to reproduce:**

- Open the website and jump to a topic like https://moonkey124.github.io/testsite/support/test.html

- Now simply reload the page with F5 and you can see it doesn’t look like before.

**Result:**
The sidebar is completely gone. The TOCs are in the middle of the page overlapping the content.
If you check the console a Hydration mismatch is displayed.

This bug only happens in the Build version and not in the DEV version.

I tried every thing I could imagine. I have some components that I load in for the Homepage that I wrapped into "ClientOnly". I googled a lot. I read the FAQs. I simply couldn’t find a solution. The only thing I notice is, that when I try to load any site except for the homepage, for a very small time the 404 page shows up and subsequently the mismatched content. I assume that somehow this leads to the hydration mismatch but can’t figure out a way to fix it. I found this topic which kinda explains it a little: https://github.com/vuejs/vuepress/issues/1382

Where did I make a mistake? What can be done to fix this? Or is this maybe a rare bug?

Thank you so much already for your help!

Best regards moonkey124

**Comment by Mister-Hope** [comment]
Sorry but I am really busy these days, I may check out your issue at weekend. If you don't see any activity till next monday, notify me again in this issue in case I forget it!

**Comment by Mister-Hope** [comment]
Waste my 15 minutes, This is a SILLY question, and I believed you can find this thing out yourself if you are trying to provide a REAL minimal reproduction instead of providing me your whole repo.

GitHub pages is case-sensitive, which means when you have `A.html`, `/a.html` will be 404 while `/A.html` is working fine.

Your folder is named

# Support

, while the link is 

# support


Very unhappy with my time wasting and a big repo which is definitely not a minimal reproducion
