### ISSUE TITLE
[HELP] duplicate ID v-b5c0c864

### ISSUE THREAD

**Issue by orefalo** [vuepress-theme-hope/vuepress-theme-hope#3308]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

I a using Search Pro plugin, any idea how to troubleshoot this error?

'duplicate ID v-b5c0c864' -
  would be great to see the file/content creating the issue...

### Additional context

not much

**Comment by Mister-Hope** [comment]
v-b5c0c864 is the page key, and you should provide the content of original markdown file.

**Comment by orefalo** [comment]
Right.. there are 200 pages in my site, how do i find matching page?   The error triggers when i start vuepress-hope on my own site
i found the index.js in the searchpro folder but no reference to the id

**Comment by orefalo** [comment]
The  project  is open [source

](https://github.com/orefalo/murex-docs/1)

**Comment by orefalo** [comment]
complete error message

```
⠴ Initializing and preparing dataerror error in hook onPrepared from vuepress-plugin-search-pro
✖ Initializing and preparing data - failed in 809ms
Error: SlimSearch: duplicate ID v-b5c0c864
    at T (file:///Users/orefalo/GitRepositories/murex-docs/node_modules/.pnpm/slimsearch@1.0.0/node_modules/slimsearch/dist/index.mjs:1:8042)
    at L (file:///Users/orefalo/GitRepositories/murex-docs/node_modules/.pnpm/slimsearch@1.0.0/node_modules/slimsearch/dist/index.mjs:1:8388)
    at file:///Users/orefalo/GitRepositories/murex-docs/node_modules/.pnpm/slimsearch@1.0.0/node_modules/slimsearch/dist/index.mjs:1:8625
    at async file:///Users/orefalo/GitRepositories/murex-docs/node_modules/.pnpm/vuepress-plugin-search-pro@2.0.0-beta.233_vuepress@2.0.0-beta.66/node_modules/vuepress-plugin-search-pro/lib/node/index.js:2:2496
    at async Promise.all (index 0)
```

**Comment by Mister-Hope** [comment]
I don't have much time to debug this, it could be great if you can try to create a minimal reproduction by removing half of the pages and rerun to locale the issue, and limit it to a single markdown file.

Likely the file is special with heading doms (h1-h6), empty heading with no text, heading with customized id or anything similar. We should handle most of the edge cases while your issue may be another one.

**Comment by Mister-Hope** [comment]
For page id, they should be based on page content, and you should be able to find it in `.temp/internal/pageComponents.js` and locale the page it represents.

**Comment by orefalo** [comment]
so in pageComponents.js I have indeed, two entries for the same id...
What would lead to this situation?

```
 // path: /commands/
  "v-b5c0c864": defineAsyncComponent(() => import(/* webpackChunkName: "v-b5c0c864" */"/Users/orefalo/GitRepositories/murex-docs/docs/.vuepress/.temp/pages/commands/index.html.vue")),

  // path: /commands/
  "v-b5c0c864": defineAsyncComponent(() => import(/* webpackChunkName: "v-b5c0c864" */"/Users/orefalo/GitRepositories/murex-docs/docs/.vuepress/.temp/pages/commands/index.html.vue")),
```

**Comment by orefalo** [comment]
ok I found the problem... @#$@#$@#$#@

In my folder I have

```
folder/
index.md
README.md
```

why is this not properly indexed?

**Comment by Mister-Hope** [comment]
README.md is converted to index.html, as this is the default homepage in markdown, so you should avoid using them both.
