### ISSUE TITLE
[Bug] 安卓平板安装pwa应用打开会强制竖屏

### ISSUE THREAD

**Issue by Trrrrw** [vuepress-theme-hope/vuepress-theme-hope#3311]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

在平板上将网页作为pwa应用安装后打开，只能竖屏。包括[pwa2插件的官网](https://plugin-pwa2.vuejs.press/zh/)
测试了小米平板5和Samsung tab s8，Ipad貌似没问题。

**Comment by Mister-Hope** [comment]
没人阻止你自己配吧？

**Comment by Trrrrw** [comment]
> 没人阻止你自己配吧？

抱歉，打扰了
