### ISSUE TITLE
手机电脑显示问题[Bug]

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#3314]
### Checklist

- [x] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

手机电脑显示问题：[https://bornforthis.cn/Memoirs.html](https://bornforthis.cn/Memoirs.html)

<img width="2240" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/48122016/d86395d0-7d5d-4bf3-93bf-27906a5935e4">
<img width="2240" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/48122016/9a56dcbd-c49a-43ce-ab0e-85b6fdf3cf62">

手机录视频了，发在群里了。「视频太大所以这里上传不了」

**Comment by AndersonHJB** [comment]
补充链接：https://bornforthis.cn/column/StableDiffusion/01.html

**Comment by Mister-Hope** [comment]
I can not reproduce one chrome 115, is there any error in console?

**Comment by AndersonHJB** [comment]
浏览器没有任何的报错、本地命令行也是。

**Comment by northword** [comment]
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/44738481/e4c9895d-3b03-453b-9994-15fd3d3446df)

edge 115.0.1901.183 (正式版本) (64 位) 复现

控制台报错
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/44738481/2ee94e0d-090e-415e-a3eb-67a7b4f71e8c)

**Comment by AndersonHJB** [comment]
> ![图像](https://user-images.githubusercontent.com/44738481/256504649-e4c9895d-3b03-453b-9994-15fd3d3446df.png)
> 
> edge 115.0.1901.183 (正式版本) (64位) 复现
> 
> 控制台报错 ![图像](https://user-images.githubusercontent.com/44738481/256505531-2ee94e0d-090e-415e-a3eb-67a7b4f71e8c.png)

确实，我测试了一下你的方法：
<img width="2240" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/48122016/d60250a6-ab2a-4414-92f7-bde755cfa01d">

**Comment by northword** [comment]
下滑到页面底部才出现的

不过我自己的站点没有出现这个问题，这个站点在火狐上也没有问题

**Comment by AndersonHJB** [comment]
确实，报错得滑到底部才能出现

**Comment by AndersonHJB** [comment]
右上角的搜索，也不太正常😂

**Comment by AndersonHJB** [comment]
<img width="2240" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/48122016/a9d1f193-4666-47d1-b40b-5b09643544de">

貌似挺多页面都有这个问题😂：https://bornforthis.cn/column/py/Lab/Lab01.html 滑到底部也有

**Comment by AndersonHJB** [comment]
侧边栏也无法展开😂
- https://bornforthis.cn/column/py/Lab/Lab01.html
<img width="2560" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/48122016/38eea921-fdfa-4fa9-ad90-093c15aa3825">

**Comment by AndersonHJB** [comment]
我准备回退到版本 231 试一试，这个版本现在基本访问都出问题，我先回退部署试一试，如果解决。大佬要研究解决这个 bug 的话，我再更新到最新版，供大佬研究。

**Comment by AndersonHJB** [comment]
旧版本并没有解决，我准备把图片的 banner 图片去掉试一试

**Comment by AndersonHJB** [comment]
很不幸，问题依然存在emmmm help

**Comment by AndersonHJB** [comment]
在测试是不是服务器问题，把网站部署到另一个 GitHub 仓库进行测试折腾中，出现如下警告：
<img width="2560" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/48122016/48fc9aec-b168-4b3a-af95-b3013f963b91">

你说会不会是相关包依赖的问题？

**Comment by rmdocs** [comment]
**此issue的主要问题已经得到解决**，主要问题产生的前提及原因有以下几点：
1.本Vuepress文档部署于阿里云服务器，网站域名及机房均属于阿里云所有
2.网站部署过程中使用ECS服务及阿里云全站加速，其主要产生的可能的原因是因为阿里云的全站CDN更新后动静态缓存，range回源以及CDN自带的html页面压缩功能与编译生成的网站内容不兼容的原因造成的，导致网站缓存与用户设备部分缓存产生冲突。
结果就产生了以正常编译的html布局 index.html进行加载，却显示出了错误的网页布局的现象
阿里云全站CDN会与正常的vuepress部分插件或功能产生不兼容情况，如遇此情况请调整全站CDN的缓存、回源配置以及压缩配置，即可得到解决。
**感谢帮助**

**Comment by AndersonHJB** [comment]
> **此问题的主要问题已经得到解决**，主要问题产生的前提及原因有以下几点： 1.本Vuepress文档部署于阿里云服务器，网站域名及机房均属于阿里云所有 2.网站部署流程中使用ECS服务及阿里云全站加速，其主要产生的可能原因是因为阿里云的全站CDN更新后动静态缓存，范围回源以及CDN自带的html页面压缩功能与编译生成的网站内容不兼容的原因造成的，导致网站服务器与用户设备部分服务器产生冲突。 结果就产生了正常编译的html布局index.html进行加载，却显示产生错误的网页布局的现象 阿里云全站CDN会与正常的vuepress部分插件或功能产生不兼容的情况，如遇此情况请调整全站CDN的缓存、回源配置以及压缩配置，即可得到解决。感谢 **帮助**

感谢提供帮助
