### ISSUE TITLE
[Feature Request] AutoCategory 组件添加一个新配置项，用于隐藏“目录”

### ISSUE THREAD

**Issue by zfben** [vuepress-theme-hope/vuepress-theme-hope#3333]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

有时候只需要插入目录的内容，并不需要展示“目录”字样。比如已经写了标题，下面再有个目录两字就很难看。

### Additional context

如果可以添加这个功能的话，我可以提交一个合并请求来实现这个功能。

**Comment by Mister-Hope** [comment]
LGTM

**Comment by Mister-Hope** [comment]
Any progress on this one? Besides if you want to globally set this, achieve it with css could be simple.

**Comment by zfben** [comment]
> Any progress on this one? Besides if you want to globally set this, achieve it with css could be simple.

I plan to do it in this weekend. And I also want to imporve some style too.

**Comment by zfben** [comment]
Closed with https://github.com/vuepress-theme-hope/vuepress-theme-hope/pull/3367
