### ISSUE TITLE
[Feature Request] Identify preprocessor commands for `#pragma region` when including a C/C++ file

### ISSUE THREAD

**Issue by kaikaibenkai** [vuepress-theme-hope/vuepress-theme-hope#3334]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

(This issue is about [Including Files](https://theme-hope.vuejs.press/guide/markdown/include.html#heading-2))

C++ now uses `#pragma region` and `#pragma endregion` to split code regions.

You can see it in VSCode:
![20230805004107_rec_](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/99722991/90468064-8843-423d-9ca3-6bb33c2302cb)

### Additional context

https://learn.microsoft.com/en-us/cpp/preprocessor/region-endregion

**Comment by Mister-Hope** [comment]
Thanks for the detailed information, but you are posting in wrong repo, please close it and open a nwe one at https://github.com/mdit-plugins/mdit-plugins

**Comment by kaikaibenkai** [comment]
I'm sorry, link https://github.com/mdit-plugins/mdit-plugins/issues/30

**Comment by kaikaibenkai** [comment]
Oh, I see it's solved. It's just a documentation problem.
https://github.com/mdit-plugins/mdit-plugins/blob/58a7f6c3594c1695d9462a177c5c4e1a85efe650/packages/include/src/plugin.ts#L35C4

**Comment by Mister-Hope** [comment]
PR welcome

**Comment by Mister-Hope** [comment]
Besides, the upstream docs could be updated as well

**Comment by kaikaibenkai** [comment]
By the way, I fixed the display of # in the tab name via the PR, which is very misleading😢
