### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by partyabu** [vuepress-theme-hope/vuepress-theme-hope#3343]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

事务原子性是undo 日志保证的；持久性性是redo日志保证的；一致性是原子性、持久性、隔离性共同保证的
![08320504](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/96345331/6a59220c-98f1-4be0-b8b7-dad77cbd3ae7)

**Comment by partyabu** [comment]
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/96345331/82e695a9-3444-4611-9768-aa0a22882ebd)

**Comment by Mister-Hope** [comment]
？
