### ISSUE TITLE
[Bug] Share 分享组件无法展示

### ISSUE THREAD

**Issue by 1226085293** [vuepress-theme-hope/vuepress-theme-hope#3352]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

1. 安装了 vuepress-plugin-components
2. 在 markdown 中使用 `<Share services="qq" />` 无法展示图标
配置如下
```
componentsPlugin({
			componentOptions: {
				share: {
					services: [
						{
							name: "qq",
							shape: `<svg t="1691496331330" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="1644" width="200" height="200"><path d="M824.8 613.2c-16-51.4-34.4-94.6-62.7-165.3C766.5 262.2 689.3 112 511.5 112 331.7 112 256.2 265.2 261 447.9c-28.4 70.8-46.7 113.7-62.7 165.3-34 109.5-23 154.8-14.6 155.8 18 2.2 70.1-82.4 70.1-82.4 0 49 25.2 112.9 79.8 159-26.4 8.1-85.7 29.9-71.6 53.8 11.4 19.3 196.2 12.3 249.5 6.3 53.3 6 238.1 13 249.5-6.3 14.1-23.8-45.3-45.7-71.6-53.8 54.6-46.2 79.8-110.1 79.8-159 0 0 52.1 84.6 70.1 82.4 8.5-1.1 19.5-46.4-14.5-155.8z" p-id="1645"></path></svg>`,
							link: "http://baidu.com",
						},
					],
					contentSelector: ".theme-hope-content",
				},
			},
		}),
```

### Additional context

node 版本：v19.1.0
windows 版本：Windows 11 专业版（22H2）
chrome 版本：113.0.5672.93（正式版本） （64 位）

示例工程
[my-docs.zip](https://github.com/vuepress-theme-hope/vuepress-theme-hope/files/12292724/my-docs.zip)

**Comment by Mister-Hope** [comment]
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/e9fd6b69-187d-4142-8338-5b544671dbbb)
?

**Comment by Mister-Hope** [comment]
Give me a stackblitz reproduction

**Comment by 1226085293** [comment]
找到原因了，我没有添加配置 `components: ['Share']`，让 share 组件没有启用，我的错
