### ISSUE TITLE
[Bug] 夜间模式下导航栏的图标没有变色

### ISSUE THREAD

**Issue by SherkeyXD** [vuepress-theme-hope/vuepress-theme-hope#3353]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

在选择夜间模式的情况下，导航栏中的图标没有切换颜色

<img width="278" alt="91adca862cf817c74832b2bf24262044" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/57581480/226e08e0-6229-4ece-9b03-9f4087317e31">

**Comment by SherkeyXD** [comment]
注意到edge的夜间模式图标有问题而火狐的没有
<img width="966" alt="d9d7c04b8583747483df33c130c6101e" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/57581480/329ab78d-8d4b-4396-8b03-54da123ca195">

**Comment by Mister-Hope** [comment]
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/9df329a9-07f0-4f7e-bfae-21ad560fb646)

**Comment by Mister-Hope** [comment]
建议先试试无痕浏览，以避免是你扩展的问题赖主题。

**Comment by SherkeyXD** [comment]
确定是插件的问题
