### ISSUE TITLE
[Question] iPhone render issue

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#3354]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/48122016/37930cd1-3d1b-4a4f-9694-34d7bd2f95c9

其它页面也是

- [https://bornforthis.cn/column/ChatGPT-Midjourney/public/01.html](https://bornforthis.cn/column/ChatGPT-Midjourney/public/01.html)

**Comment by AndersonHJB** [comment]
本地开发 dev 测试后发现，不仅仅是苹果浏览器出问题，iPhone 安装的 Chrome 显示也会出现问题。（多刷新几次）电脑貌似没有问题

**Comment by Mister-Hope** [comment]
iOS 的 Chrome 也用的 Safari 内核，没有设备 debug 不了 Safari，看起来和 https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/3257 很可能是一个问题

**Comment by Mister-Hope** [comment]
在 #3257 追踪

**Comment by AndersonHJB** [comment]
好吧
