### ISSUE TITLE
支持element plus的暗黑主题

### ISSUE THREAD

**Issue by bongxin** [vuepress-theme-hope/vuepress-theme-hope#3355]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

目前我使用vuepress默认主题时，按照element plus官方的暗黑模式配置方案，是可行的。但是切换到hope主题后，暗黑模式就失效了。

https://element-plus.org/zh-CN/guide/dark-mode.html

**Comment by Mister-Hope** [comment]
你可以自行修改暗黑模式开关。

**Comment by Mister-Hope** [comment]
Similar things can be done with the following easily:

```ts
import { useDarkMode } from '@vuepress/helper/client' // install it first!

// in setup functions:
const darkMode = useDarkMode();

onMounted(() => {
  watch(darkMode, (value) => {
    if (value) document.docuementElement.classList.add('dark')
    else document.docuementElement.classList.remove('dark')
  }, { immediate: true })
})
```
