### ISSUE TITLE
[Bug] cannot cancle excerpt generation

### ISSUE THREAD

**Issue by lxl66566** [vuepress-theme-hope/vuepress-theme-hope#3356]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

I was going to cancle the excerpt generation, but the following config in `plugins.blog` cannot do that:
1. `excerpt: false`
2. `excerptLength: 0`
3. `excerptFilter: (_) => false`

They will generate excerpt with about 180 characters.

I can only use `excerptLength: 1` to make it possible to cancle excerpt generation. And I don't know if it has side effects.
Is this design a bug or is it intentional?

### Additional context

[example](https://lxl66566.github.io/test) with `excerpt: false`; [theme.ts](https://github.com/lxl66566/test/blob/b7ee175fdbc243b9cd45cc488d95585811945f81/src/.vuepress/theme.ts#L36)
[example](https://lxl66566.github.io/) with `excerptLength: 1`; [theme.ts](https://github.com/lxl66566/lxl66566.github.io/blob/632056948f23e0de9b9f883607266b6ac8eda57f/src/.vuepress/theme.ts#L41)

**Comment by Mister-Hope** [comment]
Everything is working as expected, when you set `excerpt: false` in `plugin.blog`, the blog plugin does not generate excerpt for you anymore.

However for better SEO consideration, `vuepress-plugin-seo2` automatically generate description text for every pages, and that's a fallback content for article items in theme.

**Comment by lxl66566** [comment]
> Everything is working as expected, when you set `excerpt: false` in `plugin.blog`, the blog plugin does not generate excerpt for you anymore.

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/88281489/56477f5d-e0d0-431f-bac6-c6a2d793fe1d)

I think that is unexpected excerpt in the minimum example.
> [example](https://lxl66566.github.io/test) with `excerpt: false`; [theme.ts](https://github.com/lxl66566/test/blob/b7ee175fdbc243b9cd45cc488d95585811945f81/src/.vuepress/theme.ts#L36)

and it has not been fixed yet.
