### ISSUE TITLE
[Bug]hope主题的暗黑模式跟element plus的不兼容

### ISSUE THREAD

**Issue by bongxin** [vuepress-theme-hope/vuepress-theme-hope#3370]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

在使用vuepress2引入element plus，并设置暗黑模式时发现以下问题：
1. 如果使用vuepress2默认主题，element plus的暗黑模式生效的
2. 如果使用hope主题，element plus的暗黑模式就失效的

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/17400550/d684e575-c60b-4b4f-b388-94b335bade8e)
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/17400550/1c818610-33f7-4ec3-9d4b-9c3f7440ebbd)

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/3355
