### ISSUE TITLE
[Feature Request] customize echarts

### ISSUE THREAD

**Issue by Paper-Dragon** [vuepress-theme-hope/vuepress-theme-hope#3372]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

## echarts的建议
希望能够出一个 echarts-wordcloud 的插件生成词云。我现在是使用在后端生成图片前端markdown获取。
希望能够直接以markdown 增强插件的形式直接前端动态生成词云。
现在在markdown增强里面只加载了echats.js的js文件，并没有扩展js，希望这个js能够扩展

可能用到的资料：
-  https://www.npmjs.com/package/echarts
- https://www.npmjs.com/package/echarts-wordcloud

## 希望增加的功能
- 类似于iframe ，在markdown里嵌入一个网页的markdown增强插件

### Additional context

如果有机会，请作者喝咖啡咖啡😚！！

期待能够得到作者回复。

**Comment by Mister-Hope** [comment]
I think it's possible to achieve it with current features, I will try to make a demo for you later.

**Comment by Mister-Hope** [comment]
I encountered a problem and I am leaving a msg here: https://github.com/ecomfe/echarts-wordcloud/issues/161#issuecomment-1685167306

The main problem is that if you want to apply plugins to echarts instance, then you will have to access it.

Some new hooks could be added but I am doubting those are actually needed

**Comment by Mister-Hope** [comment]
> 类似于iframe ，在markdown里嵌入一个网页的markdown增强插件

For the iframe part, plz diy, as we do not have any markdown runtime at client.

**Comment by arthurfsy2** [comment]
我希望可以新增关于echarts的geojson的功能，用来展示地图。
预期用途：在写关于旅游类型的博客文章时，使用地图标出去过的地方将是一件有趣的事情。
但是这个新功能工作量不知道会不会很大。

**Comment by Mister-Hope** [comment]
我已经完成了一个pr，但它并没有向我预期那样工作，希望有用过词云的人找找毛病，为啥没报错但是不显示
