### ISSUE TITLE
[Feature Request] Add a limit on the maximum length of a copy

### ISSUE THREAD

**Issue by yige-yigeren** [vuepress-theme-hope/vuepress-theme-hope#3388]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

As the title suggests, I don't want to ban copying content altogether, allowing shorter content to be copied, and banning it only in longer cases (example: ban long copying of >=200 characters)

**Comment by Mister-Hope** [comment]
Sounds reasonable, but are there any special needs that you MUST choose to allow copy/disallow copy between a threshold, rather than:

- append copyright/as is between the same threshold
- disallow copy always

Any API change proposal? Too many complicated options may fit your needs, but it could also confuse newcomers.

**Comment by yige-yigeren** [comment]
> Sounds reasonable, but are there any special needs that you MUST choose to allow copy/disallow copy between a threshold, rather than:
> 
> 
> 
> - append copyright/as is between the same threshold
> 
> - disallow copy always
> 
> 
> 
> Any API change proposal? Too many complicated options may fit your needs, but it could also confuse newcomers.

I'm just trying to control the copying of large pieces, people may sometimes need a small amount of copying such as copying code, large pieces of copying is often plagiarism

Perhaps an additional trigger parameter is sufficient, like the one that triggers the copyright suffix, which prevents copying operations beyond this number, and its default value is preferably 0 to avoid problems with others and novices

**Comment by Mister-Hope** [comment]
You didnot catch my point, there is already an option called maxLength, so how can we add a new one without confusing exisiting users?

**Comment by yige-yigeren** [comment]
new parameter "maxCopyLength"? and default is 0 avoid other user have problem
