### ISSUE TITLE
[Bug]UI显示bug：使用全局组件后，文章内容重复出现两次并出现排版错误

### ISSUE THREAD

**Issue by heStudio-Network** [vuepress-theme-hope/vuepress-theme-hope#3390]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

使用全局组件后，文章内容重复出现两次并出现排版错误。

如果从上级页面进入，则不会出现这种情况。如果刷新或者直接输入网址进入，则会出现这种问题。

问题链接： https://www.hestudio.net/docs/
代码仓库： https://gitlab.com/heStudio/blog-source

![unknown_2023 08 22-12 29](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/119711513/1a13c548-0031-45ff-b014-dc19f0343734)

### Additional context

问题复现浏览器版本： Microsoft Edge 版本 115.0.1901.203 (正式版本) (64 位)
系统版本： Microsoft Windows [版本 10.0.18363.1556]

组件NormalPage代码：

```vue
<template>
    <HopeNormalPage>
        <template #contentBefore>
            <p align="center"><Share colorful /></p>
        </template>
    </HopeNormalPage>
</template>
<script setup lang="ts">
import HopeNormalPage from "vuepress-theme-hope/components/NormalPage.js";
</script>
```

**Comment by Mister-Hope** [comment]
I can not reproduce it.
