### ISSUE TITLE
[Feature Request] Support Customized URL Protocol

### ISSUE THREAD

**Issue by Masterain98** [vuepress-theme-hope/vuepress-theme-hope#3395]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

Currently, the program supports the two most common protocol URLs `HTTP` and `HTTPS`, and if it is not declared, the program will consider the link as a relative path.

However, if the customized URL protocol is declared (`://`), the program will ignore it and still convert it into a relative path. For example, `ms-windows-store://pdp/?ProductId=9PH4NXJ2JN52` will be converted into `http://hostname/ms-windows-store://pdp/?ProductId=9PH4NXJ2JN52`, instead of asking the computer to load this customized URL protocol link.

Is that possible to differentiate relative path and URL protocol links?

**Comment by Masterain98** [comment]
Issue demo: 
Commit: https://github.com/DGP-Studio/Snap.Hutao.Docs/pull/46/commits/1043e56f1f52e4dd4754f41e0dcb780a25b3da13
Preview: https://deploy-preview-46--snap-hutao-docs.netlify.app/zh/

**Comment by Mister-Hope** [comment]
The links are in markdown right?

If so send an issue upstream at vuepress/vuepress-next

**Comment by Mister-Hope** [comment]
This is a bug and it also appears upstream, you shall open a same issue at vuepress/vuepress-next.

Currently, we only support tel, mail and http links.
