### ISSUE TITLE
[Feature Request] Replit 优化

### ISSUE THREAD

**Issue by ShiYiZhiHanZhuZhuYa** [vuepress-theme-hope/vuepress-theme-hope#3406]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

当前版本的 Replit 组件会把所有的组件一块加载，很容易造成 409 导致加载过慢

可否提供懒加载选项呢？

**Comment by Mister-Hope** [comment]
The code pen has a click2run feature, and you can write a similar feature on Replit.

This feature is contribution welcome, and I may not support this myself.
