### ISSUE TITLE
[Bug] Cannot find package '@internal/pagesData' imported from...

### ISSUE THREAD

**Issue by listenzz** [vuepress-theme-hope/vuepress-theme-hope#3411]
### Checklist

- [x] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-plugin-comment2

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

<img width="998" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/4386370/e776df32-4155-4b34-a65a-5d97f076e479">

运行项目附带的 demo, 执行 `yarn demo:vite-build` 即可重现此问题。

[comment2.zip](https://github.com/vuepress-theme-hope/vuepress-theme-hope/files/12461389/comment2.zip)

**Comment by listenzz** [comment]
I've tried several versions of node but nothing works, it's probably not node related.

**Comment by Mister-Hope** [comment]
The problem is probably related to yarn, are you using yarn classic?

pnpm@v7+ npm@8 and yarn@v2+ should work.

**Comment by listenzz** [comment]
pnpm@v8 is work, npm@9 not work

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/4386370/ce0674db-92a9-4320-a117-0895dec28889)

**Comment by listenzz** [comment]
Something wrong with yarn2.

<img width="991" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/4386370/504ef968-0a81-4149-b8aa-728d5547f669">

**Comment by Mister-Hope** [comment]
Seems to be the same problem as https://github.com/vuepress/vuepress-next/issues/1283

Yarn 2 should be another one, if you can not get it run with yarn berry, open an issue at vuepress/vuepress-next
