### ISSUE TITLE
[Bug] Wrong Rendering of Next Line

### ISSUE THREAD

**Issue by Masterain98** [vuepress-theme-hope/vuepress-theme-hope#3412]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

When writing markdown, it's common to use a new line to continue writing in the same paragraph, without starting a new paragraph, starting a new paragraph requires an additional empty line. This helps the writer to read the content in the editor's view. 

This feature can be achieved in current `vuepress-next` and older versions of `vuepress-theme-hope`, but not the live version of `vuepress-theme-hope`.

For example:
```markdown
this should be 
in the same paragraph
```

```markdown
this should be 

in the different paragraph
```

The following online demo also shows the issue: 
https://stackblitz.com/edit/vuepress-theme-hope-dsm5wj?file=docs%2Fzh%2Fdemo%2Fmarkdown.md

In pure vuepress-next demo, there is no issue:
https://stackblitz.com/edit/vuepress-hijwrs?file=docs%2Fguide%2FREADME.md

### Additional context

In the theme document, only two space or `\` will be considered as next line

https://theme-hope.vuejs.press/cookbook/markdown/demo.html#line-break

**Comment by Mister-Hope** [comment]
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/8efe051a-25e1-4e46-9e94-9f0451cf8675)

Abc
Abc

```md
Abc
Abc
```
