### ISSUE TITLE
无法复制页面数据[Bug]

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#3415]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

已经在页面设置 false：
<img width="536" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/48122016/93fd3698-4ed9-4ce8-a16a-452dc3bc53b6">

但是无法进行页面数据复制。

**Comment by AndersonHJB** [comment]
最新版，在 Typora 修改文章数据后，并没有之前版本自动浏览器本地刷新加载的功能，需要手动刷新。才可以显示最新修改的数据

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/c4020953415dea6b600b927f5b0c6cef27a09d4b

**Comment by Mister-Hope** [comment]
> 最新版，在 Typora 修改文章数据后，并没有之前版本自动浏览器本地刷新加载的功能，需要手动刷新。才可以显示最新修改的数据

HMR problem should be opened in another issue, with a valid reproduction

**Comment by Snailclimb** [comment]
> ### Checklist
> * [x]  I am using **LTS** version of Node.js.
> * [x]  I am using the **latest v2 version** of VuePress and VuePress official plugins.
> * [x]  I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
> * [x]  I followed the docs and I double checked my configuration.
> * [x]  I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.
> 
> ### Package name
> vuepress-theme-hope
> 
> ### Which operating system are you using?
> * [x]  macOS
> * [ ]  Windows
> * [ ]  Linux
> 
> ### Describe the bug
> 已经在页面设置 false： <img alt="image" width="536" src="https://user-images.githubusercontent.com/48122016/264537975-93fd3698-4ed9-4ce8-a16a-452dc3bc53b6.png">
> 
> 但是无法进行页面数据复制。
> 
> ### Additional context
> _No response_

你把 global:true 这个移除就好了。


<img width="765" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/29880145/90f13315-a5b9-44df-bb5d-a6a795dc2f44">
