### ISSUE TITLE
[Bug]代码块缩进样式

### ISSUE THREAD

**Issue by cunyu1943** [vuepress-theme-hope/vuepress-theme-hope#3428]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

<img width="1329" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/22308895/1817bdf3-fdde-40a0-b6ff-5f8a406f2a84">

**Comment by Mister-Hope** [comment]
I see you just close this issue, so what's the problem? Tab/Space issue?
