### ISSUE TITLE
[Feature Request] 多语言下支持不同的字体设置

### ISSUE THREAD

**Issue by SherkeyXD** [vuepress-theme-hope/vuepress-theme-hope#3434]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

不同语言使用相同的字体可能会出现一些问题，比如当使用了中文字体时，日文内容可能会变得很难阅读MaaAssistantArknights/MaaAssistantArknights#6228
（事实上这个项目的文档没有进行过字体相关的设置，使用的是默认字体）

### Additional context

也许可以放到 .vuepress/config.ts 的 locales 下面进行设置？

**Comment by Mister-Hope** [comment]
<img width="701" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/62d53448-6c2e-4e83-8f09-6c84ee723f68">
<img width="813" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/1c3f1346-ae2e-4961-b0f9-46beb7786de1">

Is it really hard for all of you to write something like:

```css
:root {
