### ISSUE TITLE
[Bug]index.scss里修改某个样式，添加背景图，写的相对路径，结果运行图片没有加载，因为没有被打包

### ISSUE THREAD

**Issue by superermiao** [vuepress-theme-hope/vuepress-theme-hope#3436]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/24588825/1f6fd2ef-7e66-4fc6-a480-b142722ee3c4)
代码如上，运行起来如下图：
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/24588825/f81613db-0964-48ac-9a2a-9f16ed6dad18)

### Additional context

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/24588825/daddc131-5243-4387-905e-826aec231632)
使用得是最新版本得vuepress-theme-hope

**Comment by Mister-Hope** [comment]
we output relative path as is
