### ISSUE TITLE
[Feature Request] 将 Markmap 思维导图内置到 Markdown 增强

### ISSUE THREAD

**Issue by sun0225SUN** [vuepress-theme-hope/vuepress-theme-hope#3445]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

主题目前可以以外部引入的方式内嵌 [MarkMap](https://markmap.js.org/) 生成的思维导图，能否将其做成插件或者内置到主题里，这样使用起来更加方便。

npm 里面有几个包做过该需求，但我试了下，目前都不能用了。

https://www.npmjs.com/package/vuepress-plugin-markmap
https://www.npmjs.com/package/vuepress-plugin-mindmap

**Comment by Mister-Hope** [comment]
#3004

**Comment by Mister-Hope** [comment]
Markmap will be supported in next version.
