### ISSUE TITLE
[Bug]MdEnhance自定义容器与选项卡嵌套时出现错误

### ISSUE THREAD

**Issue by wozsun** [vuepress-theme-hope/vuepress-theme-hope#3462]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [X] Windows
- [X] Linux

### Describe the bug

当在自定义容器/选项卡中嵌套自定义容器时，`:::`配对出现错误，像是共用了一个`:::`，具体如图：
<img width="550" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/80951424/eff3895d-88fe-49df-88c6-bdd686e83538">
<img width="474" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/80951424/8a6d6e58-1f59-4b25-bfb4-410f78856ece">

<img width="683" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/80951424/906d18ea-d0e5-43df-9764-1607d8aabd40">
<img width="476" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/80951424/4b0a7d56-8d73-43ff-8a11-d3b978fbca43">

**Comment by Mister-Hope** [comment]
https://mdit-plugins.github.io/zh/container.html#%E6%A0%BC%E5%BC%8F

**Comment by wozsun** [comment]
> https://mdit-plugins.github.io/zh/container.html#%E6%A0%BC%E5%BC%8F

了解了，谢谢
