### ISSUE TITLE
[Feature Request] can vuepress-theme-hope support markmap?

### ISSUE THREAD

**Issue by abelit** [vuepress-theme-hope/vuepress-theme-hope#3463]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

Markmap is a mindmap package which can  visualize your Markdown as mindmaps.
It is beautiful!

I hope vuepress-theme-hope can support markmap and the makdown language gramma like this:
```
```markmap
# Fruit

## Red

- [Apple](https://en.wikipedia.org/wiki/Apple)
- *Cherry*

## Yellow

- **Lemon**
- Banana
- ~~Pumpkin~~

```

This is markmap github repository:
https://github.com/markmap/markmap.git

This is markmap used in vuepress:
https://snyk.io/advisor/npm-package/vuepress-plugin-markmap

**Comment by Mister-Hope** [comment]
>  I searched existing issues and no one else requests similar feature. 

👎

https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/3004

**Comment by Mister-Hope** [comment]
Oh, the original issues seems to be Chinese, I apology for that.

Markmap has a heavy runtime, and I am pretty not interested in bundling it, instead I even have progress to split features with heavy runtime to be a standalone plugin again as users are reporting the installation are slow.

**Comment by Mister-Hope** [comment]
Markmap will be supported in next version.
