### ISSUE TITLE
[Bug] 文章划到最底部，页底挡住了侧边栏

### ISSUE THREAD

**Issue by imnxg** [vuepress-theme-hope/vuepress-theme-hope#3464]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

在浏览[https://theme-hope.vuejs.press/zh/guide/markdown/others.html#v-pre](https://theme-hope.vuejs.press/zh/guide/markdown/others.html#v-pre) 时，出现
下图问题：
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/73350203/735f2f25-c097-468e-bdfd-1c45cd75966f)

**Comment by Mister-Hope** [comment]
Unable to reproduce 
<img width="1279" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/6621c466-0214-481a-b55b-9741336c831a">

**Comment by imnxg** [comment]
难道我谷歌浏览器问题？
