### ISSUE TITLE
[Bug]在vue组件中使用FontIcon加载不出图标

### ISSUE THREAD

**Issue by GuanErShuiShou** [vuepress-theme-hope/vuepress-theme-hope#3479]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

在vue组件中直接使用`<FontIcon icon="mark" color="red" />`,icon未能正确渲染，渲染效果如下
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/34082148/d5ff9931-08be-4f0d-aaa7-5e6e60bfaa66)

**Comment by Mister-Hope** [comment]
![Screenshot_2023-09-29-17-33-44-42_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/7e2df0bf-faf6-42c0-8c53-19219313b875)
fontaesome does not.have any icon named mark

**Comment by GuanErShuiShou** [comment]
> ![Screenshot_2023-09-29-17-33-44-42_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/33315834/271530987-7e2df0bf-faf6-42c0-8c53-19219313b875.jpg) fontaesome does not.have any icon named mark

看着文档中支持的图标是有“mark”，是我打开的方式不对吗
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/34082148/82a42f3d-7d32-4362-adfe-586069f3bb45)

**Comment by Mister-Hope** [comment]
that's iconfont
