### ISSUE TITLE
[Bug] PWA Refresh button returns to dark mode instead of the configured light mode.

### ISSUE THREAD

**Issue by fdevans** [vuepress-theme-hope/vuepress-theme-hope#3488]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [x] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

Key Site Setup basics:

- Client MacOS / Chrome Browser which is using 'dark' mode.
- Vuepress Hope Theme Color forced to 'light'
- PWA setup configured for 'hint'.

This all works as expected until clicking the refresh content button.  When that it clicked the site is returned in dark mode instead of the forced light mode.

### Additional context

I will work on and see if I can make a minimum viable reproduction to show the behavior and post back if I can.   It's hard to replicate as the site has to update in order to test it.

**Comment by Mister-Hope** [comment]
The refresh are using force refresh, and you should mock this by ctrl + F5

**Comment by fdevans** [comment]
We ended up just allowing Dark Mode.  I'll still see if I can replicate it though.

**Comment by fdevans** [comment]
I can close it for now.  I won't have time in next few days.

**Comment by Mister-Hope** [comment]
It's ok to leave it here if you do think there are issues, just keep the thread active, and provide some details later if you can.
