### ISSUE TITLE
[Bug]目录页面设置为home时加密失效

### ISSUE THREAD

**Issue by wozsun** [vuepress-theme-hope/vuepress-theme-hope#3502]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

一般情况设置目录加密有效：
<img width="1153" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/80951424/39d17d9e-5b60-42f9-b38f-6d11e80585ff">

但如果我把此目录页面设置为主页格式时，此页面的加密失效：
<img width="1436" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/80951424/60945f42-fe7b-41d8-bf57-d79bad12bdc6">

另外有个小提议，可否同时加密侧边栏？

**Comment by Mister-Hope** [comment]
只有普通界面可以被局部加密。

主页和侧边栏需使用全局加密
