### ISSUE TITLE
[Bug] Cannot find package '@internal/pagesData' imported from

### ISSUE THREAD

**Issue by joseaquino5** [vuepress-theme-hope/vuepress-theme-hope#3534]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-plugin-photo-swipe and vuepress-plugin-redirect

### Which operating system are you using?

- [ ] macOS
- [x] Windows
- [ ] Linux

### Describe the bug

I got error with vuepress-plugin-photo-swipe and vuepress-plugin-redirect but vuepress-plugin-sitemap2  works great 

I am receiving this error when build command, when developing locally everything seems to be ok

```
:heavy_check_mark: Compiling with vite - done in 16.91s
:heavy_multiplication_x: Rendering 1178 pages - failed in 48ms
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@internal/pagesData' imported from
```

This is my package.json:

```
{
  "name": "help",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "directories": {
    "doc": "docs"
  },
  "scripts": {
    "docs:dev": "vuepress dev docs",
    "docs:build": "vuepress build docs"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@vuepress/plugin-active-header-links": "^2.0.0-beta.67",
    "@vuepress/plugin-search": "^2.0.0-beta.67",
    "vuepress": "^2.0.0-beta.67",
    "vuepress-plugin-photo-swipe": "^2.0.0-beta.238",
    "vuepress-plugin-redirect": "^2.0.0-beta.238",
    "vuepress-plugin-sitemap2": "^2.0.0-beta.238"
  }
}
```

My node version is 19.19.0

**Comment by joseaquino5** [comment]
> see vp2 sticky issue

Hey man, can you offer a link of what you're pointing me. I really didn't get you.

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/vuepress-next/issues/1195

**Comment by joseaquino5** [comment]
> [vuepress/vuepress-next#1195](https://github.com/vuepress/vuepress-next/issues/1195)

I tried it, but it continues failing:

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/17714907/7cf740b7-deb6-486f-b424-cf5ca6903201)

**Comment by Mister-Hope** [comment]
Give me a reproduction first

**Comment by Mister-Hope** [comment]
Which package manger are you using?

**Comment by joseaquino5** [comment]
> Which package manger are you using?

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/17714907/6de22552-74f0-4127-b5bd-ad83b22d2404)

**Comment by joseaquino5** [comment]
I minimized the project to just contains 2 readme files and the configuration I am using, to reproduce it, you just need to have the node and npm version I describe above. 

[Reproduction project](https://github.com/vuepress-theme-hope/vuepress-theme-hope/files/12859925/repro.zip)

**Comment by Mister-Hope** [comment]
Yeah, another pm issue, I will check that later, everything should be ok with pnpm, you can use that as a workaround first

**Comment by joseaquino5** [comment]
I tested it, looks great, thank you!
