### ISSUE TITLE
[Bug] Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'katex' 

### ISSUE THREAD

**Issue by ffblanch** [vuepress-theme-hope/vuepress-theme-hope#3571]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Since this morning I have this error with a fresh installation. 
`Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'katex'  `

**Comment by vordimous** [comment]
I am also getting this error after updating.

version changes:

```
devDependencies:
- @vuepress/client 2.0.0-beta.66
+ @vuepress/client 2.0.0-beta.67
- @vuepress/plugin-docsearch 2.0.0-beta.66
+ @vuepress/plugin-docsearch 2.0.0-beta.67
- @vuepress/plugin-google-analytics 2.0.0-beta.66
+ @vuepress/plugin-google-analytics 2.0.0-beta.67
- vue 3.3.4
+ vue 3.3.7
- vuepress 2.0.0-beta.66
+ vuepress 2.0.0-beta.67
- vuepress-theme-hope 2.0.0-beta.235
+ vuepress-theme-hope 2.0.0-beta.239

Done in 11.2s
 WARN  4 deprecated subdependencies found: formidable@1.2.6, rollup-plugin-terser@7.0.2, sourcemap-codec@1.4.8, superagent@3.8.3
```

**Comment by emersers** [comment]
iI also encountered this problem during my first installation

**Comment by emersers** [comment]
> iI also encountered this problem during my first installation

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'katex' imported from I:\project\emsrsdoc\node_modules\.pnpm\@mdit+plugin-katex@0.5.0_markdown-it@13.0.2\node_modules\@mdit\plugin-katex\lib\index.mjs
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:890:9)
    at moduleResolve (node:internal/modules/esm/resolve:939:20)
    at defaultResolve (node:internal/modules/esm/resolve:1132:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by Ackerven** [comment]
After I upgraded to `2.0.0-bate.239`, I got the same error when executing `pnpm docs:build`.

Error output:
```shell
> vth-notebook@2.0.0 docs:build /xxx
> vuepress build src

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'katex' imported from /xxx/node_modules/.pnpm/@mdit+plugin-katex@0.5.0_markdown-it@13.0.2/node_modules/@mdit/plugin-katex/lib/index.mjs
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:890:9)
    at moduleResolve (node:internal/modules/esm/resolve:939:20)
    at defaultResolve (node:internal/modules/esm/resolve:1132:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)
 ELIFECYCLE  Command failed with exit code 1.
```

Node version:
```shell
$ node -v
v18.18.2
```

**Comment by zhumengyua** [comment]
我也遇到到这个问题 
node v16.16.0

**Comment by alomerry** [comment]
>https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/fd302ef9336ffd87a579e2907243716994857510

需要 pnpm add 缺失的 module

**Comment by zhumengyua** [comment]
> > [fd302ef](https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/fd302ef9336ffd87a579e2907243716994857510)
> 
> 需要 pnpm add 缺失的 module
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/32129847/3fa7b351-2883-461f-b955-ec67e5692bad)
在add2个提示的东西后运行还是会错。这个是我刚下来的项目

**Comment by alomerry** [comment]
> > > [fd302ef](https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/fd302ef9336ffd87a579e2907243716994857510)
> > 
> > 
> > 需要 pnpm add 缺失的 module
> > ![image](https://user-images.githubusercontent.com/32129847/278256307-3fa7b351-2883-461f-b955-ec67e5692bad.png)
> > 在add2个提示的东西后运行还是会错。这个是我刚下来的项目

可以参考一下

```json
"dependencies": {
    "@vue/repl": "^2.5.8",
    "@vuepress/client": "2.0.0-beta.67",
    "@vuepress/plugin-container": "2.0.0-beta.67",
    "@vuepress/shared": "2.0.0-beta.67",
    "@vuepress/utils": "2.0.0-beta.67",
    "flowchart.ts": "^1.0.1",
    "js-yaml": "4.1.0",
    "katex": "^0.16.9",
    "markdown-it": "13.0.1",
    "mathjax-full": "^3.2.2",
    "mermaid": "^10.6.0",
    "reveal.js": "^4.6.1",
    "sass-loader": "13.3.0",
    "vue": "^3.3.7",
    "vue-router": "^4.2.5",
    "vuepress": "2.0.0-beta.67",
    "vuepress-plugin-components": "2.0.0-beta.239",
    "vuepress-plugin-md-enhance": "2.0.0-beta.239",
    "vuepress-plugin-search-pro": "2.0.0-beta.239",
    "vuepress-shared": "2.0.0-beta.239",
    "vuepress-theme-hope": "2.0.0-beta.239"
  }
```

**Comment by zhumengyua** [comment]
> > > > [fd302ef](https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/fd302ef9336ffd87a579e2907243716994857510)
> > > 
> > > 
> > > 需要 pnpm add 缺失的 module
> > > ![image](https://user-images.githubusercontent.com/32129847/278256307-3fa7b351-2883-461f-b955-ec67e5692bad.png)
> > > 在add2个提示的东西后运行还是会错。这个是我刚下来的项目
> 
> 可以参考一下
> 
> ```json
> "dependencies": {
>     ...
>     "@vue/repl": "^2.5.8",
>     "flowchart.ts": "^1.0.1",
>     "js-yaml": "4.1.0",
>     "katex": "^0.16.9",
>     "markdown-it": "13.0.1",
>     "mathjax-full": "^3.2.2",
>     "mermaid": "^10.6.0",
>     "reveal.js": "^4.6.1",
>     "sass-loader": "13.3.0",
>     "vue": "^3.3.7",
>     "vue-router": "^4.2.5",
>     "vuepress": "2.0.0-beta.67",
>     ...
>   }
> ```

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/32129847/e2b4227c-2b79-4202-bda2-342773bb7737)
虽然可以跑起来。但是跑起来还是会报错。。。我重新再下一次项目试试blog能不能跑起来好了。。

**Comment by emersers** [comment]
> iI also encountered this problem during my first start

I've rolled back to vuepress-theme-hope 2.0.0-beta.238  and it is running normally

**Comment by zhumengyua** [comment]
> > iI also encountered this problem during my first start
> 
> I've rolled back to vuepress-theme-hope 2.0.0-beta.238 and it is running normally

thank you, but  i abandoned it. TAT

**Comment by Mister-Hope** [comment]
Closed with https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/a179011c2edb3e0e331c61cd40fb500f54987d3c

**Comment by ffblanch** [comment]
Thank you !!  @Mister-Hope   🥇
