### ISSUE TITLE
[Bug] 使用 waline 无法评论，显示 403

### ISSUE THREAD

**Issue by mengguyi** [vuepress-theme-hope/vuepress-theme-hope#3573]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [X] Linux

### Describe the bug

我通过 [docker 方式](https://waline.js.org/guide/deploy/vps.html#%E4%BD%BF%E7%94%A8-docker-stack-deploy-%E6%88%96%E8%80%85-docker-compose)部署了 waline
在测试评论时点击 提交 页面出现 Forbidden，waline 输出如下
```
waline  | [2023-10-25T18:56:52.918] [17] [WARN] - [Deprecated] /comment API will be deprecated in the next major version, please don't use it anymore. If you are using `@waline/client` please upgrade to `@waline/client@3`. For other scenarios, you can use `/api/comment` to replace it.
waline  | ForbiddenError: Forbidden
waline  |     at Object.throw (/app/node_modules/koa/lib/context.js:97:11)
waline  |     at module.exports.__before (/app/node_modules/@waline/vercel/src/logic/base.js:41:30)
waline  |     at /app/node_modules/think-logic/index.js:33:42
waline  |     at dispatch (/app/node_modules/koa-compose/index.js:42:32)
waline  |     at /app/node_modules/think-router-rest/index.js:31:12
waline  |     at dispatch (/app/node_modules/koa-compose/index.js:42:32)
waline  |     at Router.parseRule (/app/node_modules/think-router/router.js:266:17)
waline  |     at Router.run (/app/node_modules/think-router/router.js:291:19)
waline  |     at router (/app/node_modules/think-router/index.js:107:21)
waline  |     at dispatch (/app/node_modules/koa-compose/index.js:42:32)
```
提示升级 @waline/client 但我已经将 vuepress-theme-hope 和 VuePress 升级为最新
这是我的 package.json
```
{
  "name": "mengguyi-blog",
  "version": "1.0.0",
  "description": "MengGuyi's Blog",
  "license": "CC BY-SA 4.0",
  "type": "module",
  "scripts": {
    "docs:build": "vuepress build src",
    "docs:clean-dev": "vuepress dev src --clean-cache",
    "docs:dev": "vuepress dev src",
    "docs:update-package": "pnpm dlx vp-update"
  },
  "devDependencies": {
    "@vuepress/client": "2.0.0-beta.63",
    "vue": "^3.3.7",
    "vuepress": "2.0.0-beta.63",
    "vuepress-theme-hope": "2.0.0-beta.227"
  }
}
```
另外，在查看 pnpm-lock.yaml 时发现了这个
<img width="723" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/73788063/d2835025-d78e-4d7d-9311-5cb1b22918c5">

<img width="1280" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/73788063/810ea8ab-75a9-4267-b9c3-8e6cd6b2d73a">
<img width="1280" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/73788063/e6296fd0-5693-42f8-bf98-411e529127d8">

**Comment by Mister-Hope** [comment]
if you are receiving a 403 status code, then it's not a vth issue
