### ISSUE TITLE
[Bug] 使用Artalk评论，网页点击下一页，或者点击右边侧边栏切换文章，无法显示评论区域

### ISSUE THREAD

**Issue by itwxe** [vuepress-theme-hope/vuepress-theme-hope#3592]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

使用Artalk评论，网页点击下一页，或者点击右边侧边栏切换文章，无法显示Artalk评论区域，但是页面刷新后显示
在线地址：https://itwxe.com
存储库位置：https://github.com/itwxe/blog

**Comment by Mister-Hope** [comment]
rc1有解决这个问题么

**Comment by itwxe** [comment]
> rc1已经解决这个问题了吗

没有，rc1这个问题仍然存在

**Comment by liub1934** [comment]
rc4该问题还存在

**Comment by Mister-Hope** [comment]
我是一直坚持Artalk 有问题的。建议要求作者在他自己的文档里能够通过引入包的形式使用 Artalk。

如果他那边可以，那我这边就可以。

**Comment by liub1934** [comment]
> 我是一直坚持Artalk 有问题的。我的核心观点是旧的Artalk.init不能正确的销毁，会对新的Artalk.init有奇怪的影响。
> 
> 建议要求作者在他自己的文档里能够通过引入包的形式使用 Artalk。
> 
> 如果他那边可以，那我这边就可以。他现在用的是cdn的方法，每次切换页面必然重新加载一遍artalk

我看了他的官网vue示例是支持包引入的：https://artalk.js.org/guide/frontend/import-framework.html#vue

**Comment by Mister-Hope** [comment]
他是那么说的，我跟他已经有一次没有结果的讨论了。

> 我是一直坚持Artalk 有问题的。我的核心观点是旧的Artalk.init不能正确的销毁，会对新的Artalk.init有奇怪的影响。
>
> 建议要求作者在他自己的文档里能够通过引入包的形式使用 Artalk。

他自己文档就是用 CDN 引入的，每次切换页面重新加载脚本：

https://github.com/ArtalkJS/Artalk/blob/master/docs/.vitepress/theme/Artalk.vue

我不想跟任何人犟，只要任何人能提供一个在 Vue SSG 兼容项目中通过 import Artalk 使用的案例，并且这个案例能够随着页面正确更新，我马上照着案例修。

事实上，Artalk 那个包就是有问题的。

**Comment by Mister-Hope** [comment]
就包括开issue的 @itwxe 提供的那个奇怪的据他说可以正常工作 PR，我克隆下来该报错一样报错，只是被 try catch 块捕获不输出了而已。

**Comment by qwqcode** [comment]
> > 我看了他的官网vue示例是支持包引入的：https://artalk.js.org/guide/frontend/import-framework.html#vue
> 
> 他是那么说的，我跟他已经有一次没有结果的讨论了。**我从来就没有在 vue 项目里成功的在执行过 Artalk.init 的情况下，在执行页面导航后第二次成功初始化 Artalk 而不报错。**
> 
> > 我是一直坚持Artalk 有问题的。我的核心观点是旧的Artalk.init不能正确的销毁，会对新的Artalk.init有奇怪的影响。
> > 建议要求作者在他自己的文档里能够通过引入包的形式使用 Artalk。
> 
> 他自己文档就是用 CDN 引入的，每次切换页面重新加载脚本：
> 
> https://github.com/ArtalkJS/Artalk/blob/master/docs/.vitepress/theme/Artalk.vue
> 
> 我不想跟任何人进行这种没有营养的讨论，只要任何人能提供一个在 Vue SSG 兼容项目中通过 import Artalk 使用的案例，并且这个案例能够随着页面正确更新，我马上照着案例修。
> 
> **我坚持认为** Artalk 那个包就是有问题的。实际上我好奇过**为什么作者在 Artalk 使用 VitePress 建文档时候，不使用仓库内编译好的 Artalk 包，而非得要用 script 引入 CDN**，我强烈怀疑他自己也跑不起来就用了 script 脚本堆这了。

 什么叫没结果？旧的方式是通过 new 来创建 Artalk 实例，新版已经修改成了 API。

https://artalk.js.org/develop/fe-api.html

既然你一直坚持认为 Artalk 有问题的，如果 Artalk 可能存在不足，欢迎 PR，而不是发一个无厘头的 issue，谢谢

https://github.com/ArtalkJS/Artalk/pull/426

https://github.com/ArtalkJS/Artalk/issues/373

**Comment by qwqcode** [comment]
> **我坚持认为** Artalk 那个包就是有问题的。实际上我好奇过**为什么作者在 Artalk 使用 VitePress 建文档时候，不使用仓库内编译好的 Artalk 包，而非得要用 script 引入 CDN**，我强烈怀疑他自己也跑不起来就用了 script 脚本堆这了。

你的怀疑毫无根据。

在 Artalk 使用 VitePress 建文档时候，用 script 引入脚本是为了方便测试最新版本的构建代码，并且与后端程序版本保持匹配。

为了证明你犯的错误，我已修改为 NPM 包引入，并未发现问题：

https://github.com/ArtalkJS/Artalk/commit/f8c33003a88fdb01e163c650c7b469b8d343d66c

请检查你是的实现是否正确，并测试一下，谢谢！

**Comment by qwqcode** [comment]
https://github.com/ArtalkJS/Artalk/issues/658#issuecomment-1857820902

> 你好，之前和您进行讨论已在 #426 #373 等 PR、issues 进行积极应对和修复，感谢您的反馈与建议！
> 
> 但这并不是像你所说的：
> 
> > ”我跟他已经有一次没有结果的讨论了。“
> 
> 之后没有收到你的其他反馈，并且我这边已测试无问题，则视为问题已经修复。
> 
> VitePress 的案例目前已经修改为了 NPM 包引入，
> 
> 而并不是像您所说的：
> 
> > ”我坚持认为 Artalk 那个包就是有问题的。实际上我好奇过为什么作者在 Artalk 使用 VitePress 建文档时候，不使用仓库内编译好的 Artalk 包，而非得要用 script 引入 CDN，我强烈怀疑他自己也跑不起来就用了 script 脚本堆这了。“
> 
> 您可以参考以下代码：
> 
> https://github.com/ArtalkJS/Artalk/blob/f8c33003a88fdb01e163c650c7b469b8d343d66c/docs/.vitepress/theme/Artalk.vue
> 
> 再次感谢您的反馈！
> 
> 我知道您是 VuePress core team member and a senior Vue coder，感谢您对开源社区的贡献！
> 
> 但根据你的描述，我暂时无法确定是什么问题，欢迎进一步的讨论。
> 
> Hello,
> 
> Thank you for the proactive handling and fixes on PRs and issues such as #426 and #373, following our previous discussions. Your feedback and suggestions are greatly appreciated.
> 
> However, it's not as you mentioned: "I had one discussion with him that led nowhere."
> 
> After that, I didn't receive further feedback from you, and after testing on my end, I confirmed there were no issues, so I considered the problem fixed.
> 
> The use case for VitePress has now been modified to include the NPM package.
> 
> Contrary to what you mentioned: "I still believe that the Artalk package has issues. I'm actually curious why the author, while documenting Artalk using VitePress, didn't utilize the precompiled Artalk package in the repository and instead chose to use script tags to import CDN. I strongly suspect that they couldn't get it running themselves, so they resorted to piling script tags."
> 
> You can refer to the following code: https://github.com/ArtalkJS/Artalk/blob/f8c33003a88fdb01e163c650c7b469b8d343d66c/docs/.vitepress/theme/Artalk.vue
> 
> Thank you once again for your feedback!
> 
> I understand that you're a VuePress core team member and a senior Vue coder. Thank you for your contributions to the open-source community!
> 
> However, based on your description, I'm temporarily unable to determine the exact issue. I welcome further discussion.

**Comment by Mister-Hope** [comment]
Artalk 作者补的组件有幸却可以自己使用，但他写的组件从代码上看没有任何的销毁逻辑，所以重复挂载/移除该组件必然是会内存泄露的（e.g.: 用 v-if 控制它的切换并且用 setInterval 定时改变)

鉴于 artalk 作者拒绝解释 destroy 的作用，也并没有实质性回答问题，而我也没空看代码找实际的问题，并我个人认为 artalk 设计上就存在问题，下个版本将移除 artalk，有兴趣可以自行开发插件实现。

**Comment by Mister-Hope** [comment]
你没有回复的事情很多，比如：

1. 如何创建并保留多个artalk 实例 （应对同页面多个评论区或者 Vue `<keep-alive>` 的情况)
2. 在 artalk 初始化的过程中，由于切换页面导致元素被移除会导致异常
3. `import Artalk from 'artalk'` 并多次使用的问题

等我忙完毕业论文我会一个一个 issue 提过去。我不认为一个可以用原生 js 开发一个评论客户端的人，听不懂我在 issue 里在说什么。举个例子：

> artalk 设计上没有考虑过多实例问题么？如果我的确涉及到用 [keep-alive](https://cn.vuejs.org/guide/built-ins/keep-alive.html) 来缓存多个组件实例，而这些组件实例上有不同的 artalk 实例，我该怎么办？

没有关系，等我闲下来我给你提一打 reproduction。
