### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by HuberTRoy** [vuepress-theme-hope/vuepress-theme-hope#3604]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [X] Windows
- [X] Linux

### Describe the bug

https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/4df6e344f7c3651f46b9097e47fbc096a53244dd/packages/theme/templates/index.build.html#L15

The template on prod hardcode the background. 

The configuration background on `palette.scss` not working fully.

**Comment by Mister-Hope** [comment]
Have you ever test that? Normally, body is on html and sharing the same size, so the bgcolor will be applied correctly.

**Comment by HuberTRoy** [comment]
@Mister-Hope Sorry for waste your time. 

Please see https://github.com/subquery/documentation, check out on 0f9042f4f5a1941df508814a09281e0aa2cd90bc.

Build and serve it. 

The config is darkmode only and have configaration with 
```
$bg-color: (
  light: #060f32,
  dark: #060f32,
);
```

![微信截图_20231107200101](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/10172415/a1ca8989-4121-4154-8cfc-e47507c37da1)

![微信截图_20231107200110](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/10172415/4df931dd-ff55-4549-a5cb-c34b351804d8)

I don't find relative changes on the new version change log. If it has been change.

**Comment by HuberTRoy** [comment]
The key I think is only compile `palette.scss` as `:root` and the hardcode is 
```
      html[data-theme="dark"] {
        --bg-color: #1d1e1f;
      }

      html,
      body {
        background: var(--bg-color);
      }
```
The priority of `html[data-theme="dark"]` greater than `:root`, so `var(--bg-color)` is hardcode not custom.

**Comment by Mister-Hope** [comment]
Hi like I said above, the final color displayed should be body’s bgcolor

**Comment by Mister-Hope** [comment]
I am not sure,  as you are already applying a patch. 

Just take our theme docs as an example:

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/242d50bf-d4c8-4480-af5d-5ab01e2ab081)

The body background color comes from css file:

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/73a2a065-ed2f-4523-9a36-31541d9be905)

While the color defined in template is already overrided:

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/23026bd0-e611-4e43-a017-b725a6a138e9)

Create a new template and try modifying `$bg-color`, everthing should work as expected.

I am curious why you need an `!important`
