### ISSUE TITLE
[Bug]Error: ../../package.json: ENOENT: no such file or directory, open '../../package.json'

### ISSUE THREAD

**Issue by Ackerven** [vuepress-theme-hope/vuepress-theme-hope#3632]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

It appears when I execute `pnpm docs:build`.

```
> vuepress-theme-hope-template@2.0.0 docs:build /home/wojak/notebook/tmp/minirepo
> vuepress build src

Error: ../../package.json: ENOENT: no such file or directory, open '../../package.json'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at Object.readFileSync (/home/wojak/notebook/tmp/minirepo/node_modules/.pnpm/jsonfile@6.1.0/node_modules/jsonfile/index.js:50:22)
    at file:///home/wojak/notebook/tmp/minirepo/node_modules/.pnpm/vuepress-theme-hope@2.0.0-beta.249_@types+js-yaml@4.0.9_vuepress@2.0.0-beta.68/node_modules/vuepress-theme-hope/lib/node/index.js:128:20
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
 ELIFECYCLE  Command failed with exit code 1.
```
Minimal reproducible：[theme-hope-minirepo](https://github.com/Ackerven/theme-hope-minirepo)

Node.js version: `v18.18.2`

Pnpm version: `8.9.2`

**Comment by Mister-Hope** [comment]
fixed in 250
