### ISSUE TITLE
[Bug] 首页文章列表不显示浏览量

### ISSUE THREAD

**Issue by JQiue** [vuepress-theme-hope/vuepress-theme-hope#3637]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

使用 waline 作为评论系统，首页不会发送获取 waline 数据的请求，进入文章详情正常发送请求。此外，在首页翻页时，不能保留浏览量这个状态

**Comment by Mister-Hope** [comment]
can you give a reproduction?

**Comment by JQiue** [comment]
> can you give a reproduction?

访问 https://jinqiu.wang
