### ISSUE TITLE
[Bug]使用vuepress-plugin-components会导致图标无法被正确渲染为icon class

### ISSUE THREAD

**Issue by KyokuKong** [vuepress-theme-hope/vuepress-theme-hope#3650]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

在config.ts中配置了组件库后，发现图标为没有被正确渲染的`<fonticon>`标签导致无法正确显示，经过排障确定为该插件导致

以下是我的config.ts
``` typescript
import { defineUserConfig } from "vuepress";
import { searchProPlugin } from "vuepress-plugin-search-pro";
import { componentsPlugin } from "vuepress-plugin-components";
import theme from "./theme.js";

export default defineUserConfig({
  base: "/",

  lang: "zh-CN",
  title: "Kyoku.",
  description: "暂时是kyoku的blog",

  theme,
  plugins: [
    searchProPlugin({
      // 索引全部内容
      indexContent: true,
    }),
    componentsPlugin({
      components: [
        "BiliBili"
      ]
    }),
  ],
  // Enable it with pwa
  // shouldPrefetch: false,
});
```
在加载该插件前，网页的图标被正常渲染为`<span class="font-icon icon" data-fa-i2svg="">...</span>`的格式，图标可以正常加载，且控制台没有任何报错。
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/144906395/38596275-bc32-4760-a962-c644d912533a)

加载该插件后，网站的图标均被错误的渲染为<fonticon>标签导致全部无法正常显示，控制台报错vue组件有问题。
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/144906395/e0d3ecdf-6059-4774-bf60-863f8c7fcc0e)

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/144906395/921c519e-d9cd-48c0-8232-a5bbdd41632c)

系统为Windows11，node等环境均为按照文档安装的推荐版本，多次进行重试均可复现并确定问题发生在添加如下配置之后。
```typescript
    componentsPlugin({
      components: [
      ]
    }),
  ],
```

**Comment by KyokuKong** [comment]
尝试后发现可以通过直接在componets中加入FontIcon并设置相应的assets选项进行解决。
但是我在之前并没有在组件中开启FontIcon，是否是该插件在没有配置的情况下错误的强制接管了主题自带的hopeicon功能？

**Comment by Mister-Hope** [comment]
- https://theme-hope.vuejs.press/zh/config/plugins/
- https://theme-hope.vuejs.press/zh/faq/#%E8%81%94%E7%B3%BB%E6%88%91%E4%BB%AC
- https://theme-hope.vuejs.press/zh/faq/common-error.html#you-are-not-allowed-to-use-plugin-xxx-yourself-in-vuepress-config-file
