### ISSUE TITLE
[Bug] readingTime: false,报错：找不到 '@internal/pagesData'

### ISSUE THREAD

**Issue by 006hjy** [vuepress-theme-hope/vuepress-theme-hope#3651]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

设置
plugins: {
readingTime: false,
}
dev服务器可以使用，但是build就报错：
- Initializing and preparing data
√ Initializing and preparing data - done in 101ms
- Compiling with vite
√ Compiling with vite - done in 2.36s
- Rendering 13 pages
× Rendering 13 pages - failed in 20ms
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@internal/pagesData' imported from C:\Users\xinmi\PycharmProjects\websitedoc\node_modules\@vuepress\client\dist\chunk-DHNSDB55.js
    at new NodeError (node:internal/errors:406:5)
    at packageResolve (node:internal/modules/esm/resolve:789:9)
    at moduleResolve (node:internal/modules/esm/resolve:838:20)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:228:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36)

**Comment by Mister-Hope** [comment]
Can you try to provide a stackblitz reproduction?

**Comment by 006hjy** [comment]
我在stackblitz上创建空的nodejs项目，运行npm init vuepress-theme-hope my-docs后，找不到.vuepress文件夹。不会使用stackblitz。我只能用我的windows电脑：
1. 创建一个空文件夹
2. 在空文件夹下运行npm init vuepress-theme-hope my-docs，
3. cd my-docs，查看 vuepress-theme-hope 版本号，发现是rc0
4. 运行npm run docs:update-package，再次查看版本号，更新到了rc1
5. 把theme.js中的plugins:中加入readingTime: false,
6. 运行npm run docs:build
7. 报错。
![微信截图_20231129113107](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/70318734/36c9511f-c2e0-4a88-ad40-7667561b1331)

**Comment by 006hjy** [comment]
科学上网了，所以我直接用了npm
