### ISSUE TITLE
[Feature Request] Add AI Summarize Blog Content Plugin.

### ISSUE THREAD

**Issue by LixvYang** [vuepress-theme-hope/vuepress-theme-hope#3652]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

https://documate.site/

Many times AI is needed to summarize the content, and this plugin is not sure if it can support that

**Comment by Mister-Hope** [comment]
I don't think this is my job to do this, you can open a new issue to see if the project author can support VuePress@v2, which should be very similar to VitePress.

**Comment by Mister-Hope** [comment]
Some edits are made on the above comment, reping you here in case you miss them.
