### ISSUE TITLE
[Bug] Having No Title Shows `vp-page-title` Element.

### ISSUE THREAD

**Issue by TurtleP** [vuepress-theme-hope/vuepress-theme-hope#3684]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

In the page frontmatter, if I leave out a `title`, the div `vp-page-title` still exists. This leaves a blank underline on the page and is really strange to see.

### Additional context

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/6239208/ae993944-4e89-4386-bc44-64f9c19460eb)

Here is what it looks like while working on this page in question with no title.

**Comment by Mister-Hope** [comment]
Every page should have a title

**Comment by TurtleP** [comment]
If every page should have a title, the docs should reflect that titles are not optional and adjust the theme code accordingly. This otherwise causes confusion.

**Comment by Mister-Hope** [comment]
？why it is my job to tell you basics?

Every page should have a h1, and every markdown should have a h1 too.

**Comment by TurtleP** [comment]
I'm just pointing out that [the documentation states that the title is _optional_](https://theme-hope.vuejs.press/config/frontmatter/info.html#title). You have mentioned that every page must have a title, therefore it shouldn't be optional. I'm not trying to be rude, mind you, just trying to help.

**Comment by TurtleP** [comment]
> > I'm just pointing out that [the documentation states that the title is _optional_](https://theme-hope.vuejs.press/config/frontmatter/info.html#title). You have mentioned that every page must have a title, therefore it shouldn't be optional. I'm not trying to be rude, mind you, just trying to help.
> 
> The title in frontmatter does be optional, as if you have a level 1 heading in markdown, we will generate a title from it
> 
> Does that makes confusion to you? And any ideas improving it?

Yes and when it's not set to anything, i.e. empty, `vp-page-title` still shows up with the underline decoration, but nothing within the `h1` element. For example:

```
---
title: ""
---
```

This frontmatter gives me this on the page:

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/6239208/e6466da8-ca3a-4e4e-95b4-d97d579fc549)

So now where there *should* be a title, does not appear since it makes no sense for that `vp-page-title` to show up if the title isn't set to something that isn't empty.
