### ISSUE TITLE
[Feature Request] 希望静态文件支持中文路径

### ISSUE THREAD

**Issue by WangJincheng4869** [vuepress-theme-hope/vuepress-theme-hope#3691]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

新版本不支持静态文件中文路径了，之前是支持的，当我升级到最新版本原本存在中文路径的图片无法显示了。
当文档变大，资源文件越来越多，对于我这种英文稀烂的人来说，使用中文目录和文件名更有利于维护文档，希望给予支持，谢谢。

**Comment by Mister-Hope** [comment]
Why saying static file no longer support cjk characters, any reproduction? This could be a bug.

**Comment by Mister-Hope** [comment]
Probably you need to create a minimal reproduction repo and submit it to https://github.com/vuepress/vuepress-next

**Comment by WangJincheng4869** [comment]
> Probably you need to create a minimal reproduction repo and submit it to https://github.com/vuepress/vuepress-next

不行了，我脑子已经瓦特了，用这个 [vuepress-theme-hope.github.io/v2-new](https://vuepress-theme-hope.github.io/v2-new). 是支持中文路径的，我本地的不行。怎么能开启调试啊，我想看看为啥。
