### ISSUE TITLE
Style of Hint Boxes breaks when nesting

### ISSUE THREAD

**Issue by kaikaibenkai** [vuepress-theme-hope/vuepress-theme-hope#3694]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

Style of Hint boxes on Edge (Mobile) seems wrong
![](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/99722991/b529376a-7b5e-4d26-b11c-da9465eff081)

### Additional context

UA:
```
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Mobile Safari/537.36 EdgA/118.0.2088.66
```

**Comment by Mister-Hope** [comment]
md-demo will not correctly displau any element with negative margin
