### ISSUE TITLE
[Bug] Upgrade to 2.0.0-rc.2 unmet peer @vue/repl@^3.0.0:found 2.9.0

### ISSUE THREAD

**Issue by Ly2JR** [vuepress-theme-hope/vuepress-theme-hope#3705]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Upgrade to 2.0.0-rc.2 unmet peer @vue/repl@^3.0.0:found 2.9.0
![1701743632554](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/30518282/4a87125c-4e0a-44e8-9d17-17dcd2ebe57c)

**Comment by Mister-Hope** [comment]
Does anyone prevent you install @vue/repl 3?
