### ISSUE TITLE
[Bug] AutoCatalog not working in sub dirs

### ISSUE THREAD

**Issue by Sun-ZhenXing** [vuepress-theme-hope/vuepress-theme-hope#3708]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-plugin-auto-catalog

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Using `base` or using it in a subdirectory is shown as empty.

[demo page](https://plugin-auto-catalog-demo.vuejs.press/demo.html#display-current-dir-catalog-with-index)

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/44517244/0b7360cf-45df-4335-b02c-ac01eb83830c)

**Comment by Sun-ZhenXing** [comment]
PS: [demo pages](https://plugin-auto-catalog-demo.vuejs.press/) are also empty

<img width="564" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/44517244/631c59d4-347e-4807-9d79-6f05c91db985">

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/2928a1309b62973c2e3ebf16a5c329b5199e3fba
