### ISSUE TITLE
[Feature Request] 不知可不可以根据PWA制作消息推送

### ISSUE THREAD

**Issue by gtn1024** [vuepress-theme-hope/vuepress-theme-hope#371]
[使用Notification API来进行消息提醒](https://juejin.im/post/6844903600557129735)

**Comment by Mister-Hope** [comment]
理论上是可以的。

不过vuepress是一个静态文档生成器，不要忘记这一点，消息推送需要你自己的服务器提供支持。而目前使用我主题的人大多都是通过github或者gitee等托管。你这个需求是反vuepress的设计目标的。

所以如果有兴趣你可以自己实现一个，如 [此页](https://vuepress-theme.mrhope.site/config/plugin/pwa/#generateswconfig) 所说，@mr-hope/pwa 允许你对 workbox-build 做二次配置。你也可以自己 fork 本项目，并改动 https://github.com/Mister-Hope/vuepress-theme-hope/tree/master/packages/pwa 文件夹实现你的需求。MIT 协议记得署名就随便用的，兄弟。
