### ISSUE TITLE
[Feature Request]搜索文本定义

### ISSUE THREAD

**Issue by superen7527** [vuepress-theme-hope/vuepress-theme-hope#3712]
### 1 bug

> #resultHistoryCount
> 类型: number
> 默认值: 5
> 存储搜索结果历史的最大数量，可以设置为 0 以禁用。

 **设置0无效还是5 其他值正常**

***
### 2

 **建议把** 

>    * 搜索历史文字

>   history: string;
> 

**改成 History 和 Result**

因为名字一样看起来有点乱

本来改不了没事隐藏result就好了 结果无效..稳定版更新测试版还是这样 现在不会降回去了.. QAQ

***

### 3 
**另外问问这几个是干嘛的改了没看到变化**
 

>    * 搜素中文字
>    
>   searching: string;
> 

>    * 默认标题
>   defaultTitle: string;
> 
> 

 
```[tasklist]
### Tasks
```

**Comment by Mister-Hope** [comment]
searching 是worker搜索的时候的提示，你可以在 https://innenu.com 那里能看到这个提示，通常需要十万字以上的索引才能看到明显的延迟。

defaultTitle 是当一个页面没标题的时候，默认显示的标题名字。

**Comment by Mister-Hope** [comment]
另外感谢你的 bug 反馈和建议

**Comment by Mister-Hope** [comment]
Wait for the rc3 to land
