### ISSUE TITLE
自定义面包屑

### ISSUE THREAD

**Issue by Zoe-Z1** [vuepress-theme-hope/vuepress-theme-hope#3739]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

面包屑的展示非常别扭 明明是平级目录 在面包蟹上却被变成了上下级 希望可以自定义面包屑或者控制显示隐藏面包屑
![Snipaste_2023-12-09_21-16-00](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/49554968/533dc5be-cd55-401c-bf8f-3e5ab7d7651c)

**Comment by Mister-Hope** [comment]
Breadcrumb only depends on file structure of the website.

Create a reproduction if you think there is something wrong

https://developer.mozilla.org/en-US/docs/Glossary/Breadcrumb

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/ef841309-228a-45f3-9c19-97a9ee9438da)
