### ISSUE TITLE
[Feature Request]  Remove theme transition

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress-theme-hope/vuepress-theme-hope#3747]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

 Remove theme transition

**Comment by onekiloparsec** [comment]
I still see no easy way to switch off ALL animations and transitions. Did I miss something ? The `pure` option doesn't do the job completely.

**Comment by marcgrue** [comment]
I'd like to be able to switch off transitions too. How can I do that?
