### ISSUE TITLE
[Feature Request] 能否把`@mdit/plugin-container`中的`marker`选项添加到`MdEnhance 插件`配置中

### ISSUE THREAD

**Issue by bestruirui** [vuepress-theme-hope/vuepress-theme-hope#3748]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

能否把`@mdit/plugin-container`中的`marker`选项添加到`MdEnhance 插件`配置中

### Additional context

我看到`@mdit/plugin-container`是支持修改`marker`选项的
在[@mdit/plugin-container](https://mdit-plugins.github.io/zh/container.html#%E9%80%89%E9%A1%B9)
```ts
interface MarkdownItContainerOptions {
  /**
   * 自定义容器的名称
   */
  name: string;

  /**
   * 自定义容器的标识符
   *
   * @default ":"
   */
  marker?: string;

  /**
   * 校验内容是否应该作为此类型容器
   *
   * @param params 标识符后面的内容
   * @param markup 标识字符
   * @returns 是否是此容器类型
   *
   * @default params.trim().split(" ", 2)[0] === name
   */
  validate?: (params: string, markup: string) => boolean;

  /**
   * 开始标签渲染函数
   */
  openRender?: RenderRule;

  /**
   * 结束标签渲染函数
   */
  closeRender?: RenderRule;
}

```
- 现在在用obsidian作为编辑器使用，而在obsidian中不能识别`:`符号，只能识别到`反引号`，可以通过[插件](https://github.com/LastKnightCoder/obsidian-styled-container)的方式实现`hint 提示容器`的功能，所以希望作者能把`marker`选项增加到`MdEnhance 插件`配置中     
- 自己也寻找过很久别的markdown编辑器，几乎没有支持使用冒号的提示容器的功能，且有所见即所得功能的编辑器，而obsidian是最接近的一个编辑器，所以真的很希望作者能把这个选项添加到`MdEnhance 插件`配置中

**Comment by Mister-Hope** [comment]
你自己加一下反引号版本的容器不行么
