### ISSUE TITLE
代码块有没有可能折叠？[Feature Request]

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#3755]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

<img width="2240" alt="Snipaste_2023-12-15_15-33-32" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/48122016/c1ed3911-cf69-4e69-bf0d-08cf758d75dc">

**Comment by Mister-Hope** [comment]
那 details 块是用来干什么的？

**Comment by AndersonHJB** [comment]
好的，我原本想着代码块直接支持选择是否折叠更美观😂
