### ISSUE TITLE
[Bug]设置 必应壁纸 或 一言描述 后，运行 pnpm run docs:dev 报错

### ISSUE THREAD

**Issue by BillSaul** [vuepress-theme-hope/vuepress-theme-hope#3770]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

代码都是直接复制官方文档里的示例代码，运行 `pnpm run docs:dev` 后打开网站会报错，运行 `pnpm run docs:build` 没问题。尝试重新创建了一个新项目，也有这个问题
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/47105171/5246f074-0236-4b9f-b642-09f9f1b3e7db)

**Comment by Mister-Hope** [comment]
Probably a upstream bug, maybe related to vite-plugin-vue or vite
