### ISSUE TITLE
[Bug]侧边栏布局问题

### ISSUE THREAD

**Issue by 006hjy** [vuepress-theme-hope/vuepress-theme-hope#3787]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

目前：侧边栏的底板位于网页的底部，导致页脚footer会遮挡住侧边栏的底部的一部分。侧边栏的条目数量多起来后会有影响
正确的布局应该是：侧边栏的底部位于页脚的顶部。这样较长的侧边栏滚动到底部时才能完整显示。

**Comment by 006hjy** [comment]
复现问题的方法：创建一个空页面，侧边栏加上30多条条目，加上页脚。会发现页脚遮住了侧边栏里的最后几条。

**Comment by Mister-Hope** [comment]
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/acd4ec35-cb45-468e-ac27-de185ccb04fc)

无法复现。

如果你因为在 footer中塞入了大量内容导致布局异常，需自己调整 CSS。

**Comment by 006hjy** [comment]
> ![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/acd4ec35-cb45-468e-ac27-de185ccb04fc)
> 
> 无法复现。
> 
> 如果你因为在 footer中塞入了大量内容导致布局异常，需自己调整 CSS。

是的，footer是自定义的HTML，高度较高，滑动到页面底部时，会把侧边栏底部遮挡住
