### ISSUE TITLE
[Feature Request] Can add a function to support one -click configuration summary?

### ISSUE THREAD

**Issue by Floweryu** [vuepress-theme-hope/vuepress-theme-hope#3789]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/45811382/bc7f0733-e7f8-4768-bd49-3e595574b794)
I want to hide the summary to make home page looking simple，because i think the summary is not necessary for every article.

**Comment by Mister-Hope** [comment]
Disable article summary generation / disable seo auto description

**Comment by Mister-Hope** [comment]
I think this is the same as the existing https://github.com/orgs/vuepress-theme-hope/discussions/3635.

The fix is invalid or what?

**Comment by Mister-Hope** [comment]
Any update on this? `plugins.blog.excerpt: false` not working or what?

**Comment by Floweryu** [comment]
> Any update on this? `plugins.blog.excerpt: false` not working or what?

`plugins.blog.excerpt: false` not working，The summary on the article on the homepage list is still. this is my settings
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/45811382/bad58ac5-82b0-49c9-8261-1f7654f72ee4)

**Comment by Mister-Hope** [comment]
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/7fbe5af2-7714-4d56-a716-d98ab51cc2dc)

This is working in my case that disable excerpt generation (excerpt in frontmatter or with `<!-- more -->` are still displayed.

And when setting `excerpt: false`, only excerpt in frontmatter are seen.

Provide a minimal reproduction if you have any issue.
