### ISSUE TITLE
做一个内容容器，类似于提示容器

### ISSUE THREAD

**Issue by kings1990** [vuepress-theme-hope/vuepress-theme-hope#3791]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

查看关于提示容器的文档以及VPBanner组件，目前似乎没有以下描述的组件。

想要一个跟提示容器差不多的组件。去除了提示容器种定死的图标以及左侧竖的条纹。仅仅留下主体。主体内容 中又可以  支持 markdown、html 和主题中包含的组件支持。类似格式如下

示意 demo 如下

```
::: container color=""

## 标题

描述

![图片](some url)

:::
```

类似效果

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/8969637/90039094-272b-4751-a62c-7b7765973657)

**Comment by Mister-Hope** [comment]
可以自行通过 @md-it/plugin-container 实现

**Comment by kings1990** [comment]
不是这个提示容器，这个会有图标。 颜色也不能定制，只要身体就行

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/8969637/39efbb7f-600b-426f-baec-2e04b6911af3)

**Comment by Mister-Hope** [comment]
Use this yourself https://mdit-plugins.github.io/zh/container.html
