### ISSUE TITLE
[Bug] 评论插件好像坏了 giscus 报 403

### ISSUE THREAD

**Issue by qynx** [vuepress-theme-hope/vuepress-theme-hope#3799]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

评论插件好像坏了 giscus 报 403

### Additional context

评论插件好像坏了 giscus 报 403

**Comment by Mister-Hope** [comment]
https://github.com/giscus/giscus/issues/1269

**Comment by qynx** [comment]
> [giscus/giscus#1269](https://github.com/giscus/giscus/issues/1269)

借楼 [kotlin-playgroud](https://theme-hope.vuejs.press/guide/get-started/markdown.html#kotlin-playground) 这篇教程依赖库应该是kotlin-playground 文档里面写的@vue/repl

**Comment by Mister-Hope** [comment]
> > [giscus/giscus#1269](https://github.com/giscus/giscus/issues/1269)
> 
> 借楼 [kotlin-playgroud](https://theme-hope.vuejs.press/guide/get-started/markdown.html#kotlin-playground) 这篇教程依赖库应该是kotlin-playground 文档里面写的@vue/repl

Where? Provide screenshots plz

**Comment by qynx** [comment]
> > > [giscus/giscus#1269](https://github.com/giscus/giscus/issues/1269)
> > 
> > 
> > 借楼 [kotlin-playgroud](https://theme-hope.vuejs.press/guide/get-started/markdown.html#kotlin-playground) 这篇教程依赖库应该是kotlin-playground 文档里面写的@vue/repl
> 
> Where? Provide screenshots plz
这里～ https://theme-hope.vuejs.press/guide/markdown/kotlin-playground.html
<img width="763" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/37181043/d3c805a2-f9b7-45ca-b031-52776630cc46">
