### ISSUE TITLE
[Feature Request] 将 “star” 翻译为 “星标”

### ISSUE THREAD

**Issue by Zihan-Hu** [vuepress-theme-hope/vuepress-theme-hope#3804]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

（个人认为）“收藏”一般是访问网站的用户来管理的，但主题里的收藏是网站开发者设置的。
也许“星标”或者“推荐”会好一点（？

**Comment by Mister-Hope** [comment]
pr welcome

**Comment by Zihan-Hu** [comment]
感谢您抽出时间解决这个问题 🙏
刚刚在 #3807 里同步了文档对 *star* 的翻译，望笑纳 🙏
