### ISSUE TITLE
[Feature Request] markdown 文件引入

### ISSUE THREAD

**Issue by abgox** [vuepress-theme-hope/vuepress-theme-hope#3805]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

- 在 vitepress 里有这样一个特性，可以通过一个标记 `<!--@include: ./parts/basics.md-->`，将指定的md文件直接引入到当前的md文件中
- 最终渲染时，会在引入位置把指定的md内容渲染出来。
- 如果能有这样一个特性，md文件就可以更加精细的拆分和引入，我觉得这对于文件的管理挺好的
- 不知道是否可以考虑添加这样一个特性

**Comment by Mister-Hope** [comment]
## Read, the, docs plz!👎

<img width="514" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/9ed7239f-90d0-458d-8066-78dfef335146">

- https://theme-hope.vuejs.press/guide/markdown/include.html
