### ISSUE TITLE
[Feature Request] 添加水印预设

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress-theme-hope/vuepress-theme-hope#3808]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

添加水印预设

**Comment by MouseSun846** [comment]
Hello, may I ask if you have implemented the watermark function locally? I also need to use this feature now

**Comment by Mister-Hope** [comment]
No, I currently have no time for this, PR welcome.

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/cc7dbde1e5214fb8fc93a1d34a6cae205c9bdaa0
