### ISSUE TITLE
[Bug] RSS Feed Generation Issue in Version 2.0.0-rc.11

### ISSUE THREAD

**Issue by rockbenben** [vuepress-theme-hope/vuepress-theme-hope#3847]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

I recently encountered an issue with RSS feed generation after updating to version `2.0.0-rc.11`. Initially, I was adding the following configuration in `theme.ts` to generate RSS:

```javascript
feed: {
  rss: true,
  count: 10,
},
```

However, after the update, I found that the RSS feed URL is showing a 404 error. Following the configuration guide provided at [plugin-feed2](https://plugin-feed2.vuejs.press/zh/config/), I then added the following configuration in `config.ts`:

```javascript
feedPlugin({
  hostname: "http://localhost:8080",
  rss: true,
}),
```

After this change, I encountered a new error `You are not allowed to use plugin "vuepress-plugin-feed2" yourself in vuepress config file. Set "plugin.feed" in theme options to customize it.`, and the RSS address still shows a 404 error. 

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/28252913/d8c59896-ab34-484d-8339-3e2f3a0281f8)

**Comment by Mister-Hope** [comment]
https://theme-hope.vuejs.press/rss.xml

I need reproduction

**Comment by rockbenben** [comment]
> https://theme-hope.vuejs.press/rss.xml
> 
> I need reproduction

https://stackblitz.com/github/rockbenben/LearnData

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/28252913/9de849b2-33cc-4d59-ae18-199662d3ea8f)

**Comment by dribble-njr** [comment]
same problem

**Comment by Mister-Hope** [comment]
the feed plugin no longer support devserver after it support locales.

Usually you don't need to debug feed at devServer, and it does have noticeable influence with performance

**Comment by rockbenben** [comment]
> the feed plugin no longer support devserver after it support locales.
> 
> Usually you don't need to debug feed at devServer, and it does have noticeable influence with performance

Is the explanation provided here for [feed2](https://plugin-feed2.vuejs.press/zh/) correct? After setting up RSS in the config, during the build process, it prompts: `You are not allowed to use plugin "vuepress-plugin-feed2" yourself in vuepress config file. Set "plugin.feed" in theme options to customize it.` This is confusing.

However, after the build, I did indeed obtain an rss.xml.

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/28252913/a777b4e9-de2f-40d5-aefa-fe1c73043fb9)

**Comment by dribble-njr** [comment]
However, I did't have `feed` info. 

After `pnpm build`, but I have installed `vuepress-plugin-feed2` and configured it.

<img width="540" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/72367140/bcb177d1-5275-4d27-9759-1b35ffb82a15">

In my `theme.ts` `plugins`:
 
<img width="146" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/72367140/42390716-ce9d-4550-b771-23f78ea524e5">

And I make sure my packages are up to date.

Or do I need other configurations？

**Comment by Mister-Hope** [comment]
Nope, this is a bug

**Comment by dribble-njr** [comment]
So which version should I roll back to to avoid this bug?

**Comment by rockbenben** [comment]
> So which version should I roll back to to avoid this bug?

Check `config.ts` against https://plugin-feed2.vuejs.press/

**Comment by Mister-Hope** [comment]
just a friendly.note: we add back devServer support in the next version, but this reqiures opt-in now.
