### ISSUE TITLE
[Bug] Duplicate arcticles in autocatalog (vue 3.4.15)

### ISSUE THREAD

**Issue by smirnoffmv** [vuepress-theme-hope/vuepress-theme-hope#3854]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

When upgrading to a new version of vue core (3.4.15), autocatalog started duplicating articles. When I downgrade to 3.3.9, everything becomes normal. Apparently it is a bug of the new version 3.4.15.

![image_2024_01_22T14_49_43_093Z](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/90478289/d23b45b4-bc32-4bd3-8525-a9c5c67163da)

**Comment by Mister-Hope** [comment]
You should make sure that only a single version is inside your project

**Comment by Mister-Hope** [comment]
Should be a upstream bug.
