### ISSUE TITLE
[Bug] Individual line support for @include

### ISSUE THREAD

**Issue by vordimous** [vuepress-theme-hope/vuepress-theme-hope#3855]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

Individual line support for @include doesn't work:

```js
<!-- @include: ./foo.js{1} -->
<!-- @include: ./foo.js{2-4} -->
<!-- @include: ./foo.js#part1 -->
```
renders: 

![image](https://github.com/vuepress/vuepress-next/assets/3012311/540c6b2d-5249-4752-9fc6-8d76a3c1a024)

versions:
```
    "vue": "^3.3.4",
    "vuepress": "2.0.0-beta.67",
    "vuepress-theme-hope": "2.0.0-beta.238"
```

### Additional context

_Originally posted by @vordimous in https://github.com/vuepress/core/issues/1355#issuecomment-1758134298_

**Comment by Mister-Hope** [comment]
Use the latest version and try to repro plz? https://mdit-plugins.github.io/include.html#heading-2

**Comment by vordimous** [comment]
> Use the latest version and try to repro plz? https://mdit-plugins.github.io/include.html#heading-2

confirmed with `latest` versions

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/3012311/b0392434-af5b-4065-aa0f-a121e8237e7a)

```
  "devDependencies": {
    "@vuepress/client": "2.0.0-rc.0",
    "@vuepress/plugin-docsearch": "2.0.0-rc.0",
    "@vuepress/plugin-google-analytics": "2.0.0-rc.0",
    "@vuepress/plugin-register-components": "2.0.0-rc.0",
    "@vuepress/utils": "2.0.0-rc.0",
    "mathjax-full": "^3.2.2",
    "vue": "^3.4.15",
    "vuepress": "2.0.0-rc.0",
    "vuepress-theme-hope": "2.0.0-rc.11"
  },
```

**Comment by Mister-Hope** [comment]
As our docs is working https://plugin-md-enhance.vuejs.press/guide/content/include.html#heading-2

I want you to provide a valid minimal reproduction using github repo or.stackblitz.

**Comment by vordimous** [comment]
> The `{1}` may not work, but at least `{2-4}` should work.

This is true, `{2-4}` works and `{1-1}` works. Per the description of the docs there isn't a bug.

I will update the ticket to be a feature request.

**Comment by vordimous** [comment]
feature tracked https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/3856
