### ISSUE TITLE
[Feature Request] Individual and multiple line ref support for @include

### ISSUE THREAD

**Issue by vordimous** [vuepress-theme-hope/vuepress-theme-hope#3856]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

Allow the `@include` feature to reference multiple different segments in the file, including since line segments.

Example:
````
```yaml
foo:
<!-- @include: ./foo.yaml{1} -->
bar:
<!-- @include: ./bar.yaml{2-4} -->
baz:
<!-- @include: ./baz.yaml{6, 8-10} -->
```
````

**Comment by Mister-Hope** [comment]
Emm. actually I believe this could be better using code snippets.

Again, if a file is solid, you can just copy its content to the places you want to include; if it isn't, then line numbers could probably change when you modify the content.

The `<!-- @include: xxx -->` snippet will be totally replaced, so there is no disadvantage to write:

```
<!-- @include: ./baz.yaml{6-6} -->
<!-- @include: ./baz.yaml{8-10} -->
```

And importing only a single line is definitely a rare case
