### ISSUE TITLE
[Feature Request] 外部脚本如何才能引入

### ISSUE THREAD

**Issue by aimeiyijia** [vuepress-theme-hope/vuepress-theme-hope#3871]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

请问 外部脚本如何才能引入

**Comment by Mister-Hope** [comment]
1. Issue panel is a place to report issue, while discussion panel is where you can ask questions.
2. READ the f**king docs: https://theme-hope.vuejs.press/zh/guide/customize/external.html
