### ISSUE TITLE
[Bug] Mermaid无法渲染

### ISSUE THREAD

**Issue by dynilath** [vuepress-theme-hope/vuepress-theme-hope#3874]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [X] Linux

### Describe the bug

以这样的环境
```json
  "devDependencies": {
    "@vuepress/bundler-vite": "2.0.0-rc.2",
    "mermaid": "^10.7.0",
    "reveal.js": "^5.0.4",
    "sass-loader": "^14.1.0",
    "vue": "^3.4.15",
    "vuepress": "2.0.0-rc.2",
    "vuepress-plugin-redirect": "2.0.0-rc.16",
    "vuepress-theme-hope": "2.0.0-rc.16"
  }
```
弄了个mermaid，但是这个mermaid一直在转加载（如下图）
![QQ截图20240131022008](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/3864313/37ce7e65-c4c5-4c5a-9f90-2f0f751e1a88)

打开控制台看到了这样的信息
```console
mermaid-04fb0060.js?v=9446c278:2 Uncaught (in promise) SyntaxError: The requested module '/MyDocs/@fs/H:/gitrepo/MyDocs/node_modules/.pnpm/dayjs@1.11.10/node_modules/dayjs/dayjs.min.js?v=9446c278' does not provide an export named 'default' (at mermaid-04fb0060.js?v=9446c278:2:8)
```

**Comment by s3rius** [comment]
For me switching to webpack bundler solved the problem. 

```bash
pnpm rm @vuepress/bundler-vite
pnpm add @vuepress/bundler-webpack
```

And change it in the config. 

```js
import { webpackBundler } from '@vuepress/bundler-webpack'

export default defineUserConfig({
  ...
  bundler: webpackBundler(),
  ...
 });
```

**Comment by dynilath** [comment]
Tried with webpack.
Get this on the page

```
Uncaught runtime errors:
×
ERROR
[object Event]
    at handleError (webpack-internal:///./node_modules/.pnpm/webpack-dev-server@4.15.1_webpack@5.90.0/node_modules/webpack-dev-server/client/overlay.js:252:58)
    at eval (webpack-internal:///./node_modules/.pnpm/webpack-dev-server@4.15.1_webpack@5.90.0/node_modules/webpack-dev-server/client/overlay.js:275:7)
```

dependencies now:
```json
  "devDependencies": {
    "@vuepress/bundler-vite": "2.0.0-rc.2",
    "@vuepress/bundler-webpack": "2.0.0-rc.2",
    "mermaid": "^10.7.0",
    "reveal.js": "^5.0.4",
    "sass-loader": "^14.1.0",
    "vue": "^3.4.15",
    "vuepress": "2.0.0-rc.2",
    "vuepress-plugin-redirect": "2.0.0-rc.16",
    "vuepress-theme-hope": "2.0.0-rc.16"
  }
```

**Comment by Mister-Hope** [comment]
Seems dayjs are still problematic with pnpm, the problem is that dayjs is a invalid esm package.

**Comment by Mister-Hope** [comment]
BTW, the dayjs is becomming anothe moment.js, which is outdated for the community and not receiving bug fixes in time.
