### ISSUE TITLE
[Bug] 在特定配置下重定向失效

### ISSUE THREAD

**Issue by dynilath** [vuepress-theme-hope/vuepress-theme-hope#3877]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-plugin-redirect

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

如后文所述的项目结构，在使用`vuepress dev docs`可以正常自动语言重定向，发到github pages就不能重定向了

在本地`vuepress build docs`构建之后，用`http-server -p 8080 -c-1 --cors .`建立服务也无法重定向

项目结构如下
```powershell
Mode            Length Hierarchy
----            ------ ---------
d----        204.20 KB redirect-bug
-a---          1.04 KB ├── package.json
-a---        203.13 KB ├── pnpm-lock.yaml
-a---         29.00  B ├── tree.txt
d----          0.00  B └── docs
-a---          0.00  B     ├── A.md
d----          1.42 KB     ├── zh
-a---          1.42 KB     │   └── README.md
d----         18.00  B     ├── other
-a---         18.00  B     │   └── README.md
d----        688.00  B     ├── en
-a---        688.00  B     │   └── README.md
d----          1.75 KB     └── .vuepress
-a---        818.00  B         ├── config.ts
-a---        971.00  B         ├── theme.ts
d----        557.00  B         └── locales
-a---        248.00  B             ├── en.ts
-a---         67.00  B             ├── index.ts
-a---        242.00  B             └── zh.ts
```
`config.ts`
```typescript
import { defineUserConfig } from "vuepress";
import { redirectPlugin } from "vuepress-plugin-redirect";
import { theme } from "./theme";
import viteBundler from "@vuepress/bundler-vite";

export default defineUserConfig({
    bundler: viteBundler(),
    locales: {
        '/zh/': {
            lang: 'zh-CN',
            title: '测试测试测试',
            description: '测试测试测试'
        },
        '/en/': {
            lang: 'en-US',
            title: 'Lorem ipsum dolor sit amet',
            description: 'Lorem ipsum dolor sit amet'
        }
    },
    base: '/Test/',
    dest: 'public',
    plugins: [
        redirectPlugin({
            autoLocale: true,
            defaultBehavior: "homepage",
        })
    ],
    theme
});
```

我认为和这两个
```powershell
Mode            Length Hierarchy
----            ------ ---------
d----        204.20 KB redirect-bug
d----         18.00  B     ├── other
-a---         18.00  B     │   └── README.md
-a---          0.00  B     ├── A.md
```
不在任何语言下内容的有关系，移除掉就正常了

---

另外，我尝试将`redirect_bug/A.md`重定向到`redirect_bug/zh/A.md`
我尝试写了
```markdown
---
redirectFrom: /A.md
---
```
和

```markdown
---
redirectFrom: A.md
---
```
都无法重定向

于是我尝试建立了一个`redirect_bug/A.md`  *于是产生了上面的问题*
如果这个`redirect_bug/A.md`里面写
```markdown
---
redirectTo: /zh/A.md
---
```
会重定向到`HOST_NAME/Test//zh/A.html`然后进404.html

如果写成

```markdown
---
redirectTo: zh/A.md
---
```
那么如果使用在`redirect_bug/other/A.html`，会重定向到`HOST_NAME/Test/zh/A.htmlother/zh/A.html`然后得到404.html

这一部分（横线分隔的）现象在github pages, `vuepress dev docs` 和本地建立服务都会出现

**Comment by Mister-Hope** [comment]
I believe the redirectTo issue is fixed, you are reporting multiple issues at same  time and that confused me, can you open new pr with what you do, what's expected and what happening about the rest?

**Comment by Mister-Hope** [comment]
更新:如果你使用了autoLocale，而你的项目中存在不属于任何一个语言的页面的时候，报错是预期的，因为插件根本不清楚要做什么。

**Comment by dynilath** [comment]
简单来说这是`/A.md`改成了`/zh/A.md`

但是在`/zh/A.md`写redirectFrom没有跳转，redirectTo就得需要弄一个不属于任何语言的页面。

**Comment by Mister-Hope** [comment]
我还是没太看懂你表达了什么，你关闭的那个议题，你给出的结构和你底下说的对不上。

输出构建结果的时候，插件只会根据已有的界面来生成能够自动重定向的界面，也就是说如果你想要让 /a 能实现重定向，你需要在至少一个语言下有 a.md，否则压根就不会有这个界面，应该会默认走到404的逻辑。

**Comment by Mister-Hope** [comment]
redirectForm  的底层工作原理是插件会便利所有的数据把它们集中起来并推断出原始的重定向界面，并把那些重定向界面创建出来。

autoLocate也是一样的，插件会收集所有语言中存在过的所有路径，并在根目录自动生成他们同时提供自动从定向到一个最贴近用户语言的功能。

Redirect to的工作逻辑是直接在当前界面写一个script的标签，这个script的标签会进行跳转。

**Comment by Mister-Hope** [comment]
Reirectto不工作的原因是因为我忘了去掉parhname 最开始的斜杠了,这个问题很简单，你汇报的也很清晰，但是其他的部分我都没有听懂原因在哪里。

实际上因为插件写的比较久了，我现在也不是很确定，如果说你强行要在启用了自动语言重定向的功能时，添加一些不属于任何语言的界面，会发生什么事情，我认为那些页面会员而保留，也不会被重定向，也不应该涉及到报错。如果你添加了这些界面之后，整个自动语言程序性功能都不工作了，那可能应该算是一个bug，你可以给一个最小腹泻，或者说你在action里给出一个明确的文件结构，然后给出一系列步骤，我自己去复现。

**Comment by dynilath** [comment]
制作了一个最小重现

[minrep.zip](https://github.com/vuepress-theme-hope/vuepress-theme-hope/files/14107896/minrep.zip)

需要实现的目标是访问
`http://localhost:8080/Test/A.html`
时，自动跳转到
`http://localhost:8080/Test/zh/A.html`

有`autoLocale`的时候，`config`或者`redirectFrom`都无法从base重定向

按我的理解`autoLocale:true`的时候就算没有任何其他redirect设置也应该能实现这个定向（否则哪儿来的歧义），但是得到的是404

**Comment by Mister-Hope** [comment]
> 制作了一个最小重现
> 
> [minrep.zip](https://github.com/vuepress-theme-hope/vuepress-theme-hope/files/14107896/minrep.zip)
> 
> 需要实现的目标是访问 `http://localhost:8080/Test/A.html` 时，自动跳转到 `http://localhost:8080/Test/zh/A.html`
> 
> 有`autoLocale`的时候，`config`或者`redirectFrom`都无法从base重定向
> 
> 按我的理解`autoLocale:true`的时候就算没有任何其他redirect设置也应该能实现这个定向（否则哪儿来的歧义），但是得到的是404

把你的base和路径都改成小写之后我没有看到任何问题，大写的话，似乎 vite 开发服务器会有问题，但是生成的东西是没问题的。
小写 base:

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/d02d81be-7312-4a66-92bc-c94e0313e4f5)
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/d23c8243-0f99-4c4b-bbc5-34df8a5207d9)
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/9d2d6dcb-3046-433b-b051-7d1b7ec220d7)

大写 base：

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/5f8b5f41-a787-49bc-a10b-b5ba9e0535d1)
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/3143c59b-d35c-4895-985a-a2935565e00a)

**Comment by Mister-Hope** [comment]
另一个案例测试也是正常的，你最好确定你在汇报什么

**Comment by dynilath** [comment]
![20198](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/3864313/8a228b61-232d-413a-94fd-2b07d9adc19d)

**Comment by Mister-Hope** [comment]
> Vite 开发服务器配合 chrome 我是测出了一些问题的，在原选项卡单纯的修改大小写似乎实际访问的地址是不变的。
>
> 每次开一个新标签卡访问，并不使用任何自动补全是完全正常的。

新建一个窗口，把 `localhost:8080/Test/A.html` 粘进去回车试试

**Comment by Mister-Hope** [comment]
关于使用主题，根目录不能重定向的问题，很有可能是 auto-catalog 为你自动生成了页面。

建议配置 `plugins.autoCatalog` 把根目录排除掉 See https://plugin-auto-catalog.vuejs.press/config.html#exclude

**Comment by dynilath** [comment]
> > Vite 开发服务器配合 chrome 我是测出了一些问题的，在原选项卡单纯的修改大小写似乎实际访问的地址是不变的。
> > 每次开一个新标签卡访问，并不使用任何自动补全是完全正常的。
> 
> 新建一个窗口，把 `localhost:8080/Test/A.html` 粘进去回车试试

![20201](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/3864313/257a8411-d51b-4453-98dd-bfe65ea41867)

**Comment by Mister-Hope** [comment]
> > > Vite 开发服务器配合 chrome 我是测出了一些问题的，在原选项卡单纯的修改大小写似乎实际访问的地址是不变的。
> > > 每次开一个新标签卡访问，并不使用任何自动补全是完全正常的。
> > 
> > 
> > 新建一个窗口，把 `localhost:8080/Test/A.html` 粘进去回车试试
> 
> ![20201](https://private-user-images.githubusercontent.com/3864313/301254217-257a8411-d51b-4453-98dd-bfe65ea41867.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MjI4MjksIm5iZiI6MTcwNjcyMjUyOSwicGF0aCI6Ii8zODY0MzEzLzMwMTI1NDIxNy0yNTdhODQxMS1kNTFiLTQ0NTMtOThkZC1iZmU2NWVhNDE4NjcuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMTczNTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzY3ZDk4MjAzNjc5YTQ5ZmFlODEwYzM2MTc2NzBhY2I1NmE0ZjA2NTA5MGYwY2Q5ZWIyNmQzZjA1MTEyYzQyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Oq1Rn4zRanpD74QNP3hP2N4S0RnvupVlfFslVG3Q1FQ) [ ![20201](https://private-user-images.githubusercontent.com/3864313/301254217-257a8411-d51b-4453-98dd-bfe65ea41867.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MjI4MjksIm5iZiI6MTcwNjcyMjUyOSwicGF0aCI6Ii8zODY0MzEzLzMwMTI1NDIxNy0yNTdhODQxMS1kNTFiLTQ0NTMtOThkZC1iZmU2NWVhNDE4NjcuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMTczNTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzY3ZDk4MjAzNjc5YTQ5ZmFlODEwYzM2MTc2NzBhY2I1NmE0ZjA2NTA5MGYwY2Q5ZWIyNmQzZjA1MTEyYzQyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Oq1Rn4zRanpD74QNP3hP2N4S0RnvupVlfFslVG3Q1FQ) ](https://private-user-images.githubusercontent.com/3864313/301254217-257a8411-d51b-4453-98dd-bfe65ea41867.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MjI4MjksIm5iZiI6MTcwNjcyMjUyOSwicGF0aCI6Ii8zODY0MzEzLzMwMTI1NDIxNy0yNTdhODQxMS1kNTFiLTQ0NTMtOThkZC1iZmU2NWVhNDE4NjcuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMTczNTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzY3ZDk4MjAzNjc5YTQ5ZmFlODEwYzM2MTc2NzBhY2I1NmE0ZjA2NTA5MGYwY2Q5ZWIyNmQzZjA1MTEyYzQyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Oq1Rn4zRanpD74QNP3hP2N4S0RnvupVlfFslVG3Q1FQ) [ ](https://private-user-images.githubusercontent.com/3864313/301254217-257a8411-d51b-4453-98dd-bfe65ea41867.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MjI4MjksIm5iZiI6MTcwNjcyMjUyOSwicGF0aCI6Ii8zODY0MzEzLzMwMTI1NDIxNy0yNTdhODQxMS1kNTFiLTQ0NTMtOThkZC1iZmU2NWVhNDE4NjcuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMTczNTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzY3ZDk4MjAzNjc5YTQ5ZmFlODEwYzM2MTc2NzBhY2I1NmE0ZjA2NTA5MGYwY2Q5ZWIyNmQzZjA1MTEyYzQyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Oq1Rn4zRanpD74QNP3hP2N4S0RnvupVlfFslVG3Q1FQ)

我这边在 linux 完全复现不了，而且我是用默认主题测得，建议先切回默认主题测一下确定不是主题的问题，然后把你的路径改成全小写再测测，如果确定跟这两个无关的话，等新版发布之后再给我打个压缩包？

**Comment by Mister-Hope** [comment]
> 关于使用主题，根目录不能重定向的问题，很有可能是 auto-catalog 为你自动生成了页面。
> 
> 建议配置 `plugins.autoCatalog` 把根目录排除掉 See https://plugin-auto-catalog.vuejs.press/config.html#exclude

测了一下似乎有这个问题，插件的部分冲突需要你自行解决。主页不存在时自动生成一个目录页也是合理的。

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/43ac200ffeef00b17787f23d36343c47bc3bb292 这个 commit 你 patch 进去之后就不应该出现 // 的路径了
