### ISSUE TITLE
[Bug] sandpack-vue3 and mermaid cannot be displayed normally in dev mode

### ISSUE THREAD

**Issue by cruldra** [vuepress-theme-hope/vuepress-theme-hope#3880]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

1. I created a new project with `pnpm create vuepress-theme-hope my-docs`.
2. I added dependencies and configurations for `mermaid` and `sandpack-vue3` as instructed.
3. I included the necessary code in src/demo/README.md, which is available [here](https://github.com/cruldra/vuepress2-example/blob/master/src/demo/README.md) 
4. When I run the project with `docs:dev` or `docs:clean-dev` scripts, the display is incorrect and the console shows the following error:

![image](https://cdn.jsdelivr.net/gh/hhypygy/images@master/20240131/image.3ta0umxtzj80.png)

5. However, when I build the project with the `docs:build` script and serve it via nginx, it displays correctly and there are no errors in the console:

![image](https://cdn.jsdelivr.net/gh/hhypygy/images@master/20240131/image.6h4edgkpqrg0.png)

6. I have uploaded this erroneous example project to GitHub, available at [here](https://github.com/cruldra/vuepress2-example)

**Comment by Mister-Hope** [comment]
Thanks for reaching out.

The mermaid issue is reported and patched a workaround [here](https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/3874) (but not published yet), and the explanation is [here](https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/3874#issuecomment-1918297380)

I believed the `escape-carriage` deps might be a broken esm package similar with dayjs.

I believe the following options should bypass it:

1. Install `@vuepress/helper` and any package throwing error like `escape-carriage` (note: you should install the same version as the pkg on deps tree)
2. Add `import { addViteOptimizeDepsInclude } from "@vuepress/helper/node";` at top of `.vuepress/config.ts` (or js) and add a `extendsBundlerOptions` field in userconfig:

```ts
    extendsBundlerOptions: (bundlerOptions: unknown, app): void => {
      addViteOptimizeDepsInclude(bundlerOptions, app, [
        "dayjs",
        "escape-carriage",
      ]);
    },
```

**Comment by cruldra** [comment]
Thank you for your patient guidance. Since I need to customize the Vite configuration, I solved the problem using the following solution:
```ts
//config.ts
export default defineUserConfig({
    bundler: viteBundler({
        viteOptions: {
            optimizeDeps: {
                include: ['mermaid','sandpack-vue3' ]
            }
        },
        vuePluginOptions: {},
    }),
});
```
