### ISSUE TITLE
[Bug] Packing exception: TypeError: defineClientConfig is not a function

### ISSUE THREAD

**Issue by unknowIfGuestInDream** [vuepress-theme-hope/vuepress-theme-hope#3893]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

The following error occurs when I try to package, my project runs fine, how do I fix it?
Both vuepress-vite and vuepress-webpack will produce the following error when packaging.

## Env
Nodejs: v20.11.0
System: Windows 11
npm: v10.4.0

## Command
```
"build:vite": "vuepress-vite build docs NODE_OPTIONS=--max-old-space-size=8192",
```

## Error Message
```
(!) Some chunks are larger than 1024 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
√ Compiling with vite - done in 47.53s
× Rendering 843 pages - failed in 67ms
TypeError: defineClientConfig is not a function
    at file:///E:/webStormWorkSpace/unknowifguestindream.github.io/docs/.vuepress/.temp/.server/assets/vuepress-plugin-auto-catalog-40D9VS2e.js:61:11
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async file:///E:/webStormWorkSpace/unknowifguestindream.github.io/node_modules/@vuepress/bundler-vite/dist/index.js:406:30
    at async file:///E:/webStormWorkSpace/unknowifguestindream.github.io/node_modules/@vuepress/utils/dist/index.js:58:20
    at async build (file:///E:/webStormWorkSpace/unknowifguestindream.github.io/node_modules/@vuepress/bundler-vite/dist/index.js:395:3)
    at async CAC.<anonymous> (file:///E:/webStormWorkSpace/unknowifguestindream.github.io/node_modules/@vuepress/cli/dist/index.js:233:3)
```

### config.tx
```TypeScript
import type { UserConfig } from "vuepress";
import { defineUserConfig } from "vuepress";
import { appendDatePlugin } from "vuepress-plugin-append-date";
import { viteBundler } from '@vuepress/bundler-vite'
import theme from "./theme.js";

export default <UserConfig>defineUserConfig({
  dest: "dist",

...

  bundler: viteBundler({
    viteOptions: {
      build: {
        chunkSizeWarningLimit:2048,
        rollupOptions: {
          output:{
            manualChunks(id) {
              if (id.includes('node_modules')) {
                return id.toString().split('node_modules/')[1].split('/')[0].toString();
              }
            }
          }
        }
      }
    },
    vuePluginOptions: {},
  }),

  shouldPrefetch: false,
});
```

### client.ts
```Typescript
import { onMounted } from "vue";
import type { ClientConfig } from "vuepress/client";
import { defineClientConfig } from "vuepress/client";

export default <ClientConfig>defineClientConfig({
  setup() {
    onMounted(() => {
      console.log(String.raw`

...

`);
    });
  },
});
```

## Dependencies
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/57802425/8e00977f-c474-4e54-9048-4343731ff029)

## Result
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/57802425/2bd58d3f-9543-47e3-bccb-751af6f4e873)

## Repo
Branck `work` in `https://github.com/unknowIfGuestInDream/unknowifguestindream.github.io`

**Comment by Mister-Hope** [comment]
Provide the exact log plz, 

https://github.com/unknowIfGuestInDream/unknowifguestindream.github.io/actions/runs/7764866320/job/21178829246#step:5:25 is a known bug which is fixed but not yet released.

**Comment by unknowIfGuestInDream** [comment]
> Provide the exact log plz,

I have merged the code into master and triggered packaging, please check the link.
https://github.com/unknowIfGuestInDream/unknowifguestindream.github.io/actions/runs/7767355807/job/21184117844#step:6:29

**Comment by Mister-Hope** [comment]
Remove these **shit** and try again:

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/11d3c402-42fe-44ab-a393-5719bf9f54b6)

I strongly doubt this split strategy

**Comment by unknowIfGuestInDream** [comment]
> https://github.com/unknowIfGuestInDream/unknowifguestindream.github.io/actions/runs/7764866320/job/21178829246#step:5:25 is a known bug which is fixed but not yet released.

I added this code to solve this problem.
If this problem is fixed, I will remove the configuration here and wait for subsequent releases.

Thanks for your help.

**Comment by Mister-Hope** [comment]
that's a bug , and definitely notfixable via "clod splitting",.plz wait.for my next version.

**Comment by Mister-Hope** [comment]
rc 20 should solve your problem
