### ISSUE TITLE
[Bug] Blog article list was lost in this case

### ISSUE THREAD

**Issue by Zihan-Hu** [vuepress-theme-hope/vuepress-theme-hope#3910]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [X] Linux

### Describe the bug

When
```ts
blog: {
  filter(page) {
    const path = page.filePathRelative;
    return !page.frontmatter.home && path?.startsWith('article');
  },
},
```
...the article list (`/article/`) will fallback to catalog

Is there an issue with my configuration? I aimed to display only `article/**/*.md` as blog posts.

### Additional context

[Minimal reproduction](https://stackblitz.com/edit/vuepress-h86i3c) is available.

**Comment by Mister-Hope** [comment]
should be fixed upstream in https://github.com/vuepress/ecosystem/commit/a0069597d6052b4353b83291ab05d1d545719824
