### ISSUE TITLE
[Bug] 首页features的title会重复

### ISSUE THREAD

**Issue by J1angyue** [vuepress-theme-hope/vuepress-theme-hope#3913]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

复现仓库：https://github.com/J1angyue/docs

首页features的title在构建后会重复，开发模式下不会重复
![652c5a548a6aa68de09d4ddc3fcc6d66](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/39160902/3b4b17be-4854-4f96-8e85-c18fa6fe9627)

![628a7830337f86d08565203c5edb0264](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/39160902/73366596-34d0-48d9-bd37-4f60a4115cf0)

**Comment by Mister-Hope** [comment]
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/49789f75-133a-458f-b782-423a3b30343c)
https://theme-hope.vuejs.press/faq/common-error.html#hydration-completed-but-contains-mismatches

**Comment by J1angyue** [comment]
没有使用 SSR 和 CloudFlare 也有这个报错。

**Comment by Mister-Hope** [comment]
A note for anyone again: Unless the same type of page is broken on all other hope project, otherwise this is a user-side issue, follow the instructions in [Hydration completed but contains mismatches.](https://theme-hope.vuejs.press/zh/faq/common-error.html#hydration-completed-but-contains-mismatches) and manage to solve it yourself.
