### ISSUE TITLE
[Bug] vuepress-plugin-search-pro error spam when searching

### ISSUE THREAD

**Issue by CustomEntity** [vuepress-theme-hope/vuepress-theme-hope#3914]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

 vuepress-plugin-search-pro

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

Hello, I've just created my documentation and wanted to add ` vuepress-plugin-search-pro`. Everything is going well, however, in development mode I have my Console spamming error logs, so I tried to put my documentation into production and I have more errors. However, I have the latest versions of all the packages:

```json
  "devDependencies": {
    "@vuepress/bundler-vite": "2.0.0-rc.7",
    "vue": "^3.4.15",
    "vuepress": "2.0.0-rc.7",
    "vuepress-theme-hope": "2.0.0-rc.23"
  },
  "dependencies": {
    "vuepress-plugin-search-pro": "^2.0.0-rc.23"
  }
```

I have the following errors:

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/49997349/e75b9877-1282-47c0-9d75-7d6c670007da)

and when I look at the suggestion redirection I get this

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/49997349/1df6dc00-9026-4390-be8f-8aa55a2ba1c5)

I have no idea where it could have come from, knowing that my documentation has just been created.

thanks in advance

**Comment by Mister-Hope** [comment]
can you try to make a reproduction? and is it appears after hotreload or in all cases?

**Comment by CosmoMyzrailGorynych** [comment]
This happens only on built websites

**Comment by CustomEntity** [comment]
> can you try to make a reproduction? and is it appears after hotreload or in all cases?

I've just started again by creating blank documentation and it's still the same.



> This happens only on built websites (works in dev server, at least in my case)

Even in dev server it doesn't work in my case

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/49997349/734622e4-1041-4a82-804e-f6729cf9bf69)

**Comment by Mister-Hope** [comment]
I will relook into this very soon. VuePress has some refactor and performance improvements, and the original `key` property on Page object has been removed, it seems that search-pro is not be able to index these pages.
