### ISSUE TITLE
[Bug] code tabs margin is not consistent in mobile view

### ISSUE THREAD

**Issue by labuladong** [vuepress-theme-hope/vuepress-theme-hope#3935]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

The code tabs margin is not consistent in mobile phone:

<img width="1208" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/37220920/e05a964e-8323-4177-93d5-05608a1cc750">

I think this issue is caused by the `-1.5rem` margin style, after I remove this style, it looks better:

<img width="1208" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/37220920/6402bda5-2ce5-473a-a6c3-071df7d9adea">

**Comment by labuladong** [comment]
顺便一说，用微信开发者工具用来测试移动端显示效果感觉挺好的

**Comment by Mister-Hope** [comment]
Why this should be a bug instead of "a design"?

So these are all bugs?

- https://vitepress.dev/guide/getting-started
- https://v2.vuepress.vuejs.org/guide/getting-started.html#project-setup
