### ISSUE TITLE
[Bug] Vidstack Icons Enlarged with Webpack and Waline 403 Forbidden Error

### ISSUE THREAD

**Issue by rockbenben** [vuepress-theme-hope/vuepress-theme-hope#3941]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Hello,

I recently encountered two issues in my project after an upgrade, which are affecting the user experience and functionality.

**1. Vidstack Player Icons Enlargement with Webpack:**
When the project is bundled with Webpack, the Vidstack player's icons are significantly larger than expected, impacting the aesthetics and usability of the player.

The steps to reproduce the issues are illustrated in the screenshots provided below.
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/28252913/ef22388b-6c9c-443b-a935-a49e7fc5dd93)

**2. Waline 403 Forbidden Error for Non-Allowed Domains:**
Additionally, I'm facing an issue with Waline; it returns a "Get counter failed with 403: Forbidden" error for domains that are not explicitly allowed. Previously, the application handled non-allowed domains without resulting in Uncaught runtime errors, but now it leads to page malfunctions.

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/28252913/ce0b887e-e74e-49c0-8ce1-97a89bb06c49)

**Reproduction:**
Here is a link to reproduce the issues: [StackBlitz Reproduction Link](https://stackblitz.com/edit/github-rqamfu?file=package.json).

**Comment by Mister-Hope** [comment]
The latter is expected, now 403 will log error in console, and webpack catches and display a popup for you.

For the first one, I will check out later.

**Comment by rockbenben** [comment]
> The latter is expected, now 403 will log error in console, and webpack catches and display a popup for you. Closing it could be just fine.
> 
> For the first one, I will check out later.

Could it be possible to default hide Waline's 403 errors, allowing them to only appear in the console? Since the repository might be directly copied by others, and domains will vary, it would be preferable if other users do not encounter pop-up errors when using it.

**Comment by Mister-Hope** [comment]
那你就自己配置一下Webapck，以下行为都是合理的：

-  Webpack对错误进行弹窗提示
- waline 把异常状态码当做错误输出在控制台

**Comment by Mister-Hope** [comment]
vidstack那个issue可以提在上游的core，猜测是它的css有一些特性，不被当前的压缩插件支持，所以直接被丢弃了。

你可以试着在.vuepress/styles/index.scss下手动引一下涉及的相关css。你会发现在vite下是正常的，而在webpack会报错。

**Comment by Mister-Hope** [comment]
可能有关的:

-  https://github.com/vuepress/core/issues/1443
- https://github.com/vuepress/core/issues/1349

**Comment by Mister-Hope** [comment]
你的意思是第一个问题手动引入css可以解决？

但原则上这些css已经在js里引过了.....

你可以换成npm看看有没有问题，我很怀疑这是一个pnpm webpack 和peerDep组成的混合问题(ー_ー)!!

**Comment by Mister-Hope** [comment]
此处应该@meteorlxy，我开发也会遇到这个问题，就是pnpm webpack和peerdep的组合

**Comment by rockbenben** [comment]
> 你的意思是第一个问题手动引入css可以解决？在我主题的仓库里我直接这么引入weback会报错告诉我找不到这些css。而且原则上这些css已经在js里引过了.....
> 
> 你可以换成npm看看有没有问题，我很怀疑这是一个pnpm webpack 和peerDep组成的混合问题(ー_ー)!!

是的，添加后正常了。修改的部分是 [.vuepress/styles/index.scss](https://github.com/rockbenben/LearnData/blob/main/docs/.vuepress/styles/index.scss)。

切换到 npm 后，问题依旧，显示异常。
