### ISSUE TITLE
[Feature Request]提交防盗水印

### ISSUE THREAD

**Issue by superen7527** [vuepress-theme-hope/vuepress-theme-hope#3942]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

做一些比较机密的小圈子文档 有时候需要对上传的图片或者视频打水印。现在我是一个个ps上传，但是有时候在外面用手机提交图片不太方便的时候就想到能不能加一个控制插件。如果启用则对上传的文件媒体自动打上默认为域名/标题/地址等可设置自定义描述的文本水印，实现后端上替换原文件。如果比较复杂 只支持图片也是可以的。

还有就是像飞书那种前端整个网页的水印，这种可能对公开文档用处不大，而且一个js也能屏蔽。但是也算是一种防止截图等方案吧 当然我也觉得这种是下策。有点有点影响观感。

### Additional context

如果不支持考虑，可以直接关闭issue。我只是一个想法 记录下来而已。不是什么重要需求。

**Comment by Mister-Hope** [comment]
> 如果启用则对上传的文件媒体自动打上默认为域名/标题/地址等可设置自定义描述的文本水印，实现后端上替换原文件。如果比较复杂 只支持图片也是可以的。

这种东西跟主题有什么关系？你有需求，你自己搭一个图床不就好了吗？

**Comment by Mister-Hope** [comment]
> 还有就是像飞书那种前端整个网页的水印，这种可能对公开文档用处不大，而且一个js也能屏蔽。但是也算是一种防止截图等方案吧 当然我也觉得这种是下策。有点有点影响观感。

**Comment by Mister-Hope** [comment]
通常情况下，图片的处理这种功能不是一个打包器应该提供的，而且每次打包都要处理图片也不是一个什么好方法。

我觉得原则上你可以试着写一个webpack loader或者vite插件对相对路径引用的图片实现这一点，public本身的用意就是无需处理的任意的资源文件，这个也需要你自己搞一个pipe，总之这全都不是主题的范畴。
