### ISSUE TITLE
文档标题排序不对[Bug]

### ISSUE THREAD

**Issue by lmy668** [vuepress-theme-hope/vuepress-theme-hope#3944]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/25795645/f8d37840-17e4-477c-bd25-ab7e17b475a5)
作者你好，第二个框中的排序不对。
scene: 
 1、使用'structure'自动生成侧边栏, 
 2、 "python100" 文件夹下未写readme。

 I have the latest versions of all the packages:
"devDependencies": {
    "@vuepress/bundler-vite": "2.0.0-rc.8",
    "aplayer": "^1.10.1",
    "axios": "^1.6.7",
    "kotlin-playground": "^1.30.0",
    "nodejs-jieba": "^0.1.2",
    "vue": "^3.4.19",
    "vue-router": "^4.3.0",
    "vuepress": "2.0.0-rc.8",
    "vuepress-plugin-md-enhance": "2.0.0-rc.26",
    "vuepress-plugin-search-pro": "2.0.0-rc.26",
    "vuepress-theme-hope": "2.0.0-rc.26"
  }

**Comment by Mister-Hope** [comment]
截图一下你的文件结构

**Comment by lmy668** [comment]
> 截图一下你的文件结构。你的描述并没有很让我理解你的文件结构是什么样的。
hello，以下是文件结构
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/25795645/3665b92d-0e45-4e92-872b-b8f92a1bf859)
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/25795645/057a7df8-8186-4877-b046-76d532049200)

**Comment by Mister-Hope** [comment]
你试试多加几个10x 11x的文件看看，我有点好奇，既然 9 和 10 能被排序，没道理99和 100 就不行了

**Comment by lmy668** [comment]
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/25795645/c6483af8-dbda-4e4d-a50a-74864f22e55f)
增加了一些文件，文件结构如上，渲染后如下
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/25795645/f83c4363-cb46-40b6-b892-19677b5f1bcc)
文档上说页面里中的目录是由autocatalog这个插件实现的，是不是这个排序有问题？

**Comment by Mister-Hope** [comment]
9和10的排序正常么？

**Comment by lmy668** [comment]
正常
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/25795645/ec556b80-ffb7-4fea-890c-390d5337f819)

**Comment by Mister-Hope** [comment]
那是因为你敲的 09，你试试 9 和 10 的排序，目录插件用的是 js 原生的 [localeCompare](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) 行为就是这个行为，如有需要自行通过 `extendsPage` 周期为每个页面通过其文件名称在 frontmatter 设置对应的 order。

**Comment by Mister-Hope** [comment]
特别地，源码已经开启了这个的选项，具体行为基于浏览器：

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#%E6%95%B0%E5%AD%97%E6%8E%92%E5%BA%8F

由于你的页面标题是数字字母混排，可能走不到这个逻辑里，但是原则上纯数字的字符串是可以正确的排序的。

**Comment by lmy668** [comment]
你可能没明白我的疑惑，1、sidebar排序是可以逻辑是正常的。目录插件这个排序逻辑是否要调整下，和sidebar保持一致？
2、只是说原生的localcompare的行为直接拿整个title名作为字符串来比较，不够智能，但是为啥纯字符串排序走不到localcpmpare的options的逻辑里呢？

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/25795645/1d564fd2-35b4-45f2-8831-407fe4d50ecb)

**Comment by Mister-Hope** [comment]
纯字符串是从行首开始比的，也就是下面的排序不考虑localeCompare的数值选项开启的情况，就是预期的，也是一个非纯数字字符串走的逻辑：

```
01
02
03
09
1
10
101
102
109
11
110
111
12
19
2
20
```

**Comment by Mister-Hope** [comment]
置于为什么不一致：

- 主题的侧边栏排序是一个跑在 Node.js 一侧的复合排序器，单次运行，保留结果输出给客户端。
- 目录插件的排序是一个运行在客户端的功能，是在浏览器现场读取所有路由并动态排序生成的，从运行性能和加载性能考虑，排序代码都不会太复杂，而且插件有提供给你自动自定义order的功能，你完全可以用 defineCatalogInfoGetter 返回自己心仪的 order 来手动精准排序。所以这不会被考虑，插件在 vuepress/ecosystem 那个仓库。我不是很想在这里讨论其他项目的问题。

**Comment by lmy668** [comment]
我按照你说的，在client.ts中定义自己defineCatalogInfoGetter的order，但是为啥进入不了这个defineCatalogInfoGetter 方法呢 
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/25795645/45d5108e-a56b-4392-a205-8db23252a109)
这是调试记录
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/25795645/11991987-df00-4a2d-8cec-ba5f196301d5)

**Comment by Mister-Hope** [comment]
用错了，放在文件顶部

**Comment by lmy668** [comment]
没懂，你说是直接放在export default defineClientConfig（{}）的外面？我看文档这里这么写的
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/25795645/f986f6ce-a5db-4ee4-9ce9-1cf8b9a9168e)

**Comment by Mister-Hope** [comment]
这里有问题我改一下

**Comment by Mister-Hope** [comment]
Docs updated upstream

**Comment by lmy668** [comment]
多谢，根据提示写法，
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/25795645/512ffd38-f432-40ab-b35c-b1a3ab595c13)
基本实现了功能。但还有几点困惑
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/25795645/63fc657b-2fb7-43db-96a8-87d8574ab454)
1、meta是一个对象，t大致猜出是title，i是index，t是tag，y、c、g、e是什么意思？meta中属性为啥不用全名呢

**Comment by Mister-Hope** [comment]
因为这里用了一个 ArticleType 的 enum，为了减小尺寸。目前并不是所有的服务器都支持 gzip，而且大尺寸也会影响部署速度。
