### ISSUE TITLE
[Bug]useClientData() is called without provider.

### ISSUE THREAD

**Issue by superen7527** [vuepress-theme-hope/vuepress-theme-hope#3945]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

这个问题很奇怪 换过不同设备浏览器都有一样的问题。run以后 前几次访问正常后来就是白屏 提示
```
chunk-VA7KP4YF.js:9 Uncaught (in promise) Error: useClientData() is called without provider. at useClientData (chunk-VA7KP4YF.js:9:11) at useRouteLocale (chunk-VA7KP4YF.js:23:28) at useLocaleConfig (useLocaleConfig.js:10:25) at useCopyCode (useCopyCode.js:9:20) at Object.setup (config.js:12:9) at setup (app.js:284:29) at callWithErrorHandling (runtime-core.esm-bundler.js:192:19) at setupStatefulComponent (runtime-core.esm-bundler.js:7620:25) at setupComponent (runtime-core.esm-bundler.js:7581:36) at mountComponent (runtime-core.esm-bundler.js:5908:7)
```

我看过文档 https://theme-hope.vuejs.press/zh/faq/common-error.html#usexxx-is-called-without-provider

说是需要更新。但是我已经是最新版而且测试过 pnpm dlx vp-update 和 npx vp-update 都还是会持续出现问题。

随后，我init一个新的demo。把我的src放进去以后，就也出现了这个问题。

那么我认为 问题出现在我的文档上。接着我想尝试定位哪个文件出现的问题。把文件夹挨个移出查看效果。没想到第一次移动src里面的某一个文件夹，项目监听到文件变化后 立马就可以访问 。

我以为这个文件夹就是问题来源。准备详细观察，结果我发现这是个demo文件夹，代码根本没有修改。

疑惑以后，我把文件夹移回去，保持最开始我认为有问题的src文件夹原状。在项目又检测到监听以后，再次访问地址，结果神奇的是，网站居然依旧正常。

我停止项目，重新运行 还是正常。随后 我又测试npm和pnpm不同命令启动。依旧正常。

也就是说 出现这个问题，只需要移动一下文件，触发监听。就可以解决了。控制台如下，没有任何报错 
```
http://172.18.0.1:8080/
  ➜  Network: http://172.24.0.1:8080/
info page README.md is removed
1:29:51 AM [vite] hmr update /@fs/gpi/src/.vuepress/.temp/internal/routes.js
info page README.md is created
1:29:59 AM [vite] hmr update /@fs/gpi/src/.vuepress/.temp/internal/routes.js
```

***

还没结束。这是我在demo上转移进src文件夹测试的结果。我回到原来的项目文件夹。也这样运行以后 移动任意一个文件夹或者文件再移回去。项目主页也就完全正常了。这是预期的结果。但是问题在于，停止项目重新运行 问题又重新出现。而demo刚才测试是已经完全修复该问题。

后来又测试了一个多小时 以为问题在npm上 用pnpm好像没有问题。 结果最后pnpm也有问题。以为是某一个md写的有问题，放到demo里面去结果又正常。以为是temp和mod文件夹有问题删了缓存重新更新 pnpm docs:clean-dev 起来，还是有问题。把能删的都重新拉一遍。有一次就快以为完全成功了。用npm拉完更新又不行了。换回pnpm更新 也一样不行。乱七八糟的 每次以为找到思路结果多测试一下 又有问题。。。

我不知道得出什么结论。不知道哪个是有用的思路。我就把过程想法尽可能描述出来。希望会有帮助。

### Additional context

折腾一晚上，搞不定了。不知道从这个移动文件就能修复能看出什么来。就当作汇报吧。

**Comment by Mister-Hope** [comment]
对于一个开源项目，一个基本原则是你应该能够提供一个稳定复现的步骤。
