### ISSUE TITLE
[Bug] heroImage / Text slide down animation won't work under production

### ISSUE THREAD

**Issue by BlueCitizens** [vuepress-theme-hope/vuepress-theme-hope#3952]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

## Problem Description

I think that theme-hope provides a default transformY on hero-image, hero-title and hero-description. It looks fine **under dev on a vite server**. But after building, the animation won't show when loaded to homepage at first **under production**, though it works perfect when switching back to homepage from other routes both under dev and prod. As I might am not the only one suffering from this, I find it the same on [https://mister-hope.com/](https://mister-hope.com/). I tried it on several browsers and devices and it looks like it is not the problem with the browsers.

I also noticed that although the animation works under dev, the image / text always slide up (that means a reverse of the animation) first and then slide down when first loaded to homepage. I don't know if these have anything in common or related.

By the way, I tried to use !important to override the default animations but failed. Would you please tell me if there is anyway to customize the animation myself? Thanks a lot! 

## Environments

- NodeJS version: 20.11.0 LTS
- vuepress: 2.0.0-rc.8
- vuepress-theme-hope: 2.0.0-rc.26

![QQ2024227-231453 00_00_00-00_00_30](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/43101585/671eb971-56af-460c-b4f7-288de6f6ef6c)

**Comment by Mister-Hope** [comment]
This is by design, we avoid CLS to enhance audit scores.
