### ISSUE TITLE
[Font Bug] All words become bold for Chinese word

### ISSUE THREAD

**Issue by labuladong** [vuepress-theme-hope/vuepress-theme-hope#3962]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

I found all the `<p>` display the same as `<strong>` today. I can't believe my eyes until I saw the bug in vuepress-theme-hope official website:

<img width="1090" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/37220920/950b1fc4-7fc2-4e30-9cb7-085b84b96441">

All words become bold. 

I'm sure the words were fine yesterday, don't know why it changes now.

I upgraded to the latest version Chrome today, maybe that's the reason.

**Comment by labuladong** [comment]
This issue is found in Chrome version  122.0.6261.94

**Comment by labuladong** [comment]
I tried Edge, it also has this issue.

**Comment by labuladong** [comment]
I found one solution, follow this part:
https://theme-hope.vuejs.press/zh/guide/customize/font.html#footnote-ref3

```
$font-family: 'Georgia, -apple-system, "Nimbus Roman No9 L", "PingFang SC", "Hiragino Sans GB", "Noto Serif SC", "Microsoft Yahei", "WenQuanYi Micro Hei", "ST Heiti", sans-serif';
```

Set the `$font-family` manually, then this issue is fixed (but use a font different from before).

So I guess the root cause is the default font cannot fit Chinese well in some cases. Maybe you can upgrade the font in the document site for your wonderful theme.

**Comment by Mister-Hope** [comment]
我坚持这是你自己的设备字体问题，也许你的设备缺少某种字体的 Regular 类型或者 Regular 类型本身就是 bold 的。
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/260b5c46-c3b8-46a6-b22d-bf4402865dbf)
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/06a25381-5e6b-46b7-bdc9-fe58445cf1b8)
我不认为这和浏览器的版本有什么关系。
