### ISSUE TITLE
[Bug]每切换一次布局，导航栏中的docsearch搜索框就会叠加一个点击事件监听器，点击时会打开多个搜索弹窗

### ISSUE THREAD

**Issue by HaTaXu** [vuepress-theme-hope/vuepress-theme-hope#3964]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/114818222/d798284e-a783-44a3-9c9f-fbe52d7c31bf)
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/114818222/094107d0-4526-4ad9-803f-d92e76847a4b)
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/114818222/86ede787-6a14-437c-bd8f-03d0f4d3d21d)
第三次切换页面并点击搜索框时，已经累积了三个搜索弹窗，导致背景漆黑一片

这是我在theme.ts中的设置：
```typescript
plugins: {
  blog: true,

  docsearch: {
    appId: "7WMHCEW1R2",
    apiKey: "e5fc0abfbe4984c22080e7b8c7cd883d",
    indexName: "hataxuio",
    locales: {
      '/': {
        placeholder: '搜索文档',
        translations: {
          button: {
            buttonText: '搜索文档',
          },
        },
      },
      '/en/': {
        placeholder: 'Search Documentation',
        translations: {
          button: {
            buttonText: 'Search Documentation',
          },
        },
      },
    },
  },
},
```

**Comment by Mister-Hope** [comment]
I believe in most situation this is fixed (as long as navbar is not disabled and enabled again)
