### ISSUE TITLE
[Feature Request] Add hooks in search pro

### ISSUE THREAD

**Issue by MouseSun846** [vuepress-theme-hope/vuepress-theme-hope#3965]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

How can VuePress plugin search Pro achieve secondary development and add a filtering function to the results? How can it be implemented?

### Additional context

How can VuePress plugin search Pro achieve secondary development and add a filtering function to the results? How can it be implemented?

**Comment by Mister-Hope** [comment]
@2862

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/bbcff53be0359155d097519bd8b4a43090e27398
