### ISSUE TITLE
[Bug] SEO 插件缺少 twitter:image:src 属性且 og:image 优先度不明确

### ISSUE THREAD

**Issue by Masterain98** [vuepress-theme-hope/vuepress-theme-hope#3966]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### SEO 插件缺少 `twitter:image:src` 属性

在测试站点在 Discord 分享时的预览卡片时发现：开启SEO插件功能的页面虽然会包含 `twitter:image:alt` 和 `twitter:card` 这样针对 Twitter 卡片分享的属性，但缺少 `twitter:image:src` 字段，导致没有图片可以加载。
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/10614984/b34d2f05-89d8-468e-b32b-8d62a720f3b4)

个人想法：`twitter:image:src` 的值可以默认跟随 `og:image` 的值

---

### `og:image` 优先度不明确

在 SEO 插件文档中 `og:image` 的值是这么描述的 `themeConfig.hostname + page.frontmatter.image || 页面的第一张图片|| 插件选项的 fallbackImage`，但是页面的第一张图片的优先度是更高的：在文档中设置 `frontmatter.image` 的值之后，`og:image` 的值仍然是页面中的第一张图片。这导致在一些特定的情况下时分享效果不佳：文档中有且仅有一个不重要且不适合用于分享预览的图片，此时手动设置一个 `frontmatter.image` 值会比较重要。

参考页面：https://deploy-preview-114--snap-hutao-docs.netlify.app/en/i18n.html

在上面这个页面中，[手动设置](https://github.com/DGP-Studio/Snap.Hutao.Docs/pull/114/files#diff-6694928b7e7976470f0c0e44798882e38ab07c60c46b876817d2ee1744924e83)了  `frontmatter.image` 值为 `/images/202403/zh-default-social.webp`，但[实际的网页](https://github.com/DGP-Studio/Snap.Hutao.Docs/pull/114/files#diff-6694928b7e7976470f0c0e44798882e38ab07c60c46b876817d2ee1744924e83)中 `og:image` 值为 `https://badges.crowdin.net/snap-hutao/localized.svg`，为该页面中的一个图片。

**Comment by Mister-Hope** [comment]
其实你提错地方了，你应该ecosystem那边提╮(￣⊿￣)╭

**Comment by Mister-Hope** [comment]
fixed upstream
