### ISSUE TITLE
[Bug] plugin-md-enhance 文件导入功能，获取导入文件的git信息时失败

### ISSUE THREAD

**Issue by pengzhanbo** [vuepress-theme-hope/vuepress-theme-hope#3972]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-plugin-md-enhance

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

[diff R377-R384](https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/d2dd5130a2b6b24e78935336cccd43e59f4a1399#diff-746ce44e17c33c20898bb1ad3ed90b49a2a9bb83636b3c8478e233511b4fcb5cR377-R384)

文件导入功能，在为 导入的文件添加 git信息 后，未能找到文件。

目录结构如下：
```sh
.root
   | docs
   |   |  contributing.md
   | CONTRIBUTING.md
```

contributing.md
```md
<!-- @include: ../CONTRIBUTING.md{2-} -->
```

Log:
```log
Error: Command failed with exit code 128: git --no-pager log --format=%at contributing.md ../../CONTRIBUTING.md
[1] fatal: ../../CONTRIBUTING.md：工作区中无此路径。
```

文件导入功能在 `rc.25` 版本中可正常导入。

**Comment by Mister-Hope** [comment]
我认为这个文件应该在你的vuepress项目目录之外。git插件是设计追踪项目内的文件。

这里可以额外加一个过滤，不过本质上如果你想要的这个功能失效，你是不应该引项目外的文件的

**Comment by pengzhanbo** [comment]
但是它们都是位于同一个 git 仓库之内，并未脱离整个项目，应该是可以被追踪的。虽然我并不关心导入的文件的最后更新时间。

**Comment by pengzhanbo** [comment]
对问题进行排查，发现实际上是由于命令生成错了:

```diff
- git --no-pager log --format=%at contributing.md ../../CONTRIBUTING.md
+ git --no-pager log --format=%at contributing.md ../CONTRIBUTING.md
```
即生成了错误的 文件相对路径。

在 `docs` 目录下执行 `git --no-pager log --format=%at contributing.md ../CONTRIBUTING.md` 是可以正确获取到文件的最后更新时间的。
