### ISSUE TITLE
[Feature Request] Add other social links to Navbar

### ISSUE THREAD

**Issue by NeonGooRoo** [vuepress-theme-hope/vuepress-theme-hope#3984]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

Just as on the Guide page, add an option to add other social media like Telegram to navbar, not only GitHub
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/123720895/8e6b60a0-22d7-44dd-b3b7-8dde1613e4d2)

**Comment by Mister-Hope** [comment]
https://theme-hope.vuejs.press/guide/layout/navbar.html#layout-config
