### ISSUE TITLE
[Feature Request] markdown可以支持时间轴功能吗 类似 https://www.npmjs.com/package/vitepress-markdown-timeline?activeTab=readme

### ISSUE THREAD

**Issue by qynx** [vuepress-theme-hope/vuepress-theme-hope#3987]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

markdown可以支持时间轴功能吗 类似 https://www.npmjs.com/package/vitepress-markdown-timeline?activeTab=readme

**Comment by Mister-Hope** [comment]
Not interested, I don't think this is a common feature.

I believe you can achieve this with `@vuepress/plugin-container` by your own.
