### ISSUE TITLE
[Feature Request] Markdown 代码块无换行

### ISSUE THREAD

**Issue by hqbmc2** [vuepress-theme-hope/vuepress-theme-hope#4002]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

当前Markdown 代码块无换行，总是需要鼠标滑动才能看到剩余信息。建议添加换行处理。

### Additional context

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/162419010/1c85ce9d-6d43-4179-a4d9-309406b69c4f)

**Comment by Mister-Hope** [comment]
这是预期的，不然行高亮没法做
