### ISSUE TITLE
[Feature Request] 给 `@include` 文件添加热更新

### ISSUE THREAD

**Issue by abgox** [vuepress-theme-hope/vuepress-theme-hope#4004]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

- 当我使用  `<!-- @include:  demo.md -->`  去引入了一个 md 文件
- 之后我去修改 demo.md 文件，文档页面并没有热更新
- 希望可以添加热更新的功能

**Comment by Mister-Hope** [comment]
## Are you sure you are using the latest version?

**Comment by abgox** [comment]
```json
  "devDependencies": {
    "@vuepress/bundler-vite": "2.0.0-rc.9",
    "vue": "^3.4.21",
    "vuepress": "2.0.0-rc.9",
    "vuepress-theme-hope": "2.0.0-rc.32"
  }
```
- 这是配置的依赖
---
- 我一开始也以为可能是我没有使用新版本的原因，于是我今天直接使用 `pnpm create vuepress-theme-hope demo` 重新创建了一个测试
- 我没有改动其他的东西，仅仅只是添加了一个 md 文件，然后在 README.md 中 使用 `<!-- @include: demo.md -->` 引入
- 然后去修改了 demo.md 文件，页面确实没有热更新

**Comment by abgox** [comment]
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/131574323/4310f1f0-8f54-4bb0-985c-941886ecfe90)
当我修改正常文件的时候，会检测到文件修改，然后触发 `hmr`
但是如果这个文件是使用 `<!-- @include: demo.md -->` 这种方式引入的，它只能检测到文件更新，但是不会触发 `hmr`

**Comment by abgox** [comment]
[stackblitz - demo](https://stackblitz.com/edit/vuepress-theme-hope-mmfzab?file=docs%2Fdemo.md)
- 这里我放了一个 线上的demo
- 我在 README.md 中引入了 demo.md
- 你可以尝试在 demo.md 中修改内容，页面的热更新不会启动
- (我测试的时候，在 stackblitz 线上，第一二次修改可能会更新，后面就不会更新了)

**Comment by Mister-Hope** [comment]
Your demo is working as expected.

If you dynamically add or remove the included files in devServer, the feature may bot work properly, but if a file is included when you start the devserver, modifying that file should trigger the related page update.

**Comment by abgox** [comment]
![demo](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/131574323/615317ea-2bdf-4363-abad-96c6e8b25d09)

- 同样的演示在我的设备上并没有达到预期效果
- 像 gif 中展示的那样，只有第一次文件保存，页面热更新了，后面都没有得到及时的更新

**Comment by Mister-Hope** [comment]
你把控台里面的hmr信息也录一下

**Comment by Mister-Hope** [comment]
终端里的 hmr 看起来是正常的，那我就没有什么头绪了，控制台有报错么？

**Comment by abgox** [comment]
没有任何报错，如果在你的设备上正常生效的话，那就可能真的是我的设备问题了，有点玄学。

**Comment by Mister-Hope** [comment]
你可以在本地留意一下 .vuepress/.temp/pages 下对应的 vue 文件内容是不是跟着一起变，是的话可能是一个 HMR 的问题。

**Comment by abgox** [comment]
- 实际上，.vuepress/.temp/pages 下对应的 vue 文件是修改了的，但是并没有触发 HMR
- 从终端信息可以看出来，当我修改 1.md 文件的时候，终端里一直在打印 `info page 1.md is modified`，但是并没有 `[vite] hmr update`
- 应该就是 HMR 没有被触发导致的这样的问题，但是为什么 HMR 没有触发，我就不知道了


![demo](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/131574323/4f1c371a-6017-4ded-af77-475ed0ef2e41)

**Comment by Mister-Hope** [comment]
不不不，不是对应页面的，是待导入页面的，你要看主页那个 vue 有没有变化。

**Comment by abgox** [comment]
主页没有变化

**Comment by Mister-Hope** [comment]
Is everthing working in new version?

**Comment by abgox** [comment]
- 用的就是最新的版本


![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/131574323/96f0f30f-0d96-4219-b621-16f2c8167c67)

**Comment by Mister-Hope** [comment]
rc33 already released.

**Comment by abgox** [comment]
- 我刚刚重新开了一个 demo，在 rc33 版本中也是同样的问题

**Comment by Mister-Hope** [comment]
Everything is working fine at stackblitz and wsl for me, closing as I can not reproduce it.
