### ISSUE TITLE
[Bug]关于下一篇/页的三个问题

### ISSUE THREAD

**Issue by Leytton** [vuepress-theme-hope/vuepress-theme-hope#4005]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

1.  如下图所示，通过目录生成，希望1.1的下一页是1.1.1（而不是1.2），1.1.2的下一页是1.2（而不是没有）
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/5785077/a6bb9f62-8c9e-4580-8161-b769fd4e2225)
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/5785077/b23db567-dd8f-4a75-ab44-85889a2736e5)
此外我通过修改文档的`next: 1.1.1_量子计算和量子信息的历史`，出现了两个问题：
3. 下一页处显示`1.1.1_量子计算和量子信息的历史.html`，而不是`1.1.1 量子计算和量子信息的历史`
4. 点击下一页跳转过去，显示404，刷新一下又能正常显示
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/5785077/dc2cef5f-68a4-428c-829c-712b095668ab)
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/5785077/8510d2ca-dfed-4c48-9294-65cfe8e0d703)

感谢阅读🌹

**Comment by Mister-Hope** [comment]
The first one is expected and this is by design.

## Why?

A sub route may have it's only sidebar, this ensures the prev and next are working under the same sidebar.

E.g.: `/a/` and `/a/xx/` has different sidebar config, and the `/a/xx/` is detailed, you can not go back once you enter `/a/xx/` like the way you described.

---

I will take a look at the rest 2.

**Comment by Mister-Hope** [comment]
I believe this is fixed, if the new version still has issues, openning a new issue is welcomed.
