### ISSUE TITLE
[Bug] New media brings error

### ISSUE THREAD

**Issue by NeonGooRoo** [vuepress-theme-hope/vuepress-theme-hope#4007]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

At some point I realised that when I am trying to add new images - VuePress just doesn't see it and gives me this error.
`Failed to resolve import "IMAGE" from "PAGE". Does the file exist?`

I may have an old image imported like `![](/imgvid/i1.jpg)` and it works fine and that's why I didn't notice what caused this, but even if I rename the i1.jpg to something like i2.jpg and change the code to  `![](/imgvid/i2.jpg)` I will have the error again. It drive me mad. It doesn't matter where the image is.

You can see this behavior on this rep https://github.com/NeonGooRoo/NeonGooRu for any file. Please help.

**Comment by Mister-Hope** [comment]
Wrong place, open issue like this in vuepress/core.

There is an existing issue already, https://github.com/vuepress/core/issues/1519
