### ISSUE TITLE
[Bug] Unable to Display Page Views on Blog Homepage

### ISSUE THREAD

**Issue by rockbenben** [vuepress-theme-hope/vuepress-theme-hope#4013]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

I'm encountering an issue with the VuePress theme hope where the page views are not displayed on the blog homepage after executing `pnpm docs:build`. However, upon entering individual article pages, the page views are shown correctly.

**Steps to Reproduce:**
1. Execute `pnpm docs:build` to build the blog pages.
2. Navigate to the blog homepage. Notice that the page views are missing from the articles list.
3. Enter any article page. The page views are displayed as expected.

**Screenshots:**
- Homepage without page views: ![Homepage without page views](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/28252913/2776296e-adf1-4fb9-9244-8e1979407a6b)
- Source code snippet: ![Source code snippet](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/28252913/dead0481-88c1-4113-ad2d-75be80fb5588)
- Article page with page views: ![Article page with page views](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/28252913/c8f40c92-f542-44ee-b98f-b713d00b0d5e)

**Comment by Mister-Hope** [comment]
Which comment service are you using?

**Comment by rockbenben** [comment]
> Which comment service are you using?

waline

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/44cc9234569004d511cc7dfd9c066c805bcf8e1f

**Comment by rockbenben** [comment]
> [44cc923](https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/44cc9234569004d511cc7dfd9c066c805bcf8e1f)

The issue has reoccurred in v2.0.0-rc.34.

```
  "dependencies": {
    "@vuepress/bundler-webpack": "2.0.0-rc.9",
    "vue": "^3.4.21",
    "vuepress": "2.0.0-rc.9",
    "vuepress-plugin-search-pro": "2.0.0-rc.34",
    "vuepress-theme-hope": "2.0.0-rc.34"
  },
  "devDependencies": {
    "@vuepress/plugin-docsearch": "2.0.0-rc.24",
    "@vuepress/plugin-feed": "2.0.0-rc.24",
    "@vuepress/plugin-google-analytics": "2.0.0-rc.21",
    "@waline/client": "3.1.3",
    "cpx2": "^7.0.1",
    "markdownlint-cli": "^0.39.0",
    "mathjax-full": "^3.2.2",
    "prettier": "^3.2.5",
    "sass-loader": "^14.1.1",
    "vidstack": "^1.11.6"
  },
```

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/ecosystem/commit/4ff7a6c29641d50bc0676698f5487203cd5e5263
