### ISSUE TITLE
[Bug] 初始化在vp-blog-hero中插入元素会消失

### ISSUE THREAD

**Issue by lzy1960** [vuepress-theme-hope/vuepress-theme-hope#4016]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

我在初始化时，引入了一个script脚本，会在hero处增加一个video元素，但自从我升级版本后，video元素会先加载，之后消失，看起来应该是hero元素延迟加载导致video被覆盖了？但具体是哪个版本有问题我不清楚，只能给到一个范围

脚本如下：
```typescript
// scripts/video.ts
// build时编译为js
function initVideo () {
  const div = document.createElement('div')
  div.setAttribute('id', 'hero-video-wrapper')

  const video = document.createElement('video')
  video.setAttribute('id', 'hero-video')
  video.poster = '/background.webp'
  video.src = '/background.mp4'
  video.autoplay = true
  video.loop = true
  video.muted = true

  const blogHero = document.querySelector('.vp-blog-hero')
  div.appendChild(video)
  blogHero?.appendChild(div)
}
initVideo()
```

引入
```ts
// config.ts
export default defineUserConfig({
  head: [
    ['script', { src: '/scripts/video.js', async: true }],
  ],
});
```

### 在线链接
- 没有问题：https://lzy1960-github-io.vercel.app/
- 视频消失：https://blog-test-nu-bice.vercel.app/

### 对应的版本
没有问题的版本https://github.com/lzy1960/lzy1960.github.io
```json
"devDependencies": {
  "@vue/repl": "^3.2.0",
  "@vuepress/client": "2.0.0-rc.0",
  "@vuepress/utils": "2.0.0-rc.0",
  "chart.js": "^4.4.1",
  "echarts": "^5.4.3",
  "flowchart.ts": "^3.0.0",
  "katex": "^0.16.9",
  "mermaid": "^10.6.1",
  "reveal.js": "^5.0.4",
  "typescript": "^5.4.3",
  "vue": "^3.4.5",
  "vuepress": "2.0.0-rc.0",
  "vuepress-theme-hope": "2.0.0-rc.10"
}
```

有问题的版本https://github.com/lzy1960/lzy1960.github.io/tree/fix/error
```json
"devDependencies": {
  "@vue/repl": "^3.4.0",
  "@vuepress/bundler-vite": "2.0.0-rc.9",
  "@vuepress/client": "2.0.0-rc.9",
  "@vuepress/utils": "2.0.0-rc.9",
  "chart.js": "^4.4.2",
  "echarts": "^5.5.0",
  "flowchart.ts": "^3.0.0",
  "katex": "^0.16.10",
  "mermaid": "^10.9.0",
  "reveal.js": "^5.0.5",
  "typescript": "^5.4.3",
  "vue": "^3.4.21",
  "vuepress": "2.0.0-rc.9",
  "vuepress-theme-hope": "2.0.0-rc.32"
}
```

**Comment by Mister-Hope** [comment]
使用组件替换 https://vuepress-theme-hope.github.io/v2/zh/guide/advanced/replace.html
