### ISSUE TITLE
[Bug] 修整默认项目 GitHub Actions 推送触发器的分支名称

### ISSUE THREAD

**Issue by Masterain98** [vuepress-theme-hope/vuepress-theme-hope#4019]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

按照[创建项目](https://theme-hope.vuejs.press/zh/get-started/create.html)中的方法来初始化项目的话，会使用 `master` 作为主分支，但提供的默认 GitHub Actions 文件中则只写了 `main` 分支。建议增加 `master` 作为分支 push 的触发器，或者使二者统一。

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/1ce69c8f844d7089c1b7cca84b87052ca222ca4e
