### ISSUE TITLE
[Bug] Firefox Android 滑动时，返回到顶部按钮不会随文章变化

### ISSUE THREAD

**Issue by pheotry** [vuepress-theme-hope/vuepress-theme-hope#4020]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

Firefox Android 

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/43376740/b9e643c1-83c9-413d-bc86-fbe97965a84e)

正常状态
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/43376740/9e29f3f3-6a8e-449c-8eb7-34fadb4ce30a)

**Comment by Mister-Hope** [comment]
这是浏览器的支持问题
