### ISSUE TITLE
[Bug]Mailto:XXX@yy.com is no longer worked after upgrade to 2.0.0-rc.22

### ISSUE THREAD

**Issue by lancy6001** [vuepress-theme-hope/vuepress-theme-hope#4044]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

I have a default navbar.ts file, and I add some contents like below:
{
    text: "Contact Us",
    children: [
       {
         text: "Email Support",
         link:"mailto:XXXsupport@XXXtest.com",
         //target: "_blank", 
       }

before upgrade, it is regard as mailto bebavior and will popup outlook to write an email.
But now it is regard as a html page like mailto:XXXsupport@XXXtest.com.html
Actually, this is not a page, but a mailto behavior. Please check and correct this behavior.

### Additional context

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/59279078/398c1364-ea0b-4e58-9d2b-8aa567901bb0)

**Comment by Mister-Hope** [comment]
This is an upstream bug at vuepress core.

I tried to spend a few minutes searching protocol like this which can support it by browser but I haven't found any  specification files that describe this.

Can you help to provide one?

urls like mailto: can be sepecial because they don't have full protocols like `abc://`

**Comment by Mister-Hope** [comment]
I have found https://www.rfc-editor.org/rfc/rfc6068,  but since there are other early protocol like  tel: https://www.rfc-editor.org/rfc/rfc5341.

I just want to make sure I,can catch all of them

**Comment by Mister-Hope** [comment]
Track https://github.com/vuepress/core/issues/1528. To speed up the process, I sincerely invite you to help finding the full list of these protocols as they must be specially handled.

**Comment by lll4770** [comment]
Hi @Mister-Hope , I saw you had fixed this issue. I'm new learner in the front-end, I'm using the vuepress-theme-hope in my project, my question is how can I get your fix in my project, currently, I found the version of vuepress-theme-hope in my project is "2.0.0-rc.22" in the package.json config file.

**Comment by Mister-Hope** [comment]
IWait for a new version to land. That won't take long.

We don't create a patch release immediately for every bugs.
