### ISSUE TITLE
[Bug] code tabs in details block have extra `:::`

### ISSUE THREAD

**Issue by labuladong** [vuepress-theme-hope/vuepress-theme-hope#4051]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

Example:

```
    ::: details test title
    
    hello world
    
    ::: code-tabs
    
    @tab:active java
    ```java
    String path = "";
    ```
    
    @tab cpp
    ```cpp
    string path = "";
    ```
    
    :::
    
    :::
```

<img width="815" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/37220920/0a9a9274-2fd8-4972-9be3-5d109b85cc3e">


### Additional context

_No response_

**Comment by Mister-Hope** [comment]
https://mdit-plugins.github.io/zh/container.html#%E6%A0%BC%E5%BC%8F
