### ISSUE TITLE
[Bug] 文章右側標題 hash 連結無法滾動

### ISSUE THREAD

**Issue by im1010ioio** [vuepress-theme-hope/vuepress-theme-hope#4056]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

文章右側標題 hash 連結無法滾動（但文章內部標題可以），伴隨著錯誤訊息：
`scrollPromise is not a function`

![1712806285048](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/17057860/3b59bef5-0fc3-45ae-8e99-ff131abc6a14)
![截圖 2024-04-11 上午11 31 46](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/17057860/a25d344a-6ce7-440d-ac83-26dc5344155c)

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/pull/4055
