### ISSUE TITLE
[Bug] 无法关闭访问量

### ISSUE THREAD

**Issue by jaronnie** [vuepress-theme-hope/vuepress-theme-hope#4067]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

关闭了 comments 后访问量依然显示

### Additional context

无

**Comment by xchanper** [comment]
同样的问题，根本没有使用waline，但是会显示一个奇怪的访问量，以前版本是没有用的，升级后突然出现的
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/31340393/85ec0583-fcff-49ce-b7a8-3de062a31ecd)
看了下 @Mister-Hope 本人的博客貌似也有这个问题
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/31340393/195dfac5-b6ca-4f4f-9526-70c155d17ac7)

**Comment by stylite1024** [comment]
是的，我的也有这个问题，无论怎么设置都有
