### ISSUE TITLE
[Bug] Bold in the hint box doesn't work in some browsers

### ISSUE THREAD

**Issue by northword** [vuepress-theme-hope/vuepress-theme-hope#4068]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

```md
::: tip

xxx **bold text** xxx

:::
```

以上代码中的粗体在部分浏览器未生效，大致测试结果如下：

| 浏览器 | 系统平台 | 粗体是否生效 |
|-------|----------|-------------|
|Chrome|Windows 11| 是|
|Edge|Windows 11 | 是|
|Firefox|Windows 11|是|
|Chrome|Android|否|
|Edge|Android|否|
|Firefox|Andriod|是|
|Edge|macOS intel|否|

一些不正常示例（以官方文档截图，“带有成吨功能”这句话系粗体）：

微信 8.0.47 关闭X5内核，webview 124.0.6367.54

![99b09a704e097cb913f56dcc4369ec4](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/44738481/d0eab8ea-dadd-4b71-9243-be9ce50fd042)

Chrome Android 123.0.6312.118

![7435d094f4ec043fc9e09720eeda810](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/44738481/1da5e391-39cd-43f2-b88e-f380cd1abdbd)

edge android 122.0.2365.99 google play version

![73e1739aed95a28e744dec9b8285714](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/44738481/0631f999-69b4-4aba-a81a-baecf9f0315b)

Edge MacOS 我没有测试设备，是别人反馈的：https://github.com/zotero-chinese/wiki/pull/163#issuecomment-2056958926

**Comment by Mister-Hope** [comment]
建议自行通过更换字体，或者针对性的调整字体粗细到支持的值以解决这个问题

**Comment by northword** [comment]
打扰，我想和您确认一下：

同一个设备的不同浏览器有的是正常的，有的是不正常的，浏览器本身没有更换字体，都是使用系统默认字体

例如 firefox android 是正常的：

![Screenshot_2024-04-16-09-58-53-688_org.mozilla.firefox-edit.jpg](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/44738481/c7cf131f-2209-4dbd-9b5c-3abb9f2b147d)

这也是字体导致的问题而不是浏览器兼容性问题吗？

**Comment by Mister-Hope** [comment]
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/1901ab5b-e209-4b43-a55a-65a845a597f8)

You can try setting this one to 700, it may solve the problem in most cases. Anyway, there is nothing to do with a website, that a device browser does not support certain font-weight.

**Comment by northword** [comment]
It's working! Thank you very much for your generous answer!
