### ISSUE TITLE
[Feature Request] Hope to add advertisement support

### ISSUE THREAD

**Issue by gtn1024** [vuepress-theme-hope/vuepress-theme-hope#411]
**Describe the feature and why you wanted**
Hope to add advertisement support
Just like [AntDocs](https://antdocs.seeyoz.cn/guide/extend-config.html#%E5%B9%BF%E5%91%8A%E4%BD%8D-new) which is also a VuePress theme.

**Comment by Mister-Hope** [comment]
vuepress-theme-hope is design to be pure while powerful. I am not looking forward to this feature now.

You can edit the theme using [Theme Inheritance](https://v1.vuepress.vuejs.org/zh/theme/inheritance.html)

**Comment by Mister-Hope** [comment]
I may support this feature after I build pure mode. :smile:

**Comment by Mister-Hope** [comment]
Added in v1.18.0
