### ISSUE TITLE
[Bug] 显示兼容性问题

### ISSUE THREAD

**Issue by MouseSun846** [vuepress-theme-hope/vuepress-theme-hope#4117]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

设备型号：
Mozilla/5.0 (Linux; Android 12; ADA-AL00 Build/HUAWEIADA-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36 XWEB/1160117 MMWEBSDK/20240404 MMWEBID/7259 MicroMessenger/8.0.49.2600(0x28003137) WeChat/arm64 Weixin NetType/4G Language/zh_CN ABI/arm64

显示异常
![25849f2a0e249382c22f5b126383f0e](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/46400044/9954eefa-5672-4bc2-9a40-da0d9b4f1287)

**Comment by Mister-Hope** [comment]
the theme is working on my wechat browser.

Besides, chrome 114 is absolutely a browser we support.

Further Information about your device is needed,  And you can track the FAQ part to polyfill those legacy browsers

**Comment by Mister-Hope** [comment]
Some updates,  I confirm that on devices having  lo Android versions, wechat browser is running on the system webview.

So if your device's system webview version is lower than 88,  You may trigger issues like this.

I need further information from your response  to confirm how it happened.  If no further response is being received, I will close the issue.

**Comment by MouseSun846** [comment]
显示vuepress就没类似问题，使用hope主题就会有，不知道是什么原因导致的
