### ISSUE TITLE
搜索跳转颜色标记关键词[Feature Request]

### ISSUE THREAD

**Issue by helayD** [vuepress-theme-hope/vuepress-theme-hope#4129]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

搜索跳转颜色标记关键词

### Additional context

搜索跳转颜色标记关键词

**Comment by Mister-Hope** [comment]
请详细描述你的问题
