### ISSUE TITLE
[Feature Request] plugin-md-enhance is too large, perhaps it needs to be split

### ISSUE THREAD

**Issue by pengzhanbo** [vuepress-theme-hope/vuepress-theme-hope#4130]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

First of all, thank you to markdown enhance for providing powerful functionality support to vuepress markdown! However, it must be said that this plugin has now become very large and cumbersome, making maintenance increasingly difficult. Perhaps it is time to consider splitting it up.

My suggestion is to consider splitting from various perspectives such as new syntax, grammar extensions, third-party dependencies, resource embedding, and content container types.

For example, these combinations can be used as individual plugins.：

- content container: `hint`, `github alerts`, [`code-group`];
- new syntax: `sup`, `sub`, `task list`, `footnote`, `mark`, `spoiler`，`include`;
- grammar extensions: `attrs`, `imgSize`, `imgMark`, `obsidianImgSize`, `imgLazyload`;
- markdown render: `breaks`, `linkify`, `figure`, `stylize`;
- math Tex: `katex`, `mathjax` (optional deps);
- chart: `chart`, `echarts`, `flowchart`, `markmap`, `mermaid`, `plantuml` (optional deps);
- code blocks: [`code-group`], `code-demo`;
- code playground: `kotlin-playground`, `vue-repl`, `typescript-playground`
- ...more

**Comment by Mister-Hope** [comment]
I actually prefer function spliting, e,g. I will split imgMark imgSize and figure into one plugin called plugin-markdown-img.

Here are my plans:

- plugin-img: imgMark -> mark imgSize -> size figure -> figure
- plugin-math: katex or mathjax
- plugin-gfm: 
-

**Comment by pengzhanbo** [comment]
Comparing the more complex aspects of splitting is challenging, especially with elements like `sup`, `sub`, `task list`, `footnote`, `mark`, `spoiler`, `include`, `imgSize`, `imgMark`, `obsidianImgSize`, `imgLazyload`, `breaks`, `linkify`, `figure`, and `stylize`. Distinguishing their categories can be quite tricky.

Considering these functions are relatively simple and independent, perhaps they can be separately implemented in the upstream `mdit-plugins`, then integrated into `plugin-md-enhance`. Meanwhile, `plugin-md-enhance` should only retain these functions, with others being separated out.

e.g:

- plugin-md-enhance: `sup`, `sub`, `task list`, `footnote`, `mark`, `spoiler`, `include`, `imgSize`, `imgMark`, `obsidianImgSize`, `imgLazyload`, `breaks`, `linkify`, `figure`,  `stylize`
- plugin-hint: `hint`, `github alerts`
- plugin-math: `katex` or `mathjax`
- plugin-chart: `chart`
- plugin-echarts: `echarts`
- plugin-mermaid: `mermaid`
- ... more

**Comment by Mister-Hope** [comment]
The md-enhance plugin is already spitted into several plugins, the reset will be processed soon
