### ISSUE TITLE
会出一个对应vitepress的主题吗？

### ISSUE THREAD

**Issue by Youky1** [vuepress-theme-hope/vuepress-theme-hope#4133]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

如题，vitepress的性能比vuepress强了不少，但目前没有用着顺手的主题，是否会考虑适配呢？

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/268
