### ISSUE TITLE
[Bug] 升级后编译报错

### ISSUE THREAD

**Issue by sixmillions** [vuepress-theme-hope/vuepress-theme-hope#4134]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

# Build 报错

从 `2.0.0-rc.41` 升级到 `2.0.0-rc.42` 后，build报错

```
$ npm run docs:build

> blog@2.0.0 docs:build
> vuepress-vite build src

✔ Initializing and preparing data - done in 295ms
x Build failed in 3.94s
✖ Compiling with vite - failed in 3.98s
Error: Can't find stylesheet to import.
   ╷
16 │ @use "social-media";
   │ ^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/vuepress-theme-hope/lib/bundle/modules/blog/styles/all.scss 16:1  root stylesheet
```
我不会前端，但是我看了一下，npm仓库，这个名字对不起来，不知道是不是错误

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/41658874/9b252bcf-da77-4314-ab60-31556526c696)

**Comment by Mister-Hope** [comment]
Already fixed in https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/bea5ca5b90bc97ac8d2c7871aa74a4a5ce5cddae
