### ISSUE TITLE
[Feature Request] horizontal toc slot in non-PC layout

### ISSUE THREAD

**Issue by labuladong** [vuepress-theme-hope/vuepress-theme-hope#4138]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

How about making the toc slots horizontal when the toc displays on top? This may be more compact.

<img width="933" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/37220920/a8f3d7bc-61ec-4caa-9f12-6b97386c4a29">

**Comment by Mister-Hope** [comment]
actually, I am thinking diabling those slots on mobile, any usage for example?

**Comment by labuladong** [comment]
I just think somebody may want to add small widgets on the floating bar. But seems disabling them is easier and more reasonable.

**Comment by Mister-Hope** [comment]
This seems solved in later PR
