### ISSUE TITLE
[Feature Request] 侧边栏折叠目录增加默认展开或收起功能

### ISSUE THREAD

**Issue by bihell** [vuepress-theme-hope/vuepress-theme-hope#4141]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

如题，某些折叠目录我希望默认是展开的，但是文档似乎没有相关属性。

**Comment by Mister-Hope** [comment]
This sounds reasonable, will be added in further release.
