### ISSUE TITLE
[Feature Request] 增加属性，控制正文是否显示图标

### ISSUE THREAD

**Issue by bihell** [vuepress-theme-hope/vuepress-theme-hope#4142]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

目前有个场景，我希望侧边栏显示图标，正文不需要显示。

**Comment by Mister-Hope** [comment]
>  I think that 25%+ users are positive towards this feature.

Add a CSS to hide it or use component overriding. I am not your personal coder.
