### ISSUE TITLE
[Bug] 手机端图片同比缩小之后看不清了

### ISSUE THREAD

**Issue by bihell** [vuepress-theme-hope/vuepress-theme-hope#4143]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

我不知道这个算是 Bug 还是功能需求，是这样的我现在文档里面有几个本来就很小的图片，在 Web 端浏览正常，但是手机端访问的时候会随着页面缩小而缩小，导致看不清了。 是否加个断小图片不缩小之类？ 

**MD 代码**

入代码所示，限定了大小为75

```

| 服务商                                        | SLA  | 服务   | 综合                             | 备注               |
|--------------------------------------------|------|------|--------------------------------|------------------|
| [DMIT（大妈）](/vps/used/dmit.html)            | 棒极了  | 不错哟  | ![](/rating/star-4.5.svg =75x) |                  |
| [Bandwagon（搬瓦工）](/vps/used/bandwagon.html) | 棒极了  | 棒极了  | ![](/rating/star-4.svg =75x)   | 机器太老旧了           |
```

**网页端**

正常效果，如截图

<img width="856" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/19926035/2d500b2d-f53c-46ae-b0aa-f4728517b5a5">

**手机端**

已经看不清是什么了

![IMG_DB88C9045DCE-1](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/19926035/5a687112-9b41-4d20-8b29-fa52770687b6)

**Comment by Mister-Hope** [comment]
地址给一下？我去debug一下，这的确是不大对劲的

**Comment by bihell** [comment]
> 地址给一下？我去debug一下，这的确是不大对劲的

https://bigdata.icu/vps/vps-rank.html
