### ISSUE TITLE
[Feature Request] 博客主题根据最新修改日期排序文章

### ISSUE THREAD

**Issue by BanMing** [vuepress-theme-hope/vuepress-theme-hope#4166]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

现在博客文章排序是根据元数据中的date字段排序的，能否添加一个根据修改时间来排序。这样经常更新的以前创建的文章就可以最先就看到了。当然也可以写脚本在每次打包的时候更新元数据中的date字段来实现，但是这样来时间线功能看起来就很呆了。感恩感恩~

**Comment by Mister-Hope** [comment]
I think you can add a custom blog type yourself with `plugins.blog.types` called "Recent Updated"

> 这样经常更新的以前创建的文章就可以最先就看到了。

This is definitely not a common usage.
