### ISSUE TITLE
Type issue in stackblitz：'"vuepress"' has no exported member 'defineUserConfig' 

### ISSUE THREAD

**Issue by Youky1** [vuepress-theme-hope/vuepress-theme-hope#4168]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

引用依赖时报错，'"vuepress"' has no exported member 'defineUserConfig' ，项目无法运行。
在线演示demo中同样有这个错误
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/56068056/6be56d26-d086-44ec-b7a9-55d5c3f877ea)

**Comment by Mister-Hope** [comment]
The stack blitz editor is not a fully functional editor, which does not support pure esm packages. Report to them about esm package issues.

For local projects, ensure `type: "module"` is added or use `.mts`

**Comment by Mister-Hope** [comment]
See https://github.com/stackblitz/webcontainer-core/issues/1452

**Comment by Mister-Hope** [comment]
Closing as stale upstream.
