### ISSUE TITLE
[Bug] Set the transparent navigation bar and some content be overwritten

### ISSUE THREAD

**Issue by simeis147** [vuepress-theme-hope/vuepress-theme-hope#4173]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

设置主题预设中的[透明导航栏](https://theme-hope.vuejs.press/zh/guide/customize/presets.html#%E9%80%8F%E6%98%8E%E5%AF%BC%E8%88%AA%E6%A0%8F)后，文章的分类（article）、分类（category）、标签（tag）、时间轴（timeline）这些页面的部分内容会重叠在navbar下

未使用透明导航栏：
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/120312238/94987152-0ace-4e84-9c8b-552726dc710a)

使用透明导航栏：
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/120312238/d81737ac-0f38-459d-8552-58f94819aef2)

vuepress-theme-hope页面也有类似情况：
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/120312238/5e60d44b-bd55-49fc-b937-2c8477cf659d)
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/120312238/f736e6cf-0ad1-4d21-b02b-c53b1f60c476)
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/120312238/a5760cdd-b1b0-4f24-b94c-6308a09701b9)

**Comment by Mister-Hope** [comment]
Already fixed in https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/0f326990c9c42470453fecca1f6585341ba017f9
