### ISSUE TITLE
[Bug] Uncaught runtime errors: × ERROR [object Event]     at handleError (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:252:58)     at eval (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:275:7)

### ISSUE THREAD

**Issue by df13954** [vuepress-theme-hope/vuepress-theme-hope#4174]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

在本地开发过程中，经常弹出Uncaught runtime errors:
×
ERROR
[object Event]
    at handleError (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:252:58)
    at eval (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:275:7)

终端上面没有错误信息，一直显示：
✔ Cleaning cache - done in 11ms
✔ Initializing and preparing data - done in 218ms
✔ Compilation finished in 4772ms
success VuePress webpack dev server is listening at http://localhost:8080/
webpack compiled successfully

### Additional context

npm --version
10.2.3
node -v
v18.19.0
macos

**Comment by Mister-Hope** [comment]
There should be detailed error and error stack info in browser console

**Comment by df13954** [comment]
> There should be detailed error and error stack info in browser console

I added remote images in the article, but the image storage service provider has set a whitelist that only allows specific websites to access, with anti-theft restrictions. After removing the image, this error never occurred again. I added a regular image without an anti-theft chain and did not encounter any errors.
