### ISSUE TITLE
[Feature Request] 选项卡快速指引链接

### ISSUE THREAD

**Issue by vlssu** [vuepress-theme-hope/vuepress-theme-hope#4189]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

选项卡中，比如 https://theme-hope.vuejs.press/zh/guide/markdown/content/tabs.html#%E6%A1%88%E4%BE%8B 案例中，我能不能通过 #banana（ https://theme-hope.vuejs.press/zh/guide/markdown/content/tabs.html#banana ），直接访问 banana 选项卡，这样在别的页面能用户快速的看到我们想指向内容中  
当然也包括选项卡中的 标题（### 标题 ，### 标题2），

**Comment by Mister-Hope** [comment]
回头看看能不能通过query实现。

标题那个想多了，内容在tab组件，所以你认为的标题并不是文档标题。

**Comment by Mister-Hope** [comment]
Closing as tabs feature are moving to VuePress/ecosystem

**Comment by Mister-Hope** [comment]
Track https://github.com/vuepress/ecosystem/issues/399
