### ISSUE TITLE
[Bug] 网站链接如果直接访问带 # 的连接显示 404

### ISSUE THREAD

**Issue by suyuan32** [vuepress-theme-hope/vuepress-theme-hope#4193]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

访问网站链接 如 [地址](https://theme-hope.vuejs.press/v2/zh/guide/advanced/seo.html#%E5%BC%80%E7%AE%B1%E5%8D%B3%E7%94%A8)

会导致 404 

系统版本

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/21239039/16312254-7d48-4045-872b-19d30630e0f3)

**Comment by Mister-Hope** [comment]
# ? 

你不觉得你给的地址本来就是404么？

https://theme-hope.vuejs.press/zh/guide/advanced/seo.html#%E5%BC%80%E7%AE%B1%E5%8D%B3%E7%94%A8

**Comment by suyuan32** [comment]
https://doc.ryansu.tech/zh/guide/feature/validator.html#格式

**Comment by suyuan32** [comment]
看下上面这个

**Comment by Mister-Hope** [comment]
![Screenshot_2024-05-28-18-50-44-99_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/33315834/f2ad3bb3-1157-41b4-a4fb-4d3d625b6c19)

https://doc.ryansu.tech/zh/guide/feature/validator.html#%E6%A0%BC%E5%BC%8F

问题在哪？

**Comment by suyuan32** [comment]
> ![Screenshot_2024-05-28-18-50-44-99_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://private-user-images.githubusercontent.com/33315834/334377158-f2ad3bb3-1157-41b4-a4fb-4d3d625b6c19.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4OTM4NTQsIm5iZiI6MTcxNjg5MzU1NCwicGF0aCI6Ii8zMzMxNTgzNC8zMzQzNzcxNTgtZjJhZDNiYjMtMTE1Ny00MWI0LWE0ZmItNGQzZDYyNWI2YzE5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDEwNTIzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhODEzZDA1NDdlM2Y2NDc5YjI3MTFhZDNiMmJjZDM1MDRhNmM0YjdhZmE0NWY3NjZkNjZjZjE4NDAwMDE2ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gVnAaUWEqdWFFJZk_8v88JOxyHhn5viU3hQF4Joc5AM)
> 
> https://doc.ryansu.tech/zh/guide/feature/validator.html#%E6%A0%BC%E5%BC%8F
> 
> 问题在哪？

怪事，手机端 Chrome 可以，电脑端 Chrome 不行，就是直接访问网址不行，如果点击进入网站后再点击侧边栏访问就可以访问。

**Comment by suyuan32** [comment]
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/21239039/62de4f69-b163-4603-adb4-3bbc019b264b)

**Comment by suyuan32** [comment]
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/21239039/b2ceda9f-4120-4c21-a9c2-ad7736dc6895)

**Comment by suyuan32** [comment]
还有就是本地使用 docs:dev 模式下可以直接访问网址，是部署以后才出现的问题

**Comment by suyuan32** [comment]
本地测试模式下没问题

**Comment by suyuan32** [comment]
前几个版本是没有这个 bug 的

**Comment by suyuan32** [comment]
现在好像又可以了，可能是 cdn 缓存的问题
