### ISSUE TITLE
[Feature Request] 优化代码块样式，清除 `outline` 样式

### ISSUE THREAD

**Issue by WangJincheng4869** [vuepress-theme-hope/vuepress-theme-hope#4194]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

![{ UNZTSPMDJLJ8@2%LF7N](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/41162158/4fcc8cc9-0deb-4d7f-9466-5a890f2b7c9a)

### Additional context

可添加样式 `outline:none`

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/ecosystem/commit/3942641fab33b2e7520ad58d906ffb0070c3ec9e
