### ISSUE TITLE
[Feature Request] support the same options in the navabar as in the sidebar

### ISSUE THREAD

**Issue by skamansam** [vuepress-theme-hope/vuepress-theme-hope#4209]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

My company would like to be able to write internal docs without having to manage them. I am setting up Vuepress with the Hope theme in order to facilitate that. In order to do this efficiently, I would like to be able to add children of the navbar in the same fashion as in the sidebar, by using the `children: "structure"` option. This would also mean we could use a central file to manage the navigation items instead of two different ones.

**Comment by Mister-Hope** [comment]
Nope.

1. Navbar shows the most important navigation links for the site, probably entrance of some basic categories. The expected number of navbar links are at 3 to 10+, so it is reasonable to force you manually set it.
2. navbar only support a max of level 3 nesting, while sidebar is infinite in design (as long as you give enough width for it)
