### ISSUE TITLE
[Bug] iconify-icon dev tool warning after update to 2.0.0-rc.47

### ISSUE THREAD

**Issue by mario4tier** [vuepress-theme-hope/vuepress-theme-hope#4211]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

See image for before/after the upgrade from 2.0.0-rc.38 to 2.0.0-rc.47

The icons for my external links are changed and there is an error shown in the chrome dev tools (also the blue color customization with the link is gone, don't know if related!?)

**Before (2.0.0-rc.38 external links working as expected)**
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/4542410/6cec66f2-43b2-44cd-9229-a61805330f61)

**After (2.0.0-rc.47 with dev tool error)**
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/4542410/b18a24be-c6f2-45e2-9f70-e7fb3c5f7d3c)

**Related Markdown**
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/4542410/68306e08-133c-4a0c-9e64-c658e2db66a3)

**Website Code**
On my dev setup, there is no change from this version on git, except the upgrade to 2.0.0-rc.47
https://github.com/ChainMovers/suibase/tree/main/docs

**Update Information**
![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/4542410/ff270821-25e0-465d-98f9-a477b2387fe2)

**Comment by Mister-Hope** [comment]
thanks for reporting, I will investigate that later.
