### ISSUE TITLE
[Bug] open docsearch with shortcuts

### ISSUE THREAD

**Issue by labuladong** [vuepress-theme-hope/vuepress-theme-hope#4214]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

Using `cmd+k` to open docsearch will open many overlapping dialogs.

Expect:
<img width="1468" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/37220920/a317a137-3ab9-404e-bc10-f4bfb3fb175d">

Actual:
<img width="1468" alt="image" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/37220920/d111f451-1d13-4ad8-80b4-a1fce1fae133">

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/3964
