### ISSUE TITLE
[Bug]手机端detail 代码段文字缩放问题

### ISSUE THREAD

**Issue by bihell** [vuepress-theme-hope/vuepress-theme-hope#4224]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

手机端文字大小有明显问题。

电脑端看很正常，如下

<img width="902" alt="Snipaste_2024-06-12_21-57-58" src="https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/19926035/08628d0b-dee4-4606-b3c4-92035e2c1398">

但是手机端代码段文字明显大了

![IMG_EF9DEB3656E3-1](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/19926035/06293995-603a-4c9d-9432-e793d27b21ec)

**Comment by Mister-Hope** [comment]
提供给reproduction，另外任何safari的问题我只接受PR，因为我没有设备调试

**Comment by bihell** [comment]
reproduction 见附件，访问地址 http://localhost:8080/vps/changelog.html
[demo.zip](https://github.com/user-attachments/files/15847216/demo.zip)
