### ISSUE TITLE
[Bug] algolia search will append dup base path

### ISSUE THREAD

**Issue by labuladong** [vuepress-theme-hope/vuepress-theme-hope#4234]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

The search result looks good:

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/37220920/9ac2b985-1077-4fe1-96e7-d6d5e46b05b8)

But after clicking the result, there are dup base paths:

![image](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/37220920/e2b97a75-5c83-4ff5-8071-231e03c29020)

I believe https://github.com/vuepress/ecosystem/pull/138 introduced this issue. After reverting it, this issue was fixed.

I'm not sure is the hope-theme missing any updates to fit https://github.com/vuepress/ecosystem/pull/138, so create an issue here.

**Comment by Mister-Hope** [comment]
I need the docsearch config without apikey and appid, and your crawler config

**Comment by fdevans** [comment]
This is the same issue that I was running into in the PR thread.   I will see if I can reproduce minimally if I have time, but our site, when updated to all latest packages will result in this bug returning.  If there's anything I can do to help let me know.

**Comment by fdevans** [comment]
I've tried creating a minimal reproduction, but can't seem to mimic the behavior.  If it helps I can create a branch on our repo/site that mimics the behavior.

**Comment by fdevans** [comment]
I am able to reproduce it on this branch of our site: https://github.com/rundeck/docs/tree/dev_search_test

Our main branch is working since I've reverted versions in package.json to prior to this fix.

I understand it's not "mimimal reproduction", but it can be used to see the behavior and full configs for crawler, vuepress, etc.

**Comment by Mister-Hope** [comment]
Busy in real life now, will take a look later

**Comment by Mister-Hope** [comment]
I will relook into this this week

**Comment by Mister-Hope** [comment]
Closed with https://github.com/vuepress/ecosystem/commit/7e56412a1b21bb3974668230496708a5bd6d71fe

**Comment by fdevans** [comment]
Thank you for fixing this!  Will test when I can navigate the package dependencies.  It seems Hope theme still wants theme-default version 39.

**Comment by Mister-Hope** [comment]
Yes, busy on another project now.

**Comment by fdevans** [comment]
Tried recently with the latest version .52 and there are still some package issues:

```
# npm resolution error report

While resolving: vuepress-theme-hope@2.0.0-rc.52
Found: @vuepress/plugin-prismjs@2.0.0-rc.40
node_modules/@vuepress/plugin-prismjs
  @vuepress/plugin-prismjs@"2.0.0-rc.40" from @vuepress/theme-default@2.0.0-rc.40
  node_modules/@vuepress/theme-default
    dev @vuepress/theme-default@"^2.0.0-rc.40" from the root project

Could not resolve dependency:
peerOptional @vuepress/plugin-prismjs@"2.0.0-rc.39" from vuepress-theme-hope@2.0.0-rc.52
node_modules/vuepress-theme-hope
  dev vuepress-theme-hope@"2.0.0-rc.52" from the root project

Conflicting peer dependency: @vuepress/plugin-prismjs@2.0.0-rc.39
node_modules/@vuepress/plugin-prismjs
  peerOptional @vuepress/plugin-prismjs@"2.0.0-rc.39" from vuepress-theme-hope@2.0.0-rc.52
  node_modules/vuepress-theme-hope
    dev vuepress-theme-hope@"2.0.0-rc.52" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by vordimous** [comment]
I am running into this issue as well. @fdevans @Mister-Hope is there a workaround until it is fixed?
