### ISSUE TITLE
[Bug]在主题中配置searchPro全文检索后搜索中文浏览器报错

### ISSUE THREAD

**Issue by 2290774104** [vuepress-theme-hope/vuepress-theme-hope#4237]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

使用文档提供的命令创建项目后，在 `theme.ts` 中的 searchPro 配置 `indexContent: true` 时，搜索中文会导致页面报错，但 `config.ts` 中配置则可以正常搜索
```sh
pnpm create vuepress-theme-hope my-docs
pnpm add -D vuepress-plugin-search-pro
```
```ts
// theme.ts
export default hopeTheme({
  plugins: {
    searchPro: {
      indexContent: true;
    }
  }
})
```
这是在 `theme.ts` 中配置后搜索出现的错误
![theme.ts配置报错](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/72640061/1bbd8d2b-f0d0-46ba-acaa-bfd0c87d624c)

```ts
// config.ts
import { searchProPlugin } from 'vuepress-plugin-search-pro';

export default defineUserConfig({
  plugins: [
    searchProPlugin({
      indexContent: true
    }),
  ]
})
```
这是在 `config.ts` 中配置的搜索成功
![config.ts配置后成功](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/72640061/742c19a0-cfef-44c7-8c90-8aa75f2fc9a5)

### Additional context

开发环境：
node v18.20.3
npm 10.7.0
pnpm 9.4.0
项目依赖版本
"@vuepress/bundler-vite": "2.0.0-rc.14",
"vue": "^3.4.27",
"vuepress": "2.0.0-rc.14",
"vuepress-plugin-search-pro": "2.0.0-rc.50",
"vuepress-theme-hope": "2.0.0-rc.50"

**Comment by Mister-Hope** [comment]
A reproduction is required.

**Comment by abstiger** [comment]
same problem

**Comment by 2290774104** [comment]
I created a new repository for reproducing：https://github.com/2290774104/vuepress-theme-hope_search-demo.git

**Comment by Mister-Hope** [comment]
Just some update I am busy with my other project and also a lot of things happened in my real life. One of my family members just passed away in last month and  I had to work on some other important things.

I would likely to review this issue once I'm spare again,  But i am afraid that the time table will be no longer early then October this year.

So if anyone wants to have a look at this issue,  further Information about this is welcome in this thread

**Comment by CuteReimu** [comment]
我提供一些我发现的线索吧，希望能够有所帮助。
1. 我最初（大约是54版本）是好的，在进行过一些版本更新（含主题版本和插件版本更新）后出现的问题。
2. 在dev环境是好的，build才会出问题。
3. 我尝试修改在`config.ts`，也是不行的。
4. 我这里的报错有些不同：

```
Uncaught Error: SlimSearch: cannot deserialize an index created with an incompatible version
    at zt (search-pro.worker.js:1:12257)
    at search-pro.worker.js:1:173726
    at Array.map (<anonymous>)
    at search-pro.worker.js:1:173710
```

断点了一下看对应的位置，`c`值为`undefined`

```js
const zt = ({index: e, documentCount: t, nextId: s, documentIds: n, fieldIds: o, fieldLength: u, averageFieldLength: i, storedFields: r, dirtCount: d, serializationVersion: c}, a) => {
    if (c !== 1 && c !== 2)
        throw new Error("SlimSearch: cannot deserialize an index created with an incompatible version");
    const h = new Et(a);
```

不知是否有所帮助。

**Comment by xyz3282836** [comment]
> 我提供一些我发现的线索吧，希望能够有所帮助。
> 
> 1. 我最初（大约是54版本）是好的，在进行过一些版本更新（含主题版本和插件版本更新）后出现的问题。
> 2. 在dev环境是好的，build才会出问题。
> 3. 我尝试修改在`config.ts`，也是不行的。
> 4. 我删掉`indexContent: true`，也是不行的。
> 5. 我这里的报错有些不同：
> 
> ```
> Uncaught Error: SlimSearch: cannot deserialize an index created with an incompatible version
>     at zt (search-pro.worker.js:1:12257)
>     at search-pro.worker.js:1:173726
>     at Array.map (<anonymous>)
>     at search-pro.worker.js:1:173710
> ```
> 
> 断点了一下看对应的位置，`c`值为`undefined`
> 
> ```js
> const zt = ({index: e, documentCount: t, nextId: s, documentIds: n, fieldIds: o, fieldLength: u, averageFieldLength: i, storedFields: r, dirtCount: d, serializationVersion: c}, a) => {
>     if (c !== 1 && c !== 2)
>         throw new Error("SlimSearch: cannot deserialize an index created with an incompatible version");
>     const h = new Et(a);
> ```
> 
> 不知是否有所帮助。

vuepress-plugin-search-pro 2.0.0-rc.54版本也不行

**Comment by Mister-Hope** [comment]
Search pro is deprecated and no future version will be released, please use `@vuepress/plugin-slimsearch` instead.

If any issue occurs, report to vuepress/ecosystem repo.
