### ISSUE TITLE
[Bug] Failed to display .txt/.py/.c/ raw file in vuepress

### ISSUE THREAD

**Issue by pjg864** [vuepress-theme-hope/vuepress-theme-hope#4250]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

When I add `[download url](./test.py)` in my markdown file, which is located in docs/test/ directory, It'll jump to http://xxxx/test.py.html, and display 404.

Why not jump to  http://xxxx/test.py, and display the raw content?

How can I fix this issue?

**Comment by Mister-Hope** [comment]
only markdown files in directory are converted to actual routes.

You can use the public folder and withBase helper
