### ISSUE TITLE
[Bug] 無法正常顯示 fontawesome Classic 以外的圖示。

### ISSUE THREAD

**Issue by nnn950711** [vuepress-theme-hope/vuepress-theme-hope#4260]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

無法顯示除 fontawesome Classic 以外的圖示包，例如：Twitter, Linux 等

 已設定 iconAssets: "fontawesome"

![螢幕截圖_20240709_075551](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/41001774/34497fd4-7e88-4f34-99d7-e705563a37d3)
![螢幕截圖_20240709_075641-1](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/41001774/6640dd58-1311-4e5a-b0d7-def89ba49bdc)
![螢幕截圖_20240709_075524](https://github.com/vuepress-theme-hope/vuepress-theme-hope/assets/41001774/b682a7c0-70fe-4187-99e3-70f79359d36f)

**Comment by Mister-Hope** [comment]
So why there is a `fontawesome-with-brand`?

**Comment by nnn950711** [comment]
> So why there is a `fontawesome-with-brand`?

設定成 fontawesome-with-brand 後台顯示：
vuepress-plugin-components:  ✖ Can not recognize icon link: "fontawesome-with-brand"

**Comment by itldg** [comment]
```
iconAssets: "fontawesome-with-brands",
```
I usually do this

```
title: 后端
icon: fab fa-linux
```
![image](https://github.com/user-attachments/assets/53020917-c0d8-4e9b-a1d3-7b18212cf00d)
