### ISSUE TITLE
[Bug] 启动开发服务器，浏览器打开http://localhost:8080后，终端出现警告

### ISSUE THREAD

**Issue by i7366464** [vuepress-theme-hope/vuepress-theme-hope#4264]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.
具体警告如图所示。
![image](https://github.com/user-attachments/assets/f2a71d4a-f98d-4147-b501-a6f43fd36eed)

**Comment by Mister-Hope** [comment]
- https://github.com/sass/dart-sass/issues/2276
- https://github.com/vitejs/vite/issues/7116
