### ISSUE TITLE
[Bug] 右侧目录的引导线滚动异常，具体看图

### ISSUE THREAD

**Issue by sunn4room** [vuepress-theme-hope/vuepress-theme-hope#4269]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

![2024-07-21_16-16](https://github.com/user-attachments/assets/6cc4e54a-9d04-4ea1-b609-e9916a1569ba)

当目录长度大于页面高度时，目录引导线会随着滚动而上移，出现缺口。

**Comment by Mister-Hope** [comment]
Thanks for the report
