### ISSUE TITLE
[Bug] improvement for a long sidebar

### ISSUE THREAD

**Issue by labuladong** [vuepress-theme-hope/vuepress-theme-hope#4271]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

It is not a bug seriously, but could be better. This will happen when you keep scrolling down:

![image](https://github.com/user-attachments/assets/2d85019f-7161-43cd-8d98-00d3241426d8)

Example page:
https://theme-hope.vuejs.press/zh/guide/#%E5%AF%BB%E6%B1%82%E5%B8%AE%E5%8A%A9

### Additional context

I guess it only needs a CSS improvement.

**Comment by Mister-Hope** [comment]
![QQ_1721654255336](https://github.com/user-attachments/assets/82b30f02-6857-4805-b99e-a9a112231d89)

I think it's possible that it's your own browser issue. PROBABLY some extensions are injecting unkown styles that break this.

**Comment by labuladong** [comment]
Thanks, but it can be reproduced in  Incognito Mode:
![image](https://github.com/user-attachments/assets/d54e18a0-66e7-4122-9234-48e1446ff41c)

I guess the style is injected by Chrome. I'm using Chrome 125.0.6422.142

**Comment by Mister-Hope** [comment]
Could not reproduce with the give version.

You need to debug yourself above how the footer is "lifted", and show the debug result.

**Comment by labuladong** [comment]
Thanks, I'll investigate this and put the solution here

**Comment by labuladong** [comment]
FYI @Mister-Hope , I can still reproduce the issue, and found the root cause:

reproduce in Chrome:

<img width="1506" alt="image" src="https://github.com/user-attachments/assets/2e444ff6-aff7-4320-b2f4-11cd5b4af033">

reproduce in Edge:
<img width="1500" alt="image" src="https://github.com/user-attachments/assets/3f9e2fe3-ff98-4ecf-893c-19bd3efe1b20">


If I remove the `z-index` CSS, it looks good, but there is a line on TOC part:

fix in chrome:
<img width="1501" alt="image" src="https://github.com/user-attachments/assets/4d470b1d-eae2-430f-8347-0c3efc52f2a1">

fix in edge:
<img width="1505" alt="image" src="https://github.com/user-attachments/assets/43773e2d-de66-42a8-b0df-1a77f2bfb8bc">


Example link: https://theme-hope.vuejs.press/zh/changelog.html#%E6%9B%B4%E5%A4%9A

**Comment by labuladong** [comment]
> ![QQ_1721654255336](https://private-user-images.githubusercontent.com/33315834/350978506-82b30f02-6857-4805-b99e-a9a112231d89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMjU0NjUsIm5iZiI6MTcyNDEyNTE2NSwicGF0aCI6Ii8zMzMxNTgzNC8zNTA5Nzg1MDYtODJiMzBmMDItNjg1Ny00ODA1LWI5OWUtYTlhMTEyMjMxZDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDAzMzkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyZmRlOGMyOWZhZTVkOWFiMDBmMDRiOWRhMTVjYWU2ZjcxOWEwYWM4MWFlOTNiNjNjMzNjOTIwNWIzNDRlYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uEcIlkjq37Cx5dk0Qq-b8YOu78ZB-RCWJj1FHRLUoMY)
> 
> I think it's possible that it's your own browser issue. PROBABLY some extensions are injecting unkown styles that break this.

In your example, the sidebar didn't exceed the bottom. Maybe you can try to open the bottom side dev console, to make the sidebar overflow. Then you may reproduce the issue.

**Comment by labuladong** [comment]
I can't reopen this issue, but I think there should be a CSS fix, not my local misconfiguration. Could you please reopen it? Thanks @Mister-Hope

**Comment by Mister-Hope** [comment]
Why in my example it's not reaching the bottom? THe scrollbar is already at the bottom at the right side.

Also I did not see "ANY further investivate about how it happenes, if you say that footer is floating, then there must be some elements after it and taking spaces, what are thoee? Again, I never ever reproduce what you are reporting.

Further information is needed.
