### ISSUE TITLE
[Feature Request] Support link in code block？

### ISSUE THREAD

**Issue by Naza3** [vuepress-theme-hope/vuepress-theme-hope#4279]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

我在 qt 的[文档](https://doc.qt.io/qt-6/qtqml-cppintegration-definetypes.html#registering-an-instantiable-object-type)中看到代码块中的变量支持链接。我看markdown增强插件好像不支持。
比如：
```cpp
 class Message : public [QObject](https://doc.qt.io/qt-6/qobject.html)
 {
     Q_OBJECT
     Q_PROPERTY([QObject](https://doc.qt.io/qt-6/qobject.html)
}
```

**Comment by Mister-Hope** [comment]
Any provement about what you are talking (syntax I mean)

Is that doc open source?

**Comment by Naza3** [comment]
> Any provement about what you are talking (syntax I mean)
> 
> Is that doc open source?

There is a html source [qtqml](https://github.com/QtCommunityCN/QtDocs/blob/main/qtqml/qtqml-cppintegration-definetypes.html)

This is how it is represented in HTML:
```html
<pre class="cpp" translate="no">
 <span class="keyword">class</span> Message : <span class="keyword">public</span> <span class="type"><a href="../qtcore/qobject.html" translate="no">QObject</a></span>
 {
     Q_OBJECT
     Q_PROPERTY(<span class="type"><a href="../qtcore/qstring.html" translate="no">QString</a></span> author READ author WRITE setAuthor NOTIFY authorChanged)
     Q_PROPERTY(<span class="type"><a href="../qtcore/qdatetime.html" translate="no">QDateTime</a></span> creationDate READ creationDate WRITE setCreationDate NOTIFY creationDateChanged)
     QML_ELEMENT
 <span class="keyword">public</span>:
     <span class="comment">// ...</span>
 };
</pre>
```

**Comment by Mister-Hope** [comment]
I think this is something like twosplash in shiki,  which requires at least ast parsing.

I'm definitely sure that the grammar you imagine is wrong,  And there is likely contents for any program languages to contain some part of markdown syntax.

So closing this one as you are just providing non JavaScript based features  And also not providing reasonable ways to achieve this.

**Comment by Mister-Hope** [comment]
Also a reminder further discussion is not welcomed at least  You had read through all the qdoc codes,  And can provide a reasonable way to achieve this with javascript based sync markdown parsers.
