### ISSUE TITLE
[Feature Request] 希望支持 `@shikijs/transformers `

### ISSUE THREAD

**Issue by WangJincheng4869** [vuepress-theme-hope/vuepress-theme-hope#4281]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

今天偶然发现 [shiki](https://shiki.tmrs.site/packages/transformers#transformernotationdiff) 这个转换器非常符合我的需求。
特别是这个 diff 的功能。既能保留代码的高亮显示，又能显示 diff，简直完美。

![图片](https://github.com/user-attachments/assets/ad789fd7-bfe6-466e-80c0-a29e4c5c2684)

还有这个重点代码的功能，绝了。日常写文档的确有类似的场景，如果代码只贴一部分，那么有些人看不懂。这个就可以贴上全部的代码，将重要的部分高亮。

![图片](https://github.com/user-attachments/assets/2b3f9c21-3720-4115-9e49-cfbe184fe3ee)

还支持不少其他的[功能](https://shiki.tmrs.site/packages/transformers#transformernotationdiff)，我目前的场景没有太大用处。

**Comment by WangJincheng4869** [comment]
已解决，在 `shiki` 配置中添加 `notationDiff: true` 即可

**Comment by Mister-Hope** [comment]
I think you can do anything you want with the existing shiki plugin.

For further questions please ahead to vuepress/ecosystem repo.
