### ISSUE TITLE
[Bug] 行号消失了，在 `shiki` 中设置 `lineNumbers: true` 也无效。

### ISSUE THREAD

**Issue by WangJincheng4869** [vuepress-theme-hope/vuepress-theme-hope#4282]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### 已经添加了配置
![图片](https://github.com/user-attachments/assets/ee4b1b8b-67c0-43ef-a17a-e356031b8c42)

### 依旧没有行号
![图片](https://github.com/user-attachments/assets/f3072731-702f-420f-8e40-3150d8c682bc)

### `markdown.code` 配置已经不可用

![图片](https://github.com/user-attachments/assets/3b0d09a4-e62b-4ad6-88fc-729837a00bbb)

**Comment by ChenSino** [comment]
+1，另外内容超长时也没有滚动条了，之前是有的

**Comment by ChenSino** [comment]
![image](https://github.com/user-attachments/assets/d4e15bee-5df4-424f-959b-59b93b97834c)

**Comment by laolang2016** [comment]
使用 `prismjs` 不就好了
[https://ecosystem.vuejs.press/zh/plugins/markdown/prismjs.html](https://ecosystem.vuejs.press/zh/plugins/markdown/prismjs.html)

**Comment by jpf91** [comment]
The issue can also be seen on the demo page: https://theme-hope.vuejs.press/cookbook/vuepress/markdown.html#code-blocks No highlighted lines and no line numbers.
