### ISSUE TITLE
[Bug] MarkdownIt.render() and mdEnhance_include conflict

### ISSUE THREAD

**Issue by LincZero** [vuepress-theme-hope/vuepress-theme-hope#4283]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

![39d8d34f6f210d6bf70d8b92a662a542](https://github.com/user-attachments/assets/992dfd6c-3317-473f-9784-cecb68e1dd48)

问题如上图

一些个人调试：

1. 注释掉include: true恢复正常
2. 不注释掉的话，使用单独下载的markdown-it也能正常：
    ```
    // npm install markdown-it
    import MarkdownIt from "markdown-it"
    let origin_mdit = MarkdownIt();
    // 用这个 origin_mdit 执行 .render() 是正常的
    ```
    但这种方式无法彻底解决，因为原生markdown-it渲染出来和vuepress markdown-it渲染出来的样式是不一样的，后者对mdit做了些自定义
3. 不注释掉的话，将 .render() 换成 .renderInline() 也能正常，但那个只能渲染内联

**Comment by Mister-Hope** [comment]
I try to reproduce what you are reporting at https://github.com/vuepress-theme-hope/vuepress-theme-hope/commits/include/

But everything works fine for me, so give me a reproduction by creating a fork and adding a few lines.

**Comment by LincZero** [comment]
好了，版本问题，https://vuepress-theme-hope.github.io/v2-new rc.44 不复现，回退更早版本可复现
