### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by WebGamer** [vuepress-theme-hope/vuepress-theme-hope#4315]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

本地开发发不到生产环境页面展示不一致，内容缺失

### Additional context

![image](https://github.com/user-attachments/assets/e6d054ac-d1fc-4a67-9672-0bd70600c285)
![image](https://github.com/user-attachments/assets/5314b6e1-e477-414d-a9a6-6d38d3511a04)

**Comment by WebGamer** [comment]
![image](https://github.com/user-attachments/assets/b707661f-1def-4f91-83ba-b631d6b81d79)

**Comment by Mister-Hope** [comment]
ul is not allowed inside p.

For fully customizing homepage,  I'm suggesting using componentsoverriding or customizing layout.
