### ISSUE TITLE
[Feature Request] plantuml的纯javascript实现

### ISSUE THREAD

**Issue by LincZero** [vuepress-theme-hope/vuepress-theme-hope#4316]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

在 #2773 中，提到了两个plantuml链接：一个借助离线的服务器，另一个借助本地jar环境。他们一个存在延迟和网络要求，另一个部署麻烦。

这是由于 plantuml 使用java所写的。而去年，plantuml 发布了新的纯js实现的plantuml，原理是用CheerpJ将java字节码转webAssembly/JavaScript。

我相信这会让 plantuml 变得更泛用（我认为plantuml的功能比mermaid更强大得多，mermaid有时用起来挺难受，只是过去plantuml碍于对java环境的要求而变得不易被嵌入）

相关链接：https://github.com/plantuml/plantuml-core

**Comment by LincZero** [comment]
该issue你可以先搁置一会，过几天我也会详细研究下，不排除会自己PR

**Comment by Mister-Hope** [comment]
我没有看到此PR的任何益处？从实现原理上 plantuml-core 的性能一定会弱于 Java 版本的 plantuml，而且它也并不能引入什么新功能？

借助 Plantuml 官方 playground 实现的 plantuml 渲染也许是性能更优的？

**Comment by Mister-Hope** [comment]
你能更好的描述一个合理动机？来来描述我们应该迁移到 JavaScript 版本的 plantuml 么？

**Comment by LincZero** [comment]
## 性能问题

之前调研的结果是确实会更慢一点，确实如你所说的，对于稍微复杂一点的图甚至慢于使用网络请求的方式，不占优。

- 主要是第一次初始化要cheerJ init等较慢，第一次渲染可能达到2s
- 后续比较快，普通的时序图在270ms，官网中最复杂的那个架构图耗900ms
- 而网络时延，多简单请求也要300ms，那个复杂的架构图耗450ms（图片不复杂）

反正不优。同样是 pure js 的 mermaid其实也好不了多少，同复杂度可能也就节省个百ms左右。但好像初始化比较轻

## 解除网络需求和服务器依赖

本来想用Pure JS的主要原因是，为了解除网络请求及服务器依赖，以便在一些限制场景中使用（纯内网搭建文档库）。但为了达到这个需求，不一定需要用js版的plantuml，后来想了下方法还是挺多的：

1. 用 plantuml js
2. 如果只是为了在访问期解除网络需求，其实可以在渲染时的plantuml-encoder阶段就把图片缓存下来。
   目前的plantuml原理是：将plantuml语法通过plantuml-encoder编码，目的是去除在url不合法的字符及压缩。然后变成 img 标签。在访问期则使用编译期给的img标签，访问时进行网络请求渲染。那么如果在编译期就将图片缓存下来，那么就可以避免在访问时重复进行请求。
3. 如果为了在编译期也解除网络需求，可以仿照 https://github.com/joethei/obsidian-plantuml 的做法，将plantuml的jar放在本地，编译时使用本地的jar编译 (或使用本地docker)

方式一不是很优，一开始我是想使用虚拟Dom在编译期将其渲染，那么这种方式是优的，而且也没性能缺陷。但在Github code里搜发现没人做过，自己尝试了下也没成功，我没弄出来，就只能在浏览器渲染了。可以是可以，但个人感觉似乎不如第二种方式，主要是方式二比方式一要快一点

## 总结

折腾起来发现太麻烦了，搞不来，还是不如mermaid方便。

我放弃折腾了，放弃在非通用环境下使用plantuml了

**Comment by Mister-Hope** [comment]
可是如果说你把图片的渲染交给一个外部服务器，通过在连接中编码plantuml文本的方式来进行的话，对于浏览器本身并不会带来额外的开销，只是需要消耗一定带宽来接收服务器的返回图片。至于请求渲染再返回所带来的延时，我觉得只要不大于两秒都是可以接受的，毕竟你所用框架的主要场景也是静态文档渲染，你也没有很多的情景是你必须要从某个plantuml流程图开始看起的。

而正如你所说，如果说我们选择内置一个转义过的服务器，不仅本身包尺寸会有很大的提升，而这种提升通常来说对ci是不友好的，并且你也会增加额外的部署体积。如果你想要避免打包时间的增加以及重复部署相同的内容，你还要做额外的优化以将这部分代码从vuepress的打包管线中排除，而实际上这最好的方式却又是建立一个独立的基于plantuml-core的服务器，反而莫不如直接使用一个原版的。

如果你说你想在本地运行plantuml-core来直接打包选然后的图片，首先额外的尺寸增加和构建时间增长仍然是不可避免的，而且我不确定plantuml-core是否是同步的，如果不同步，那么无法嵌入我们现有的markdown渲染逻辑，如果同步，我想这也会一定程度导致markdown渲染线程的阻塞增加打包时间，而且我并没有看到这种直接将图片准备好打包的优势在哪里，尤其是当plantuml使用次数越来越多的时候。

综上你的上一条回复并没有给我实际带来任何的启发，也并没有展示一些可供展望的新前景。
