### ISSUE TITLE
[Bug] codetabs 在亮色风格时依然是暗黑风格样式

### ISSUE THREAD

**Issue by Feawaris** [vuepress-theme-hope/vuepress-theme-hope#4333]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

官网示例也是一样的效果：https://theme-hope.vuejs.press/zh/guide/markdown/code/code-tabs.html#%E6%BC%94%E7%A4%BA
dark: ![WX20240810-162724@2x](https://github.com/user-attachments/assets/aa7ad97e-7265-4190-a558-e6c13b4edd94)
light: ![WX20240810-162709@2x](https://github.com/user-attachments/assets/179caad9-bb14-400a-8239-b07e87a70aed)

**Comment by Menghuan1918** [comment]
same problem

**Comment by Mister-Hope** [comment]
#4320
