### ISSUE TITLE
[Bug] Slide Content Displayed Too Small After Upgrade

### ISSUE THREAD

**Issue by ryanlo713** [vuepress-theme-hope/vuepress-theme-hope#4335]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

Copied from [discussions:4334](https://github.com/orgs/vuepress-theme-hope/discussions/4334#discussion-7035485) 

**Description:**

After upgrading to the latest version, I've noticed that the slide content is displayed at a much smaller scale than expected.

**Comparison of Version Numbers:**
![Comparison of Version Numbers](https://github.com/user-attachments/assets/028ec8f1-0947-4af3-9a06-dd6d32702890)

**Issue Detail:**
As demonstrated in the attached screenshot, the content is scaled too small, making it difficult to read and follow along with the presentation. This issue also occurs in the slide examples of the official documentation, which indicates that it may be a broader problem.

**Attachments:**
![screenshot showing the scaling issue](https://github.com/user-attachments/assets/f7c072c5-36da-425c-a8f1-ab0b699e606f)
![another screenshot showing the same problem in the official documentation slides](https://github.com/user-attachments/assets/d63368d1-b726-4ccb-922c-0bf5ecabca80)

Please investigate this issue, as it severely impacts readability.

Thank you!

**Comment by Mister-Hope** [comment]
weird, I don't think.I.did any changes in recent versions, I will have a look.
