### ISSUE TITLE
[Bug] Custom alignment doesn't work on the table.

### ISSUE THREAD

**Issue by BaoYier** [vuepress-theme-hope/vuepress-theme-hope#4338]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

Custom alignment doesn't work on Markdown's table such as:
```
::: center
| Table   |
| ------- |
| content |
:::
```

**Comment by Mister-Hope** [comment]
That's expected, because there are extra styles on it.

You can use the attrs feature to apply styles to it.
