### ISSUE TITLE
[Feature Request] Make structure parsing also available for index.md files

### ISSUE THREAD

**Issue by robertraaijmakers** [vuepress-theme-hope/vuepress-theme-hope#4352]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

I have a feature request. Currently the structure feature of the sidebar only considers readme.me. As practice (at least in the previous vue versions) it was recommended to always have an index.md file. This is also better practices for indexing sites as Google to have an index.html file in folders.

Is it possible that people can choose between index.md or readme.md as "indexing" file of the folder? This would be great for us as we don't have to rename 100+ files in our existing folders (and probably as well for others that want to start using this feature) :)

**Comment by Mister-Hope** [comment]
> As practice (at least in the previous vue versions) it was recommended to always have an index.md file. This is also better practices for indexing sites as Google to have an index.html file in folders.

NO, as the core team member of VuePress, I can say that `index.md` is never ever encouraged, unless you are using VitePress.

https://v1.vuepress.vuejs.org/guide/directory-structure.html#default-page-routing

**Comment by robertraaijmakers** [comment]
Wow, that is a quick fix! Thank you very much!

Back then I understood the support of index.md differently, so thought it was supported. But great to see that it is now back! 👍 
https://v1.vuepress.vuejs.org/guide/markdown.html#links
https://github.com/vuejs/vuepress/issues/944
https://vuepress.github.io/guide/page.html#routing
