### ISSUE TITLE
[Feature Request] Pure feature

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress-theme-hope/vuepress-theme-hope#438]
I am going to build a `pure` mode for those who are using this theme as a doc theme.

In the pure mode, the hint is no more with emojis, and some animations and fancy buttons will be disabled. And the rest of the screen will be blured while reading, just like [nuxt docs](https://zh.nuxtjs.org/guide)

The new option will be:

```js
module.export = {
  themeConfig: {
    pure: true,
  }
};
```

---

This feature may or may not be shipped with 1.6.0.

**Comment by Cokaps** [comment]
> In the pure mode, the hint is no more with emojis, and some animations and fancy buttons will be diabled. And the rest of the screen will be blured while reading, just like [nuxt docs](https://zh.nuxtjs.org/guide)

I think you mean disable not diable, aren't you?

**Comment by Mister-Hope** [comment]
Closed as it's been added. (Futher optimized is needed though)
