### ISSUE TITLE
[Bug] navbar配置里类型报错

### ISSUE THREAD

**Issue by ifrvn** [vuepress-theme-hope/vuepress-theme-hope#4393]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

navbar配置里的类型有问题，children的children里写字符串会报错

图里是默认的demo

![image](https://github.com/user-attachments/assets/02d790c0-976b-4eab-a70b-110aa60f9ae4)
![image](https://github.com/user-attachments/assets/aecc111d-26d0-43a2-b347-1c2a2c0add46)

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/433e8375d8f06fa24cd85ec56e51d075626b52d1
