### ISSUE TITLE
[Bug]代码块分组的机型适配问题

### ISSUE THREAD

**Issue by CuteReimu** [vuepress-theme-hope/vuepress-theme-hope#4396]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

部分机型在代码块分组的显示有适配问题，如图。

有问题的（宽度撑满了）：
![image](https://github.com/user-attachments/assets/5c9a8c18-7d0f-45c9-a6bd-188b39a3d214)

没问题的：
![image](https://github.com/user-attachments/assets/ac15894d-fd0e-4309-9dd7-56dea9f1c0a1)

使用电脑浏览器的开发者模式切换不同机型预览也能看出部分机型有问题，部分机型没有问题。

**Comment by jinyu2022** [comment]
怎么两张图的圆角样式也不一样？

**Comment by CuteReimu** [comment]
> 怎么两张图的圆角样式也不一样？也是bug？感觉第一张图才是正确的样式

第一张图圆角是不是出屏幕了

**Comment by Mister-Hope** [comment]
This is not a bug, on narrow screen devices, we choose to disable code block horizontal margin to improve readability for code blocks.

**Comment by Mister-Hope** [comment]
Oh I get you, there is a incorrect margin with code tabs.

**Comment by CuteReimu** [comment]
@Mister-Hope 似乎仍然有问题，可以看本项目的文档，这里就有问题了：

https://theme-hope.vuejs.press/zh/guide/markdown/grammar/tex.html#%E9%85%8D%E7%BD%AE

![image](https://github.com/user-attachments/assets/d06b2d71-fae3-4af0-9225-c02e37c9cc9c)

环境：MacOS Google浏览器

**Comment by Mister-Hope** [comment]
这个已经修过了，还没发

**Comment by CuteReimu** [comment]
这次是代码块的问题，不同机型的表现有很明显的不同，部分机型的代码块会拉满整个屏幕宽度，不知是设计如此还是仍有问题？ @Mister-Hope 
![image](https://github.com/user-attachments/assets/58cc7f19-3046-4e4c-b174-8db1218f7e74)
![image](https://github.com/user-attachments/assets/e0409fb9-5628-41ff-8943-3830d5720ed6)

**Comment by Mister-Hope** [comment]
根据屏幕大小来的吧

**Comment by CuteReimu** [comment]
不是的，有的是填满整个屏幕宽度，有的是左右留了小部分空白，有很明显的区别，这个在我上面一条回复的两张截图可以看到。
