### ISSUE TITLE
如何在Slides中支持Reveal.js的Chalkboard插件

### ISSUE THREAD

**Issue by abelit** [vuepress-theme-hope/vuepress-theme-hope#4397]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

希望在vuepress中集成Reveal.js插件， 如chalkboard插件非常好用。

Reveal.js插件示例： https://github.com/rajgoel/reveal.js-demos
Reveal.js插件地址： https://github.com/rajgoel/reveal.js-plugins/tree/master/chalkboard

**Comment by Mister-Hope** [comment]
https://plugin-md-enhance.vuejs.press/zh/guide/content/revealjs/#%E8%87%AA%E5%AE%9A%E4%B9%89-reveal-js
