### ISSUE TITLE
Vuepress实现朋友圈功能

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#4398]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

hexo项目地址：https://github.com/Rock-Candy-Tea/hexo-circle-of-friends

效果：https://blog.bornforthis.cn/fcircle/

这样很方便订阅别人的文档或者新文章，希望有机会支持～

**Comment by Mister-Hope** [comment]
Again: VuePress is a static site generator.
