### ISSUE TITLE
Code blocks on mobile are buggy

### ISSUE THREAD

**Issue by IcySnex** [vuepress-theme-hope/vuepress-theme-hope#4400]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

Hello,

I have noticed that the code blocks on mobile devices look very out of place. This is definitely a bug and not by design.

The font size is huge (see images attached).
Most of the code blocks look like this but not all of them for some reason. This is also visible on the official vuepress-hope-theme docs website.
![IMG_7384](https://github.com/user-attachments/assets/0865ccd7-48b0-42d0-9f96-578715f9cf58)
![IMG_7385](https://github.com/user-attachments/assets/a2fec191-4373-4239-826f-faf71479a514)
![IMG_7386](https://github.com/user-attachments/assets/d62840bf-b391-4a93-8403-6304fcbec25c)

### Additional context

This issue did not occurr when testing in dev tools on a Desktop browser. This issue only occurred on an actual mobile device (iOS).

I have not tested on other mobile devices. Maybe it is an issue with the iOS Safari browser engine.

**Comment by Mister-Hope** [comment]
This is weird,  All styles are expected into a single xss file,  So it would be strange for you to say that some of the cold blocks are fine while others are not.

I don't have a mac device to debug it,  So I can only leave this issue here.

**Comment by IcySnex** [comment]
See the 3rd screenshot: The top code block looks completely fine but the second code block (only a few lines under the first one) is absolutely huge.

I have just tested the website on an iPadOS device and it looks completely fine - no bugs at all. I have also quickly fired up an Android emulator to check there and it looks normal as well, so it's only an issue with iPhone devices.

On the same iOS device I have visited a default themed VuePress site and it looks normal.
I thought maybe the issue is because of the "Shiki code block styling" but I have visited their site and it also looked completely fine.
So I could only think of an issue with this theme specifically.

**Comment by Mister-Hope** [comment]
The default theme and shiki theme are all developed by me, and I am sure they are using the same style.

**Comment by IcySnex** [comment]
That seems really weird then. Do you have any idea by what this issue is caused and how we could fix it?

**Comment by Mister-Hope** [comment]
> I don't have a mac device to debug it, So I can only leave this issue here.

No

**Comment by Mister-Hope** [comment]
![image](https://github.com/user-attachments/assets/f032eced-bd29-47d6-b4b0-d29589c2cdea)![image](https://github.com/user-attachments/assets/3d5d5f7f-3309-46e9-a73d-e9035f688bbc)
Hi , I can not reproduce it on iOS 18.

Further information is needed.

**Comment by IcySnex** [comment]
Hello,
thanks for coming back to this issue.

While trying to create a reproduction project I have noticed that the issue has been fixed in the latest vuepress update which released a week ago. Updating from `"vuepress": "2.0.0-rc.14"` to `"vuepress": "2.0.0-rc.17"` fixed all weird scaling issues of code blocks on iPhone devices.
I have also noticed that the vuepress-theme-hope has updated its vuepress dependency so no issues on this site anymore as well.

Updating though, has messed up my theme-color and all my other custom pallete colors.

**Comment by Mister-Hope** [comment]
The whole palette system are rebuild, you can check the docs.

**Comment by IcySnex** [comment]
Thank you, I am currently retheming everything.

Though, I'm a bit confused on why the `theme-color` in `config.scss` only uses the hue value of the color.
So for example `#ffa6a6` gets translated to `#ff0000`. I havent found anything in the docs about this.
It could be possible that I am overlooking something.

**Comment by Mister-Hope** [comment]
We are taking control of theme color lightness for a set of theme colors, you can manually set those colors e.g. `$vp-c-accent` as you like
