### ISSUE TITLE
[Bug]多语言模式设置默认语言为中文

### ISSUE THREAD

**Issue by Cuteli12138** [vuepress-theme-hope/vuepress-theme-hope#4407]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

抱歉我没有找到设置默认语言的选项（如果有的话希望告知我谢谢），我想把根目录默认语言设为中文（考虑到初期主要受众是国内用户，但不排除国外受众的可能性），采用了比较粗暴的办法，建立/en目录，把生成的英文文件全扔进去，再把中文的文件移出来，更改config、theme等文件（很繁琐还是希望直接配置比较好），执行，然后终端一直显示`Initializing and preparing data`，电脑出现明显卡顿。

**Comment by bennyz327** [comment]
@Cuteli12138 配置有修改正確應該是沒問題的，可以參考我將默認根路徑改為中文的個人網站的[源碼](https://github.com/bennyz327/bennyz327.github.io/tree/main/blog/vuepress-theme-hope/src)
你可以比對一下你的配置哪邊不一樣

**Comment by Cuteli12138** [comment]
@bennyz327 我看你的源码在config.ts文件里把/en注释掉了，我这边注释后也是没问题的，不过英文就没法启用了，不注释就出现上述情况。

**Comment by Mister-Hope** [comment]
https://theme-hope.vuejs.press/zh/config/i18n.html

**Comment by smallfawn** [comment]
我也是这个问题 明明改了zh-CN了还是英文 不知道为啥
