### ISSUE TITLE
[Feature Request]ECharts实在是太大了，有没有办法可以把按需打包的插件引入进这个项目？

### ISSUE THREAD

**Issue by CuteReimu** [vuepress-theme-hope/vuepress-theme-hope#4408]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

目前的Echarts似乎采用的是全导入，这样打包出来的js文件差不多有1MB以上，在正常的网速下首次打开页面加渲染加图标显示完毕差不多要10秒左右。

目前已有成熟的开源的按需打包插件，有没有什么办法可以引入到这个项目来？

**Comment by Mister-Hope** [comment]
> 目前已有成熟的开源的按需打包插件，有没有什么办法可以引入到这个项目来？

Reference plz

**Comment by Mister-Hope** [comment]
> 另外，在Echarts官网上也提供了在线定制，只下载需要的模块的echarts.min.js的方式。

你可以使用 alias，将 echarts 设置为你定制的更小文件的别名。

**Comment by Mister-Hope** [comment]
不过也许这可以作为未来的一个优化点。

一个难点在于插件可能需要生成临时文件来优化入口，这可能会较大幅度的增加开发服务器的启动时间与打包用时。

**Comment by Mister-Hope** [comment]
我本地试了一下，echarts 默认是有压缩好的 min.js 的，这很快，如果改用生成临时文件的方式，webpack的启动时间会极大增加，因此就不再推进了。如果有更好的意见欢迎提出。
