### ISSUE TITLE
[Bug] 当前代码演示中vue和react类型无法正常显示

### ISSUE THREAD

**Issue by flysha1** [vuepress-theme-hope/vuepress-theme-hope#4409]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

当前代码演示中vue和react类型无法正常显示

![屏幕截图 2024-09-03 135022](https://github.com/user-attachments/assets/78b756e0-32d1-414b-8655-b7831d3ae25b)

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/4355
