### ISSUE TITLE
[Bug]import CommonWrapper from "@theme-hope/components/CommonWrapper";或import NormalPage from "vuepress-theme-hope/components/NormalPage.js";报错

### ISSUE THREAD

**Issue by CZHanoi** [vuepress-theme-hope/vuepress-theme-hope#4419]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

我在使用自己添加的组件PageFooter时，为了替换成新的footer，引入了
`import HopePageFooter from "vuepress-theme-hope/components/PageFooter.js";`
出现了报错
Failed to resolve import "@theme-hope/composables/index" from "node_modules/.pnpm/vuepress-theme-hope@2.0.0-rc.52_markdown-it@14.1.0_vuepress@2.0.0-rc.14_@vuepress+bundler-vit_7mkiy3yfqqhrbzmj6qd5ncyt4i/node_modules/vuepress-theme-hope/lib/client/components/PageFooter.js?v=45638155". Does the file exist?

**Comment by CZHanoi** [comment]
Or is there another way to replace the theme Footer？

**Comment by CZHanoi** [comment]
I'm sorry, it's a little urgent. Could you give me an answer as soon as possible?

**Comment by CZHanoi** [comment]
alias: {
    "@theme-hope/components/PageFooter": footerPath,
/*     "@theme-hope/modules/navbar/components/Navbar": path.resolve(
      __dirname,
      "./components/Navbar.vue"
    ), */

  }
I do this but no use.

**Comment by Mister-Hope** [comment]
set `custom: true` in theme behavior options, this is clearly described in docs.
