### ISSUE TITLE
[Bug]Webpack没办法本地引用字体

### ISSUE THREAD

**Issue by CZHanoi** [vuepress-theme-hope/vuepress-theme-hope#4462]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

当前版本用Webpack没办法本地引用字体，
```
ERROR in ./node_modules/.pnpm/vuepress-theme-hope@2.0.0-rc.52_@vuepress+plugin-pwa@2.0.0-rc.39_vuepress@2.0.0-rc.14_@vuepre_p6cckxkmktxkyn433ewc66u4ay/node_modules/vuepress-theme-hope/lib/client/styles/index.scss (./node_modules/.pnpm/css-loader@7.1.2_webpack@5.94.0/node_modules/css-loader/dist/cjs.js??clonedRuleSet-9.use[1]!./node_modules/.pnpm/postcss-loader@8.1.1_postcss@8.4.47_webpack@5.94.0/node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-9.use[2]!./node_modules/.pnpm/sass-loader@14.2.1_sass@1.78.0_webpack@5.94.0/node_modules/sass-loader/dist/cjs.js??clonedRuleSet-9.use[3]!./node_modules/.pnpm/vuepress-theme-hope@2.0.0-rc.52_@vuepress+plugin-pwa@2.0.0-rc.39_vuepress@2.0.0-rc.14_@vuepre_p6cckxkmktxkyn433ewc66u4ay/node_modules/vuepress-theme-hope/lib/client/styles/index.scss) 7:36-84
Module not found: Error: Can't resolve 'BerlinSansFBDemi.ttf' in 'C:\Users\Hanoi\Desktop\Saomei\as\fudan\node_modules\.pnpm\vuepress-theme-hope@2.0.0-rc.52_@vuepress+plugin-pwa@2.0.0-rc.39_vuepress@2.0.0-rc.14_@vuepre_p6cckxkmktxkyn433ewc66u4ay\node_modules\vuepress-theme-hope\lib\client\styles'
```
我已经排除是路径的问题。

**Comment by CZHanoi** [comment]
Intrestingly, when I use Vite, the same code works perfectly fine.

**Comment by Mister-Hope** [comment]
Seems to be the same thing as https://github.com/vuepress/core/issues/1443
