### ISSUE TITLE
[Warn] It seems that some components are registered repeatedly.

### ISSUE THREAD

**Issue by CuteReimu** [vuepress-theme-hope/vuepress-theme-hope#4463]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

When I run  `npm run docs:build`, it says:

```
✔ Initializing and preparing data - done in 827ms
✔ Compiling with vite - done in 5.37s
⠋ Rendering 31 pages
[Vue warn]: Component "ChartJS" has already been registered in target app.
[Vue warn]: Component "CodeTabs" has already been registered in target app.
[Vue warn]: Component "CodeGroup" has already been registered in target app.
[Vue warn]: Component "CodeGroupItem" has already been registered in target app.
[Vue warn]: Component "MarkMap" has already been registered in target app.
✔ Rendering 31 pages - done in 323ms
success VuePress build completed in 6.84s!
```

### Additional context

This warning is introduced in the latest version `2.0.0-rc.53`. It works well before.

**Comment by Mister-Hope** [comment]
Already tracked and fixed upstream, needs a new version
