### ISSUE TITLE
[Bug]mark标记失效

### ISSUE THREAD

**Issue by HappySimple** [vuepress-theme-hope/vuepress-theme-hope#4464]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

语法"==xxx=="失效

**Comment by CuteReimu** [comment]
I encountered the same bugs. It doesn't work since the version `v2.0.0-rc.53`.
