### ISSUE TITLE
[Bug] Compiling fails because generated config.js has invalid syntax (mismatched parentheses)

### ISSUE THREAD

**Issue by tchajed** [vuepress-theme-hope/vuepress-theme-hope#4473]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

In v2.0.0-rc.54 I'm getting this error when running `vuepress build docs`:

> ✖ Compiling with vite - failed in 72ms
[vite:build-import-analysis] [plugin vite:build-import-analysis] docs/.vuepress/.temp/theme-hope/config.js: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.

I have a fix ready and will submit a PR right away.

### Additional context

This bug was introduced in c817d03a51cee1606. The similar changes in prepareConfigFile.ts are correct because they also remove `defineUserConfig(`, but prepareBundleConfigFile.ts is buggy.

**Comment by Mister-Hope** [comment]
https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/ed1535312112fcfe4e0e2bb877c610a5268a8d36
