### ISSUE TITLE
[Feature Request] 博客文章列表标题和摘要增强提示

### ISSUE THREAD

**Issue by Alex6357** [vuepress-theme-hope/vuepress-theme-hope#4476]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

建议把博客文章列表的标题做成鼠标移动上去变色同时下划线，摘要做成可以点进文章，提示性更强

**Comment by Mister-Hope** [comment]
The excerpt content may contain interactive elements, e.g.: A detail container.

In this case we can not make the excerpt clickable.

For the title, it's constant against navbar items, and I don't think it need to be changed.
