### ISSUE TITLE
[Feature Request] Provide focus mode

### ISSUE THREAD

**Issue by Snailclimb** [vuepress-theme-hope/vuepress-theme-hope#4478]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

在文章阅读界面提供一个沉浸式阅读模式按钮，点击该按钮进入沉浸式阅读，沉浸式阅读模式下侧边栏和导航栏都模糊掉只显示文档的主体，包括文章内容和目录。

### Additional context

这个功能对于知识文档类网站还挺实用的，可以挺高阅读体验。

**Comment by Mister-Hope** [comment]
I am wondering the option name
