### ISSUE TITLE
[Feature Request]  Date format in Timeline

### ISSUE THREAD

**Issue by leandro-costa** [vuepress-theme-hope/vuepress-theme-hope#4479]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

the date formatting in timeline is not considering the locale. perhaps changing the line 

https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/main/packages/theme/src/client/modules/blog/composables/setupTimeline.ts#L60
 
to 

... get locale ...

`date: result.toLocaleDateString(locale , {month: "numeric",day: "numeric"})`

may be a good option

### Additional context

In pt-BR date format is dd/mm

**Comment by Mister-Hope** [comment]
Thank you for your suggestion. https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/50635863bd3a4447b0843aae65a895578bd12722
