### ISSUE TITLE
[Bug]The timeline isn't showing right

### ISSUE THREAD

**Issue by zxwin0125** [vuepress-theme-hope/vuepress-theme-hope#4495]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

![image](https://github.com/user-attachments/assets/b856ad21-985b-493f-95f0-90027d9ca041)
这里显示重复的时间线，但是我并没有这个日期的文档记录，不应该出现这个日期的时间线

**Comment by King-sj** [comment]
![屏幕截图 2024-10-25 095740](https://github.com/user-attachments/assets/20a02482-b1a8-4460-a9be-310ade2aae61)

我也出现了这个问题， 每次提交后， 所有文章更新的时间都变成了最新的一天。
我是通过Github Actions 构建和部署的。
