### ISSUE TITLE
[Bug]博客文章摘要中，代码块与行号重合

### ISSUE THREAD

**Issue by Leo01234** [vuepress-theme-hope/vuepress-theme-hope#4497]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

![](https://github.com/user-attachments/assets/619505e9-cd85-439b-9325-5ffea6281b62)

**Comment by sakamoto-poteko** [comment]
Do you have an ETA for this? The misaligned code block is quite annoying, especially when it's colorfully rendered.

<img width="176" alt="image" src="https://github.com/user-attachments/assets/5f9dc5a9-7be9-4124-b1e9-91d1aad2f786">

**Comment by Mister-Hope** [comment]
You can have your own fix by adding extra css, so this does not have a high priority
