### ISSUE TITLE
[Bug] SCSS font settings are no longer respected in the latest version

### ISSUE THREAD

**Issue by sakamoto-poteko** [vuepress-theme-hope/vuepress-theme-hope#4505]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

It seems that the SCSS font settings are no longer being applied correctly in the latest version.

As outlined in the [documentation](https://theme-hope.vuejs.press/guide/customize/font.html#font-library), fonts should be customizable via `styles/palette.scss`. This configuration worked as expected in earlier versions, specifically in rc.52, prior to the recent update.

However, after upgrading to rc.58, the settings in `palette.scss` no longer seem to take effect.

Here’s a minimal diff to reproduce the issue using a new template repository (`pnpm create vuepress-theme-hope my-docs`):
```diff
diff --git a/src/.vuepress/config.ts b/src/.vuepress/config.ts
index f339377..9fd297d 100644
--- a/src/.vuepress/config.ts
+++ b/src/.vuepress/config.ts
@@ -9,6 +9,24 @@ export default defineUserConfig({
   title: "Blog Demo",
   description: "A blog demo for vuepress-theme-hope",
 
+  head: [
+    //...
+
+    // Import the corresponding link
+    ["link", { rel: "preconnect", href: "https://fonts.googleapis.com" }],
+    [
+      "link",
+      { rel: "preconnect", href: "https://fonts.gstatic.com", crossorigin: "" },
+    ],
+    [
+      "link",
+      {
+        href: "https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@400;500;700&display=swap",
+        rel: "stylesheet",
+      },
+    ],
+  ],
+
   theme,
 
   // Enable it with pwa
diff --git a/src/.vuepress/styles/palette.scss b/src/.vuepress/styles/palette.scss
index d271cb0..044f99b 100644
--- a/src/.vuepress/styles/palette.scss
+++ b/src/.vuepress/styles/palette.scss
@@ -1 +1,3 @@
 // you can change colors here
+// apply font
+$font-family: "Helvetica, Lora, serif";
```

![image](https://github.com/user-attachments/assets/20aa6938-6239-4829-a2fc-d437ac7733ba)
![image](https://github.com/user-attachments/assets/8399ce44-ca81-4cdd-bac4-510cceea6217)

### Additional context

```
$ node -v
v20.15.0
$ pnpm -v
9.9.0
```

**Comment by Mister-Hope** [comment]
https://theme-hope.vuejs.press/config/style.html#font

**Comment by sakamoto-poteko** [comment]
Ah, I see. Thanks for the clarification. Would it be possible for you to update the documentation https://theme-hope.vuejs.press/guide/customize/font.html#font-library to help prevent any further confusion?

Thanks!
