### ISSUE TITLE
[Bug] Writing and last modified dates no longer come from git

### ISSUE THREAD

**Issue by tchajed** [vuepress-theme-hope/vuepress-theme-hope#4507]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

I'm not seeing git-based writing date or last modified dates in my website. They do show up when running a development server with `--debug`, but not in production.

I added `fetch-depth: 0` to my CI build, and I also tried building locally.

### Additional context

This bug doesn't appear in v2.0.0-rc.56 but does in v2.0.0-rc.58, which means it was quite recently introduced.

**Comment by tchajed** [comment]
This is fixable by adding `plugins.git: { createdTime: true, updatedTime: true }` (or simply `plugins.git: true`) to the theme config, at the cost of also getting git information during development.

The docs mention this approach only in the context of the dev server. I still think there's a regression in how this is handled.

**Comment by CuteReimu** [comment]
```ts
{
  plugins: {
    process.env.NODE_ENV === "production",
  }
}
```

**Comment by Mister-Hope** [comment]
This is weird because I did not change any related code at all.

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/core/issues/1612
