### ISSUE TITLE
[Bug] date in frontmatter cannot be set manually

### ISSUE THREAD

**Issue by tchajed** [vuepress-theme-hope/vuepress-theme-hope#4509]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

Trying to set the `date` frontmatter field to a date string (which the [documentation](https://theme-hope.vuejs.press/config/frontmatter/info.html#date) says is allowed) results in an error during build:

```
⚠ date in frontMatter should be a valid Date
```

The code is checking that the field is an instance of `Date` but in this case it needs to be a string.

**Comment by Mister-Hope** [comment]
js-yaml support date values, and I believe you should try to do a search yourself.

Otherwise, you should at least give some error examples for me to correct you.

**Comment by tchajed** [comment]
You're right, I should've given exactly what I tried. I was using `date: "2024-09-04"` and it should be `date: 2024-09-04` (and in practice you need a time as well).

I did not think to search for exactly this since it was outside my mental model for how YAML works - I thought these were all parsed as strings and interpreted by the consumer, and the code I read does not do this. I did look for the type of the field, `DateString`, which doesn't turn up anything relevant.

I don't mean to waste your time.
