### ISSUE TITLE
[Bug]“页面信息”中的"写作日期"不见了

### ISSUE THREAD

**Issue by CuteReimu** [vuepress-theme-hope/vuepress-theme-hope#4510]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Describe the bug

最新版本的更新中才出现的问题。
在本项目的文档中也可以看出来，写作日期不见了：https://theme-hope.vuejs.press/zh/guide/feature/page-info.html

不知是设计如此还是新引入的bug？

**Comment by tchajed** [comment]
I think this is the same as #4507 (based on a Google translation this issue to English).

**Comment by CuteReimu** [comment]
@tchajed Thanks a lot. So this issue is repeated. I'll close it.
