### ISSUE TITLE
[Bug] theme-color config panic

### ISSUE THREAD

**Issue by BTMuli** [vuepress-theme-hope/vuepress-theme-hope#4521]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

After config `$theme-color: #f6bec8l;` refer to [doc](https://theme-hope.vuejs.press/zh/guide/interface/theme-color.html#%E8%AE%BE%E7%BD%AE%E9%BB%98%E8%AE%A4%E4%B8%BB%E9%A2%98%E8%89%B2), 

it builds error and throw `[vite] Internal server error: [sass] Error: $map: #f6bec8l is not a map.`

Details: https://github.com/DGP-Studio/Snap.Hutao.Docs/actions/runs/11384834035/job/31673386129

**Comment by Mister-Hope** [comment]
This is werid, as all my other projects including [my blog](https://mister-hope.com) [waline](https://waline.js.org), [markdown-it plugins](https://mdit-plugins.github.io) [mptool](https://miniapp-tool.github.io) are all customizing theme colors, and they work fine.

Could you check your own customizations again?
