### ISSUE TITLE
[Feature Request] Ability to set the date format

### ISSUE THREAD

**Issue by AdamBearWA** [vuepress-theme-hope/vuepress-theme-hope#4541]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

Currently there isn't an easy way to override the date format. For example, in english it's always the US format. This is very confusing for users in my region as 9/1/2024 means the page is 9 months old in my region, but only 1 month old in the US.

Currently, to fix this requires creating a custom component, which isn't ideal as it would need maintaining every time.

Ideally, we should be able to set the date format in the theme configuration somewhere and have it passed through. Alternatively, it would be ok if we could customise only the parts of the components that have dates so we can override them without so much code.

Below is my example for updating the date format in the PageMeta component.

### Enable the custom theme option to expose @theme-hope

```
theme: hopeTheme({
  },
  {
    custom: true,
  }),
}
```

### Add an alias to the defaultUserConfig to overvide an existing component

```
alias: {
  "@theme-hope/modules/info/components/PageMeta": path.resolve(
    __dirname,
    "./components/PageMetaCustom.vue",
  ),
},
```

## Create a new component from scratch that replicates the existing component, but changes the date format

```
<template>
  <footer class="vp-page-meta">
    <div v-if="editLink" class="vp-meta-item edit-link">
      <AutoLink :config="editLink" class="vp-meta-label">
        <template #before>
          <EditIcon />
        </template>
      </AutoLink>
    </div>
    <div class="vp-meta-item git-info">
      <div v-if="formattedUpdatedTime" class="update-time">
        <span class="vp-meta-label">{{ metaLocales.lastUpdated }}: </span>
        <span class="vp-meta-info" data-allow-mismatch="text">{{ formattedUpdatedTime }}</span>
      </div>
      <div v-if="contributors.length" class="contributors">
        <span class="vp-meta-label">{{ metaLocales.contributors }}: </span>
        <span v-for="(contributor, index) in contributors" :key="contributor.email" class="vp-meta-info"
          :title="`email: ${contributor.email}`">
          {{ contributor.name }}<span v-if="index !== contributors.length - 1">,</span>
        </span>
      </div>
    </div>
  </footer>
</template>

<script setup>
import { computed } from 'vue'
import AutoLink from '@theme-hope/components/AutoLink'
import { EditIcon } from '@theme-hope/components/icons/index'
import { useThemeLocaleData } from '@theme-hope/composables/index'
import { useContributors, useEditLink, useUpdateTime } from '@theme-hope/modules/info/composables/index'
import { format } from 'date-fns'

const themeLocale = useThemeLocaleData()
const editLink = useEditLink()
const updateTime = useUpdateTime()
const contributors = useContributors()

// override the date format
const formattedUpdatedTime = computed(() => {
  if (updateTime.value) {
    return format(new Date(updateTime.value), 'd/M/yyyy h:mm aa')
  }
  return ''
})

const metaLocales = computed(() => themeLocale.value.metaLocales)
</script>

<style scoped>
@import "../styles/page-meta.scss";
</style>
```

**Comment by Mister-Hope** [comment]
> For example, in english it's always the US format.

I believe the page meta is calling toLocateString internally, so that if you set the page language to another English region value, it shall match the format in your location

**Comment by Mister-Hope** [comment]
Furthermore, you shall override the composable alias.

To do so, you shall write a customized useUpdateTime composable, and the re-export all other exports in the same file, then set it as alias of meta composable.

These will require less code than your implementation

**Comment by AdamBearWA** [comment]
> * Somehow you cannot set the language code to the correct one

This is correct. I'd like to set it to en-AU. I tried setting the lang to en-AU, but the site won't load when I do this. It will only load if lang isn't set or is set to en-US.

**Comment by Mister-Hope** [comment]
What do you mean by "the site won't load"?

The whole site goes blank or what?

Provide full terminal log and console messages

**Comment by AdamBearWA** [comment]
> Furthermore, you shall override the composable alias.
> 
> To do so, you shall write a customized useUpdateTime composable, and the re-export all other exports in the same file, then set it as alias of meta composable.
> 
> These will require less code than your implementation

I can try this, but I'm not sure what you mean about re-exporting all the other exports in the same file.

**Comment by AdamBearWA** [comment]
> What do you mean by "the site won't load"?
> 
> The whole site goes blank or what?
> 
> Provide full terminal log and console messages

Correct. 100% white page when changing `lang: 'en-US'` to `lang: 'en-AU'`. Console errors are below. Changing it back and the site loads immediately.

![image](https://github.com/user-attachments/assets/60caba01-ee96-419a-bdbc-55732ccd18c6)

![image](https://github.com/user-attachments/assets/196d3f22-dbdc-4d8f-84a0-1b6a3e7ac89d)

**Comment by AdamBearWA** [comment]
Based on [this page](https://theme-hope.vuejs.press/config/i18n.html#supported-languages) in the documentation, I assumed en-AU wasn't supported.

**Comment by AdamBearWA** [comment]
I tried to override the composable as you suggested, but I'm getting circular reference errors.

```
alias: {
    "@theme-hope/modules/info/composables/index": path.resolve(
      __dirname,
      "./composables/useUpdateTimeEnAU",
    ),
  },
```

```
import { computed } from "vue";
import { usePageData, usePageFrontmatter, /*useSiteLocaleData,*/ } from "vuepress/client";
import { useThemeLocaleData } from "@theme-hope/composables/index";
export const useUpdateTime = () => {
    //const siteLocale = useSiteLocaleData();
    const themeLocale = useThemeLocaleData();
    const page = usePageData();
    const frontmatter = usePageFrontmatter();
    return computed(() => {
        const showLastUpdated = frontmatter.value.lastUpdated ?? themeLocale.value.lastUpdated ?? true;
        if (!showLastUpdated)
            return null;
        if (!page.value.git?.updatedTime)
            return null;
        const updatedDate = new Date(page.value.git?.updatedTime);
        // hard code lang for testing
        return updatedDate.toLocaleString('en-AU');
    });
};
// Re-export
export { useContributors, useEditLink, useMetaLocale } from "@theme-hope/modules/info/composables/index";
```

```
Uncaught SyntaxError: Detected cycle while resolving name 'useContributors' in '/.vuepress/composables/useUpdateTimeEnAU.js' (at enau.js:19:10)
```

**Comment by Mister-Hope** [comment]
Hi this is fixed upstream at @vuepress/helper. The next version release will fix this, but I have plenty works to do across projects. So please be patient.
