### ISSUE TITLE
[Bug]关于 URL 大小写敏感导致网页 404 的问题

### ISSUE THREAD

**Issue by wzh656** [vuepress-theme-hope/vuepress-theme-hope#4555]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

在我使用含有大写字母的文件夹/文件名时, 访问时的 url 也会含有大写字母, 这在 docs:dev 环境和其它本地服务器环境下可以正常运作。
但当我尝试使用 Netlify 等服务器托管环境时, 按 F5 刷新网页时或直接通过 url 访问时, url 中大写字母会自动变成小写字母, 从而导致 404 错误, 这导致通过 url 访问时会发生 404 错误。尽管搜索引擎任然能爬取网站的内容, 但点击访问时却会得到一个 404 错误。这使我不得不手动修改所有文件夹和文件名变成小写。
但有时对于一些专有名词我希望能保持文件夹或文件名使用大写字母, 请问可以提供一个选项使打包生成的 url 自动变成小写吗?

**Comment by Mister-Hope** [comment]
Url是大小写敏感的，你可以自行配制netify
