### ISSUE TITLE
[Bug] Uncaught Error: SlimSearch: cannot deserialize an index created with an incompatible version

### ISSUE THREAD

**Issue by gspgsp** [vuepress-theme-hope/vuepress-theme-hope#4559]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [ ] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-plugin-search-pro

### Which operating system are you using?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Describe the bug

my current env:
"vuepress": "^2.0.0-rc.18",
 "vuepress-plugin-search-pro": "^2.0.0-rc.59"
 
 use in config.js:
 import { searchProPlugin } from "vuepress-plugin-search-pro";
 
 searchProPlugin({
            autoSuggestions: false,
            indexContent: true,
            queryHistoryCount: 0,
            resultHistoryCount: 60,
        })
        
when click search box,  it will report the following errors:
Uncaught Error: SlimSearch: cannot deserialize an index created with an incompatible version

**Comment by Mister-Hope** [comment]
Clean cache and run again, it's possible that you have a outdated search worker cached.

**Comment by talhasaeed22** [comment]
I am also facing the same issue. I have run on different browsers and different laptops. But error message is same.

**Comment by gspgsp** [comment]
> Clean cache and reload the window, it's possible that you have a outdated search worker cached.
thanks for your reply, i had tried many times, and run on different browsers and different computers, but the error message is same.

**Comment by mo7cc** [comment]
![8e5c905e39a2be4a484880749532789e](https://github.com/user-attachments/assets/6a344bff-d81c-4c8d-851b-0db4d15a9de9)
遇到了同样的问题。我非常确信这是一个BUG

**Comment by Mister-Hope** [comment]
Can anyone give me a living reproduction?

The plugin is already rebuilt as `@vuepress/plugin-slimsearch` via an existing PR, but the PR is working fine.

**Comment by Novices666** [comment]
After I installed it, it ran normally in the development environment, but after packaging, the same error was reported.

**Comment by Mister-Hope** [comment]
This plugin will be deprecated immediately without future release.

The official replacement is `@vuepress/plugin-slimsearch`. Please check it, and report to VuePress/ecosystem if same issue occurs. 

Thanks to everyone who reporting this.

**Comment by Novices666** [comment]
> This plugin will be deprecated immediately without future release.
> 
> The official replacement is `@vuepress/plugin-slimsearch`. Please check it, and report to VuePress/ecosystem if same issue occurs.
> 
> Thanks to everyone who reporting this.

OK, thank you. Is there any configuration item document for the new replacement? Is it still the same as before?

**Comment by Mister-Hope** [comment]
Documentation here: https://ecosystem.vuejs.press/plugins/search/slimsearch.html

The behavior should be the same
