### ISSUE TITLE
[Bug]幻灯片中的图片无法和普通页面一样被正确展现

### ISSUE THREAD

**Issue by wood3** [vuepress-theme-hope/vuepress-theme-hope#4571]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [X] Linux

### Describe the bug

```markdown
---
title: 测试
---

![这里可以成功看到图片](1.jpg)

@slidestart blood

## 测试

![这里的图片无法看到](1.jpg)

@slideend
```

我正常配置了幻灯片工具，幻灯片的其他功能没有问题，使用 webpack 打包和预览时看到图片的情况如上。

（顺便，使用 vite 时 docs:dev 没有问题，但是 build 会出错，所以转成了用 webpack）

**Comment by Mister-Hope** [comment]
这是因为markdown是交给revealjs渲染的，因此打包器并不清楚存在一个需要打包的图片，也不会替换路径。因此不能使用相对路径图片。
