### ISSUE TITLE
[Feature Request]自动生成侧边栏的，能不能实现设置默认的 icon 呢？

### ISSUE THREAD

**Issue by AndersonHJB** [vuepress-theme-hope/vuepress-theme-hope#4579]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

<img width="2560" alt="image" src="https://github.com/user-attachments/assets/fbfc883e-cdef-45ae-a5d6-595e9eb26a57">
自动生成侧边栏的，能不能实现设置默认的 icon 呢？

**Comment by Mister-Hope** [comment]
No, setting a default icon doesn't mean anything.

A icon should represent the page content and differ from the siblings
