### ISSUE TITLE
[Feature Request]组件库支持Aplayer

### ISSUE THREAD

**Issue by yyyytawa** [vuepress-theme-hope/vuepress-theme-hope#4580]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

一个美观的音乐播放器
官网: https://aplayer.js.org/

**Comment by Mister-Hope** [comment]
https://github.com/u2sb/vuepress-plugin-sbaudio
