### ISSUE TITLE
[Bug] `.sr-only` class is blocking the logo on the page

### ISSUE THREAD

**Issue by rockbenben** [vuepress-theme-hope/vuepress-theme-hope#4619]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

The `<a href="#main-content" class="vp-skip-link sr-only">跳至主要內容</a>` element, appears to be blocking the logo on the page. To resolve this, I added the following CSS to the `.sr-only` class to ensure it doesn’t visually block other content:

```css
.sr-only { 
  clip: rect(0, 0, 0, 0);
}
```

With this addition, the skip link no longer affects the layout, and everything appears to work fine.

![image](https://github.com/user-attachments/assets/d63d9ec6-80c2-40c3-8b96-51bff93749b5)
![image](https://github.com/user-attachments/assets/94903bca-6ac9-49b1-bb51-11b146cd3c21)

**Comment by Mister-Hope** [comment]
So if my understanding is correct, you are reporting that `sr-only` styles are lost in the new version?

**Comment by rockbenben** [comment]
> So if my understanding is correct, you are reporting that `sr-only` styles are lost in the new version?

Yes

**Comment by Mister-Hope** [comment]
This is werid, sr-only style import is added in theme client config file, see:

- https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/ded153a30f632f0169b8383605be6128548c996c/packages/theme/src/node/prepare/prepareBundleConfigFile.ts#L81
- https://github.com/vuepress-theme-hope/vuepress-theme-hope/blob/ded153a30f632f0169b8383605be6128548c996c/packages/theme/src/node/prepare/prepareSeparatedConfigFile.ts#L79

I would prefer a reproduction

**Comment by rockbenben** [comment]
Yes, the issue can be reproduced in [this repository](https://github.com/rockbenben/LearnData). 

However, it doesn't work on StackBlitz as expected. Please downloading the repository to your local machine and running it there.

**Comment by Mister-Hope** [comment]
https://github.com/vuepress/ecosystem/pull/297
