### ISSUE TITLE
[Bug] iconfont阿里巴巴矢量库不能正常显示

### ISSUE THREAD

**Issue by StarsPicking** [vuepress-theme-hope/vuepress-theme-hope#4628]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

| 环境 | 版本 |
| ------------- | ------------- |
| 系统  | windows11  |
| 浏览器  | Edge&chrome  |
| vuepress  | 2.0.0-rc.19  |
| vuepress-theme-hope  | 2.0.0-rc.63  |
 
> 按照最新文档，设置自定义阿里矢量库图标`iconAssets: "//at.alicdn.com/t/c/font_4780043_v0hrgp3lqf.css"`
> 按照说明无论设置或者不设置`iconPrefix: "iconfont icon-"`,都无法显示自定图标
> f12看对应的css应该是加载了，请问这块是新版本有问题吗

- 原配置情况下加载可以正常显示
- ![1734168302676](https://github.com/user-attachments/assets/0e5b326d-eaef-4598-a681-29d0c80784ce)
- 自定义加载
    - 个人设置截图
    - ![image](https://github.com/user-attachments/assets/77fa391b-6336-4426-a683-f2d004f9ecd8)
    -  css资源加载情况
    - ![1734168523877](https://github.com/user-attachments/assets/f97e358a-37ca-4c7f-9d8e-1ec0a547b9c5)
    - 图标不显示
    - ![1734168639656](https://github.com/user-attachments/assets/bf849d5a-a2c6-4f5c-bb87-235c0fdf3aab)

- 请问是我设置有问题，还是这块有bug？按照文档的解释，我理解，如果使用阿里矢量库图标，直接设置对应项目的`iconAssets:`就可以了？我尝试过设置`iconPrefix`，但是效果和上面截图是一样的。请问我该如何处理这种情况

**Comment by typed-sigterm** [comment]
如果使用 TS 可以发现 `iconfont` 已经不在 `iconAssets` 的枚举值中了，see a50a4d546bcbb981966c3b6144293936e443c274

**Comment by DeepOcean299** [comment]
@typed-sigterm 首先感谢您的回复，我懂了为何会出现这种情况。另外，我想，如何在项目中添加除了枚举类型以外的图标，是否可以通过 icon: https://example/xxxxicon.svg(png) or icon: AbsolutePath/ xxxxicon.svg(png) 的形式去使用

**Comment by Mister-Hope** [comment]
I think you should double check the iconfont guideline in docs. Iconfont is still supported and my blog https://mister-hope.com is working as expected in latest version.

**Comment by DeepOcean299** [comment]
> I think you should double check the iconfont guideline in docs. Iconfont is still supported and my blog https://mister-hope.com is working as expected in latest version.
> 
> If you insist there are issues, provide a valid minimal reproducion.

@Mister-Hope 感谢回复，我将主题升级到最新版，并且重新复现了这个问题，并且提供了三个文件，并且在readme.md中详细描述了复现步骤，以及文件中的具体改动，目前我的结论是`setupTransparentNavbar` 会影响到图标加载。详情请移步至仓库https://github.com/DeepOcean299/vuepress-theme-hope-bug4628/tree/main

**Comment by DeepOcean299** [comment]
> 我认为你应该仔细检查文档中的 iconfont 指南。Iconfont 仍然受支持，我的博客 https://mister-hope.com 在最新版本中按预期工作。
> 
> 如果您坚持认为存在问题，请提供有效的最小重现。

@Mister-Hope 感谢回复，我将主题升级到最新版，重新复现了这个问题。我提供了三个文件，并且在 readme.md 中详细描述了复现步骤，以及文件中的具体改动，目前我的结论是`setupTransparentNavbar`会影响到图标加载。详情请移步至仓库 https://github.com/DeepOcean299/vuepress-theme-hope-bug4628/tree/mainsetupTransparentNavbar

**Comment by Mister-Hope** [comment]
Can you deploy it somewhere for me to preview it?

**Comment by DeepOcean299** [comment]
> Can you deploy it somewhere for me to preview it? E.g.: Github Pages

@Mister-Hope 我通过npm run docs:build 部署后不会出现问题，但是通过npm run docs:dev在本地运行会出问题，我不是前端工作者，所以不知道具体的细节差异在哪里。我提供了更改的具体文件

[需要替换的文件.zip](https://github.com/user-attachments/files/18141237/default.zip)

以及复现步骤供您参考：
https://github.com/DeepOcean299/vuepress-theme-hope-bug4628.git

如果有打包dev环境下的文件的方法，那么我会尝试通过deploy的方式来复现

**Comment by Mister-Hope** [comment]
The problem is I can not reproduce what you are reporting even following your reproduction guidelines.

Try clear cache and use another browser. I question that this could be your own issue.

**Comment by StarsPicking** [comment]
@Mister-Hope   好的。那我关闭了这个问题了。谢谢解答
