### ISSUE TITLE
[Bug] unable to turn off i18n notification for switching languages 

### ISSUE THREAD

**Issue by NeonGooRoo** [vuepress-theme-hope/vuepress-theme-hope#4644]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

![IMG_20241217_095222_095](https://github.com/user-attachments/assets/da5c3f2e-61b1-4957-a523-5968ca73c961)
This thing. Using the i18n settings brings error that the theme doesn't have such a variable

**Comment by Mister-Hope** [comment]
Set `plugins.redirect: false`, for details see @vuepress/plugin-redirect docs.
