### ISSUE TITLE
[Feature Request] Support Page Merging for Printing Full courses or documents

### ISSUE THREAD

**Issue by aaronlippold** [vuepress-theme-hope/vuepress-theme-hope#4662]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

Many times users break up their classes, guides etc into sections for easier reading but sometimes we need a 'pdf or word' version of the online content. Supporting something like:

<https://github.com/vinicius73/vuepress-plugin-merge-pages>

Or a flag in the metadata of the README.md for the section would be great. 

pandoc may also be able to help 'round out' the capability with a <print as pdf> or <print as docx> option is really what my students have asked for.

**Comment by aaronlippold** [comment]
As an example, for my courses, https://mitre.github.io/saf-training/courses/ - if this section had a Print Course or PDF of the 'full course' it would be very helpful.

**Comment by Mister-Hope** [comment]
[### ](https://github.com/vuepress/ecosystem/issues/305)

**Comment by aaronlippold** [comment]
I may be missing something, and the plugin above already merges the multiple markdown files and I just need to configure it, the built in print to pdf that is on the right hand sidebar is not exactly what we are going for. 

What I was hoping was that for documentation that is broken into multiple markdown files, if we could also build in the merge capability so that the multiple pages could be concatenated into a single document and then the pdf print plugin would be able to print the full version of the content.

Am I missing something in the referenced plugin above?

Thanks :)

**Comment by Mister-Hope** [comment]
I am not fully understand what you mean here

>  if we could also build in the merge capability so that the multiple pages could be concatenated into a single document and then the pdf print plugin would be able to print the full version of the content.

Both the them print button and the pdf button is doing the same thing: requesting to "print the page" via browser and save the result to a pdf.

Since the browser only supports printing the current page, so you must pre-generate every pdfs you need via a local browser and then merge it locally first, then provide accessible links for users.

**Comment by Mister-Hope** [comment]
So basically that sounds like a feature that you should implement by yourself, and probably by "component overriding" in the advanced section

**Comment by Mister-Hope** [comment]
So basically that sounds like a feature that you should implement by yourself, and probably by "component overriding" in the advenced section

**Comment by aaronlippold** [comment]
Ok. I’ll look into it.

--------
Aaron Lippold

***@***.***

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'
