### ISSUE TITLE
[Bug] Some component's layout broken on version rc.64~66

### ISSUE THREAD

**Issue by sakuhanachan** [vuepress-theme-hope/vuepress-theme-hope#4663]
### Checklist

- [X] I am using **LTS** version of Node.js.
- [X] I am using the **latest v2 version** of VuePress and VuePress official plugins.
- [X] I am using the **latest v2 version** of vuepress-theme-hope and all plugins in this repo.
- [X] I followed the docs and I double checked my configuration.
- [X] I have searched [FAQ](https://theme-hope.vuejs.press/faq/) and I did not find the answer.

### Package name

vuepress-theme-hope

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Describe the bug

After update to version rc.64~66, some component's layout like slot ``contentAfter`` or ``contentBefore`` layout has broken like in screenshot

![image](https://github.com/user-attachments/assets/88ab408d-6c1c-4862-96d2-cefaa248b44c)

But it should be like this (version rc.63)

![image](https://github.com/user-attachments/assets/85d90375-e13a-4317-bac0-7ab6dfc2f078)

### Additional context

Reproduction repo for test here: https://stackblitz.com/edit/vuepress-theme-hope-t5wt62qg?file=package.json

**Comment by Mister-Hope** [comment]
Why this should be a valid reproduction?

A lot of style only applies on `vp-content`
