### ISSUE TITLE
[Bug] nav-item只能精确匹配路径

### ISSUE THREAD

**Issue by pengwangpengwang** [vuepress-theme-hope/vuepress-theme-hope#579]
**Describe the bug**

**Screenshots**

**Additional context**
Add any other context about the problem here. Especially the issue occurs in certain OS, browser or configuation.

**Comment by Mister-Hope** [comment]
请给出详细的复现步骤与截图

**Comment by pengwangpengwang** [comment]
> 请给出详细的复现步骤与截图

官方文档点击导航栏配置，随后点击主题配置，导航栏配置没有高亮
![image](https://user-images.githubusercontent.com/29265420/106981445-fa7d3200-679c-11eb-91c4-dd0c5240900b.png)

**Comment by Mister-Hope** [comment]
感谢反馈，稍后修复

**Comment by pengwangpengwang** [comment]
什么时候修复啊，我看你的网站是修复了，但是我这边下载看还是有这个问题

**Comment by Mister-Hope** [comment]
修复了，我今天晚些发布新版本。最近在忙一个别的项目。

**Comment by Mister-Hope** [comment]
Fixed in 1.9.6
