### ISSUE TITLE
[Bug]comment plugin can not disable

### ISSUE THREAD

**Issue by Isarg** [vuepress-theme-hope/vuepress-theme-hope#587]
**Describe the bug**
When the comment plugin option set to false, it doesn't work.

**Screenshots**
![bug](https://user-images.githubusercontent.com/32994302/112616924-43796a80-8e5f-11eb-922d-f3ee318d477b.png)

**Additional context**

**Comment by Mister-Hope** [comment]
That's expected. You can disable all the features by setting type to disable and pageInfo to false in options.
