### ISSUE TITLE
[Feature Request] Add QR-Code in V2

### ISSUE THREAD

**Issue by gtn1024** [vuepress-theme-hope/vuepress-theme-hope#592]
**Describe the feature and why you wanted**

Could you please add QR-Code support in v2?

This may like below.

![image](https://user-images.githubusercontent.com/69113276/113499881-312cba00-954c-11eb-9263-32285a322ae8.png)

And the config:
```js
module.export = {
  themeConfig: {
    qrcode: true,
  }
};
```

**Comment by Mister-Hope** [comment]
That can be a good enhacnement.

Actually now you can use the `addThis` option to enable `vuepress-plugin-add-this` to provide similar share functions.

My consideration is that QRCode is weaker than the browser share action on mobile devices. And I don't think it's common for a people to switch to mobile devices when reading a documentation on PCs. Reading on PCs is  more  comfortable with it's layout.

I see you are a chinese, I guess maybe your thought came from Official Accounts articles in wechat. Wechat has that button becase the articles are design for mobile devices and do have a better experience on them. But vuepress is definitely the opposite.

Could you show more why this feature is needed? And which case would people prefer to continue reading on mobile devices, thanks.

**Comment by gtn1024** [comment]
This may just an idea. Better than nothing. 😁

**Comment by Mister-Hope** [comment]
I would add a powerful share plugin with common sociel app share action in V2, so I will close this one.

P.S.: I ask 8 theme users, 8/8 users don't think this QRCode is helpful, also QRcode will increase the output size, so I won't add this feature. Neither docs nor blog need to users to switch from PC to mobile. For now you can try [this](http://vuepress-theme-hope.github.io/add-this/)

**Comment by Mister-Hope** [comment]
Share component in `vuepress-plugin-components` now support this feature.
