### ISSUE TITLE
Question for custom titles

### ISSUE THREAD

**Issue by b00f** [vuepress-theme-hope/vuepress-theme-hope#593]
o you think Hope can support question for custom title? Like this:
```
::: question

....

:::
```

**Comment by Mister-Hope** [comment]
Do you mean the same as info tip warn danger, but with a question mark?

We can do add this, but my consideration is that a docs or blog should not contain questions in common cases. If so, that's a Q&A, not just a question.

In the above case, a tip container could be used with a custom title containing the question, and the container content is the answer.

If you have other opinion and have a common situation where the question container could be used. Welcome to show a part of docs or article, including the question container. I will add it if it can be a common case.

**Comment by b00f** [comment]
> Do you mean the same as info tip warn danger, but with a question mark?

Exactly.

> While my consideration is that a docs or blog should not contain questions in common cases.

Users might find it useful.
I my point of view, HOPE should be able to provide more options to users without sacrificing the performance and its internal design.

**Comment by Mister-Hope** [comment]
There are great difference between "most of the users think this userful and use it", "some users think this userful and use it "and "you regard this userful and use it". I can see that you want it, but please give some examples about in which situtaion can people use it.

There is really little difference between

```md
::: question Why it XXXXXXXX?

XXXXXXXXXXXXXXXXXXXXXXXXX

:::
```

and 


```md
::: info Info about XXXXXXXX 

XXXXXXXXXXXXXX, so XXXXXXXXXXX

:::
```

```md
::: tip XXXXXXXX 

XXXXXXXXXXXXXX, so XXXXXXXXXXX

:::
```

And most of the docs is negative to the first one. Most of the document are not children encyclopaedia. We don't need to make the description, infomation, or warnings to be a "question".

Like I said:

> If you have other opinion and have a common situation where the question container could be used. Welcome to show a part of docs or article, including the question container.

If you have a strong reason or common cases, maybe we can even add this feature to `@vuepress/theme-default`.

**Comment by Mister-Hope** [comment]
E.g.: https://v1.vuepress.vuejs.org/guide/markdown-slot.html#named-slots

```md
::: tip 
Here we are using slot-key instead of slot, because in Vue, slot is a reserved prop name.
:::
```


```md
::: qiuestion Why using slot-key instead of slot?
In Vue, slot is a reserved prop name.
:::
```

The second one this actually more confusing when they are not confused about it.
