### ISSUE TITLE
[Feature Request] 期望支持多选框

### ISSUE THREAD

**Issue by AWhiteMouse** [vuepress-theme-hope/vuepress-theme-hope#594]
在markdown中，可以使用 [x] xxx 和  [ ] xxx 的方式来表示多选框的选中和未选中

**Comment by Mister-Hope** [comment]
I may support this feature in newer versions, but now you can sure import `markdown-it-checkbox` and apply it ussing `extendMarkdown` option https://v1.vuepress.vuejs.org/zh/plugin/option-api.html#extendmarkdown

**Comment by Mister-Hope** [comment]
This will be supported in next minor version. Feature has alreadly been made. Thanks again for your advice.
