### ISSUE TITLE
[Bug] Can't run docs:dev

### ISSUE THREAD

**Issue by MarcoCestari** [vuepress-theme-hope/vuepress-theme-hope#595]
When running docs:dev, it's throwing Cyclic dependency error.

```
C:\Project\node_modules\vuepress-html-webpack-plugin\node_modules\toposort\index.js:35
      throw new Error('Cyclic dependency' + nodeRep)
      ^
```

**Comment by Mister-Hope** [comment]
Thanks for reporting, I will check that out.

**Comment by yesixuan** [comment]
I got the same bug
![image](https://user-images.githubusercontent.com/22050621/115113332-5e518180-9fbc-11eb-9612-55e7fc5c04cf.png)

**Comment by yesixuan** [comment]
Remove this code block can running normally

![image](https://user-images.githubusercontent.com/22050621/115113401-c30cdc00-9fbc-11eb-8170-b4d704c63a8a.png)

**Comment by Mister-Hope** [comment]
Thanks for reporting, I am just come back from a trip, I will start fixing it, may release a fix today or tomorrow.

**Comment by Mister-Hope** [comment]
1.14.5 should work.

**Comment by MarcoCestari** [comment]
Thanks! It's working now.
