### ISSUE TITLE
[Feature Request] Citation and Bibliography

### ISSUE THREAD

**Issue by dennislblog** [vuepress-theme-hope/vuepress-theme-hope#599]
Rightnow I am using `markdown-it-footnote` to add citations to my articles. It will really make writing enjoyable if citations from bibtex file can be easily imported and rendered. I have found a quite powerful [markdown-it-plugin](https://www.npmjs.com/package/markdown-it-bibliography). Please consider adding this feature if you have time to look at it :-)

希望增加文献引用功能，目前有markdown-it-citation(不再维护)和markdown-it-bibiliography, 他们好像都是module不能被直接导入

**Comment by Mister-Hope** [comment]
Thanks for your suggestion, you can fork `markdown-it-citation` and upgrade it to support markdown-it@v8 or you can try to use `chainMarkdown` in vuepress api and use `markdown-it-bibliography` to see if it works. 

A package with 3 download per week is definitely outside my consideration.

Besides, I do think that markdown-it-footnote is enough to make a declaration where a blockquote from.

**Comment by Mister-Hope** [comment]
Just a suggestion:

If you are writing some academic articles, maybe latex is something you need. Some latex project can output html for you. You can use iframe to include them in your webpage. Markdown is just built for notes, not academic articles.
