### ISSUE TITLE
[Feature Request] 评论插件是否会考虑支持 waline

### ISSUE THREAD

**Issue by L-cw** [vuepress-theme-hope/vuepress-theme-hope#602]
**Describe the feature and why you wanted**
哈喽，作者您好

  请问评论插件是否会考虑支持 [waline](https://waline.js.org/) 呢

**Comment by Mister-Hope** [comment]
预计这几天就支持了。今天一下午大致捋了一下 waline 的客户端代码。贡献排名直接ma蟒到第三....🤣明天再帮 waline 完善完善，重构一下它的样式系统，我就着手在评论插件添加支持。
![image](https://user-images.githubusercontent.com/33315834/116556700-54227200-a930-11eb-858d-5e994e1f07fc.png)

**Comment by Mister-Hope** [comment]
抱歉耽误的有些久了，这周末前后有望添加此功能。最近忙着完善waline。重构了它的样式系统，修复了数个bug，添加了字数，防xss等功能。waline现在已经可以完美的嵌入到主题中了。


![image](https://user-images.githubusercontent.com/33315834/117529426-1695a700-b00a-11eb-8f65-e3aee9e3bcfc.png)

**Comment by L-cw** [comment]
> 抱歉耽误的有些久了，这周末前后有望添加此功能。最近忙着完善waline。重构了它的样式系统，修复了数个bug，添加了字数，防xss等功能。waline现在已经可以完美的嵌入到主题中了。

---

能添加支持太赞了，作者辛苦了，**感谢**！

**Comment by Mister-Hope** [comment]
> 这周末前后有望添加此功能

啊嘞？我还没加入主题支持呢？

**Comment by Mister-Hope** [comment]
Already added in 1.17.x
