### ISSUE TITLE
[Feature Request] Synchronize the <CodeGroup> components in a single page

### ISSUE THREAD

**Issue by pamodaaw** [vuepress-theme-hope/vuepress-theme-hope#604]
**Describe the feature and why you wanted**

I have several `<CodeGroup>` components on a single page. I want them to be synchronized so that if I change the tab in one component, all the other components will change to the same tab.

This will reduce the burden of the user in selecting the preferred code language multiple times when referring to the documentation.

In addition to synchronizing, it would be required to have isolated `<CodeGroup>` as well. For the cases where we do not need to change dynamically. 

**Additional context**
The output will be as follows,
![codeblockSync](https://user-images.githubusercontent.com/12439288/117106924-59534700-ad9e-11eb-95e2-69cc5a28d110.png)

If I change the language of step 1 to `npm`, the language of step 2 will be automatically changed to `npm` as well.
But the step 3 will not change as I change the other two steps.

**Comment by Mister-Hope** [comment]
Think about this: It won't be the expect behaviour in every cases.
