### ISSUE TITLE
[Bug] Init the vuepress-theme-hope

### ISSUE THREAD

**Issue by Cokaps** [vuepress-theme-hope/vuepress-theme-hope#610]
Hi, When I run the following command, after waiting for a while, it come to this issue (using Mac OS X 10.11.6):
```bash
yarn create vuepress-theme-hope /Users/loctran016/Desktop/EFI\ Collection/website
```
[Problem Hope.txt](https://github.com/vuepress-theme-hope/vuepress-theme-hope/files/6595895/Problem.Hope.txt)

Anyway, thanks for creating such a wonderful theme!

**Comment by Mister-Hope** [comment]
This issue came from npm itself. Please clean (or verify) your npm cache ,ensure your network with npm registery then try again.

You may found more details in npm docs or just search this error on Google or stackoverflow.

**Comment by Mister-Hope** [comment]
At lease for me I have nothing to do, I just called `npm install` for you.

**Comment by Cokaps** [comment]
Would you mind telling me/adding to the doc what does this command create (so that I can create them manually)

**Comment by Mister-Hope** [comment]
The template should be injected in to your project, just manually install and run it should be fine.
