### ISSUE TITLE
[Bug] `overflow-x: auto` for code blocks not working in iOS safari

### ISSUE THREAD

**Issue by yesixuan** [vuepress-theme-hope/vuepress-theme-hope#611]
最新版本，ios 手机 safari 浏览器上代码代码过长会导致折行，从而导致行号错乱

**Comment by Mister-Hope** [comment]
Could you provide a screenshot?

**Comment by Mister-Hope** [comment]
This bug belongs to iOS safari render strategy, and should be consider as a bug because it's not following the CSS standard.

Since I don't have a Mac so I cannot debug my iOS device, if anyone knows how to fix this, PR is welcomed.

**Comment by Mister-Hope** [comment]
Fixed in V2.

**Comment by Mister-Hope** [comment]
Also I am not going to keep working on v1, but If you want this fixed and stay in v1,V1 PR is always welcome.
