### ISSUE TITLE
[Bug] features link不支持ftp协议

### ISSUE THREAD

**Issue by ElvisTan** [vuepress-theme-hope/vuepress-theme-hope#633]
## Additional context

Add any other context about the problem here. Especially the issue occurs in certain OS, browser or configuation.

**Comment by Mister-Hope** [comment]
Maybe you ahould place the link in an actual page.

Anyway, PR welcome. I don't have plans to support this myself.

**Comment by Mister-Hope** [comment]
This should be working in latest rc version
