### ISSUE TITLE
[Bug] md flowchart

### ISSUE THREAD

**Issue by lunxian8** [vuepress-theme-hope/vuepress-theme-hope#702]
1. ubantu build 这个警告有没用什么问题？

![image](https://user-images.githubusercontent.com/27261113/123886028-28982400-d981-11eb-81a9-0ce2483127a4.png)

2. 只写了一个flowchart更新后 pwa提示刷新这里正常显示，但是手动f5 或者刷新浏览器页面就出来了三个

页面：

![image](https://user-images.githubusercontent.com/27261113/123886247-9f352180-d981-11eb-9ca5-66f4703d2542.png)

code：

![image](https://user-images.githubusercontent.com/27261113/123886286-b6740f00-d981-11eb-9701-0fda60882a27.png)

前端抛出的错误

![image](https://user-images.githubusercontent.com/27261113/123886348-d60b3780-d981-11eb-871d-8618e2fb719e.png)

**Comment by Mister-Hope** [comment]
1. hostname是必填项，详见主题配置，否则请将feed，seo，sitemap插件手动禁用

2. toUppercase 这个问题，检测所有的frontmatter，大概率是哪个页面没设置category

3. 第三个问题请测试主题文档能否复现，不能的话请提min repro

**Comment by lunxian8** [comment]
> 1. hostname是必填项，详见主题配置，否则请将feed，seo，sitemap插件手动禁用
> 2. toUppercase 这个问题，检测所有的frontmatter，大概率是哪个页面没设置category
> 3. 第三个问题请测试主题文档能否复现，不能的话请提min repro

我这是局域网部署 hostname不写应该没事吧？ 那我把feed，seo，sitemap禁用掉

第三个主题文档是？

**Comment by Mister-Hope** [comment]
> 第三个主题文档是？

主题文档就是你看的那个文档。利用主题模板创建工具创建的默认模板也有flowchart，你可以试试这两个有没有问题。

**Comment by Mister-Hope** [comment]
另外hostname你可以设置为局域网ip之类的东西。我印象中主题可能遇到了这个变量，所以不允许不设置，如果一直报错你可以传入一个 `/` 进去。也欢迎反馈你不设置是否有强制报错的行为。时间比较久了(相关代码一年多以前)我也记不太清我的逻辑。

**Comment by lunxian8** [comment]
> 另外hostname你可以设置为局域网ip之类的东西。我印象中主题可能用到了这个变量，所以当初设计不允许不设置，如果一直报错你可以传入一个 `/` 进去。也欢迎反馈你不设置是否有强制报错的行为。时间比较久了(相关代码一年多以前)我也记不太清我的逻辑。

好的好的，暂时来说除了编译的时候抛出了错误，使用还没遇见问题，后续遇到来反馈

**Comment by lunxian8** [comment]
> > 第三个主题文档是？
> 
> 主题文档就是你看的那个文档。利用主题模板创建工具创建的默认模板也有flowchart，你可以试试这两个有没有问题。

😄 这个不太清楚在哪呀？有没有相关语法 我直接复制上去试试

**Comment by Mister-Hope** [comment]
就是主页的安装...我做了一个包可以快速生成一个模板， npm init 或 yarn create + vuepress-theme-hope + [dir]

**Comment by Mister-Hope** [comment]
你可以快速创建一个全新的模板，看看有没有问题，如果模板都挺正常的，那问题就出在你的项目里，或者是你项目的某些内容会引发这个问题。总之我这边没有遇到过这个问题，所以需要你给一个最小的复现我才能开始排查。

**Comment by lunxian8** [comment]
> 你可以快速创建一个全新的模板，看看有没有问题，如果模板都挺正常的，那问题就出在你的项目里，或者是你项目的某些内容会引发这个问题。总之我这边没有遇到过这个问题，所以需要你给一个最小的复现我才能开始排查。

我懂你的意思了 😆

**Comment by lunxian8** [comment]
> 你可以快速创建一个全新的模板，看看有没有问题，如果模板都挺正常的，那问题就出在你的项目里，或者是你项目的某些内容会引发这个问题。总之我这边没有遇到过这个问题，所以需要你给一个最小的复现我才能开始排查。

看来是我项目的问题了

**Comment by Mister-Hope** [comment]
你可以找找，也许你的项目中含有特定内容的时候这个情况会发生。

**Comment by Mister-Hope** [comment]
想了几分钟，帮你想到了一个可能的问题，请检查你出现问题的页面是不是有重复的flowchart

我们是完全根据flowchart内容进行has来生成id的，如果id重复，有可能会导致客户端多次渲染。

**Comment by lunxian8** [comment]
> 你可以找找，也许你的项目中含有特定内容的时候这个情况会发生。

ok

**Comment by lunxian8** [comment]
> 想了几分钟，帮你想到了一个可能的问题，请检查你出现问题的页面是不是有重复的flowchart
> 
> 我们是完全根据flowchart内容进行hash来生成id的，所以如果id重复，有可能会导致客户端多次渲染。





应该没吧？搜索关键词就俩：


```flow
st=>start: Start|past:>http://www.google.com[blank]
e=>end: End|future:>http://www.google.com
op1=>operation: My Operation|past
op2=>operation: Do something|current
sub1=>subroutine: My Subroutine|invalid
cond=>condition: Yes
or No?|approved:>http://www.google.com
c2=>condition: Good idea|rejected
io=>inputoutput: catch something...|future

st->op1(right)->cond
cond(yes, right)->c2
cond(no)->sub1(left)->op1
c2(yes)->io->e
c2(no)->op2->e
```


和

```mermaid
flowchart TB
    c1-->a2
    subgraph one
    a1-->a2
    end
    subgraph two
    b1-->b2
    end
    subgraph three
    c1-->c2
    end
    one --> two
    three --> two
    two --> c2
```


从官方复制来的

**Comment by lunxian8** [comment]
![image](https://user-images.githubusercontent.com/27261113/124055175-002e2980-da56-11eb-8550-ff7217766bac.png)


![image](https://user-images.githubusercontent.com/27261113/124055189-06bca100-da56-11eb-91dd-039078a44ca1.png)

**Comment by Mister-Hope** [comment]
meraid 和 flowchart是两个包，而且flowchart在v2中已经被移除了。

你可以找找其他地方.....

**Comment by lunxian8** [comment]
> meraid 和 flowchart是两个包，而且flowchart在v2中已经被移除了。
> 
> 你可以找找其他地方.....

没了呀 一共还没几个页面 其它的都是基础的md标签

**Comment by Mister-Hope** [comment]
We are using flowchart-ts now, ooen new issue if there is any problem
