### ISSUE TITLE
[Bug] Router Warning with CJK filename(unencoded characters)

### ISSUE THREAD

**Issue by wafer-li** [vuepress-theme-hope/vuepress-theme-hope#750]
## Describe the bug

Router will complain the CJK filename.

## Screenshots

![image](https://user-images.githubusercontent.com/12459199/124960297-bf827180-e04e-11eb-9d4d-edf53be333ac.png)

## Additional context

Add any other context about the problem here. Especially the issue occurs in certain OS, browser or configuation.

**Comment by wafer-li** [comment]
I think, it is the framework's duty to use a `encodedURI()`.

Or is there some bug with `encodedURI()` fucntion?

**Comment by Mister-Hope** [comment]
See https://vuepress-theme-hope.github.io/zh/FAQ/#%E8%AE%BF%E9%97%AE%E9%83%A8%E5%88%86%E9%93%BE%E6%8E%A5-404

![Screenshot_20210709-010800.jpg](https://user-images.githubusercontent.com/33315834/124963217-205f7900-e052-11eb-8b0d-fa06c13d1de4.jpg)

I have done all I could.

**Comment by wafer-li** [comment]
Sorry for my blind eye.

I checked that your branch is still ahead of the origin remote.

Therefore you could try to publish your own npm package under your namespace.

And use the fixed version to resolve this problem.

**Comment by Mister-Hope** [comment]
> I checked that your branch is still ahead of the origin remote.

What do you mean here? What is the origin remote? My main branch aligning to vuepress@2?

> Therefore you could try to publish your own npm package under your namespace.
> And use the fixed version to resolve this problem.

You are just triggering a warning, and it will have no effect in production mode.

The only problem is that you cannot directly navigate to a category or tag page, but that' a rare case. Also vuepress2 is on the way.

So I have no interest in forking a copy of vuepress-plugin-blog and maintain by my own. Reme,ber that's an official plugin, which means the official has dropped vuepress v1 support.

**Comment by wafer-li** [comment]
I have tinkered this problem the whole night.

Even though I found out some solutions, neither of them is better than yours.

For now, we could only expect the vuepress2 release might be solving the problem.

<details>

<summary>The explanations to the misunderstanding containing my naive thoughts</summary>

> What do you mean here? What is the origin remote, my main branch aligning to vuepress@2? My code is nothing related to vuepress-plugin-blog

I mean that you already make a PR of fix to `vuepress-plugin-blog`, that means you already have a fork of this plugin.

Then you could just publish a fixed version of `vuepress-plugin-blog` and use it as dependency in this theme.
</details>

**Comment by Mister-Hope** [comment]
See https://github.com/vuepress/vuepress-plugin-blog/issues/95#issuecomment-876957635

If it's not been replyed in 3 days, I will publish a version.

**Comment by wafer-li** [comment]
And there is another approach, check https://github.com/vuepress-reco/vuepress-theme-reco/commit/8fefc9f9adb82412ef273a8474b7428659f24839

**Comment by Mister-Hope** [comment]
This problem must be fixed on plugin-blog side, becase `/tag/使用指南/` is just what they are registing.
