### ISSUE TITLE
[Bug] The link is different in page and excerpt

### ISSUE THREAD

**Issue by wafer-li** [vuepress-theme-hope/vuepress-theme-hope#753]
## Describe the bug

The relative link of other md file will have different result in page and excerpt.

When link in excerpt which display in homepage, it has base path of `/`

And link display in page has base path of `/path/to/page`.

It causes 404 if you click the link in excerpt.

## Screenshots

Link in excerpt
![image](https://user-images.githubusercontent.com/12459199/125119182-4f91eb00-e123-11eb-9cac-e0d7b01b42b0.png)

Link in page
![image](https://user-images.githubusercontent.com/12459199/125119255-6afcf600-e123-11eb-8be7-7db5f342f439.png)

## Additional context

[My blog](https://wafer.li) (It might be https error since it takes time to become global)

The markdown source

```md
[上文](../itemdecoration-实战之-girdspacingitemdecoration（一）)
```

**Comment by Mister-Hope** [comment]
Do not use links in excerpt.

If you ro think it's a bug report it to vuepress.

**Comment by wafer-li** [comment]
Since vuepress is transiting to v2, so I decided to wait until its stable release.

If it still has this problem, I will post an issue then.
