### ISSUE TITLE
[Bug] Charset should be in the first 1024 bytes

### ISSUE THREAD

**Issue by jiazengp** [vuepress-theme-hope/vuepress-theme-hope#798]
## Describe the bug

Always declare the encoding of your document using a element with a attribute, or using the and attributes (called a pragma directive). The declaration should fit completely within the first 1024 bytes at the start of the file, so it's best to put it immediately after the opening tag.metacharsethttp-equivcontenthead

**Comment by Mister-Hope** [comment]
不不不，你给我发是没用的，原则上你应该发给vuepress

**Comment by jiazengp** [comment]
哦，那我走。

**Comment by jiazengp** [comment]
我想 SEO2 插件或许能解决这个问题
